export const cn = [{
            ar: "For years, scientists have been working to find a cure for Alzheimer's disease, a progressive brain disorder that affects millions of people worldwide. The disease is caused by the buildup of abnormal proteins in the brain that damage and kill brain cells, leading to memory loss and other cognitive problems. Although there is currently no cure for Alzheimer's disease, there are medications that can help manage symptoms and improve quality of life for patients.Recently, researchers at the University of Texas at Dallas may have made a breakthrough in the search for a cure. In a study published in the journal Science Advances, the team showed that they were able to clear out the abnormal proteins that cause Alzheimer's disease from the brains of mice. They did this by using ultrasound waves to stimulate microglial cells in the brain, which are responsible for removing waste and other harmful substances. The researchers found that the ultrasound waves caused the microglial cells to consume the abnormal proteins, reducing their buildup in the brain.The study is still in its early stages, and more research is needed to determine whether the same approach could be effective in humans. However, the results are promising, and could pave the way for a future cure for Alzheimer's disease.",
            q: ["What is Alzheimer's disease?","What causes Alzheimer's disease?","Is there currently a cure for Alzheimer's disease?","What did researchers at the University of Texas at Dallas do to clear out the abnormal proteins that cause Alzheimer's disease from the brains of mice?","Is the study mentioned in the passage likely to lead to a cure for Alzheimer's disease in humans?",],
            q_sel:[[" A type of cancer"," A progressive brain disorder"," A genetic disorder"," A disorder caused by a virus",],[" The buildup of abnormal proteins in the brain"," A virus"," Genetics"," Smoking",],[" Yes, there is a cure."," No, there is no cure."," There is a cure, but it is not effective."," There used to be a cure, but it is no longer available.",],[" They used chemotherapy."," They used ultrasound waves to stimulate microglial cells."," They removed the affected parts of the brain."," They gave the mice a new medication.",],[" Yes, a cure is now available for humans."," No, the study is unlikely to lead to a cure for humans."," It is too early to tell."," The study has already led to a cure for humans.",],],
            q_ex: ["文章第一句就提到 Alzheimer's disease 是一种「progressive brain disorder」，因此答案为 B。","文章中提到 Alzheimer's disease 是由于「the buildup of abnormal proteins in the brain」所引起，因此答案为 A。","文章中提到目前没有针对 Alzheimer's disease 的治疗方法，只有一些可以帮助缓解症状的药物，因此答案为 B。","文章中提到研究人员使用「ultrasound waves to stimulate microglial cells in the brain」以清除掉引起 Alzheimer's disease 的异常蛋白质，因此答案为 B。","文章中提到这项研究仍处于早期阶段，需要更多的研究才能确定同样的方法是否对人类有效，因此答案为 C。文中也提到研究结果具有前途，但仍需要进一步的研究。",],
            q_a: [" B"," A"," B"," B"," C",],
            zh: "多年来，科学家们一直致力于寻找治疗阿尔茨海默病的方法，阿尔茨海默病是一种影响全球数百万人的进行性脑部疾病。这种疾病是由大脑中异常蛋白质的积累引起的，这些蛋白质会损害和杀死脑细胞，从而导致记忆力减退和其他认知问题。虽然目前还没有治愈阿尔茨海默病的方法，但有一些药物可以帮助控制症状并改善患者的生活质量。最近，德克萨斯大学达拉斯分校的研究人员可能在寻找治愈方法方面取得了突破。在《科学进展》杂志上发表的一项研究中，该团队表明他们能够从小鼠大脑中清除导致阿尔茨海默病的异常蛋白质。他们通过使用超声波刺激大脑中负责清除废物和其他有害物质的小神经胶质细胞来做到这一点。研究人员发现，超声波导致小胶质细胞消耗异常蛋白质，减少了它们在大脑中的积聚。这项研究仍处于早期阶段，需要更多的研究来确定同样的方法是否对人类有效。然而，结果很有希望，并可能为未来治愈阿尔茨海默病铺平道路。"
        },{
            ar: "In recent years, climate change has become an increasingly urgent issue. As global temperatures rise and extreme weather events become more frequent, it is clear that we need to take action to reduce our carbon footprint and prevent further damage to the planet. One solution that has gained popularity in recent years is renewable energy, which comes from sources that are naturally replenished and can be used without depleting finite resources.Renewable energy sources include solar, wind, and hydro power, as well as geothermal and biomass energy. These sources have many advantages over traditional fossil fuels, such as coal and oil. For example, they produce little to no emissions and are much less harmful to the environment. They also provide a sustainable and reliable source of energy, as they are not subject to the same price fluctuations and supply constraints as fossil fuels.Despite these advantages, renewable energy sources still face many challenges. For one, they are often more expensive to develop and implement than traditional energy sources. In addition, their effectiveness can be limited by factors such as weather patterns and geographic location. As a result, governments and private companies alike must invest in research and development to make renewable energy more efficient and cost-effective.",
            q: ["What is one reason why climate change has become an increasingly urgent issue in recent years?","What is renewable energy?","What are some examples of renewable energy sources?","What is one advantage of renewable energy sources over traditional fossil fuels?","What is one challenge that renewable energy sources face?",],
            q_sel:[[" Global temperatures are decreasing."," Extreme weather events are becoming less frequent."," The use of fossil fuels is declining."," Global temperatures are rising.",],[" Energy that is produced from fossil fuels."," Energy that is not subject to price fluctuations."," Energy that is naturally replenished and does not deplete finite resources."," Energy that produces large amounts of emissions.",],[" Coal and oil."," Natural gas and petroleum."," Solar, wind, and hydro power."," Nuclear and geothermal energy.",],[" Renewable energy sources are subject to price fluctuations."," Renewable energy sources are harmful to the environment."," Renewable energy sources are less expensive to develop and implement."," Renewable energy sources produce little to no emissions.",],[" They are often more expensive to develop and implement than traditional energy sources."," They produce large amounts of emissions."," They are subject to the same price fluctuations and supply constraints as fossil fuels."," They are not effective sources of energy.",],],
            q_ex: ["文章开头就提到全球气温上升，显然地指出了气候变迁成为一个越来越迫切的问题，因此答案为 D。","文章中提到 renewable energy 是指那些来源是自然再生的，可以使用而不会耗尽有限资源的能源，因此答案为 C。","文章中列举了太阳能、风能和水能等能源，这些都是 renewable energy sources 的例子，因此答案为 C。","文章中提到 renewable energy sources 相较于传统的化石燃料，例如煤炭和石油，会产生较少的排放物，因此答案为 D。","文章中提到 renewable energy sources 通常比传统能源更昂贵，因此需要更多的研究和发展来使其更有效率和具有成本效益，因此答案为 A。",],
            q_a: [" D"," C"," C"," D"," A",],
            zh: "近年来，气候变化已成为一个日益紧迫的问题。随着全球气温上升和极端天气事件变得更加频繁，显然我们需要采取行动减少我们的碳足迹并防止对地球造成进一步破坏。近年来流行的一种解决方案是可再生能源，它来自自然补充的资源，可以在不耗尽有限资源的情况下使用。可再生能源包括太阳能、风能和水力发电，以及地热和生物质能。与煤炭和石油等传统化石燃料相比，这些资源具有许多优势。例如，它们几乎不产生排放物，对环境的危害也小得多。它们还提供可持续和可靠的能源来源，因为它们不像化石燃料那样受到价格波动和供应限制的影响。尽管有这些优势，可再生能源仍然面临许多挑战。一方面，与传统能源相比，它们的开发和实施成本往往更高。此外，它们的有效性可能会受到天气模式和地理位置等因素的限制。因此，政府和私营公司都必须投资于研发，以提高可再生能源的效率和成本效益。"
        },{
            ar: "In recent years, there has been growing concern about the impact of social media on mental health. While social media platforms have the potential to connect people from all over the world, they also have some negative effects. One study found that people who spend more than two hours a day on social media are more likely to experience feelings of social isolation and depression.One way that social media can contribute to mental health problems is through the comparison of oneself to others. Social media platforms often present idealized versions of people's lives, and users may feel pressure to conform to these unrealistic standards. This can lead to feelings of inadequacy and low self-esteem.Another way that social media can affect mental health is through the spread of misinformation. False information and rumors can spread rapidly on social media, leading to anxiety and confusion. In some cases, this can even lead to dangerous behavior or beliefs.Despite these negative effects, social media can also be a source of support and community for some people. It is important to use social media in a balanced and responsible way, and to be aware of the potential risks.",
            q: ["What is one concern about the impact of social media on mental health?","How can social media contribute to mental health problems?","What is one way that social media can lead to feelings of inadequacy and low self-esteem?",],
            q_sel:[[" Social media platforms can only connect people from certain parts of the world."," Social media platforms have no negative effects on mental health."," People who use social media are less likely to experience feelings of social isolation and depression."," People who spend more than two hours a day on social media are more likely to experience feelings of social isolation and depression.",],[" By presenting realistic versions of people's lives."," By providing users with accurate information."," By spreading rumors and misinformation."," By connecting people from all over the world.",],[" By providing users with support and community."," By presenting idealized versions of people's lives."," By spreading accurate information."," By connecting people from all over the world.",],],
            q_ex: ["文章中提到花费超过每天两个小时在社交媒体上的人，更有可能出现社交孤立和抑郁的感觉，因此答案为 D。","文章中提到社交媒体可以通过传播不实信息和谣言对心理健康造成影响，因此答案为 C。","文章中提到社交媒体平台经常呈现人们生活的理想化版本，使用者可能感到需要符合这些不现实的标准，这可能导致自卑和低自尊心，因此答案为 B。",],
            q_a: [" D"," C"," B",],
            zh: "近年来，人们越来越关注社交媒体对心理健康的影响。虽然社交媒体平台有可能将来自世界各地的人们联系起来，但它们也有一些负面影响。一项研究发现，每天在社交媒体上花费超过两个小时的人更有可能体验到社交孤立和抑郁的感觉。社交媒体导致心理健康问题的一种方式是通过自我与他人的比较。社交媒体平台经常呈现人们生活的理想化版本，用户可能会感到有压力要遵守这些不切实际的标准。这会导致自卑感和自卑感。社交媒体影响心理健康的另一种方式是传播错误信息。虚假信息和谣言会在社交媒体上迅速传播，导致焦虑和困惑。在某些情况下，这甚至会导致危险的行为或信念。尽管有这些负面影响，社交媒体也可以成为某些人的支持和社区来源。以平衡和负责任的方式使用社交媒体并了解潜在风险非常重要。"
        },{
            ar: "As the world becomes more technologically advanced, people are becoming more and more reliant on electronic devices. While these devices can make life easier and more convenient in many ways, there are also downsides to this dependence.One issue is the effect of electronic devices on sleep. Studies have shown that the blue light emitted by screens can interfere with the production of melatonin, a hormone that helps regulate sleep. This can lead to difficulty falling asleep, as well as poor-quality sleep.Another issue is the impact of electronic devices on social interaction. Many people now spend a significant amount of time interacting with others through social media and messaging apps, rather than in-person communication. This can lead to feelings of loneliness and isolation, as well as a lack of important social skills.Despite these downsides, electronic devices are not going anywhere. It is important for individuals to recognize the potential negative effects of these devices and take steps to mitigate them, such as limiting screen time before bed and making an effort to engage in face-to-face communication with others.",
            q: ["What is the main topic of the passage?","What is one negative impact of electronic devices on sleep?","How can overuse of electronic devices affect social skills?","What is the author's main message?","What is one step individuals can take to mitigate the negative effects of electronic devices?",],
            q_sel:[[" The benefits of electronic devices"," The downsides of electronic devices"," The future of electronic devices"," The evolution of electronic devices",],[" Increased production of melatonin"," Improved sleep quality"," Interference with melatonin production"," Increased likelihood of dreaming",],[" It can improve social interaction"," It can lead to feelings of loneliness and isolation"," It can increase face-to-face communication"," It can enhance the ability to read social cues",],[" Electronic devices are all bad"," Electronic devices are all good"," Electronic devices have both benefits and downsides"," Electronic devices will eventually disappear",],[" Increase screen time before bed"," Avoid face-to-face communication"," Use electronic devices more frequently"," Limit screen time before bed",],],
            q_ex: ["文章第一段提到了电子产品的优点，但是整篇文章都是在探讨电子产品的缺点，因此答案为B。","根据文章第二段的描述，电子产品发出的蓝光会干扰褪黑激素的产生，进而影响睡眠，因此答案为C。","文章第三段提到，人们现在花大量的时间透过社交媒体和消息应用程式与他人互动，而不是进行面对面的交流，这会导致孤独感和孤立感，以及缺乏重要的社交技能，因此答案为B。","文章提到了电子产品的缺点，但也指出了电子产品的优点，并强调了个人需要认识到这些设备的潜在负面影响，并采取措施来缓解它们带来的影响，因此答案为C。","文章最后一段建议个人应该认识到电子产品的潜在负面影响，并采取措施来缓解它们带来的影响，其中一个建议就是在睡前限制使用电子产品的时间，因此答案为D。",],
            q_a: [" B"," C"," B"," C"," D",],
            zh: "随着世界技术变得越来越先进，人们越来越依赖电子设备。虽然这些设备可以在许多方面让生活更轻松、更方便，但这种依赖也有不利之处。一个问题是电子设备对睡眠的影响。研究表明，屏幕发出的蓝光会干扰褪黑激素的产生，褪黑激素是一种有助于调节睡眠的激素。这会导致难以入睡，以及睡眠质量差。另一个问题是电子设备对社交互动的影响。许多人现在花费大量时间通过社交媒体和消息应用程序与他人互动，而不是面对面交流。这可能会导致孤独感和孤立感，以及缺乏重要的社交技能。尽管有这些缺点，电子设备仍无处可去。个人必须认识到这些设备的潜在负面影响并采取措施减轻这些影响，例如限制睡前看屏幕的时间并努力与他人进行面对面的交流。"
        },{
            ar: "The human brain is incredibly complex, and there is still much that researchers do not understand about how it works. However, one thing that is clear is that the brain is highly adaptable and capable of change.Neuroplasticity is the term used to describe the brain's ability to reorganize itself in response to new experiences. This can involve creating new neural connections or strengthening existing ones. Neuroplasticity is thought to be a key factor in learning and memory, as well as in recovery from brain injuries.While the brain is capable of neuroplasticity throughout life, the extent to which it can change decreases with age. This means that young children are particularly adept at learning and adapting, while older adults may have more difficulty in these areas.However, there are things that individuals can do to promote neuroplasticity and enhance their brain's ability to adapt. Engaging in activities that are mentally stimulating, such as reading or solving puzzles, is one way to promote neuroplasticity. Physical exercise has also been shown to have a positive impact on brain function and neuroplasticity.",
            q: ["What is the main topic of the passage?","What is neuroplasticity?","How does neuroplasticity impact learning and memory?","What is one way to promote neuroplasticity?",],
            q_sel:[[" The complexity of the human brain"," The role of neuroplasticity in brain function"," The effects of aging on the brain"," The benefits of mental stimulation",],[" The brain's ability to change in response to new experiences"," The brain's ability to maintain the status quo"," The brain's inability to change with age"," The brain's resistance to new experiences",],[" It has no effect on learning and memory"," It makes learning and memory more difficult"," It is a key factor in learning and memory"," It only impacts memory, not learning",],[" Avoid mental stimulation"," Limit physical exercise"," Engage in mentally stimulating activities"," Only engage in physical exercise",],],
            q_ex: ["文章主要在谈论神经可塑性对于大脑功能的影响，因此答案为B。","文章第二段中提到，神经可塑性是大脑对新体验做出反应时重新组织自己的能力，包括建立新的神经连接或加强现有的连接，因此答案为A。","文章中提到神经可塑性是学习和记忆的关键因素之一，因此答案为C。","文章中提到，进行脑力刺激的活动（例如阅读或解决问题）是促进神经可塑性的一种方式，因此答案为C。",],
            q_a: [" B"," A"," C"," C",],
            zh: "人脑极其复杂，研究人员对它的工作原理仍有很多不了解。然而，有一点是明确的，即大脑具有高度的适应性和变化能力。神经可塑性是用来描述大脑重组自身以响应新体验的能力的术语。这可能涉及创建新的神经连接或加强现有的神经连接。神经可塑性被认为是学习和记忆以及脑损伤恢复的关键因素。虽然大脑在整个生命过程中都具有神经可塑性，但它可以改变的程度会随着年龄的增长而降低。这意味着年幼的孩子特别善于学习和适应，而老年人在这些方面可能会遇到更多困难。但是，个人可以做一些事情来促进神经可塑性并增强大脑的适应能力。参与精神刺激的活动，例如阅读或解决难题，是促进神经可塑性的一种方式。体育锻炼也被证明对大脑功能和神经可塑性有积极影响。"
        },{
            ar: "Climate change is a pressing issue that has garnered significant attention in recent years. While there is still debate about the causes and extent of climate change, most scientists agree that it is largely driven by human activities, such as the burning of fossil fuels and deforestation.One of the consequences of climate change is rising sea levels. As temperatures continue to rise, glaciers and ice sheets are melting, causing water to flow into the oceans and contributing to sea level rise. This can have a devastating impact on coastal cities and communities, as well as on wildlife and ecosystems.Another consequence of climate change is extreme weather events, such as heat waves, droughts, and hurricanes. These events can lead to crop failures, water shortages, and infrastructure damage, among other things. They also pose a significant threat to human health and well-being.Addressing climate change requires a coordinated effort from individuals, governments, and businesses around the world. This may involve reducing greenhouse gas emissions, transitioning to renewable energy sources, and investing in technologies that can help mitigate the impacts of climate change.",
            q: ["What is the main topic of the passage?","What are some human activities that are contributing to climate change?","What is one consequence of rising temperatures?","What is one way to address climate change?","What is the author's opinion on climate change?",],
            q_sel:[[" The causes of climate change"," The impacts of climate change"," The debate about climate change"," The role of individuals in addressing climate change",],[" Eating meat and dairy products"," Planting trees and other vegetation"," Burning fossil fuels and deforestation"," Recycling and composting",],[" Decreasing sea levels"," Reduced crop yields"," Increased forest cover"," Improved wildlife habitats",],[" Increase greenhouse gas emissions"," Continue to rely on fossil fuels"," Transition to renewable energy sources"," Build more infrastructure in coastal areas",],[" It is not a significant issue"," It is entirely caused by human activities"," It is a topic of debate among scientists"," It requires a coordinated effort to address",],],
            q_ex: ["文章主要在谈论气候变化对于环境、野生动物和人类社区带来的影响，因此答案为B。","文章中提到，气候变化很大程度上是由人类活动引起的，例如燃烧化石燃料和森林砍伐，因此答案为C。","文章中提到，随着温度持续上升，冰川和冰原融化，导致水流入海洋并促成海平面上升，这对沿海城市和社区以及野生动物和生态系统都会产生毁灭性的影响。因此答案为B。","文章中提到，应对气候变化需要全球个人、政府和企业之间的协调努力，这可能包括减少温室气体排放，转向可再生能源来源以及投资于能减缓气候变化影响的技术等。因此答案为C。","文章作者没有表达对气候变化本身的观点，而是强调需要全球个人、政府和企业之间的协调努力才能应对气候变化。因此答案为D。",],
            q_a: [" B"," C"," B"," C"," D",],
            zh: "气候变化是一个紧迫的问题，近年来引起了广泛关注。尽管对气候变化的原因和程度仍有争论，但大多数科学家都认为，气候变化主要是由人类活动驱动的，例如燃烧化石燃料和砍伐森林。气候变化的后果之一是海平面上升。随着气温持续上升，冰川和冰原正在融化，导致水流入海洋并导致海平面上升。这会对沿海城市和社区以及野生动物和生态系统产生毁灭性影响。气候变化的另一个后果是极端天气事件，例如热浪、干旱和飓风。这些事件可能导致作物歉收、缺水和基础设施损坏等。它们还对人类健康和福祉构成重大威胁。应对气候变化需要全世界个人、政府和企业的协调努力。这可能涉及减少温室气体排放、转向可再生能源以及投资有助于减轻气候变化影响的技术。"
        },{
            ar: "The concept of climate change has become an increasingly pressing issue in recent years. Climate change refers to the long-term changes in Earth's climate, including changes in temperature, precipitation, and wind patterns, among others. While natural factors such as volcanic activity and solar radiation can contribute to climate change, the overwhelming scientific consensus is that human activities, particularly the burning of fossil fuels, are the primary cause of the current trend.The consequences of climate change are vast and far-reaching. Rising temperatures can lead to extreme weather events such as hurricanes, floods, and droughts, which in turn can cause significant damage to infrastructure, property, and crops. Melting ice caps and rising sea levels can lead to the displacement of communities living in low-lying coastal areas. Climate change can also have negative impacts on public health, such as the spread of diseases and the exacerbation of existing health conditions.In response to the threat of climate change, many countries have taken action to reduce their greenhouse gas emissions and transition to more sustainable forms of energy. These efforts include investing in renewable energy sources such as wind and solar power, improving energy efficiency, and promoting public transportation and electric vehicles. While much remains to be done to address the challenges of climate change, there is reason for hope as countries and individuals work towards a more sustainable future.",
            q: ["What is climate change?","What is the primary cause of climate change, according to the scientific consensus?","What are some consequences of climate change?","What are some ways countries have responded to the threat of climate change?","What is the author's attitude towards the future of addressing climate change?",],
            q_sel:[[" Changes in temperature only"," Changes in temperature and precipitation only"," Changes in temperature, precipitation, and wind patterns, among others"," Changes in wind patterns only",],[" Volcanic activity"," Solar radiation"," Human activities, particularly the burning of fossil fuels"," A combination of natural and human factors",],[" Improved public health"," Decreased frequency of extreme weather events"," Damage to infrastructure, property, and crops due to extreme weather events"," Increased availability of natural resources",],[" Increasing the burning of fossil fuels"," Investingin renewable energy sources"," Encouraging the use of single-use plastics"," Decreasing public transportation options",],[" Pessimistic"," Optimistic"," Ambivalent"," Uncertain",],],
            q_ex: ["文章中说明了气候变化包括许多方面的长期变化，包括温度、降水和风等方面的变化。因此，答案为C。","文章指出，虽然自然因素如火山活动和太阳辐射也会对气候变化作出贡献，但压倒性的科学共识是人类活动，尤其是化石燃料的燃烧是当前气候变化的主要原因。因此，答案为C。","文章中提到，气候变化的后果是广泛而深远的，包括极端天气事件，如飓风、洪水和干旱，进而可能对基础设施、财产和作物造成重大破坏。因此，答案为C。","文章提到，为了应对气候变化的威胁，许多国家已经采取了行动，包括投资于可再生能源，提高能源效率，以及促进公共交通和电动汽车的使用。因此，答案为B。","文章中提到，虽然应对气候变化的挑战仍然存在，但是由于各国和个人正致力于实现更可持续的未来，因此有希望。这表明作者对应对气候变化的未来持乐观态度。因此，答案为B。",],
            q_a: [" C"," C"," C"," B"," B",],
            zh: "近年来，气候变化的概念已成为一个日益紧迫的问题。气候变化是指地球气候的长期变化，包括温度、降水和风型等的变化。虽然火山活动和太阳辐射等自然因素会导致气候变化，但压倒性的科学共识是人类活动，特别是化石燃料的燃烧，是当前趋势的主要原因。气候变化的后果是巨大而深远的-达到。气温上升会导致飓风、洪水和干旱等极端天气事件，进而对基础设施、财产和农作物造成重大破坏。冰盖融化和海平面上升可能导致生活在低洼沿海地区的社区流离失所。气候变化还会对公共卫生产生负面影响，例如疾病的传播和现有健康状况的恶化。为应对气候变化的威胁，许多国家已采取行动减少温室气体排放并向更可持续的转型能量形式。这些努力包括投资风能和太阳能等可再生能源，提高能源效率，以及推广公共交通和电动汽车。尽管要应对气候变化的挑战还有很多工作要做，但随着各国和个人朝着更可持续的未来努力，我们有理由抱有希望。"
        },{
            ar: "The Importance of SleepWe all know that getting a good night's sleep is important, but many of us still don't get enough sleep on a regular basis. In fact, studies have shown that more than one-third of American adults do not get the recommended seven hours of sleep each night.Lack of sleep can have a variety of negative effects on both our physical and mental health. For example, it can increase the risk of developing chronic health conditions such as obesity, diabetes, and cardiovascular disease. It can also impair our immune system, making us more susceptible to illnesses.In addition to these physical health effects, lack of sleep can also affect our mental health. It can lead to problems with mood regulation, making us more irritable, anxious, and depressed. It can also impair cognitive function, making it harder to concentrate, learn, and remember things.So how can we improve our sleep habits? Here are some tips:Stick to a regular sleep schedule. Go to bed and wake up at the same time every day, even on weekends.Create a relaxing sleep environment. Keep your bedroom dark, quiet, and cool, and avoid using electronic devices before bed.Avoid caffeine, nicotine, and alcohol before bedtime, as they can disrupt your sleep.Get regular exercise, but avoid exercising too close to bedtime.If you have trouble sleeping, try relaxation techniques such as deep breathing or meditation, or consider talking to a healthcare professional about sleep aids.",
            q: ["What is the main idea of the passage?","According to the passage, what are some physical health effects of lack of sleep?","What is the author's advice for creating a relaxing sleep environment?","According to the passage, what is one potential consequence of impaired cognitive function due to lack of sleep?","What is the author's advice for improving sleep habits?",],
            q_sel:[[" Lack of sleep can have negative effects on physical health."," Lack of sleep can have negative effects on mental health."," Lack of sleep is a problem for many Americans."," Getting a good night's sleep is important.",],[" Increased risk of developing depression."," Impaired cognitive function."," Increased risk of developing cardiovascular disease."," Difficulty concentrating.",],[" Use electronic devices before bed."," Keep the bedroom warm and bright."," Avoid noise in the bedroom."," Keep the bedroom cool and dark.",],[" Increased risk of developing obesity."," Difficulty concentrating and learning."," Higher susceptibility to illnesses."," Problems with mood regulation.",],[" Drink alcohol before bedtime."," Exercise right before going to bed."," Stick to a regular sleep schedule."," Use electronic devices in bed.",],],
            q_ex: ["文章一开始就提到了睡眠的重要性，后面的内容也在强调睡眠的好处以及如何改善睡眠习惯。因此，答案为D。","文章提到，缺乏睡眠可以增加患上慢性疾病（例如肥胖症、糖尿病和心血管疾病）的风险。因此，答案为C。","文章提到了创建一个放松的睡眠环境的建议，其中包括保持卧室凉爽、黑暗以及避免在睡前使用电子设备。因此，答案为D。","文章提到了缺乏睡眠对认知功能的影响，可能会让人难以集中注意力、学习和记忆。因此，答案为B。","文章提到了改善睡眠习惯的建议，其中包括保持规律的睡眠时间表，晚上睡前避免饮用咖啡因、尼古丁和酒精，以及避免在睡前使用电子设备。因此，答案为C。",],
            q_a: [" D"," C"," D"," B"," C",],
            zh: "睡眠的重要性我们都知道睡个好觉很重要，但我们中的许多人仍然没有定期获得足够的睡眠。事实上，研究表明，超过三分之一的美国成年人每晚没有达到建议的七小时睡眠时间。睡眠不足会对我们的身心健康产生各种负面影响。例如，它会增加患肥胖症、糖尿病和心血管疾病等慢性疾病的风险。它还会损害我们的免疫系统，使我们更容易生病。除了这些身体健康影响外，睡眠不足还会影响我们的心理健康。它会导致情绪调节问题，使我们更加易怒、焦虑和抑郁。它还会损害认知功能，使注意力、学习和记忆变得更加困难。那么我们如何改善睡眠习惯呢？这里有一些提示： 坚持规律的睡眠时间表。每天在同一时间睡觉和起床，周末也不例外。营造轻松的睡眠环境。保持卧室黑暗、安静和凉爽，睡前避免使用电子设备。睡前避免咖啡因、尼古丁和酒精，因为它们会扰乱您的睡眠。定期锻炼，但避免在临睡前锻炼。如果您有睡眠困难，尝试放松技巧，如深呼吸或冥想，或考虑与医疗保健专业人员讨论助眠剂。"
        },{
            ar: "In recent years, there has been a growing interest in plant-based diets. Advocates of these diets argue that they are healthier for both people and the planet. But are plant-based diets really better? Let's take a closer look.One of the main benefits of plant-based diets is that they tend to be lower in saturated fats and higher in fiber, vitamins, and minerals. This can help reduce the risk of heart disease, stroke, and certain types of cancer. Plant-based diets have also been shown to be effective for weight loss and improving overall health.However, some people worry that plant-based diets might not provide all of the necessary nutrients, especially for people who are pregnant, breastfeeding, or have certain health conditions. For example, plant-based diets may not provide enough protein, calcium, or vitamin B12.Another concern is that some plant-based foods, such as soy and nuts, can be allergenic and cause reactions in some people. Additionally, some plant-based diets may not be sustainable in the long-term due to the large amounts of water and other resources needed to produce certain crops.Overall, plant-based diets can be a healthy and sustainable choice for many people. However, it's important to ensure that you are getting all of the necessary nutrients, and to speak with a healthcare professional before making any major dietary changes.",
            q: ["What is the main benefit of plant-based diets according to the passage?","According to the passage, what is a potential concern with plant-based diets?","What is the author's advice regarding plant-based diets?","According to the passage, why might some plant-based diets not be sustainable in the long-term?","What is the author's main purpose in writing this passage?",],
            q_sel:[[" They are lower in fiber and higher in saturated fats."," They can increase the risk of heart disease and stroke."," They can help reduce the risk of certain types of cancer."," They are less effective for weight loss than other diets.",],[" They may not provide enough protein, calcium, or vitamin B12."," They may cause allergic reactions in some people."," They may not be effective for weight loss."," They require more resources to produce than other diets.",],[" Everyone should switch to a plant-based diet immediately."," Plant-based diets are not sustainable in the long-term."," It is important to make sure you are getting all necessary nutrients."," Healthcare professionals do not need to be consulted before making dietary changes.",],[" They require too much time and effort to prepare."," They can cause allergic reactions in some people."," They are less effective for weight loss than other diets."," They require large amounts of water and resources to produce certain crops.",],[" To promote the benefits of a plant-based diet."," To provide a comprehensive guide to different types of diets."," To caution readers about the potential risks and drawbacks of plant-based diets."," To criticize the medical establishment for failing to promote plant-based diets.",],],
            q_ex: ["文章提到，植物性饮食具有降低心脏病、中风和某些癌症风险的益处，因为它们通常含有较少的饱和脂肪，较多的纤维素、维生素和矿物质。因此，答案为C。","文章提到了有些人担心植物性饮食可能无法提供所有必需的营养素，尤其是对于怀孕、哺乳或患有某些健康问题的人。例如，植物性饮食可能无法提供足够的蛋白质、钙或维生素B12。因此，答案为A。","文章提到了如果想要选择植物性饮食，就必须确保自己摄取所有必要的营养素，而且在进行任何重大饮食变化之前应该咨询医疗保健专业人员。因此，答案为C。","文章提到了一些植物性饮食可能在长期内不可持续，这是因为生产某些作物需要大量的水和其他资源。因此，答案为D。","通过本文，作者的主要目的是提醒读者植物性饮食可能存在潜在风险和缺点，并强调重要性以保持均衡的饮食并向医疗保健专业人员咨询。因此，答案为C。",],
            q_a: [" C"," A"," C"," D"," C",],
            zh: "近年来，人们对植物性饮食越来越感兴趣。这些饮食的倡导者认为，它们对人类和地球都更健康。但是植物性饮食真的更好吗？让我们仔细看看。植物性饮食的主要好处之一是它们的饱和脂肪含量往往较低，纤维、维生素和矿物质含量较高。这有助于降低患心脏病、中风和某些类型癌症的风险。植物性饮食也被证明可有效减轻体重和改善整体健康。然而，有些人担心植物性饮食可能无法提供所有必需的营养，尤其是对于孕妇、哺乳期或患有某些疾病的人健康状况。例如，植物性饮食可能无法提供足够的蛋白质、钙或维生素 B12。另一个问题是一些植物性食物，如大豆和坚果，可能会引起过敏并引起某些人的反应。此外，由于生产某些作物需要大量的水和其他资源，一些植物性饮食可能无法长期持续。总的来说，植物性饮食对许多人来说是一种健康和可持续的选择。但是，重要的是要确保您获得所有必需的营养，并在进行任何重大饮食改变之前咨询医疗保健专业人员。"
        },{
            ar: "It’s a common misconception that introverts are shy, antisocial individuals who don’t enjoy socializing. While introverts may not seek out constant social stimulation like their extroverted counterparts, they do enjoy social interaction, albeit in smaller doses.In fact, introverts can be just as social as extroverts, but they simply need more time to recharge after socializing. This is because introverts are more sensitive to external stimuli and tend to be more easily overwhelmed by excessive socializing or sensory input.Introverts also tend to be more reflective and introspective than extroverts, and may prefer to spend time alone with their thoughts rather than engaging in constant external stimulation. This can be mistaken for shyness or aloofness, but in reality, introverts are simply processing and reflecting on their experiences in a deeper way.Despite the common misconception that introverts are at a disadvantage in social situations, introverts can actually be very effective communicators. They tend to be more thoughtful and deliberate in their speech, taking the time to carefully choose their words and express their ideas in a clear and concise manner.Overall, introversion is simply a personality trait that reflects a preference for solitude and introspection, rather than a social deficit or inability to communicate effectively.",
            q: ["According to the passage, what is a common misconception about introverts?","What does the passage suggest about the difference between introverts and extroverts?","What is the main difference between introverts and extroverts in terms of socializing, according to the passage?",],
            q_sel:[[" They are more easily overwhelmed by external stimuli."," They do not enjoy socializing."," They are less effective communicators than extroverts."," They are more reflective and introspective than extroverts.",],[" Introverts need more time to recharge after socializing."," Extroverts are more easily overwhelmed by external stimuli."," Introverts are less thoughtful and deliberate in their speech."," Extroverts are more reflective and introspective than introverts.",],[" Introverts enjoy socializing more than extroverts."," Extroverts need more time to recharge after socializing."," Introverts are more easily overwhelmed by socializing."," There is no difference between introverts and extroverts in terms of socializing.",],],
            q_ex: ["文章开始时提到了关于内向者的一个常见误解，即他们不喜欢社交。因此，答案为B。","根据文章所说，相较于外向者，内向者需要更多时间来重新充电，以应对社交造成的影响。因此，答案为A。","根据文章，相较于外向者，内向者更容易被过度的社交或感官刺激所压垮，因此在进行社交活动时更容易感到不适。因此，答案为C。",],
            q_a: [" B"," A"," C",],
            zh: "一个普遍的误解是，内向的人是害羞的、反社会的，不喜欢社交。虽然内向的人可能不会像外向的人那样寻求持续的社交刺激，但他们确实喜欢社交互动，尽管程度较低。事实上，内向的人可以和外向的人一样社交，只是他们在社交后需要更多的时间来充电。这是因为内向的人对外部刺激更敏感，更容易被过度的社交或感官输入所淹没。内向的人也往往比外向的人更善于反思和内省，并且可能更喜欢花时间独自思考而不是参与不断的外部刺激。这可能会被误认为害羞或冷漠，但实际上，内向的人只是在更深层次地处理和反思他们的经历。尽管人们普遍误解内向的人在社交场合处于劣势，但内向的人实际上可以成为非常有效的沟通者。他们在说话时往往更深思熟虑，花时间仔细选择自己的用词，并以清晰简洁的方式表达自己的想法。总的来说，内向只是一种性格特征，反映了对孤独和内省的偏好，而不是社交缺陷或无法有效沟通。"
        },{
            ar: "As the world becomes more technologically advanced, people are becoming more and more reliant on electronic devices. While these devices can make life easier and more convenient in many ways, there are also downsides to this dependence.One issue is the effect of electronic devices on sleep. Studies have shown that the blue light emitted by screens can interfere with the production of melatonin, a hormone that helps regulate sleep. This can lead to difficulty falling asleep, as well as poor-quality sleep.Another issue is the impact of electronic devices on social interaction. Many people now spend a significant amount of time interacting with others through social media and messaging apps, rather than in-person communication. This can lead to feelings of loneliness and isolation, as well as a lack of important social skills.Despite these downsides, electronic devices are not going anywhere. It is important for individuals to recognize the potential negative effects of these devices and take steps to mitigate them, such as limiting screen time before bed and making an effort to engage in face-to-face communication with others.",
            q: ["What is the main topic of the passage?","What is one negative impact of electronic devices on sleep?","How can overuse of electronic devices affect social skills?","What is the author's main message?","What is one step individuals can take to mitigate the negative effects of electronic devices?",],
            q_sel:[[" The benefits of electronic devices"," The downsides of electronic devices"," The future of electronic devices"," The evolution of electronic devices",],[" Increased production of melatonin"," Improved sleep quality"," Interference with melatonin production"," Increased likelihood of dreaming",],[" It can improve social interaction"," It can lead to feelings of loneliness and isolation"," It can increase face-to-face communication"," It can enhance the ability to read social cues",],[" Electronic devices are all bad"," Electronic devices are all good"," Electronic devices have both benefits and downsides"," Electronic devices will eventually disappear",],[" Increase screen time before bed"," Avoid face-to-face communication"," Use electronic devices more frequently"," Limit screen time before bed",],],
            q_ex: ["文章第一段提到了电子产品的优点，但是整篇文章都是在探讨电子产品的缺点，因此答案为B。","根据文章第二段的描述，电子产品发出的蓝光会干扰褪黑激素的产生，进而影响睡眠，因此答案为C。","文章第三段提到，人们现在花大量的时间透过社交媒体和消息应用程式与他人互动，而不是进行面对面的交流，这会导致孤独感和孤立感，以及缺乏重要的社交技能，因此答案为B。","文章提到了电子产品的缺点，但也指出了电子产品的优点，并强调了个人需要认识到这些设备的潜在负面影响，并采取措施来缓解它们带来的影响，因此答案为C。","文章最后一段建议个人应该认识到电子产品的潜在负面影响，并采取措施来缓解它们带来的影响，其中一个建议就是在睡前限制使用电子产品的时间，因此答案为D。",],
            q_a: [" B"," C"," B"," C"," D",],
            zh: "随着世界技术变得越来越先进，人们越来越依赖电子设备。虽然这些设备可以在许多方面让生活更轻松、更方便，但这种依赖也有不利之处。一个问题是电子设备对睡眠的影响。研究表明，屏幕发出的蓝光会干扰褪黑激素的产生，褪黑激素是一种有助于调节睡眠的激素。这会导致难以入睡，以及睡眠质量差。另一个问题是电子设备对社交互动的影响。许多人现在花费大量时间通过社交媒体和消息应用程序与他人互动，而不是面对面交流。这可能会导致孤独感和孤立感，以及缺乏重要的社交技能。尽管有这些缺点，电子设备仍无处可去。个人必须认识到这些设备的潜在负面影响并采取措施减轻这些影响，例如限制睡前看屏幕的时间并努力与他人进行面对面的交流。"
        },{
            ar: "The human brain is incredibly complex, and there is still much that researchers do not understand about how it works. However, one thing that is clear is that the brain is highly adaptable and capable of change.Neuroplasticity is the term used to describe the brain's ability to reorganize itself in response to new experiences. This can involve creating new neural connections or strengthening existing ones. Neuroplasticity is thought to be a key factor in learning and memory, as well as in recovery from brain injuries.While the brain is capable of neuroplasticity throughout life, the extent to which it can change decreases with age. This means that young children are particularly adept at learning and adapting, while older adults may have more difficulty in these areas.However, there are things that individuals can do to promote neuroplasticity and enhance their brain's ability to adapt. Engaging in activities that are mentally stimulating, such as reading or solving puzzles, is one way to promote neuroplasticity. Physical exercise has also been shown to have a positive impact on brain function and neuroplasticity.",
            q: ["What is the main topic of the passage?","What is neuroplasticity?","How does neuroplasticity impact learning and memory?","What is one way to promote neuroplasticity?",],
            q_sel:[[" The complexity of the human brain"," The role of neuroplasticity in brain function"," The effects of aging on the brain"," The benefits of mental stimulation",],[" The brain's ability to change in response to new experiences"," The brain's ability to maintain the status quo"," The brain's inability to change with age"," The brain's resistance to new experiences",],[" It has no effect on learning and memory"," It makes learning and memory more difficult"," It is a key factor in learning and memory"," It only impacts memory, not learning",],[" Avoid mental stimulation"," Limit physical exercise"," Engage in mentally stimulating activities"," Only engage in physical exercise",],],
            q_ex: ["文章主要在谈论神经可塑性对于大脑功能的影响，因此答案为B。","文章第二段中提到，神经可塑性是大脑对新体验做出反应时重新组织自己的能力，包括建立新的神经连接或加强现有的连接，因此答案为A。","文章中提到神经可塑性是学习和记忆的关键因素之一，因此答案为C。","文章中提到，进行脑力刺激的活动（例如阅读或解决问题）是促进神经可塑性的一种方式，因此答案为C。",],
            q_a: [" B"," A"," C"," C",],
            zh: "人脑极其复杂，研究人员对它的工作原理仍有很多不了解。然而，有一点是明确的，即大脑具有高度的适应性和变化能力。神经可塑性是用来描述大脑重组自身以响应新体验的能力的术语。这可能涉及创建新的神经连接或加强现有的神经连接。神经可塑性被认为是学习和记忆以及脑损伤恢复的关键因素。虽然大脑在整个生命过程中都具有神经可塑性，但它可以改变的程度会随着年龄的增长而降低。这意味着年幼的孩子特别善于学习和适应，而老年人在这些方面可能会遇到更多困难。但是，个人可以做一些事情来促进神经可塑性并增强大脑的适应能力。参与精神刺激的活动，例如阅读或解决难题，是促进神经可塑性的一种方式。体育锻炼也被证明对大脑功能和神经可塑性有积极影响。"
        },{
            ar: "Climate change is a pressing issue that has garnered significant attention in recent years. While there is still debate about the causes and extent of climate change, most scientists agree that it is largely driven by human activities, such as the burning of fossil fuels and deforestation.One of the consequences of climate change is rising sea levels. As temperatures continue to rise, glaciers and ice sheets are melting, causing water to flow into the oceans and contributing to sea level rise. This can have a devastating impact on coastal cities and communities, as well as on wildlife and ecosystems.Another consequence of climate change is extreme weather events, such as heat waves, droughts, and hurricanes. These events can lead to crop failures, water shortages, and infrastructure damage, among other things. They also pose a significant threat to human health and well-being.Addressing climate change requires a coordinated effort from individuals, governments, and businesses around the world. This may involve reducing greenhouse gas emissions, transitioning to renewable energy sources, and investing in technologies that can help mitigate the impacts of climate change.",
            q: ["What is the main topic of the passage?","What are some human activities that are contributing to climate change?","What is one consequence of rising temperatures?","What is one way to address climate change?","What is the author's opinion on climate change?",],
            q_sel:[[" The causes of climate change"," The impacts of climate change"," The debate about climate change"," The role of individuals in addressing climate change",],[" Eating meat and dairy products"," Planting trees and other vegetation"," Burning fossil fuels and deforestation"," Recycling and composting",],[" Decreasing sea levels"," Reduced crop yields"," Increased forest cover"," Improved wildlife habitats",],[" Increase greenhouse gas emissions"," Continue to rely on fossil fuels"," Transition to renewable energy sources"," Build more infrastructure in coastal areas",],[" It is not a significant issue"," It is entirely caused by human activities"," It is a topic of debate among scientists"," It requires a coordinated effort to address",],],
            q_ex: ["文章主要在谈论气候变化对于环境、野生动物和人类社区带来的影响，因此答案为B。","文章中提到，气候变化很大程度上是由人类活动引起的，例如燃烧化石燃料和森林砍伐，因此答案为C。","文章中提到，随着温度持续上升，冰川和冰原融化，导致水流入海洋并促成海平面上升，这对沿海城市和社区以及野生动物和生态系统都会产生毁灭性的影响。因此答案为B。","文章中提到，应对气候变化需要全球个人、政府和企业之间的协调努力，这可能包括减少温室气体排放，转向可再生能源来源以及投资于能减缓气候变化影响的技术等。因此答案为C。","文章作者没有表达对气候变化本身的观点，而是强调需要全球个人、政府和企业之间的协调努力才能应对气候变化。因此答案为D。",],
            q_a: [" B"," C"," B"," C"," D",],
            zh: "气候变化是一个紧迫的问题，近年来引起了广泛关注。尽管对气候变化的原因和程度仍有争论，但大多数科学家都认为，气候变化主要是由人类活动驱动的，例如燃烧化石燃料和砍伐森林。气候变化的后果之一是海平面上升。随着气温持续上升，冰川和冰原正在融化，导致水流入海洋并导致海平面上升。这会对沿海城市和社区以及野生动物和生态系统产生毁灭性影响。气候变化的另一个后果是极端天气事件，例如热浪、干旱和飓风。这些事件可能导致作物歉收、缺水和基础设施损坏等。它们还对人类健康和福祉构成重大威胁。应对气候变化需要全世界个人、政府和企业的协调努力。这可能涉及减少温室气体排放、转向可再生能源以及投资有助于减轻气候变化影响的技术。"
        },{
            ar: "In recent years, social media has become an integral part of many people's lives. Social media platforms such as Facebook, Twitter, and Instagram allow individuals to connect with others, share information and opinions, and stay up-to-date with the latest news and trends.While social media has many benefits, there are also concerns about its impact on mental health. Studies have found that excessive social media use can lead to feelings of loneliness, anxiety, and depression. This is partly due to the fact that social media often presents an idealized version of reality, which can lead to feelings of inadequacy and low self-esteem.Another concern is the spread of misinformation and fake news on social media. With the ability for anyone to publish and share information, it can be difficult to distinguish between fact and fiction. This can lead to confusion, anxiety, and even harm if individuals make decisions based on false information.Despite these concerns, social media remains a popular and influential medium. As such, it is important for individuals to use social media responsibly and critically evaluate the information they encounter online.",
            q: ["What is the main topic of the passage?","What are some negative impacts of excessive social media use?","What is one concern about the spread of information on social media?","What is one way to use social media responsibly?","What is the author's overall attitude towards social media?",],
            q_sel:[[" The benefits of social media"," The impact of social media on mental health"," The spread of misinformation on social media"," The popularity of social media",],[" Improved self-esteem and mental well-being"," Increased feelings of connectedness and social support"," Feelings of loneliness, anxiety, and depression"," Improved ability to distinguish between fact and fiction",],[" The lack of access to information"," The inability to connect with others"," The spread of misinformation and fake news"," The cost of using social media",],[" Post without considering the impact on others"," Share all information encountered online"," Critically evaluate information encountered online"," Spend excessive amounts",],[" Positive"," Negative"," Neutral"," Ambivalent",],],
            q_ex: ["文章主要在谈论社交媒体对于精神健康的影响，提到社交媒体的好处和担忧，并强调了社交媒体使用的责任。因此答案为B。","文章中提到，过度使用社交媒体可能会导致孤独、焦虑和抑郁等负面情绪，部分原因是社交媒体经常呈现现实的理想化版本，这可能会导致自尊心和自我价值感的不足。因此答案为C。","文章中提到，社交媒体上的误解和虚假新闻可能会导致混淆、焦虑，甚至造成伤害，如果个人基于错误信息做出决定。因此答案为C。","文章强调了使用社交媒体的责任，个人应该批判性地评估在线遇到的信息。因此，答案为C。","作者在文章中提到社交媒体的好处和担忧，并强调了社交媒体使用的责任。因此，作者的态度是矛盾的（ambivalent），既有正面的看法，也有担忧。因此答案为D。",],
            q_a: [" B"," C"," C"," C"," D",],
            zh: "近年来，社交媒体已成为许多人生活中不可或缺的一部分。 Facebook、Twitter 和 Instagram 等社交媒体平台允许个人与他人联系、分享信息和观点，并及时了解最新消息和趋势。虽然社交媒体有很多好处，但也有人担心它对心理健康的影响。研究发现，过度使用社交媒体会导致孤独、焦虑和抑郁的感觉。部分原因是社交媒体经常呈现理想化的现实版本，这会导致自卑感和自卑感。另一个担忧是社交媒体上错误信息和假新闻的传播。由于任何人都可以发布和共享信息，因此很难区分事实和虚构。如果个人根据虚假信息做出决定，这可能会导致混乱、焦虑甚至伤害。尽管存在这些担忧，社交媒体仍然是一种流行且有影响力的媒体。因此，个人负责任地使用社交媒体并批判性地评估他们在网上遇到的信息非常重要。"
        },{
            ar: "The concept of climate change has become an increasingly pressing issue in recent years. Climate change refers to the long-term changes in Earth's climate, including changes in temperature, precipitation, and wind patterns, among others. While natural factors such as volcanic activity and solar radiation can contribute to climate change, the overwhelming scientific consensus is that human activities, particularly the burning of fossil fuels, are the primary cause of the current trend.The consequences of climate change are vast and far-reaching. Rising temperatures can lead to extreme weather events such as hurricanes, floods, and droughts, which in turn can cause significant damage to infrastructure, property, and crops. Melting ice caps and rising sea levels can lead to the displacement of communities living in low-lying coastal areas. Climate change can also have negative impacts on public health, such as the spread of diseases and the exacerbation of existing health conditions.In response to the threat of climate change, many countries have taken action to reduce their greenhouse gas emissions and transition to more sustainable forms of energy. These efforts include investing in renewable energy sources such as wind and solar power, improving energy efficiency, and promoting public transportation and electric vehicles. While much remains to be done to address the challenges of climate change, there is reason for hope as countries and individuals work towards a more sustainable future.",
            q: ["What is climate change?","What is the primary cause of climate change, according to the scientific consensus?","What are some consequences of climate change?","What are some ways countries have responded to the threat of climate change?","What is the author's attitude towards the future of addressing climate change?",],
            q_sel:[[" Changes in temperature only"," Changes in temperature and precipitation only"," Changes in temperature, precipitation, and wind patterns, among others"," Changes in wind patterns only",],[" Volcanic activity"," Solar radiation"," Human activities, particularly the burning of fossil fuels"," A combination of natural and human factors",],[" Improved public health"," Decreased frequency of extreme weather events"," Damage to infrastructure, property, and crops due to extreme weather events"," Increased availability of natural resources",],[" Increasing the burning of fossil fuels"," Investing in renewable energy sources"," Encouraging the use of single-use plastics"," Decreasing public transportation options",],[" Pessimistic"," Optimistic"," Ambivalent"," Uncertain",],],
            q_ex: ["文章中说明了气候变化包括许多方面的长期变化，包括温度、降水和风等方面的变化。因此，答案为C。","文章指出，虽然自然因素如火山活动和太阳辐射也会对气候变化作出贡献，但压倒性的科学共识是人类活动，尤其是化石燃料的燃烧是当前气候变化的主要原因。因此，答案为C。","文章中提到，气候变化的后果是广泛而深远的，包括极端天气事件，如飓风、洪水和干旱，进而可能对基础设施、财产和作物造成重大破坏。因此，答案为C。","文章提到，为了应对气候变化的威胁，许多国家已经采取了行动，包括投资于可再生能源，提高能源效率，以及促进公共交通和电动汽车的使用。因此，答案为B。","文章中提到，虽然应对气候变化的挑战仍然存在，但是由于各国和个人正致力于实现更可持续的未来，因此有希望。这表明作者对应对气候变化的未来持乐观态度。因此，答案为B。",],
            q_a: [" C"," C"," C"," B"," B",],
            zh: "近年来，气候变化的概念已成为一个日益紧迫的问题。气候变化是指地球气候的长期变化，包括温度、降水和风型等的变化。虽然火山活动和太阳辐射等自然因素会导致气候变化，但压倒性的科学共识是人类活动，特别是化石燃料的燃烧，是当前趋势的主要原因。气候变化的后果是巨大而深远的-达到。气温上升会导致飓风、洪水和干旱等极端天气事件，进而对基础设施、财产和农作物造成重大破坏。冰盖融化和海平面上升可能导致生活在低洼沿海地区的社区流离失所。气候变化还会对公共卫生产生负面影响，例如疾病的传播和现有健康状况的恶化。为应对气候变化的威胁，许多国家已采取行动减少温室气体排放并向更可持续的转型能量形式。这些努力包括投资风能和太阳能等可再生能源，提高能源效率，以及推广公共交通和电动汽车。尽管要应对气候变化的挑战还有很多工作要做，但随着各国和个人朝着更可持续的未来努力，我们有理由抱有希望。"
        },{
            ar: "The Importance of SleepWe all know that getting a good night's sleep is important, but many of us still don't get enough sleep on a regular basis. In fact, studies have shown that more than one-third of American adults do not get the recommended seven hours of sleep each night.Lack of sleep can have a variety of negative effects on both our physical and mental health. For example, it can increase the risk of developing chronic health conditions such as obesity, diabetes, and cardiovascular disease. It can also impair our immune system, making us more susceptible to illnesses.In addition to these physical health effects, lack of sleep can also affect our mental health. It can lead to problems with mood regulation, making us more irritable, anxious, and depressed. It can also impair cognitive function, making it harder to concentrate, learn, and remember things.So how can we improve our sleep habits? Here are some tips:Stick to a regular sleep schedule. Go to bed and wake up at the same time every day, even on weekends.Create a relaxing sleep environment. Keep your bedroom dark, quiet, and cool, and avoid using electronic devices before bed.Avoid caffeine, nicotine, and alcohol before bedtime, as they can disrupt your sleep.Get regular exercise, but avoid exercising too close to bedtime.If you have trouble sleeping, try relaxation techniques such as deep breathing or meditation, or consider talking to a healthcare professional about sleep aids.",
            q: ["What is the main idea of the passage?","According to the passage, what are some physical health effects of lack of sleep?","What is the author's advice for creating a relaxing sleep environment?","According to the passage, what is one potential consequence of impaired cognitive function due to lack of sleep?","What is the author's advice for improving sleep habits?",],
            q_sel:[[" Lack of sleep can have negative effects on physical health."," Lack of sleep can have negative effects on mental health."," Lack of sleep is a problem for many Americans."," Getting a good night's sleep is important.",],[" Increased risk of developing depression."," Impaired cognitive function."," Increased risk of developing cardiovascular disease."," Difficulty concentrating.",],[" Use electronic devices before bed."," Keep the bedroom warm and bright."," Avoid noise in the bedroom."," Keep the bedroom cool and dark.",],[" Increased risk of developing obesity."," Difficulty concentrating and learning."," Higher susceptibility to illnesses."," Problems with mood regulation.",],[" Drink alcohol before bedtime."," Exercise right before going to bed."," Stick to a regular sleep schedule."," Use electronic devices in bed.",],],
            q_ex: ["文章一开始就提到了睡眠的重要性，后面的内容也在强调睡眠的好处以及如何改善睡眠习惯。因此，答案为D。","文章提到，缺乏睡眠可以增加患上慢性疾病（例如肥胖症、糖尿病和心血管疾病）的风险。因此，答案为C。","文章提到了创建一个放松的睡眠环境的建议，其中包括保持卧室凉爽、黑暗以及避免在睡前使用电子设备。因此，答案为D。","文章提到了缺乏睡眠对认知功能的影响，可能会让人难以集中注意力、学习和记忆。因此，答案为B。","文章提到了改善睡眠习惯的建议，其中包括保持规律的睡眠时间表，晚上睡前避免饮用咖啡因、尼古丁和酒精，以及避免在睡前使用电子设备。因此，答案为C。",],
            q_a: [" D"," C"," D"," B"," C",],
            zh: "睡眠的重要性我们都知道睡个好觉很重要，但我们中的许多人仍然没有定期获得足够的睡眠。事实上，研究表明，超过三分之一的美国成年人每晚没有达到建议的七小时睡眠时间。睡眠不足会对我们的身心健康产生各种负面影响。例如，它会增加患肥胖症、糖尿病和心血管疾病等慢性疾病的风险。它还会损害我们的免疫系统，使我们更容易生病。除了这些身体健康影响外，睡眠不足还会影响我们的心理健康。它会导致情绪调节问题，使我们更加易怒、焦虑和抑郁。它还会损害认知功能，使注意力、学习和记忆变得更加困难。那么我们如何改善睡眠习惯呢？这里有一些提示： 坚持规律的睡眠时间表。每天在同一时间睡觉和起床，周末也不例外。营造轻松的睡眠环境。保持卧室黑暗、安静和凉爽，睡前避免使用电子设备。睡前避免咖啡因、尼古丁和酒精，因为它们会扰乱您的睡眠。定期锻炼，但避免在临睡前锻炼。如果您有睡眠困难，尝试放松技巧，如深呼吸或冥想，或考虑与医疗保健专业人员讨论助眠剂。"
        },{
            ar: "It’s a common misconception that introverts are shy, antisocial individuals who don’t enjoy socializing. While introverts may not seek out constant social stimulation like their extroverted counterparts, they do enjoy social interaction, albeit in smaller doses.In fact, introverts can be just as social as extroverts, but they simply need more time to recharge after socializing. This is because introverts are more sensitive to external stimuli and tend to be more easily overwhelmed by excessive socializing or sensory input.Introverts also tend to be more reflective and introspective than extroverts, and may prefer to spend time alone with their thoughts rather than engaging in constant external stimulation. This can be mistaken for shyness or aloofness, but in reality, introverts are simply processing and reflecting on their experiences in a deeper way.Despite the common misconception that introverts are at a disadvantage in social situations, introverts can actually be very effective communicators. They tend to be more thoughtful and deliberate in their speech, taking the time to carefully choose their words and express their ideas in a clear and concise manner.Overall, introversion is simply a personality trait that reflects a preference for solitude and introspection, rather than a social deficit or inability to communicate effectively.",
            q: ["According to the passage, what is a common misconception about introverts?","What does the passage suggest about the difference between introverts and extroverts?","What is the main difference between introverts and extroverts in terms of socializing, according to the passage?",],
            q_sel:[[" They are more easily overwhelmed by external stimuli."," They do not enjoy socializing."," They are less effective communicators than extroverts."," They are more reflective and introspective than extroverts.",],[" Introverts need more time to recharge after socializing."," Extroverts are more easily overwhelmed by external stimuli."," Introverts are less thoughtful and deliberate in their speech."," Extroverts are more reflective and introspective than introverts.",],[" Introverts enjoy socializing more than extroverts."," Extroverts need more time to recharge after socializing."," Introverts are more easily overwhelmed by socializing."," There is no difference between introverts and extroverts in terms of socializing.",],],
            q_ex: ["文章开始时提到了关于内向者的一个常见误解，即他们不喜欢社交。因此，答案为B。","根据文章所说，相较于外向者，内向者需要更多时间来重新充电，以应对社交造成的影响。因此，答案为A。","根据文章，相较于外向者，内向者更容易被过度的社交或感官刺激所压垮，因此在进行社交活动时更容易感到不适。因此，答案为C。",],
            q_a: [" B"," A"," C",],
            zh: "一个普遍的误解是，内向的人是害羞的、反社会的，不喜欢社交。虽然内向的人可能不会像外向的人那样寻求持续的社交刺激social media and messaging apps, rather than in-person communication. This can lead to feelings of loneliness and isolation, as well as a lack of important social skills.Despite these downsides, electronic devices are not going anywhere. It is important for individuals to recognize the potential negative effects of these devices and take steps to mitigate them, such as limiting screen time before bed and making an eff，但他们确实喜欢社交互动，尽管程度较低。事实上，内向的人可以和外向的人一样社交，只是他们在社交后需要更多的时间来充电。这是因为内向的人对外部刺激更敏感，更容易被过度的社交或感官输入所淹没。内向的人也往往比外向的人更善于反思和内省，并且可能更喜欢花时间独自思考而不是参与不断的外部刺激。这可能会被误认为害羞或冷漠，但实际上，内向的人只是在更深层次地处理和反思他们的经历。尽管人们普遍误解内向的人在社交场合处于劣势，但内向的人实际上可以成为非常有效的沟通者。他们在说话时往往更深思熟虑，花时间仔细选择自己的用词，并以清晰简洁的方式表达自己的想法。总的来说，内向只是一种性格特征，反映了对孤独和内省的偏好，而不是社交缺陷或无法有效沟通。"
        },{
            ar: "As the world becomes more technologically advanced, people are becoming more and more reliant on electronic devices. While these devices can make life easier and more convenient in many ways, there are also downsides to this dependence.One issue is the effect of electronic devices on sleep. Studies have shown that the blue light emitted by screens can interfere with the production of melatonin, a hormone that helps regulate sleep. This can lead to difficulty falling asleep, as well as poor-quality sleep.Another issue is the impact of electronic devices on social interaction. Many people now spend a significant amount of time interacting with others through ort to engage in face-to-face communication with others.",
            q: ["What is the main topic of the passage?","What is one negative impact of electronic devices on sleep?","How can overuse of electronic devices affect social skills?","What is the author's main message?","What is one step individuals can take to mitigate the negative effects of electronic devices?",],
            q_sel:[[" The benefits of electronic devices"," The downsides of electronic devices"," The future of electronic devices"," The evolution of electronic devices",],[" Increased production of melatonin"," Improved sleep quality"," Interference with melatonin production"," Increased likelihood of dreaming",],[" It can improve social interaction"," It can lead to feelings of loneliness and isolation"," It can increase face-to-face communication"," It can enhance the ability to read social cues",],[" Electronic devices are all bad"," Electronic devices are all good"," Electronic devices have both benefits and downsides"," Electronic devices will eventually disappear",],[" Increase screen time before bed"," Avoid face-to-face communication"," Use electronic devices more frequently"," Limit screen time before bed",],],
            q_ex: ["文章第一段提到了电子产品的优点，但是整篇文章都是在探讨电子产品的缺点，因此答案为B。","根据文章第二段的描述，电子产品发出的蓝光会干扰褪黑激素的产生，进而影响睡眠，因此答案为C。","文章第三段提到，人们现在花大量的时间透过社交媒体和消息应用程式与他人互动，而不是进行面对面的交流，这会导致孤独感和孤立感，以及缺乏重要的社交技能，因此答案为B。","文章提到了电子产品的缺点，但也指出了电子产品的优点，并强调了个人需要认识到这些设备的潜在负面影响，并采取措施来缓解它们带来的影响，因此答案为C。","文章最后一段建议个人应该认识到电子产品的潜在负面影响，并采取措施来缓解它们带来的影响，其中一个建议就是在睡前限制使用电子产品的时间，因此答案为D。",],
            q_a: [" B"," C"," B"," C"," D",],
            zh: "随着世界技术变得越来越先进，人们越来越依赖电子设备。虽然这些设备可以在许多方面让生活更轻松、更方便，但这种依赖也有不利之处。一个问题是电子设备对睡眠的影响。研究表明，屏幕发出的蓝光会干扰褪黑激素的产生，褪黑激素是一种有助于调节睡眠的激素。这会导致难以入睡，以及睡眠质量差。另一个问题是电子设备对社交互动的影响。许多人现在花费大量时间通过社交媒体和消息应用程序与他人互动，而不是面对面交流。这可能会导致孤独感和孤立感，以及缺乏重要的社交技能。尽管有这些缺点，电子设备仍无处可去。个人必须认识到这些设备的潜在负面影响并采取措施减轻这些影响，例如限制睡前看屏幕的时间并努力与他人进行面对面的交流。"
        },{
            ar: "The human brain is incredibly complex, and there is still much that researchers do not understand about how it works. However, one thing that is clear is that the brain is highly adaptable and capable of change.Neuroplasticity is the term used to describe the brain's ability to reorganize itself in response to new experiences. This can involve creating new neural connections or strengthening existing ones. Neuroplasticity is thought to be a key factor in learning and memory, as well as in recovery from brain injuries.While the brain is capable of neuroplasticity throughout life, the extent to which it can change decreases with age. This means that young children are particularly adept at learning and adapting, while older adults may have more difficulty in these areas.However, there are things that individuals can do to promote neuroplasticity and enhance their brain's ability to adapt. Engaging in activities that are mentally stimulating, such as reading or solving puzzles, is one way to promote neuroplasticity. Physical exercise has also been shown to have a positive impact on brain function and neuroplasticity.",
            q: ["What is the main topic of the passage?","What is neuroplasticity?","How does neuroplasticity impact learning and memory?","What is one way to promote neuroplasticity?",],
            q_sel:[[" The complexity of the human brain"," The role of neuroplasticity in brain function"," The effects of aging on the brain"," The benefits of mental stimulation",],[" The brain's ability to change in response to new experiences"," The brain's ability to maintain the status quo"," The brain's inability to change with age"," The brain's resistance to new experiences",],[" It has no effect on learning and memory"," It makes learning and memory more difficult"," It is a key factor in learning and memory"," It only impacts memory, not learning",],[" Avoid mental stimulation"," Limit physical exercise"," Engage in mentally stimulating activities"," Only engage in physical exercise",],],
            q_ex: ["文章主要在谈论神经可塑性对于大脑功能的影响，因此答案为B。","文章第二段中提到，神经可塑性是大脑对新体验做出反应时重新组织自己的能力，包括建立新的神经连接或加强现有的连接，因此答案为A。","文章中提到神经可塑性是学习和记忆的关键因素之一，因此答案为C。","文章中提到，进行脑力刺激的活动（例如阅读或解决问题）是促进神经可塑性的一种方式，因此答案为C。",],
            q_a: [" B"," A"," C"," C",],
            zh: "人脑极其复杂，研究人员对它的工作原理仍有很多不了解。然而，有一点是明确的，即大脑具有高度的适应性和变化能力。神经可塑性是用来描述大脑重组自身以响应新体验的能力的术语。这可能涉及创建新的神经连接或加强现有的神经连接。神经可塑性被认为是学习和记忆以及脑损伤恢复的关键因素。虽然大脑在整个生命过程中都具有神经可塑性，但它可以改变的程度会随着年龄的增长而降低。这意味着年幼的孩子特别善于学习和适应，而老年人在这些方面可能会遇到更多困难。但是，个人可以做一些事情来促进神经可塑性并增强大脑的适应能力。参与精神刺激的活动，例如阅读或解决难题，是促进神经可塑性的一种方式。体育锻炼也被证明对大脑功能和神经可塑性有积极影响。"
        },{
            ar: "Climate change is a pressing issue that has garnered significant attention in recent years. While there is still debate about the causes and extent of climate change, most scientists agree that it is largely driven by human activities, such as the burning of fossil fuels and deforestation.One of the consequences of climate change is rising sea levels. As temperatures continue to rise, glaciers and ice sheets are melting, causing water to flow into the oceans and contributing to sea level rise. This can have a devastating impact on coastal cities and communities, as well as on wildlife and ecosystems.Another consequence of climate change is extreme weather events, such as heat waves, droughts, and hurricanes. These events can lead to crop failures, water shortages, and infrastructure damage, among other things. They also pose a significant threat to human health and well-being.Addressing climate change requires a coordinated effort from individuals, governments, and businesses around the world. This may involve reducing greenhouse gas emissions, transitioning to renewable energy sources, and investing in technologies that can help mitigate the impacts of climate change.",
            q: ["What is the main topic of the passage?","What are some human activities that are contributing to climate change?","What is one consequence of rising temperatures?","What is one way to address climate change?","What is the author's opinion on climate change?",],
            q_sel:[[" The causes of climate change"," The impacts of climate change"," The debate about climate change"," The role of individuals in addressing climate change",],[" Eating meat and dairy products"," Planting trees and other vegetation"," Burning fossil fuels and deforestation"," Recycling and composting",],[" Decreasing sea levels"," Reduced crop yields"," Increased forest cover"," Improved wildlife habitats",],[" Increase greenhouse gas emissions"," Continue to rely on fossil fuels"," Transition to renewable energy sources"," Build more infrastructure in coastal areas",],[" It is not a significant issue"," It is entirely caused by human activities"," It is a topic of debate among scientists"," It requires a coordinated effort to address",],],
            q_ex: ["文章主要在谈论气候变化对于环境、野生动物和人类社区带来的影响，因此答案为B。","文章中提到，气候变化很大程度上是由人类活动引起的，例如燃烧化石燃料和森林砍伐，因此答案为C。","文章中提到，随着温度持续上升，冰川和冰原融化，导致水流入海洋并促成海平面上升，这对沿海城市和社区以及野生动物和生态系统都会产生毁灭性的影响。因此答案为B。","文章中提到，应对气候变化需要全球个人、政府和企业之间的协调努力，这可能包括减少温室气体排放，转向可再生能源来源以及投资于能减缓气候变化影响的技术等。因此答案为C。","文章作者没有表达对气候变化本身的观点，而是强调需要全球个人、政府和企业之间的协调努力才能应对气候变化。因此答案为D。",],
            q_a: [" B"," C"," B"," C"," D",],
            zh: "气候变化是一个紧迫的问题，近年来引起了广泛关注。尽管对气候变化的原因和程度仍有争论，但大多数科学家都认为，气候变化主要是由人类活动驱动的，例如燃烧化石燃料和砍伐森林。气候变化的后果之一是海平面上升。随着气温持续上升，冰川和冰原正在融化，导致水流入海洋并导致海平面上升。这会对沿海城市和社区以及野生动物和生态系统产生毁灭性影响。气候变化的另一个后果是极端天气事件，例如热浪、干旱和飓风。这些事件可能导致作物歉收、缺水和基础设施损坏等。它们还对人类健康和福祉构成重大威胁。应对气候变化需要全世界个人、政府和企业的协调努力。这可能涉及减少温室气体排放、转向可再生能源以及投资有助于减轻气候变化影响的技术。"
        },{
            ar: "For many years, scientists have been trying to find a cure for cancer. They have made some progress, but they still have not found a complete cure. However, there are ways to reduce the risk of getting cancer. One of these ways is to have a healthy diet.Eating a healthy diet is important for many reasons. A healthy diet can help you maintain a healthy weight, which is important because being overweight can increase your risk of cancer. A healthy diet can also provide your body with the nutrients it needs to fight off cancer.So what is a healthy diet? A healthy diet is one that is high in fruits, vegetables, whole grains, and lean protein. It is also low in saturated and trans fats, processed foods, and sugar. Eating a healthy diet can be challenging, but there are many resources available to help you make the right choices.In addition to eating a healthy diet, there are other things you can do to reduce your risk of cancer. These include exercising regularly, not smoking, and protecting your skin from the sun. By making these healthy choices, you can reduce your risk of cancer and improve your overall health.",
            q: ["What have scientists been trying to find for many years?","What are the benefits of eating a healthy diet?","What should a healthy diet be low in?","What are some other ways to reduce the risk of cancer?",],
            q_sel:[[" A complete cure for cancer."," A way to reduce the risk of cancer."," A healthy diet."," A bed diet.",],[" Maintaining a healthy weight and providing the body with the nutrients it needs."," Reducing the risk of smoking and protecting the skin from the sun."," Eating lean protein and avoiding processed foods."," Trying to find a cure for cancer.",],[" Fruits, vegetables, and whole grains."," Saturated and trans fats, processed foods, and sugar."," Lean protein."," A healthy diet can help you maintain a healthy weight.",],[" Eating a healthy diet and exercising regularly."," Smoking and protecting the skin from the sun."," Drinking alcohol and eating processed foods."," Reduce your risk of cancer.",],],
            q_ex: ["根据文章第一句话'For many years, scientists have been trying to find a cure for cancer.'可知科学家多年来一直在寻找治愈癌症的方法，而本段的主要内容是讲述吃健康饮食可以降低患癌症的风险，因此答案为A。","根据文章第二段的内容，一个健康的饮食可以帮助人们保持健康的体重，同时也能提供身体所需的营养素，因此答案为A。","根据文章第三段的内容，一个健康的饮食应该低于饱和和反式脂肪、加工食品和糖，因此答案为B。","根据文章第四段的内容，健康饮食和定期锻炼，可以降低患癌症的风险，因此答案为A。",],
            q_a: [" A"," A"," B"," A",],
            zh: "多年来，科学家们一直在努力寻找治疗癌症的方法。他们取得了一些进展，但仍未找到彻底治愈的方法。但是，有一些方法可以降低患癌症的风险。其中一种方法是健康饮食。出于多种原因，健康饮食很重要。健康的饮食可以帮助您保持健康的体重，这很重要，因为超重会增加患癌症的风险。健康的饮食还可以为您的身体提供抗癌所需的营养。那么什么是健康的饮食呢？健康的饮食是富含水果、蔬菜、全谷物和瘦肉蛋白的饮食。它的饱和脂肪和反式脂肪、加工食品和糖含量也很低。健康饮食可能具有挑战性，但有许多资源可以帮助您做出正确的选择。除了健康饮食之外，您还可以采取其他措施来降低患癌症的风险。这些措施包括定期锻炼、不吸烟和保护皮肤免受阳光照射。通过做出这些健康的选择，您可以降低患癌症的风险并改善整体健康状况。"
        },{
            ar: "The Great Barrier Reef is a natural wonder located off the coast of Australia. It is the largest coral reef system in the world, stretching over 2,300 kilometers. The Great Barrier Reef is home to thousands of species of marine life, including sea turtles, dolphins, and over 1,500 species of fish.Unfortunately, the Great Barrier Reef is facing many threats. Climate change is causing the water temperatures to rise, which is bleaching the coral and killing off many of the marine species that live there. Pollution from land-based activities is also damaging the reef. This includes pollution from agricultural runoff, sewage, and industrial waste.To help protect the Great Barrier Reef, the Australian government has implemented several initiatives. These include reducing carbon emissions, improving water quality, and reducing the amount of pollution that enters the reef. There are also many conservation organizations that are working to protect the reef, such as the Great Barrier Reef Foundation.It is important that we all do our part to protect the Great Barrier Reef. We can do this by reducing our carbon footprint, using environmentally-friendly products, and being mindful of our water usage. By working together, we can help ensure that the Great Barrier Reef remains a natural wonder for generations to come.",
            q: ["Where is the Great Barrier Reef located?","What is the Great Barrier Reef known for?","What are some threats to the Great Barrier Reef?","What initiatives has the Australian government implemented to protect the Great Barrier Reef?","How can we help protect the Great Barrier Reef?",],
            q_sel:[[" Off the coast of Africa."," Off the coast of Asia."," Off the coast of Australia."," Off the coast of Japen.",],[" Being the largest coral reef system in the world."," Being home to thousands of species of marine life."," Both A and B ."," To help protect the Great Barrier Reef.",],[" Rising water temperatures and pollution."," Overfishing and tourism."," Hurricanes and earthquakes."," The Australian government has implemented several initiatives.",],[" Reducing carbon emissions, improving water quality, and reducing pollution."," Increasing carbon emissions, improving tourism, and reducing fishing."," Both A and B ."," We can do this by reducing our carbon footprint.",],[" By using environmentally-friendly products."," By reducing our carbon footprint."," By being mindful of our water usage."," All of the above.",],],
            q_ex: ["根据文章第一句话'The Great Barrier Reef is a natural wonder located off the coast of Australia.'可知大堡礁位于澳洲海岸外，因此答案为C。","根据文章第一段可知，大堡礁是世界上最大的珊瑚礁系统，同时也是数千种海洋生物的家园，因此答案为C。","根据文章第二段的内容，大堡礁正面临许多威胁，包括水温上升和来自陆地活动的污染，因此答案为A。","根据文章第三段的内容，澳洲政府实施了许多措施，包括减少碳排放、改善水质和减少进入珊瑚礁的污染，因此答案为A。","根据文章最后一段的内容，我们可以透过减少碳足迹、使用环保产品和注意节约用水等方式来帮助保护大堡礁，因此答案为D。",],
            q_a: [" C"," C"," A"," A"," D",],
            zh: "大堡礁是位于澳大利亚海岸外的自然奇观。它是世界上最大的珊瑚礁系统，绵延 2,300 多公里。大堡礁是数千种海洋生物的家园，包括海龟、海豚和 1,500 多种鱼类。不幸的是，大堡礁正面临着许多威胁。气候变化导致水温升高，导致珊瑚白化并杀死许多生活在那里的海洋物种。陆上活动造成的污染也在破坏珊瑚礁。这包括农业径流、污水和工业废料造成的污染。为帮助保护大堡礁，澳大利亚政府实施了多项举措。其中包括减少碳排放、改善水质以及减少进入珊瑚礁的污染量。也有许多保护组织致力于保护大堡礁，例如大堡礁基金会。重要的是我们都尽自己的一份力量来保护大堡礁。我们可以通过减少碳足迹、使用环保产品和注意用水来做到这一点。通过共同努力，我们可以帮助确保大堡礁为子孙后代留下一个自然奇观。"
        },{
            ar: "The Importance of SleepSleep is an essential part of a healthy lifestyle. It allows our bodies to rest and recharge, and it plays a vital role in our overall well-being. Unfortunately, many people do not get enough sleep, which can have serious consequences for their health and well-being.There are several reasons why people may not be getting enough sleep. Some people have busy schedules and find it difficult to make time for sleep. Others may have trouble falling asleep or staying asleep due to stress or anxiety. In addition, the use of electronic devices such as smartphones and computers before bedtime can interfere with sleep patterns.The consequences of not getting enough sleep can be severe. Lack of sleep can lead to a weakened immune system, increased risk of accidents, and decreased cognitive function. It can also contribute to mental health issues such as depression and anxiety.To ensure that you are getting enough sleep, it is important to establish a regular sleep schedule and stick to it. This means going to bed and waking up at the same time every day, even on weekends. Avoiding caffeine and alcohol before bedtime can also help improve sleep quality. Additionally, creating a relaxing sleep environment and limiting the use of electronic devices before bedtime can also improve sleep.In conclusion, sleep is a crucial part of a healthy lifestyle. By making sleep a priority and taking steps to improve sleep quality, we can improve our overall health and well-being.",
            q: ["What is the importance of sleep?","What are some reasons why people may not be getting enough sleep?","What are some consequences of not getting enough sleep?","What can we do to improve our sleep quality?",],
            q_sel:[[" It allows our bodies to rest and recharge."," It plays a vital role in our overall well-being."," Both A and B ."," It is important to establish a regular sleep schedule and stick to it.",],[" Busy schedules and stress."," Use of electronic devices before bedtime."," Both A and B ."," It allows our bodies to rest and recharge.",],[" Weakened immune system and increased risk of accidents."," Decreased cognitive function and mental health issues."," Both A and B ."," To ensure that you are getting enough sleep.",],[" Establish a regular sleep schedule and stick to it."," Avoid caffeine and alcohol before bedtime."," Create a relaxing sleep environment and limit the use of electronic devices before bedtime."," All of the above.",],],
            q_ex: ["根据文章第一句话，睡眠是健康生活方式中必不可少的一部分，它让我们的身体得到休息和充电，对我们的整体健康起着至关重要的作用，因此答案为C。","根据文章第二段的内容，有些人因为繁忙的日程而很难为睡眠腾出时间，有些人可能因为压力或焦虑而难以入睡或保持睡眠，此外，在睡前使用电子设备，如智能手机和电脑，也会影响睡眠模式，因此答案为C。","根据文章第三段的内容，睡眠不足会导致免疫系统虚弱，增加意外事故风险，并减少认知功能。它还可能导致心理健康问题，如抑郁和焦虑，因此答案为C。","根据文章最后一段的内容，确保有足够的睡眠，需要建立一个定期的睡眠计划并坚持下去，避免在睡前使用咖啡因和酒精，同时创造一个放松的睡眠环境和限制睡前使用电子设备，因此答案为D。",],
            q_a: [" C"," C"," C"," D",],
            zh: "睡眠的重要性睡眠是健康生活方式的重要组成部分。它让我们的身体得到休息和充电，对我们的整体健康起着至关重要的作用。不幸的是，许多人睡眠不足，这会对他们的健康和福祉造成严重后果。人们可能睡眠不足的原因有多种。有些人的日程安排很忙，很难抽出时间睡觉。其他人可能由于压力或焦虑而难以入睡或难以入睡。此外，睡前使用智能手机和电脑等电子设备会干扰睡眠模式。睡眠不足的后果可能很严重。睡眠不足会导致免疫系统减弱、事故风险增加和认知功能下降。它还会导致心理健康问题，例如抑郁和焦虑。为确保您获得充足的睡眠，重要的是要制定规律的睡眠时间表并坚持下去。这意味着每天在同一时间睡觉和起床，即使在周末也不例外。睡前避免摄入咖啡因和酒精也有助于改善睡眠质量。此外，创造一个放松的睡眠环境和限制睡前使用电子设备也可以改善睡眠。总之，睡眠是健康生活方式的重要组成部分。通过将睡眠放在首位并采取措施改善睡眠质量，我们可以改善整体健康和福祉。"
        },{
            ar: "In recent years, there has been a growing interest in sustainable fashion. Sustainable fashion aims to reduce the negative impact that the fashion industry has on the environment, while also promoting fair labor practices and ethical treatment of workers. This can include using eco-friendly materials, reducing waste through recycling and upcycling, and ensuring that workers are paid fair wages and have safe working conditions.",
            q: ["What is sustainable fashion?","What are some ways sustainable fashion can reduce negative impact on the environment?","What does sustainable fashion aim to promote?",],
            q_sel:[[" Fashion that is expensive."," Fashion that is trendy."," Fashion that aims to reduce negative impact on the environment and promote fair labor practices."," Fashion that is not made in developing countries.",],[" Using eco-friendly materials."," Promoting fair labor practices."," Recycling and upcycling."," Both A and C .",],[" Fair labor practices and ethical treatment of workers."," The use of expensive materials."," The production of trendy fashion."," The use of developing countries for manufacturing.",],],
            q_ex: ["根据文章第一句话“近年来，对可持续时尚的关注越来越高”，可知这段文章主要在谈论可持续时尚。可持续时尚的目标是减少时尚产业对环境的负面影响，同时促进公平劳动惯例和对工人的道德对待。因此，答案为C。","根据文章第二句话“可持续时尚旨在通过使用环保材料、通过回收和再利用减少浪费以及确保工人得到公平的工资和安全的工作条件等方式来减少时尚对环境的负面影响”，可知答案为D，即使用环保材料和通过回收和再利用减少浪费。","根据文章第一句话“可持续时尚旨在减少时尚产业对环境的负面影响，同时促进公平劳动惯例和对工人的道德对待”，可知可持续时尚旨在促进公平劳动惯例和对工人的道德对待。因此，答案为A。",],
            q_a: [" C"," D"," A",],
            zh: "近年来，人们对可持续时尚的兴趣与日俱增。可持续时尚旨在减少时尚业对环境的负面影响，同时促进公平的劳动实践和对工人的道德对待。这可以包括使用环保材料，通过回收和升级回收减少浪费，并确保工人获得公平的工资和安全的工作条件。"
        },{
            ar: "Technology has transformed the way we live, work, and communicate. One area that has seen a significant impact is the job market. The rise of automation and artificial intelligence has led to the automation of many tasks that were previously performed by humans. This has resulted in a shift in the types of jobs available, with an increasing focus on jobs that require higher levels of skill, such as programming and data analysis.",
            q: ["What is the main idea of this passage?","What is one consequence of the rise of automation and artificial intelligence?","What types of jobs are becoming more important?",],
            q_sel:[[" Technology has had a significant impact on our lives."," The rise of automation and artificial intelligence has changed the job market."," Jobs that require higher levels of skill are becoming more important."," Both B and C .",],[" A decrease in the number of available jobs."," An increase in the types of jobs available."," A decrease in the need for workers with high levels of skill."," A decrease in the need for workers who can adapt to new technology.",],[" Jobs that require lower levels of skill."," Jobs that require higher levels of skill."," Jobs that can be automated."," Both A and C .",],],
            q_ex: ["文章讲述了科技对生活、工作和沟通的影响，但重点是科技对就业市场的影响，尤其是自动化和人工智慧的崛起导致了许多以前由人类执行的任务自动化。这导致了可用工作类型的转变，越来越注重需要更高水平技能的工作，如编程和数据分析。因此，答案为D。","根据文章第二句话“自动化和人工智慧的崛起导致了许多以前由人类执行的任务自动化”，可知自动化和人工智慧的崛起导致了更多类型的工作，因此答案为B。","根据文章最后一句话“越来越注重需要更高水平技能的工作，如编程和数据分析”，可知需要更高水平技能的工作正在变得更加重要，因此答案为B。",],
            q_a: [" D"," B"," B",],
            zh: "技术改变了我们生活、工作和交流的方式。一个受到重大影响的领域是就业市场。自动化和人工智能的兴起导致许多以前由人类执行的任务实现了自动化。这导致了可用工作类型的转变，人们越来越关注需要更高技能水平的工作，例如编程和数据分析。"
        },{
            ar: "In recent years, there has been a growing concern about the impact of plastic waste on the environment. It is estimated that over 8 million tons of plastic end up in the oceans every year, harming marine life and polluting our beaches. While recycling can help to reduce the amount of plastic waste, it is not a complete solution. To truly address the problem, we need to reduce our reliance on single-use plastics and find alternative materials that are more environmentally friendly.",
            q: ["What is the main idea of this passage?","What is the impact of plastic waste on the oceans?","What is the solution to the problem of plastic waste?",],
            q_sel:[[" Plastic waste is harming the environment."," Recycling is not a complete solution to the problem of plastic waste."," We need to reduce our reliance on single-use plastics and find alternative materials."," Both A and C .",],[" It harms marine life."," It increases the number of fish in the oceans."," It reduces pollution on the beaches."," Both B and C .",],[" Recycling."," Finding alternative materials."," Reducing our reliance on single-use plastics."," Both B and C .",],],
            q_ex: ["文章讲述了塑料垃圾对环境的影响，尤其是对海洋生态系统的影响。文章认为，尽管回收可以帮助减少塑料垃圾的量，但这不是一个完整的解决方案。为了真正解决问题，我们需要减少对一次性塑料制品的依赖，找到更环保的替代材料。因此，答案为D。","根据文章第一句话“近年来，人们越来越关注塑料垃圾对环境的影响”，和第二句话“据估计，每年有超过800万吨的塑料垃圾进入海洋，损害海洋生物并污染我们的海滩”，可知塑料垃圾对海洋生态系统有害，因此答案为A。","根据文章最后一句话“我们需要减少对一次性塑料制品的依赖，找到更环保的替代材料”，可知解决塑料垃圾问题的方案是找到更环保的替代材料和减少对一次性塑料制品的依赖，因此答案为D。",],
            q_a: [" D"," A"," D",],
            zh: "近年来，人们越来越关注塑料垃圾对环境的影响。据估计，每年有超过 800 万吨塑料最终流入海洋，危害海洋生物并污染我们的海滩。虽然回收有助于减少塑料垃圾的数量，但这并不是一个完整的解决方案。要真正解决这个问题，我们需要减少对一次性塑料的依赖，并寻找更环保的替代材料。"
        },{
            ar: "Climate change is one of the biggest challenges facing our planet today. The burning of fossil fuels, such as coal and oil, releases carbon dioxide and other greenhouse gases into the atmosphere, trapping heat and causing global temperatures to rise. The consequences of climate change include rising sea levels, more frequent and severe weather events, and the extinction of plant and animal species. To address this urgent issue, we must reduce our greenhouse gas emissions and transition to renewable energy sources such as wind, solar, and hydro power.",
            q: ["What is the main challenge facing our planet today?","What is the cause of global temperature rise?","What are the consequences of climate change?","What is the solution to address the issue of climate change?",],
            q_sel:[[" Rising sea levels."," Climate change."," The extinction of plant and animal species."," Burning fossil fuels.",],[" Rising sea levels."," Burning of fossil fuels."," Extinction of plant and animal species."," None of the above.",],[" Rising sea levels."," More frequent and severe weather events."," The extinction of plant and animal species."," All of the above.",],[" Reduce greenhouse gas emissions."," Transition to renewable energy sources."," Both A and B ."," None of the above.",],],
            q_ex: ["文章开头提到了「气候变迁」这个词，接着说明了其原因和后果，因此可以判断出主要挑战是气候变迁，答案为B。","根据文章提到的「化石燃料的燃烧，如煤和油，释放出二氧化碳和其他温室气体到大气中，将热量困住，导致全球气温上升。」可知全球气温上升的原因是化石燃料的燃烧，答案为B。","根据文章提到的「气候变迁的后果包括海平面上升、更频繁和严重的气象事件以及植物和动物物种的灭绝。」可知气候变迁的后果有海平面上升、更频繁和严重的气象事件以及植物和动物物种的灭绝，答案为D。","根据文章提到的「要解决这个紧迫的问题，我们必须减少温室气体排放，转向风、太阳和水力发电等可再生能源。」可知解决气候变迁问题的方法是减少温室气体排放和转向可再生能源，答案为C。",],
            q_a: [" B"," B"," D"," C",],
            zh: "气候变化是当今地球面临的最大挑战之一。煤炭和石油等化石燃料的燃烧会向大气中释放二氧化碳和其他温室气体，吸收热量并导致全球气温上升。气候变化的后果包括海平面上升、更频繁和更恶劣的天气事件以及植物和动物物种的灭绝。为了解决这个紧迫的问题，我们必须减少温室气体排放，并转向风能、太阳能和水力发电等可再生能源。"
        },]