const q = [{
            ars: "The new restaurant in town is already causing quite a _____ with its unique menu and elegant atmosphere. The restaurant's owner, a well-known chef, has created a _____ dining experience that is both delicious and memorable. The restaurant offers a wide variety of dishes, ranging from classic comfort food to exotic _____ from around the world. Customers can choose to dine in the main dining room or in a more intimate private _____ for special occasions. The restaurant also offers catering services for corporate events and private parties.",
            reals: "The new restaurant in town is already causing quite a stir with its unique menu and elegant atmosphere. The restaurant's owner, a well-known chef, has created a refined dining experience that is both delicious and memorable. The restaurant offers a wide variety of dishes, ranging from classic comfort food to exotic delicacies from around the world. Customers can choose to dine in the main dining room or in a more intimate private booth for special occasions. The restaurant also offers catering services for corporate events and private parties.",
            sels: ["stir","steer","stare","store","refined","delightful","extravagant","delicate","delicacies","spices","beverages","desserts","booth","chamber","lounge","terrace",],
            exps: "这是一篇关于一家新餐厅的文章，文章提到了该餐厅的菜单和氛围。从上下文中可以得出：句子一中提到了餐厅的独特菜单和优雅的氛围，因此答案应该是「stir」。句子二中提到了该餐厅的菜品美味而且难忘，因此答案应该是「refined」。句子三中提到了该餐厅提供的菜品种类很多，包括经典舒适食物和世界各地的异国美食，因此答案应该是「delicacies」。句子四中提到了该餐厅提供的私人用餐区，因此答案应该是「booth」。因此，答案为 (A) stir、(E) refined、(I) delicacies 和 (M) booth。",
            ans: ["(A)","(E)","(I)","(M)",],
            cns: "镇上的新餐厅已经引起了不小的轰动 以其独特的菜单和优雅的氛围。餐厅的老板是一位知名厨师，他创造了一个精致的 既美味又难忘的用餐体验。餐厅提供种类繁多的菜肴，从经典的舒适食品到异国风味的美食 来自世界各地的。顾客可以选择在主餐厅或更私密的包厢用餐 特殊场合。餐厅还为企业活动和私人聚会提供餐饮服务。"
        },{
            ars: "The new marketing campaign has been _____ successful, with sales increasing by 20% since its launch. The campaign's focus on social media has helped the company reach a wider _____, particularly among younger consumers who spend a lot of time on their phones. The company's _____ strategy, which includes targeted ads and influencer partnerships, has also contributed to its success. However, the company's _____ has also played a role in the campaign's success, as its reputation for high-quality products has helped build trust with customers.",
            reals: "The new marketing campaign has been tremendously successful, with sales increasing by 20% since its launch. The campaign's focus on social media has helped the company reach a wider audience, particularly among younger consumers who spend a lot of time on their phones. The company's promotion strategy, which includes targeted ads and influencer partnerships, has also contributed to its success. However, the company's reputation has also played a role in the campaign's success, as its reputation for high-quality products has helped build trust with customers.",
            sels: ["moderately","tremendously","barely","slightly","audience","market","sector","niche","pricing","promotion","distribution","packaging","innovation","reputation","location","convenience",],
            exps: "这是一篇关于市场营销活动的文章，文章提到了这个活动的成功原因。从上下文中可以得出：句子一中提到了该活动的成功，因此答案应该是「tremendously」。句子二中提到了该活动尤其受到了年轻消费者的欢迎，因此答案应该是「audience」。句子三中提到了该活动的策略，包括有针对性的广告和影响者合作，因此答案应该是「promotion」。句子四中提到了公司的声誉，这有助于建立客户的信任，因此答案应该是「reputation」。因此，答案为 (B) tremendously、(E) audience、(J) promotion 和 (N) reputation。",
            ans: ["(B)","(E)","(J)","(N)",],
            cns: "新的营销活动取得了巨大的成功 成功，自推出以来销售额增长了 20%。该活动对社交媒体的关注帮助该公司覆盖了更广泛的受众，尤其是在手机上花费大量时间的年轻消费者中。公司宣传 包括有针对性的广告和有影响力的合作伙伴关系在内的战略也为其成功做出了贡献。但是，公司的声誉 也为活动的成功发挥了作用，因为其高质量产品的声誉有助于建立客户的信任。"
        },{
            ars: "The company has announced plans to _____ its workforce by 10% in an effort to reduce costs. The layoffs will primarily affect _____ in the company's administrative and support departments, although some managers and executives will also be let go. The company's CEO has stated that these changes are necessary to ensure the long-term _____ of the company and maintain its competitiveness in the marketplace. The company will provide severance packages and _____ services to affected employees to help them transition to new employment.",
            reals: "The company has announced plans to downsize its workforce by 10% in an effort to reduce costs. The layoffs will primarily affect employees in the company's administrative and support departments, although some managers and executives will also be let go. The company's CEO has stated that these changes are necessary to ensure the long-term sustainability of the company and maintain its competitiveness in the marketplace. The company will provide severance packages and counseling services to affected employees to help them transition to new employment.",
            sels: ["expand","downsize","diversify","centralize","employees","shareholders","customers","suppliers","profitability","stability","flexibility","sustainability","relocation","retraining","counseling","mentoring",],
            exps: "这是一篇关于公司裁员计划的文章，文章提到了计划的原因和影响。从上下文中可以得出：句子一中提到了公司的裁员计划，因此答案应该是「downsize」。句子二中提到了员工中的特定部门受到影响，因此答案应该是「employees」。句子三中提到了公司的CEO认为这些变化是必要的，以确保公司的长期稳定性和竞争力，因此答案应该是「sustainability」。句子四中提到了公司提供撤职费和辅导服务，以帮助受影响的员工过渡到新的就业，因此答案应该是「counseling」。因此，答案为 (B) downsize、(E) employees、(L) sustainability 和 (O) counseling。",
            ans: ["(B)","(E)","(L)","(O)",],
            cns: "公司已宣布裁员计划 其劳动力减少了 10%，以努力降低成本。裁员主要影响员工 在公司的行政和支持部门，虽然一些经理和高管也会被裁掉。公司首席执行官表示，这些变化对于确保长期可持续性是必要的 并保持公司在市场上的竞争力。公司将提供遣散费和辅导 为受影响的员工提供服务，帮助他们过渡到新的工作岗位。"
        },{
            ars: "The _____ of the company's new product has been delayed due to manufacturing issues. The company had originally planned to launch the product in Q2, but now expects to release it in Q4. The delay has been _____ disappointing for the company, which had invested heavily in research and development and marketing efforts to support the launch. The company's management has reassured shareholders that the delay is temporary and that the product will be worth the wait, with features that are _____ superior to those of its competitors.",
            reals: "The launch of the company's new product has been delayed due to manufacturing issues. The company had originally planned to launch the product in Q2, but now expects to release it in Q4. The delay has been extremely disappointing for the company, which had invested heavily in research and development and marketing efforts to support the launch. The company's management has reassured shareholders that the delay is temporary and that the product will be worth the wait, with features that are significantly superior to those of its competitors.",
            sels: ["launch","design","development","testing","highly","somewhat","extremely","moderately","significantly","marginally","slightly","barely",],
            exps: "这是一篇关于新产品延迟问题的文章，文章提到了延迟的原因和公司的反应。从上下文中可以得出：句子一中提到了产品的发布被延迟，因此答案应该是「launch」。句子二中提到了公司对这个延迟非常失望，因此答案应该是「extremely」。句子三中提到了产品将拥有优越的功能，因此答案应该是「significantly」。因此，答案为 (A) launch、(G) extremely 和 (I) significantly。",
            ans: ["(A)","(G)","(I)",],
            cns: "发射，市场投入 由于制造问题，该公司的新产品已被推迟。该公司原计划在第二季度推出该产品，但现在预计将在第四季度发布。延迟非常严重 这对公司来说是令人失望的，该公司在研发和营销方面投入了大量资金来支持发布。公司管理层已向股东保证，延迟是暂时的，该产品值得等待，具有显著的功能 优于其竞争对手。"
        },{
            ars: "The hotel industry in the city has been experiencing a boom in recent years due to increased tourism. Many new hotels have _____ up in the city center, offering tourists a range of options at different price points. However, this growth has also led to increased _____ and competition among hotels, with some struggling to fill their rooms during off-peak seasons. To address this, many hotels have been _____ their services to appeal to a wider range of customers, such as offering discounted rates to business travelers and families.",
            reals: "The hotel industry in the city has been experiencing a boom in recent years due to increased tourism. Many new hotels have opened up in the city center, offering tourists a range of options at different price points. However, this growth has also led to increased supply and competition among hotels, with some struggling to fill their rooms during off-peak seasons. To address this, many hotels have been diversifying their services to appeal to a wider range of customers, such as offering discounted rates to business travelers and families.",
            sels: ["closed","opened","expanded","renovated","demand","supply","marketing","innovation","diversifying","outsourcing","downsizing","streamlining",],
            exps: "这是一篇关于城市酒店行业发展的文章，文章提到了酒店行业的增长和相关问题。从上下文中可以得出：句子一中提到了城市酒店行业近年来繁荣发展，因此答案应该是「opened」。句子二中提到了增长也带来了竞争和供过于求的问题，因此答案应该是「supply」。句子三中提到了许多酒店正在调整其服务，以应对市场变化，因此答案应该是「diversifying」。因此，答案为 (B) opened、(F) supply 和 (I) diversifying。",
            ans: ["(B)","(F)","(I)",],
            cns: "近年来，由于旅游业的发展，该市的酒店业一直在蓬勃发展。许多新酒店已经开业 位于市中心，以不同的价位为游客提供多种选择。然而，这种增长也导致供应增加 以及酒店之间的竞争，一些酒店在淡季期间难以填补房间。为了解决这个问题，许多酒店一直在多元化 他们的服务以吸引更广泛的客户，例如为商务旅客和家庭提供折扣价。"
        },{
            ars: "The pharmaceutical industry has come under increased scrutiny in recent years due to concerns about rising drug prices and the role of pharmaceutical companies in the opioid crisis. Many consumers are _____ to pay for medications that they need to maintain their health, leading to calls for greater government regulation of drug prices. Meanwhile, several pharmaceutical companies have faced lawsuits for their role in the opioid epidemic, with some accused of _____ their products and contributing to addiction and overdose deaths. In response, the industry has pledged to improve transparency and _____ in drug pricing and marketing practices.",
            reals: "The pharmaceutical industry has come under increased scrutiny in recent years due to concerns about rising drug prices and the role of pharmaceutical companies in the opioid crisis. Many consumers are reluctant to pay for medications that they need to maintain their health, leading to calls for greater government regulation of drug prices. Meanwhile, several pharmaceutical companies have faced lawsuits for their role in the opioid epidemic, with some accused of overpromoting their products and contributing to addiction and overdose deaths. In response, the industry has pledged to improve transparency and accountability in drug pricing and marketing practices.",
            sels: ["reluctant","eager","unwilling","hesitant","overpromoting","underpromoting","misrepresenting","falsifying","accountability","efficiency","innovation","profitability",],
            exps: "这是一篇关于制药行业问题的文章，文章提到了药价上涨和制药公司在阿片类药物危机中的角色等问题。从上下文中可以得出：句子一中提到了许多消费者不愿意支付高昂的药费，因此答案应该是「reluctant」。句子二中提到了一些制药公司被指控过度宣传其产品，贡献了成瘾和过量死亡等问题，因此答案应该是「overpromoting」。句子三中提到了制药行业承诺改善透明度和负责任的药品定价和市场营销实践，因此答案应该是「accountability」。因此，答案为 (A) reluctant、(E) overpromoting 和 (I) accountability。",
            ans: ["(A)","(E)","(I)",],
            cns: "近年来，由于担心药品价格上涨以及制药公司在阿片类药物危机中的作用，制药行业受到越来越多的审查。许多消费者不愿意 支付他们维持健康所需的药物费用，导致政府呼吁加强对药品价格的监管。与此同时，几家制药公司因其在阿片类药物流行中的作用而面临诉讼，其中一些公司被指控过度宣传 他们的产品并导致成瘾和过量死亡。作为回应，该行业已承诺提高透明度和问责制 在药品定价和营销实践中。"
        },{
            ars: "In recent years, the global energy sector has undergone significant changes, driven by concerns about _____ and the need to reduce carbon emissions. As a result, many countries have implemented policies aimed at increasing the use of renewable energy sources, such as wind and solar power. This has led to a _____ in the renewable energy industry, with companies investing heavily in research and development to improve the efficiency and cost-effectiveness of their products. However, the shift towards renewable energy has not been without its _____, as some traditional energy companies have struggled to adapt to the changing market conditions.",
            reals: "In recent years, the global energy sector has undergone significant changes, driven by concerns about sustainability and the need to reduce carbon emissions. As a result, many countries have implemented policies aimed at increasing the use of renewable energy sources, such as wind and solar power. This has led to a surge in the renewable energy industry, with companies investing heavily in research and development to improve the efficiency and cost-effectiveness of their products. However, the shift towards renewable energy has not been without its challenges, as some traditional energy companies have struggled to adapt to the changing market conditions.",
            sels: ["sustainability","diversity","innovation","competition","surge","decline","stagnation","consolidation","challenges","opportunities","benefits","rewards",],
            exps: "这是一篇关于全球能源行业的文章，文章提到了该行业的变化和相应的挑战。从上下文中可以得出：句子一中提到了对永续性的关注和减少碳排放的需求，因此答案应该是「sustainability」。句子二中提到了可再生能源行业的激增，因此答案应该是「surge」。句子三中提到了传统能源公司适应市场变化的困难，因此答案应该是「challenges」。因此，答案为 (A) sustainability、(E) surge 和 (I) challenges。",
            ans: ["(A)","(E)","(I)",],
            cns: "近年来，在对可持续性的担忧推动下，全球能源行业发生了重大变化 以及减少碳排放的必要性。因此，许多国家实施了旨在增加风能和太阳能等可再生能源使用的政策。这导致了激增 在可再生能源行业，公司在研发方面投入巨资，以提高其产品的效率和成本效益。然而，向可再生能源的转变并非没有挑战，因为一些传统能源公司一直在努力适应不断变化的市场条件。"
        },{
            ars: "Over the past decade, advances in technology have transformed the way we live and work. One of the most significant changes has been the widespread adoption of _____ devices, such as smartphones and tablets. These devices have revolutionized the way we _____ information, allowing us to access a wealth of knowledge at our fingertips. However, they have also had a number of _____ effects, such as the erosion of face-to-face communication skills and the development of addiction to social media.",
            reals: "Over the past decade, advances in technology have transformed the way we live and work. One of the most significant changes has been the widespread adoption of mobile devices, such as smartphones and tablets. These devices have revolutionized the way we retrieve information, allowing us to access a wealth of knowledge at our fingertips. However, they have also had a number of detrimental effects, such as the erosion of face-to-face communication skills and the development of addiction to social media.",
            sels: ["mobile","wireless","digital","handheld","process","retrieve","disseminate","interpret","beneficial","detrimental","positive","negative",],
            exps: "这是一篇关于技术变革的文章，文章提到了技术变革对生活和工作的影响。从上下文中可以得出：句子一中提到了智能手机和平板电脑等行动设备的广泛使用，因此答案应该是「mobile」。句子二中提到了使用这些设备获取知识的革命性变化，因此答案应该是「retrieve」。句子三中提到了使用这些设备的负面效应，因此答案应该是「detrimental」。因此，答案为 (A) mobile、(F) retrieve 和 (J) detrimental。",
            ans: ["(A)","(F)","(J)",],
            cns: "在过去十年中，技术的进步改变了我们的生活和工作方式。最重要的变化之一是移动互联网的广泛采用 设备，例如智能手机和平板电脑。这些设备彻底改变了我们检索的方式 信息，使我们能够触手可及地获取丰富的知识。然而，他们也有一些有害的 影响，例如面对面交流技巧的侵蚀和社交媒体成瘾的发展。"
        },{
            ars: "In recent years, businesses have increasingly turned to social media to _____ with their customers. Platforms like Facebook and Twitter offer companies a way to _____ with their audience in real-time, and can help to create a sense of community around a brand. However, social media also presents a number of _____, including the potential for negative feedback to spread quickly and damage a company's reputation.",
            reals: "In recent years, businesses have increasingly turned to social media to engage with their customers. Platforms like Facebook and Twitter offer companies a way to interact with their audience in real-time, and can help to create a sense of community around a brand. However, social media also presents a number of drawbacks, including the potential for negative feedback to spread quickly and damage a company's reputation.",
            sels: ["collaborate","engage","compete","negotiate","interact","market","advertise","promote","opportunities","challenges","benefits","drawbacks",],
            exps: "这是一篇关于企业使用社交媒体与客户互动的文章，文章提到了社交媒体对企业的影响。从上下文中可以得出：句子一中提到了企业越来越多地使用社交媒体与客户互动，因此答案应该是「engage」。句子二中提到了社交媒体可以帮助企业建立品牌社区，因此答案应该是「interact」。句子三中提到了使用社交媒体所面临的风险，因此答案应该是「drawbacks」。因此，答案为 (B) engage、(E) interact 和 (L) drawbacks。",
            ans: ["(B)","(E)","(L)",],
            cns: "近年来，企业越来越多地转向社交媒体参与 与他们的客户。 Facebook 和 Twitter 等平台为公司提供了一种互动方式 与他们的观众实时交流，并有助于营造围绕品牌的社区感。然而，社交媒体也存在一些缺点，包括负面反馈迅速传播并损害公司声誉的可能性。"
        },{
            ars: "The hotel industry is experiencing a _____ in business due to the recent economic boom. With more people _____ disposable income, more and more individuals are choosing to travel and stay in hotels. In order to meet the demand, hotels are expanding their facilities and _____ their services to attract customers.",
            reals: "The hotel industry is experiencing a surge in business due to the recent economic boom. With more people spending disposable income, more and more individuals are choosing to travel and stay in hotels. In order to meet the demand, hotels are expanding their facilities and improving their services to attract customers.",
            sels: ["decline","stagnation","surge","fluctuation","having","earning","spending","saving","improving","reducing","limiting","discontinuing",],
            exps: "这是一篇关于酒店业务增长的文章，文章提到了随着经济的蓬勃发展，越来越多的人选择旅行和住酒店，酒店业务出现了一个「surge」。从上下文中可以得出：句子一中提到了「surge」，因此答案应该是 (C) surge。句子二中提到了随着人们「spending」更多的可支配收入，他们越来越多地选择旅行和住酒店，因此答案应该是 (G) spending。句子三中提到了为了满足需求，酒店正在扩大设施并「improving」其服务来吸引顾客，因此答案应该是 (I) improving。因此，答案为 (C) surge、(G) spending 和 (I) improving。",
            ans: ["(C)","(G)","(I)",],
            cns: "酒店业正在经历一场激增 由于最近的经济繁荣而从事商业活动。随着越来越多的人消费 随着可支配收入的增加，越来越多的人选择旅游和入住酒店。为了满足需求，酒店正在扩建设施和改进 他们的服务来吸引顾客。"
        },{
            ars: "In recent years, online shopping has become increasingly popular among consumers. One of the biggest advantages of online shopping is that it allows customers to _____ items from the comfort of their own homes. This means that people can avoid the hassle of traffic and crowded stores. Additionally, online shopping often offers a wider variety of products than traditional retail stores, as well as _____ prices. Many retailers also offer free shipping or other _____ to encourage customers to shop online.",
            reals: "In recent years, online shopping has become increasingly popular among consumers. One of the biggest advantages of online shopping is that it allows customers to purchase items from the comfort of their own homes. This means that people can avoid the hassle of traffic and crowded stores. Additionally, online shopping often offers a wider variety of products than traditional retail stores, as well as lower prices. Many retailers also offer free shipping or other promotions to encourage customers to shop online.",
            sels: ["purchase","return","exchange","rent","lower","higher","fixed","fluctuating","promotions","warranties","discounts","contracts",],
            exps: "这是一篇关于网路购物的文章，文章提到了网路购物的优点，包括方便、避免交通和人潮、商品种类丰富、价格更低、还有店家提供的促销和免运费等等。从上下文中可以得出：句子一中提到了网路购物可以让人们从家中购买商品，因此答案应该是 (A) purchase。句子二中提到了网路购物的优势之一是价格更低，因此答案应该是 (E) lower。句子三中提到了店家提供的促销和免运费等等，因此答案应该是 (I) promotions。因此，答案为 (A) purchase、(E) lower 和 (I) promotions。",
            ans: ["(A)","(E)","(I)",],
            cns: "近年来，网上购物越来越受到消费者的欢迎。网上购物的最大优势之一是它允许客户购买 从他们自己家中舒适的物品。这意味着人们可以避免交通和商店拥挤的麻烦。此外，网上购物通常比传统零售店提供更多种类的产品，而且价格更低 价格。许多零售商还提供免费送货或其他促销活动 以鼓励顾客在线购物。"
        },{
            ars: "The hospitality industry, which includes hotels, restaurants, and catering services, plays a crucial role in the global economy. As international travel continues to _____, the demand for hotels and restaurants has increased. In addition, many people today prefer to _____ out or order in rather than cook at home. This has led to a growth in the number of restaurants and catering services, both small and large.When it comes to hotels, there are a wide variety of options available to travelers. From luxury hotels to budget accommodations, there is something for every _____ of traveler. Many hotels now offer additional amenities such as fitness centers, swimming pools, and complimentary breakfast. In order to stay competitive, hotels must also keep up with the latest technologies, such as online reservation systems and mobile check-in options.",
            reals: "The hospitality industry, which includes hotels, restaurants, and catering services, plays a crucial role in the global economy. As international travel continues to increase, the demand for hotels and restaurants has increased. In addition, many people today prefer to dine out or order in rather than cook at home. This has led to a growth in the number of restaurants and catering services, both small and large.When it comes to hotels, there are a wide variety of options available to travelers. From luxury hotels to budget accommodations, there is something for every category of traveler. Many hotels now offer additional amenities such as fitness centers, swimming pools, and complimentary breakfast. In order to stay competitive, hotels must also keep up with the latest technologies, such as online reservation systems and mobile check-in options.",
            sels: ["decrease","stagnate","increase","fluctuate","eat","dine","take","make","kind","level","group","category",],
            exps: "这是一篇关于餐饮和旅馆产业的文章。文章提到了随着国际旅游的增加，对旅馆和餐厅的需求也增加了。同时，越来越多的人选择外出用餐或点外送食物，因此餐厅和餐饮服务的数量也在增长。另外，旅馆也提供了各种各样的选择，包括豪华旅馆和预算住宿等等，而且为了保持竞争力，旅馆也必须跟上最新的技术。句子一中提到了随着国际旅游的增加，对旅馆和餐厅的需求也增加了，因此答案应该是 (C) increase。句子二中提到了越来越多的人选择外出用餐或点外送食物，因此答案应该是 (F) dine。句子三中提到了旅馆提供各种选择，包括豪华旅馆和预算住宿等等，因此答案应该是 (L) category。因此，答案为 (C) increase、(F) dine 和 (L) category。",
            ans: ["(C)","(F)","(L)",],
            cns: "包括酒店、餐厅和餐饮服务在内的酒店业在全球经济中发挥着至关重要的作用。随着国际旅行的不断增加，对旅馆和餐馆的需求增加了。此外，如今许多人更喜欢用餐 外出或订购而不是在家做饭。这导致了大大小小的餐馆和餐饮服务数量的增加。说到酒店，旅客可以有多种选择。从豪华酒店到经济型住宿，每个类别都有适合的东西 的旅行者。许多酒店现在提供额外的便利设施，例如健身中心、游泳池和免费早餐。为了保持竞争力，酒店还必须跟上最新技术，例如在线预订系统和移动入住选项。"
        },]