const q = [{
            ars: "The new restaurant in town is already causing quite a _____ with its unique menu and elegant atmosphere. The restaurant's owner, a well-known chef, has created a _____ dining experience that is both delicious and memorable. The restaurant offers a wide variety of dishes, ranging from classic comfort food to exotic _____ from around the world. Customers can choose to dine in the main dining room or in a more intimate private _____ for special occasions. The restaurant also offers catering services for corporate events and private parties.",
            reals: "The new restaurant in town is already causing quite a stir with its unique menu and elegant atmosphere. The restaurant's owner, a well-known chef, has created a refined dining experience that is both delicious and memorable. The restaurant offers a wide variety of dishes, ranging from classic comfort food to exotic delicacies from around the world. Customers can choose to dine in the main dining room or in a more intimate private booth for special occasions. The restaurant also offers catering services for corporate events and private parties.",
            sels: ["stir","steer","stare","store","refined","delightful","extravagant","delicate","delicacies","spices","beverages","desserts","booth","chamber","lounge","terrace",],
            exps: "This is an article about a new restaurant, mentioning the menu and atmosphere of the restaurant. From the context: Sentence one mentions the restaurant's unique menu and elegant ambiance, so the answer should be stir. Sentence 2 mentions that the restaurant's dishes are delicious and memorable, so the answer should be refined. Sentence 3 mentions that the restaurant serves a wide variety of dishes, including classic comfort food and exotic cuisines from around the world, so the answer should be delicacies. Sentence four refers to the private dining area that the restaurant offers, so the answer should be booth. Therefore, the answers are (A) stir, (E) refined, (I) delicacies, and (M) booth.",
            ans: ["(A)","(E)","(I)","(M)",],
            cns: "The new restaurant in town is already causing quite a stir with its unique menu and elegant ambiance. The owner of the restaurant is a renowned chef who has created a refined dining experience that is both delicious and memorable. The restaurant offers a wide variety of dishes, from classic comfort food to exotic cuisine from around the world. Patrons can choose to dine in the main dining room or in more intimate boxes for special occasions. The restaurant also caters for corporate events and private parties."
        },{
            ars: "The new marketing campaign has been _____ successful, with sales increasing by 20% since its launch. The campaign's focus on social media has helped the company reach a wider _____, particularly among younger consumers who spend a lot of time on their phones. The company's _____ strategy, which includes targeted ads and influencer partnerships, has also contributed to its success. However, the company's _____ has also played a role in the campaign's success, as its reputation for high-quality products has helped build trust with customers.",
            reals: "The new marketing campaign has been tremendously successful, with sales increasing by 20% since its launch. The campaign's focus on social media has helped the company reach a wider audience, particularly among younger consumers who spend a lot of time on their phones. The company's promotion strategy, which includes targeted ads and influencer partnerships, has also contributed to its success. However, the company's reputation has also played a role in the campaign's success, as its reputation for high-quality products has helped build trust with customers.",
            sels: ["moderately","tremendously","barely","slightly","audience","market","sector","niche","pricing","promotion","distribution","packaging","innovation","reputation","location","convenience",],
            exps: "This is an article about a marketing campaign that mentions why the campaign was successful. From the context, it follows that the success of the campaign is mentioned in sentence one, so the answer should be tremendously. Sentence 2 mentions that the event is especially popular with young consumers, so the answer should be audience. The strategy of the campaign is mentioned in the third sentence, including targeted advertising and influencer cooperation, so the answer should be promotion. The reputation of the company is mentioned in sentence four, which helps to build trust with customers, so the answer should be reputation. So, the answers are (B) enormously, (E) audience, (J) promotion, and (N) reputation.",
            ans: ["(B)","(E)","(J)","(N)",],
            cns: "The new marketing campaign has been a huge success, with sales up 20% since launch. The campaign's focus on social media has helped the company reach a wider audience, especially among younger consumers who spend a lot of time on their phones. Corporate publicity strategies including targeted advertising and influencer partnerships have also contributed to its success. However, a company's reputation also plays a role in the event's success, as its reputation for high-quality products helps build customer trust."
        },{
            ars: "The company has announced plans to _____ its workforce by 10% in an effort to reduce costs. The layoffs will primarily affect _____ in the company's administrative and support departments, although some managers and executives will also be let go. The company's CEO has stated that these changes are necessary to ensure the long-term _____ of the company and maintain its competitiveness in the marketplace. The company will provide severance packages and _____ services to affected employees to help them transition to new employment.",
            reals: "The company has announced plans to downsize its workforce by 10% in an effort to reduce costs. The layoffs will primarily affect employees in the company's administrative and support departments, although some managers and executives will also be let go. The company's CEO has stated that these changes are necessary to ensure the long-term sustainability of the company and maintain its competitiveness in the marketplace. The company will provide severance packages and counseling services to affected employees to help them transition to new employment.",
            sels: ["expand","downsize","diversify","centralize","employees","shareholders","customers","suppliers","profitability","stability","flexibility","sustainability","relocation","retraining","counseling","mentoring",],
            exps: "This is an article about a company's layoff plan, and the article mentions the causes and effects of the plan. It can be concluded from the context: Sentence 1 mentions the company's layoff plan, so the answer should be downsize. Sentence 2 mentions that a specific department of employees is affected, so the answer should be employees. Sentence 3 mentions that the company's CEO believes that these changes are necessary to ensure the company's long-term stability and competitiveness, so the answer should be sustainability. Sentence 4 mentions that the company provides severance pay and counseling services to help affected employees transition to new employment, so the answer should be counseling. So the answers are (B) downsize, (E) employees, (L) sustainability and (O) counseling.",
            ans: ["(B)","(E)","(L)","(O)",],
            cns: "The company has announced plans to reduce its workforce by 10% in an effort to reduce costs. Layoffs primarily affect employees in the company's administrative and support functions, although some managers and executives will also be let go. The company's CEO said the changes were necessary to ensure long-term sustainability and maintain the company's competitiveness in the market. The company will provide severance pay and mentoring services to affected employees to help them transition to new jobs."
        },{
            ars: "The _____ of the company's new product has been delayed due to manufacturing issues. The company had originally planned to launch the product in Q2, but now expects to release it in Q4. The delay has been _____ disappointing for the company, which had invested heavily in research and development and marketing efforts to support the launch. The company's management has reassured shareholders that the delay is temporary and that the product will be worth the wait, with features that are _____ superior to those of its competitors.",
            reals: "The launch of the company's new product has been delayed due to manufacturing issues. The company had originally planned to launch the product in Q2, but now expects to release it in Q4. The delay has been extremely disappointing for the company, which had invested heavily in research and development and marketing efforts to support the launch. The company's management has reassured shareholders that the delay is temporary and that the product will be worth the wait, with features that are significantly superior to those of its competitors.",
            sels: ["launch","design","development","testing","highly","somewhat","extremely","moderately","significantly","marginally","slightly","barely",],
            exps: "This is an article about delays in new products, the reasons for the delays and the company's response. It follows from the context: Sentence 1 mentions that the release of the product is delayed, so the answer should be launch. The second sentence mentioned that the company was very disappointed with this delay, so the answer should be extremely. Sentence 3 mentions that the product will have superior functions, so the answer should be significantly. So the answers are (A) launch, (G) extremely, and (I) significantly.",
            ans: ["(A)","(G)","(I)",],
            cns: "Launch, market launch The company's new product has been delayed due to manufacturing issues. The company had originally planned to launch the product in the second quarter, but now expects a release in the fourth quarter. The delay was severe, which is disappointing for the company, which has invested heavily in R&D and marketing to support the launch. Company management has assured shareholders that the delay is temporary and that the product is worth the wait, with notable features over its competitors."
        },{
            ars: "The hotel industry in the city has been experiencing a boom in recent years due to increased tourism. Many new hotels have _____ up in the city center, offering tourists a range of options at different price points. However, this growth has also led to increased _____ and competition among hotels, with some struggling to fill their rooms during off-peak seasons. To address this, many hotels have been _____ their services to appeal to a wider range of customers, such as offering discounted rates to business travelers and families.",
            reals: "The hotel industry in the city has been experiencing a boom in recent years due to increased tourism. Many new hotels have opened up in the city center, offering tourists a range of options at different price points. However, this growth has also led to increased supply and competition among hotels, with some struggling to fill their rooms during off-peak seasons. To address this, many hotels have been diversifying their services to appeal to a wider range of customers, such as offering discounted rates to business travelers and families.",
            sels: ["closed","opened","expanded","renovated","demand","supply","marketing","innovation","diversifying","outsourcing","downsizing","streamlining",],
            exps: "This is an article about the development of the hotel industry in the city, the article mentions the growth of the hotel industry and related issues. It can be concluded from the context: Sentence 1 mentions that the urban hotel industry has flourished in recent years, so the answer should be opened. Sentence 2 mentions that growth also brings competition and oversupply, so the answer should be supply. Sentence 3 mentions that many hotels are adjusting their services in response to market changes, so the answer should be diversifying. Therefore, the answers are (B) opened, (F) supply, and (I) diversifying.",
            ans: ["(B)","(F)","(I)",],
            cns: "In recent years, the city's hotel industry has been booming thanks to the growth of tourism. Many new hotels have opened in the city center, offering tourists a variety of options at different price points. However, this growth has also led to increased supply and competition among hotels, with some hotels struggling to fill rooms during the off-season. To combat this, many hotels have been diversifying their offerings to appeal to a wider clientele, such as offering discounted rates for business travelers and families."
        },{
            ars: "The pharmaceutical industry has come under increased scrutiny in recent years due to concerns about rising drug prices and the role of pharmaceutical companies in the opioid crisis. Many consumers are _____ to pay for medications that they need to maintain their health, leading to calls for greater government regulation of drug prices. Meanwhile, several pharmaceutical companies have faced lawsuits for their role in the opioid epidemic, with some accused of _____ their products and contributing to addiction and overdose deaths. In response, the industry has pledged to improve transparency and _____ in drug pricing and marketing practices.",
            reals: "The pharmaceutical industry has come under increased scrutiny in recent years due to concerns about rising drug prices and the role of pharmaceutical companies in the opioid crisis. Many consumers are reluctant to pay for medications that they need to maintain their health, leading to calls for greater government regulation of drug prices. Meanwhile, several pharmaceutical companies have faced lawsuits for their role in the opioid epidemic, with some accused of overpromoting their products and contributing to addiction and overdose deaths. In response, the industry has pledged to improve transparency and accountability in drug pricing and marketing practices.",
            sels: ["reluctant","eager","unwilling","hesitant","overpromoting","underpromoting","misrepresenting","falsifying","accountability","efficiency","innovation","profitability",],
            exps: "This is an article about issues in the pharmaceutical industry, with references to issues such as rising drug prices and the role of pharmaceutical companies in the opioid crisis. It can be drawn from the context: Sentence 1 mentions that many consumers are unwilling to pay high drug costs, so the answer should be reluctant. Sentence 2 mentions that some pharmaceutical companies have been accused of overpromoting their products, contributing to problems such as addiction and overdose deaths, so the answer should be overpromoting. Sentence three refers to the pharmaceutical industry's commitment to improving transparency and responsible drug pricing and marketing practices, so the answer should be accountability. So the answers are (A) reluctant, (E) overpromoting, and (I) accountability.",
            ans: ["(A)","(E)","(I)",],
            cns: "The pharmaceutical industry has come under increased scrutiny in recent years amid concerns about rising drug prices and drug companies' role in the opioid crisis. Many consumers are unwilling to pay for the drugs they need to maintain their health, leading governments to call for greater regulation of drug prices. Meanwhile, several pharmaceutical companies are facing lawsuits over their role in the opioid epidemic, with some accused of overpromoting their products and causing addiction and overdose deaths. In response, the industry has pledged to increase transparency and accountability in drug pricing and marketing practices."
        },{
            ars: "In recent years, the global energy sector has undergone significant changes, driven by concerns about _____ and the need to reduce carbon emissions. As a result, many countries have implemented policies aimed at increasing the use of renewable energy sources, such as wind and solar power. This has led to a _____ in the renewable energy industry, with companies investing heavily in research and development to improve the efficiency and cost-effectiveness of their products. However, the shift towards renewable energy has not been without its _____, as some traditional energy companies have struggled to adapt to the changing market conditions.",
            reals: "In recent years, the global energy sector has undergone significant changes, driven by concerns about sustainability and the need to reduce carbon emissions. As a result, many countries have implemented policies aimed at increasing the use of renewable energy sources, such as wind and solar power. This has led to a surge in the renewable energy industry, with companies investing heavily in research and development to improve the efficiency and cost-effectiveness of their products. However, the shift towards renewable energy has not been without its challenges, as some traditional energy companies have struggled to adapt to the changing market conditions.",
            sels: ["sustainability","diversity","innovation","competition","surge","decline","stagnation","consolidation","challenges","opportunities","benefits","rewards",],
            exps: "This is an article about the global energy industry, which mentions the changes in the industry and the corresponding challenges. It can be drawn from the context: Sentence 1 mentions the concern for sustainability and the need to reduce carbon emissions, so the answer should be sustainability. Sentence two mentions the surge in the renewable energy industry, so the answer should be surge. Sentence 3 mentioned the difficulty for traditional energy companies to adapt to market changes, so the answer should be challenges. So the answers are (A) sustainability, (E) surge and (I) challenges.",
            ans: ["(A)","(E)","(I)",],
            cns: "In recent years, the global energy industry has undergone major changes, driven by concerns about sustainability and the need to reduce carbon emissions. As a result, many countries have implemented policies aimed at increasing the use of renewable energy sources such as wind and solar. This has led to a surge in the renewable energy industry, with companies investing heavily in research and development to improve the efficiency and cost-effectiveness of their products. However, the transition to renewable energy has not been without challenges, as some traditional energy companies have struggled to adapt to changing market conditions."
        },{
            ars: "Over the past decade, advances in technology have transformed the way we live and work. One of the most significant changes has been the widespread adoption of _____ devices, such as smartphones and tablets. These devices have revolutionized the way we _____ information, allowing us to access a wealth of knowledge at our fingertips. However, they have also had a number of _____ effects, such as the erosion of face-to-face communication skills and the development of addiction to social media.",
            reals: "Over the past decade, advances in technology have transformed the way we live and work. One of the most significant changes has been the widespread adoption of mobile devices, such as smartphones and tablets. These devices have revolutionized the way we retrieve information, allowing us to access a wealth of knowledge at our fingertips. However, they have also had a number of detrimental effects, such as the erosion of face-to-face communication skills and the development of addiction to social media.",
            sels: ["mobile","wireless","digital","handheld","process","retrieve","disseminate","interpret","beneficial","detrimental","positive","negative",],
            exps: "This is an article about technological change, and the article mentions the impact of technological change on life and work. From the context: Sentence 1 mentions the widespread use of mobile devices such as smartphones and tablets, so the answer should be mobile. Sentence two mentions the revolutionary change in knowledge acquisition using these devices, so the answer should be retrieve. The negative effect of using these devices is mentioned in the third sentence, so the answer should be detrimental. So the answers are (A) mobile, (F) retrieve, and (J) detrimental.",
            ans: ["(A)","(F)","(J)",],
            cns: "Over the past decade, advances in technology have transformed the way we live and work. One of the most important changes is the widespread adoption of mobile Internet devices, such as smartphones and tablets. These devices have revolutionized the way we retrieve information, putting a wealth of knowledge at our fingertips. However, they also have deleterious effects, such as the erosion of face-to-face communication skills and the development of social media addiction."
        },{
            ars: "In recent years, businesses have increasingly turned to social media to _____ with their customers. Platforms like Facebook and Twitter offer companies a way to _____ with their audience in real-time, and can help to create a sense of community around a brand. However, social media also presents a number of _____, including the potential for negative feedback to spread quickly and damage a company's reputation.",
            reals: "In recent years, businesses have increasingly turned to social media to engage with their customers. Platforms like Facebook and Twitter offer companies a way to interact with their audience in real-time, and can help to create a sense of community around a brand. However, social media also presents a number of drawbacks, including the potential for negative feedback to spread quickly and damage a company's reputation.",
            sels: ["collaborate","engage","compete","negotiate","interact","market","advertise","promote","opportunities","challenges","benefits","drawbacks",],
            exps: "This is an article about businesses using social media to interact with customers, the article mentions the impact of social media on businesses. From the context: Sentence 1 mentions that businesses are increasingly using social media to interact with customers, so the answer should be engage. Sentence 2 mentioned that social media can help companies build brand communities, so the answer should be interact. Sentence 3 mentions the risks of using social media, so the answer should be drawbacks. So the answer is (B) engage, (E) interact and (L) drawbacks.",
            ans: ["(B)","(E)","(L)",],
            cns: "In recent years, businesses have increasingly turned to social media to engage with their customers. Platforms such as Facebook and Twitter offer companies an interactive way to communicate with their audiences in real time and help create a sense of community around a brand. However, social media also has some disadvantages, including the potential for negative feedback to spread quickly and damage a company's reputation."
        },{
            ars: "The hotel industry is experiencing a _____ in business due to the recent economic boom. With more people _____ disposable income, more and more individuals are choosing to travel and stay in hotels. In order to meet the demand, hotels are expanding their facilities and _____ their services to attract customers.",
            reals: "The hotel industry is experiencing a surge in business due to the recent economic boom. With more people spending disposable income, more and more individuals are choosing to travel and stay in hotels. In order to meet the demand, hotels are expanding their facilities and improving their services to attract customers.",
            sels: ["decline","stagnation","surge","fluctuation","having","earning","spending","saving","improving","reducing","limiting","discontinuing",],
            exps: "This is an article about the growth of the hotel business. The article mentioned that as the economy booms and more and more people choose to travel and stay in hotels, there is a surge in the hotel business. From the context, it follows that surge is mentioned in sentence one, so the answer should be (C) surge. Sentence 2 mentions that as people spend more disposable income, they increasingly choose to travel and stay in hotels, so the answer should be (G) spending. Sentence 3 mentioned that in order to meet the demand, the hotel is expanding its facilities and improving its services to attract customers, so the answer should be (I) improving. So the answers are (C) surge, (G) spending, and (I) improving.",
            ans: ["(C)","(G)","(I)",],
            cns: "The hospitality industry is experiencing a surge in business activity due to the recent economic boom. As more and more people consume With the increase of disposable income, more and more people choose to travel and stay in hotels. To meet the demand, hotels are expanding their facilities and improving their services to attract customers."
        },{
            ars: "In recent years, online shopping has become increasingly popular among consumers. One of the biggest advantages of online shopping is that it allows customers to _____ items from the comfort of their own homes. This means that people can avoid the hassle of traffic and crowded stores. Additionally, online shopping often offers a wider variety of products than traditional retail stores, as well as _____ prices. Many retailers also offer free shipping or other _____ to encourage customers to shop online.",
            reals: "In recent years, online shopping has become increasingly popular among consumers. One of the biggest advantages of online shopping is that it allows customers to purchase items from the comfort of their own homes. This means that people can avoid the hassle of traffic and crowded stores. Additionally, online shopping often offers a wider variety of products than traditional retail stores, as well as lower prices. Many retailers also offer free shipping or other promotions to encourage customers to shop online.",
            sels: ["purchase","return","exchange","rent","lower","higher","fixed","fluctuating","promotions","warranties","discounts","contracts",],
            exps: "This is an article about online shopping. The article mentions the advantages of online shopping, including convenience, avoiding traffic and crowds, wide variety of products, lower prices, promotions offered by stores, free shipping, etc. It can be drawn from the context: Sentence 1 mentions that online shopping allows people to buy goods from home, so the answer should be (A) purchase. Sentence 2 mentions that one of the advantages of online shopping is lower prices, so the answer should be (E) lower. Sentence 3 mentions the promotions and free shipping offered by the store, etc., so the answer should be (I) promotions. So the answer is (A) purchase, (E) lower and (I) promotions.",
            ans: ["(A)","(E)","(I)",],
            cns: "In recent years, online shopping has become more and more popular among consumers. One of the greatest advantages of online shopping is that it allows customers to purchase items from the comfort of their own homes. This means people can avoid the hassle of traffic and crowded shops. In addition, online shopping often offers a wider variety of products than traditional retail stores, and at lower prices. Many retailers also offer free shipping or other promotions to encourage customers to shop online."
        },{
            ars: "The hospitality industry, which includes hotels, restaurants, and catering services, plays a crucial role in the global economy. As international travel continues to _____, the demand for hotels and restaurants has increased. In addition, many people today prefer to _____ out or order in rather than cook at home. This has led to a growth in the number of restaurants and catering services, both small and large.When it comes to hotels, there are a wide variety of options available to travelers. From luxury hotels to budget accommodations, there is something for every _____ of traveler. Many hotels now offer additional amenities such as fitness centers, swimming pools, and complimentary breakfast. In order to stay competitive, hotels must also keep up with the latest technologies, such as online reservation systems and mobile check-in options.",
            reals: "The hospitality industry, which includes hotels, restaurants, and catering services, plays a crucial role in the global economy. As international travel continues to increase, the demand for hotels and restaurants has increased. In addition, many people today prefer to dine out or order in rather than cook at home. This has led to a growth in the number of restaurants and catering services, both small and large.When it comes to hotels, there are a wide variety of options available to travelers. From luxury hotels to budget accommodations, there is something for every category of traveler. Many hotels now offer additional amenities such as fitness centers, swimming pools, and complimentary breakfast. In order to stay competitive, hotels must also keep up with the latest technologies, such as online reservation systems and mobile check-in options.",
            sels: ["decrease","stagnate","increase","fluctuate","eat","dine","take","make","kind","level","group","category",],
            exps: "This is an article about the restaurant and hotel industry. The article mentions that as international tourism increases, so does the demand for hotels and restaurants. At the same time, more and more people are choosing to eat out or order food delivery, so the number of restaurants and catering services is also growing. In addition, hotels also offer a variety of options, including luxury hotels and budget accommodation, etc., and in order to remain competitive, hotels must also keep up with the latest technology. Sentence 1 mentions that as international tourism increases, so does the demand for hotels and restaurants, so the answer should be (C) increase. Sentence 2 mentions that more and more people choose to eat out or order food delivery, so the answer should be (F) dine. Sentence 3 mentions that the hotel offers various options, including luxury hotels and budget accommodation, etc., so the answer should be (L) category. Therefore, the answers are (C) increase, (F) dine, and (L) category.",
            ans: ["(C)","(F)","(L)",],
            cns: "The hospitality industry, including hotels, restaurants, and foodservice, plays a vital role in the global economy. As international travel continues to increase, the demand for hotels and restaurants has increased. Additionally, many people today prefer to dine out or order rather than cook at home. This has led to an increase in the number of large and small restaurants and food services. When it comes to hotels, travelers have a variety of options. From luxury hotels to budget lodging, there is something for every category of traveller. Many hotels now offer extra amenities such as fitness centers, swimming pools and free breakfast. To remain competitive, hotels must also keep up with the latest technologies, such as online reservation systems and mobile check-in options."
        },]