const q = [{
            ars: "The new restaurant in town is already causing quite a _____ with its unique menu and elegant atmosphere. The restaurant's owner, a well-known chef, has created a _____ dining experience that is both delicious and memorable. The restaurant offers a wide variety of dishes, ranging from classic comfort food to exotic _____ from around the world. Customers can choose to dine in the main dining room or in a more intimate private _____ for special occasions. The restaurant also offers catering services for corporate events and private parties.",
            reals: "The new restaurant in town is already causing quite a stir with its unique menu and elegant atmosphere. The restaurant's owner, a well-known chef, has created a refined dining experience that is both delicious and memorable. The restaurant offers a wide variety of dishes, ranging from classic comfort food to exotic delicacies from around the world. Customers can choose to dine in the main dining room or in a more intimate private booth for special occasions. The restaurant also offers catering services for corporate events and private parties.",
            sels: ["stir","steer","stare","store","refined","delightful","extravagant","delicate","delicacies","spices","beverages","desserts","booth","chamber","lounge","terrace",],
            exps: "Este es un artículo sobre un nuevo restaurante, mencionando el menú y el ambiente del restaurante. Del contexto: la oración uno menciona el menú único del restaurante y el ambiente elegante, por lo que la respuesta debería ser revolver. La oración 2 menciona que los platos del restaurante son deliciosos y memorables, por lo que la respuesta debe ser refinada. La oración 3 menciona que el restaurante sirve una amplia variedad de platos, que incluyen comida reconfortante clásica y cocinas exóticas de todo el mundo, por lo que la respuesta debería ser delicias. La oración cuatro se refiere al comedor privado que ofrece el restaurante, por lo que la respuesta debería ser cabina. Por lo tanto, las respuestas son (A) remover, (E) refinado, (I) manjares y (M) stand.",
            ans: ["(A)","(E)","(I)","(M)",],
            cns: "El nuevo restaurante de la ciudad ya está causando revuelo con su menú único y ambiente elegante. El propietario del restaurante es un chef de renombre que ha creado una experiencia gastronómica refinada que es a la vez deliciosa y memorable. El restaurante ofrece una amplia variedad de platos, desde comida reconfortante clásica hasta cocina exótica de todo el mundo. Los clientes pueden optar por cenar en el comedor principal o en palcos más íntimos para ocasiones especiales. El restaurante también atiende eventos corporativos y fiestas privadas."
        },{
            ars: "The new marketing campaign has been _____ successful, with sales increasing by 20% since its launch. The campaign's focus on social media has helped the company reach a wider _____, particularly among younger consumers who spend a lot of time on their phones. The company's _____ strategy, which includes targeted ads and influencer partnerships, has also contributed to its success. However, the company's _____ has also played a role in the campaign's success, as its reputation for high-quality products has helped build trust with customers.",
            reals: "The new marketing campaign has been tremendously successful, with sales increasing by 20% since its launch. The campaign's focus on social media has helped the company reach a wider audience, particularly among younger consumers who spend a lot of time on their phones. The company's promotion strategy, which includes targeted ads and influencer partnerships, has also contributed to its success. However, the company's reputation has also played a role in the campaign's success, as its reputation for high-quality products has helped build trust with customers.",
            sels: ["moderately","tremendously","barely","slightly","audience","market","sector","niche","pricing","promotion","distribution","packaging","innovation","reputation","location","convenience",],
            exps: "Este es un artículo sobre una campaña de marketing que menciona por qué la campaña fue exitosa. Del contexto, se deduce que el éxito de la campaña se menciona en la oración uno, por lo que la respuesta debería ser tremendamente. La oración 2 menciona que el evento es especialmente popular entre los consumidores jóvenes, por lo que la respuesta debería ser público. La estrategia de la campaña se menciona en la tercera oración, incluida la publicidad dirigida y la cooperación de personas influyentes, por lo que la respuesta debería ser promoción. La reputación de la empresa se menciona en la oración cuatro, lo que ayuda a generar confianza con los clientes, por lo que la respuesta debería ser reputación. Entonces, las respuestas son (B) enormemente, (E) audiencia, (J) promoción y (N) reputación.",
            ans: ["(B)","(E)","(J)","(N)",],
            cns: "La nueva campaña de marketing ha sido un gran éxito, con un aumento de las ventas del 20 % desde su lanzamiento. El enfoque de la campaña en las redes sociales ha ayudado a la compañía a llegar a una audiencia más amplia, especialmente entre los consumidores más jóvenes que pasan mucho tiempo en sus teléfonos. Las estrategias de publicidad corporativa, incluida la publicidad dirigida y las asociaciones con personas influyentes, también han contribuido a su éxito. Sin embargo, la reputación de una empresa también influye en el éxito del evento, ya que su reputación de productos de alta calidad ayuda a generar confianza en el cliente."
        },{
            ars: "The company has announced plans to _____ its workforce by 10% in an effort to reduce costs. The layoffs will primarily affect _____ in the company's administrative and support departments, although some managers and executives will also be let go. The company's CEO has stated that these changes are necessary to ensure the long-term _____ of the company and maintain its competitiveness in the marketplace. The company will provide severance packages and _____ services to affected employees to help them transition to new employment.",
            reals: "The company has announced plans to downsize its workforce by 10% in an effort to reduce costs. The layoffs will primarily affect employees in the company's administrative and support departments, although some managers and executives will also be let go. The company's CEO has stated that these changes are necessary to ensure the long-term sustainability of the company and maintain its competitiveness in the marketplace. The company will provide severance packages and counseling services to affected employees to help them transition to new employment.",
            sels: ["expand","downsize","diversify","centralize","employees","shareholders","customers","suppliers","profitability","stability","flexibility","sustainability","relocation","retraining","counseling","mentoring",],
            exps: "Este es un artículo sobre el plan de despidos de una empresa, y el artículo menciona las causas y los efectos del plan. Del contexto se puede concluir: La oración 1 menciona el plan de despidos de la empresa, por lo que la respuesta debería ser reducir. La oración 2 menciona que un departamento específico de empleados se ve afectado, por lo que la respuesta debe ser empleados. La oración 3 menciona que el director general de la empresa cree que estos cambios son necesarios para asegurar la estabilidad y competitividad a largo plazo de la empresa, por lo que la respuesta debe ser sostenibilidad. La oración 4 menciona que la empresa brinda indemnizaciones por despido y servicios de asesoramiento para ayudar a los empleados afectados en la transición a un nuevo empleo, por lo que la respuesta debería ser asesoramiento. Entonces, las respuestas son (B) reducción de tamaño, (E) empleados, (L) sostenibilidad y (O) asesoramiento.",
            ans: ["(B)","(E)","(L)","(O)",],
            cns: "La compañía ha anunciado planes para reducir su fuerza laboral en un 10% en un esfuerzo por reducir costos. Los despidos afectan principalmente a los empleados en funciones administrativas y de apoyo a la empresa, aunque también se despedirá a algunos gerentes y ejecutivos. El presidente ejecutivo de la empresa dijo que los cambios eran necesarios para garantizar la sustentabilidad a largo plazo y mantener la competitividad de la empresa en el mercado. La empresa proporcionará indemnización por despido y servicios de tutoría a los empleados afectados para ayudarlos en la transición a nuevos trabajos."
        },{
            ars: "The _____ of the company's new product has been delayed due to manufacturing issues. The company had originally planned to launch the product in Q2, but now expects to release it in Q4. The delay has been _____ disappointing for the company, which had invested heavily in research and development and marketing efforts to support the launch. The company's management has reassured shareholders that the delay is temporary and that the product will be worth the wait, with features that are _____ superior to those of its competitors.",
            reals: "The launch of the company's new product has been delayed due to manufacturing issues. The company had originally planned to launch the product in Q2, but now expects to release it in Q4. The delay has been extremely disappointing for the company, which had invested heavily in research and development and marketing efforts to support the launch. The company's management has reassured shareholders that the delay is temporary and that the product will be worth the wait, with features that are significantly superior to those of its competitors.",
            sels: ["launch","design","development","testing","highly","somewhat","extremely","moderately","significantly","marginally","slightly","barely",],
            exps: "Este es un artículo sobre retrasos en nuevos productos, los motivos de los retrasos y la respuesta de la empresa. Se deduce del contexto: la oración 1 menciona que el lanzamiento del producto se retrasa, por lo que la respuesta debería ser lanzamiento. La segunda oración menciona que la empresa estaba muy decepcionada con este retraso, por lo que la respuesta debería ser extremadamente. La oración 3 menciona que el producto tendrá funciones superiores, por lo que la respuesta debe ser significativamente. Entonces, las respuestas son (A) lanzamiento, (G) extremadamente y (I) significativamente.",
            ans: ["(A)","(G)","(I)",],
            cns: "Lanzamiento, lanzamiento al mercado El nuevo producto de la compañía se ha retrasado debido a problemas de fabricación. La compañía había planeado originalmente lanzar el producto en el segundo trimestre, pero ahora espera un lanzamiento en el cuarto trimestre. El retraso fue grave, lo que es decepcionante para la empresa, que ha invertido mucho en I+D y marketing para respaldar el lanzamiento. La dirección de la compañía ha asegurado a los accionistas que el retraso es temporal y que el producto merece la espera, con características notables sobre sus competidores."
        },{
            ars: "The hotel industry in the city has been experiencing a boom in recent years due to increased tourism. Many new hotels have _____ up in the city center, offering tourists a range of options at different price points. However, this growth has also led to increased _____ and competition among hotels, with some struggling to fill their rooms during off-peak seasons. To address this, many hotels have been _____ their services to appeal to a wider range of customers, such as offering discounted rates to business travelers and families.",
            reals: "The hotel industry in the city has been experiencing a boom in recent years due to increased tourism. Many new hotels have opened up in the city center, offering tourists a range of options at different price points. However, this growth has also led to increased supply and competition among hotels, with some struggling to fill their rooms during off-peak seasons. To address this, many hotels have been diversifying their services to appeal to a wider range of customers, such as offering discounted rates to business travelers and families.",
            sels: ["closed","opened","expanded","renovated","demand","supply","marketing","innovation","diversifying","outsourcing","downsizing","streamlining",],
            exps: "Este es un artículo sobre el desarrollo de la industria hotelera en la ciudad, el artículo menciona el crecimiento de la industria hotelera y temas relacionados. Del contexto se puede concluir: La oración 1 menciona que la industria hotelera urbana ha florecido en los últimos años, por lo que la respuesta debe ser “abierta”. La oración 2 menciona que el crecimiento también trae competencia y sobreoferta, por lo que la respuesta debería ser oferta. La oración 3 menciona que muchos hoteles están ajustando sus servicios en respuesta a los cambios del mercado, por lo que la respuesta debería ser diversificar. Por tanto, las respuestas son (B) apertura, (F) oferta y (I) diversificación.",
            ans: ["(B)","(F)","(I)",],
            cns: "En los últimos años, la industria hotelera de la ciudad ha estado en auge gracias al crecimiento del turismo. Se han abierto muchos hoteles nuevos en el centro de la ciudad, que ofrecen a los turistas una variedad de opciones a diferentes precios. Sin embargo, este crecimiento también ha llevado a una mayor oferta y competencia entre los hoteles, con algunos hoteles luchando por llenar las habitaciones fuera de temporada. Para combatir esto, muchos hoteles han estado diversificando sus ofertas para atraer a una clientela más amplia, como ofrecer tarifas con descuento para viajeros de negocios y familias."
        },{
            ars: "The pharmaceutical industry has come under increased scrutiny in recent years due to concerns about rising drug prices and the role of pharmaceutical companies in the opioid crisis. Many consumers are _____ to pay for medications that they need to maintain their health, leading to calls for greater government regulation of drug prices. Meanwhile, several pharmaceutical companies have faced lawsuits for their role in the opioid epidemic, with some accused of _____ their products and contributing to addiction and overdose deaths. In response, the industry has pledged to improve transparency and _____ in drug pricing and marketing practices.",
            reals: "The pharmaceutical industry has come under increased scrutiny in recent years due to concerns about rising drug prices and the role of pharmaceutical companies in the opioid crisis. Many consumers are reluctant to pay for medications that they need to maintain their health, leading to calls for greater government regulation of drug prices. Meanwhile, several pharmaceutical companies have faced lawsuits for their role in the opioid epidemic, with some accused of overpromoting their products and contributing to addiction and overdose deaths. In response, the industry has pledged to improve transparency and accountability in drug pricing and marketing practices.",
            sels: ["reluctant","eager","unwilling","hesitant","overpromoting","underpromoting","misrepresenting","falsifying","accountability","efficiency","innovation","profitability",],
            exps: "Este es un artículo sobre temas de la industria farmacéutica, con referencias a temas como el aumento de los precios de los medicamentos y el papel de las empresas farmacéuticas en la crisis de los opiáceos. Se puede extraer del contexto: la oración 1 menciona que muchos consumidores no están dispuestos a pagar los altos costos de los medicamentos, por lo que la respuesta debería ser renuente. La oración 2 menciona que algunas compañías farmacéuticas han sido acusadas de sobrepromocionar sus productos, lo que contribuye a problemas como la adicción y las muertes por sobredosis, por lo que la respuesta debería ser sobrepromoción. La oración tres se refiere al compromiso de la industria farmacéutica de mejorar la transparencia y las prácticas responsables de mercadeo y fijación de precios de medicamentos, por lo que la respuesta debería ser rendición de cuentas. Entonces, las respuestas son (A) reacio, (E) promoción excesiva y (I) responsabilidad.",
            ans: ["(A)","(E)","(I)",],
            cns: "La industria farmacéutica ha sido objeto de un mayor escrutinio en los últimos años en medio de preocupaciones sobre el aumento de los precios de los medicamentos y el papel de las compañías farmacéuticas en la crisis de los opiáceos. Muchos consumidores no están dispuestos a pagar por los medicamentos que necesitan para mantener su salud, lo que lleva a los gobiernos a exigir una mayor regulación de los precios de los medicamentos. Mientras tanto, varias compañías farmacéuticas enfrentan demandas por su papel en la epidemia de opiáceos, y algunas están acusadas de sobrepromocionar sus productos y causar muertes por adicción y sobredosis. En respuesta, la industria se comprometió a aumentar la transparencia y la rendición de cuentas en las prácticas de mercadeo y fijación de precios de medicamentos."
        },{
            ars: "In recent years, the global energy sector has undergone significant changes, driven by concerns about _____ and the need to reduce carbon emissions. As a result, many countries have implemented policies aimed at increasing the use of renewable energy sources, such as wind and solar power. This has led to a _____ in the renewable energy industry, with companies investing heavily in research and development to improve the efficiency and cost-effectiveness of their products. However, the shift towards renewable energy has not been without its _____, as some traditional energy companies have struggled to adapt to the changing market conditions.",
            reals: "In recent years, the global energy sector has undergone significant changes, driven by concerns about sustainability and the need to reduce carbon emissions. As a result, many countries have implemented policies aimed at increasing the use of renewable energy sources, such as wind and solar power. This has led to a surge in the renewable energy industry, with companies investing heavily in research and development to improve the efficiency and cost-effectiveness of their products. However, the shift towards renewable energy has not been without its challenges, as some traditional energy companies have struggled to adapt to the changing market conditions.",
            sels: ["sustainability","diversity","innovation","competition","surge","decline","stagnation","consolidation","challenges","opportunities","benefits","rewards",],
            exps: "Este es un artículo sobre la industria energética global, que menciona los cambios en la industria y los desafíos correspondientes. Se puede extraer del contexto: la oración 1 menciona la preocupación por la sostenibilidad y la necesidad de reducir las emisiones de carbono, por lo que la respuesta debería ser sostenibilidad. La oración dos menciona el auge de la industria de las energías renovables, por lo que la respuesta debería ser aumento. La oración 3 mencionó la dificultad de las empresas de energía tradicionales para adaptarse a los cambios del mercado, por lo que la respuesta debería ser desafíos. Entonces, las respuestas son (A) sostenibilidad, (E) aumento y (I) desafíos.",
            ans: ["(A)","(E)","(I)",],
            cns: "En los últimos años, la industria energética mundial ha experimentado grandes cambios, impulsada por la preocupación por la sostenibilidad y la necesidad de reducir las emisiones de carbono. Como resultado, muchos países han implementado políticas destinadas a aumentar el uso de fuentes de energía renovables como la eólica y la solar. Esto ha llevado a un aumento en la industria de la energía renovable, con empresas que invierten mucho en investigación y desarrollo para mejorar la eficiencia y la rentabilidad de sus productos. Sin embargo, la transición a la energía renovable no ha estado exenta de desafíos, ya que algunas empresas de energía tradicionales han tenido dificultades para adaptarse a las condiciones cambiantes del mercado."
        },{
            ars: "Over the past decade, advances in technology have transformed the way we live and work. One of the most significant changes has been the widespread adoption of _____ devices, such as smartphones and tablets. These devices have revolutionized the way we _____ information, allowing us to access a wealth of knowledge at our fingertips. However, they have also had a number of _____ effects, such as the erosion of face-to-face communication skills and the development of addiction to social media.",
            reals: "Over the past decade, advances in technology have transformed the way we live and work. One of the most significant changes has been the widespread adoption of mobile devices, such as smartphones and tablets. These devices have revolutionized the way we retrieve information, allowing us to access a wealth of knowledge at our fingertips. However, they have also had a number of detrimental effects, such as the erosion of face-to-face communication skills and the development of addiction to social media.",
            sels: ["mobile","wireless","digital","handheld","process","retrieve","disseminate","interpret","beneficial","detrimental","positive","negative",],
            exps: "Este es un artículo sobre el cambio tecnológico, y el artículo menciona el impacto del cambio tecnológico en la vida y el trabajo. Del contexto: la oración 1 menciona el uso generalizado de dispositivos móviles como teléfonos inteligentes y tabletas, por lo que la respuesta debería ser móvil. La oración dos menciona el cambio revolucionario en la adquisición de conocimiento utilizando estos dispositivos, por lo que la respuesta debería ser recuperar. El efecto negativo del uso de estos dispositivos se menciona en la tercera oración, por lo que la respuesta debería ser perjudicial. Entonces, las respuestas son (A) móvil, (F) recuperar y (J) perjudicial.",
            ans: ["(A)","(F)","(J)",],
            cns: "Durante la última década, los avances tecnológicos han transformado la forma en que vivimos y trabajamos. Uno de los cambios más importantes es la adopción generalizada de dispositivos móviles de Internet, como teléfonos inteligentes y tabletas. Estos dispositivos han revolucionado la forma en que recuperamos información, poniendo una gran cantidad de conocimiento al alcance de la mano. Sin embargo, también tienen efectos nocivos, como la erosión de las habilidades de comunicación cara a cara y el desarrollo de la adicción a las redes sociales."
        },{
            ars: "In recent years, businesses have increasingly turned to social media to _____ with their customers. Platforms like Facebook and Twitter offer companies a way to _____ with their audience in real-time, and can help to create a sense of community around a brand. However, social media also presents a number of _____, including the potential for negative feedback to spread quickly and damage a company's reputation.",
            reals: "In recent years, businesses have increasingly turned to social media to engage with their customers. Platforms like Facebook and Twitter offer companies a way to interact with their audience in real-time, and can help to create a sense of community around a brand. However, social media also presents a number of drawbacks, including the potential for negative feedback to spread quickly and damage a company's reputation.",
            sels: ["collaborate","engage","compete","negotiate","interact","market","advertise","promote","opportunities","challenges","benefits","drawbacks",],
            exps: "Este es un artículo sobre las empresas que utilizan las redes sociales para interactuar con los clientes, el artículo menciona el impacto de las redes sociales en las empresas. Del contexto: la oración 1 menciona que las empresas utilizan cada vez más las redes sociales para interactuar con los clientes, por lo que la respuesta debería ser interactuar. La oración 2 mencionó que las redes sociales pueden ayudar a las empresas a construir comunidades de marca, por lo que la respuesta debería ser interactuar. La oración 3 menciona los riesgos de usar las redes sociales, por lo que la respuesta debería ser inconvenientes. Entonces la respuesta es (B) participar, (E) interactuar y (L) inconvenientes.",
            ans: ["(B)","(E)","(L)",],
            cns: "En los últimos años, las empresas han recurrido cada vez más a las redes sociales para interactuar con sus clientes. Plataformas como Facebook y Twitter ofrecen a las empresas una forma interactiva de comunicarse con sus audiencias en tiempo real y ayudan a crear un sentido de comunidad en torno a una marca. Sin embargo, las redes sociales también tienen algunas desventajas, incluida la posibilidad de que los comentarios negativos se propaguen rápidamente y dañen la reputación de una empresa."
        },{
            ars: "The hotel industry is experiencing a _____ in business due to the recent economic boom. With more people _____ disposable income, more and more individuals are choosing to travel and stay in hotels. In order to meet the demand, hotels are expanding their facilities and _____ their services to attract customers.",
            reals: "The hotel industry is experiencing a surge in business due to the recent economic boom. With more people spending disposable income, more and more individuals are choosing to travel and stay in hotels. In order to meet the demand, hotels are expanding their facilities and improving their services to attract customers.",
            sels: ["decline","stagnation","surge","fluctuation","having","earning","spending","saving","improving","reducing","limiting","discontinuing",],
            exps: "Este es un artículo sobre el crecimiento del negocio hotelero. El artículo menciona que a medida que la economía crece y más y más personas eligen viajar y quedarse en hoteles, hay un aumento en el negocio hotelero. Del contexto, se deduce que surgimiento se menciona en la oración uno, por lo que la respuesta debería ser (C) aumento. La oración 2 menciona que a medida que las personas gastan más ingresos disponibles, optan cada vez más por viajar y hospedarse en hoteles, por lo que la respuesta debería ser (G) gasto. La oración 3 mencionó que para satisfacer la demanda, el hotel está ampliando sus instalaciones y “mejorando” sus servicios para atraer clientes, por lo que la respuesta debería ser (I) mejorando. Entonces, las respuestas son (C) aumento, (G) gasto y (I) mejora.",
            ans: ["(C)","(G)","(I)",],
            cns: "La industria de la hospitalidad está experimentando un aumento en la actividad comercial debido al reciente auge económico. A medida que más y más personas consumen Con el aumento de la renta disponible, más y más personas optan por viajar y alojarse en hoteles. Para satisfacer la demanda, los hoteles están ampliando sus instalaciones y mejorando sus servicios para atraer clientes."
        },{
            ars: "In recent years, online shopping has become increasingly popular among consumers. One of the biggest advantages of online shopping is that it allows customers to _____ items from the comfort of their own homes. This means that people can avoid the hassle of traffic and crowded stores. Additionally, online shopping often offers a wider variety of products than traditional retail stores, as well as _____ prices. Many retailers also offer free shipping or other _____ to encourage customers to shop online.",
            reals: "In recent years, online shopping has become increasingly popular among consumers. One of the biggest advantages of online shopping is that it allows customers to purchase items from the comfort of their own homes. This means that people can avoid the hassle of traffic and crowded stores. Additionally, online shopping often offers a wider variety of products than traditional retail stores, as well as lower prices. Many retailers also offer free shipping or other promotions to encourage customers to shop online.",
            sels: ["purchase","return","exchange","rent","lower","higher","fixed","fluctuating","promotions","warranties","discounts","contracts",],
            exps: "Este es un artículo sobre compras en línea. El artículo menciona las ventajas de comprar en línea, incluida la comodidad, evitar el tráfico y las aglomeraciones, gran variedad de productos, precios más bajos, promociones ofrecidas por las tiendas, envío gratuito, etc. Se puede extraer del contexto: la oración 1 menciona que las compras en línea permiten a las personas comprar productos desde casa, por lo que la respuesta debería ser (A) comprar. La oración 2 menciona que una de las ventajas de comprar en línea son los precios más bajos, por lo que la respuesta debería ser (E) más baja. La oración 3 menciona las promociones y el envío gratuito que ofrece la tienda, etc., por lo que la respuesta debe ser (I) promociones. Entonces la respuesta es (A) compra, (E) rebaja y (I) promociones.",
            ans: ["(A)","(E)","(I)",],
            cns: "En los últimos años, las compras en línea se han vuelto cada vez más populares entre los consumidores. Una de las mayores ventajas de las compras en línea es que permite a los clientes comprar artículos desde la comodidad de sus hogares. Esto significa que las personas pueden evitar las molestias del tráfico y las tiendas llenas de gente. Además, las compras en línea a menudo ofrecen una variedad más amplia de productos que las tiendas minoristas tradicionales y a precios más bajos. Muchos minoristas también ofrecen envío gratuito u otras promociones para alentar a los clientes a comprar en línea."
        },{
            ars: "The hospitality industry, which includes hotels, restaurants, and catering services, plays a crucial role in the global economy. As international travel continues to _____, the demand for hotels and restaurants has increased. In addition, many people today prefer to _____ out or order in rather than cook at home. This has led to a growth in the number of restaurants and catering services, both small and large.When it comes to hotels, there are a wide variety of options available to travelers. From luxury hotels to budget accommodations, there is something for every _____ of traveler. Many hotels now offer additional amenities such as fitness centers, swimming pools, and complimentary breakfast. In order to stay competitive, hotels must also keep up with the latest technologies, such as online reservation systems and mobile check-in options.",
            reals: "The hospitality industry, which includes hotels, restaurants, and catering services, plays a crucial role in the global economy. As international travel continues to increase, the demand for hotels and restaurants has increased. In addition, many people today prefer to dine out or order in rather than cook at home. This has led to a growth in the number of restaurants and catering services, both small and large.When it comes to hotels, there are a wide variety of options available to travelers. From luxury hotels to budget accommodations, there is something for every category of traveler. Many hotels now offer additional amenities such as fitness centers, swimming pools, and complimentary breakfast. In order to stay competitive, hotels must also keep up with the latest technologies, such as online reservation systems and mobile check-in options.",
            sels: ["decrease","stagnate","increase","fluctuate","eat","dine","take","make","kind","level","group","category",],
            exps: "Este es un artículo sobre la industria restaurantera y hotelera. El artículo menciona que a medida que aumenta el turismo internacional, también lo hace la demanda de hoteles y restaurantes. Al mismo tiempo, cada vez más personas optan por comer fuera o pedir comida a domicilio, por lo que el número de restaurantes y servicios de catering también está creciendo. Además, los hoteles también ofrecen una variedad de opciones, incluidos hoteles de lujo y alojamiento económico, etc., y para seguir siendo competitivos, los hoteles también deben mantenerse al día con la última tecnología. La oración 1 menciona que a medida que aumenta el turismo internacional, también aumenta la demanda de hoteles y restaurantes, por lo que la respuesta debería ser (C) aumentar. La oración 2 menciona que cada vez más personas optan por comer fuera o pedir comida a domicilio, por lo que la respuesta debería ser (F) cenar. La oración 3 menciona que el hotel ofrece varias opciones, incluidos hoteles de lujo y alojamiento económico, etc., por lo que la respuesta debe ser categoría (L). Por lo tanto, las respuestas son (C) aumentar, (F) cenar y (L) categoría.",
            ans: ["(C)","(F)","(L)",],
            cns: "La industria hotelera, incluidos los hoteles, los restaurantes y los servicios de comidas, desempeña un papel fundamental en la economía mundial. A medida que los viajes internacionales continúan aumentando, la demanda de hoteles y restaurantes ha aumentado. Además, muchas personas hoy en día prefieren cenar fuera o hacer pedidos en lugar de cocinar en casa. Esto ha llevado a un aumento en el número de restaurantes y servicios de comida grandes y pequeños. Cuando se trata de hoteles, los viajeros tienen una variedad de opciones. Desde hoteles de lujo hasta alojamiento económico, hay algo para cada categoría de viajero. Muchos hoteles ahora ofrecen servicios adicionales como gimnasios, piscinas y desayuno gratis. Para seguir siendo competitivos, los hoteles también deben mantenerse al día con las últimas tecnologías, como los sistemas de reserva en línea y las opciones de check-in móvil."
        },]