const q = [{
            ars: "The new restaurant in town is already causing quite a _____ with its unique menu and elegant atmosphere. The restaurant's owner, a well-known chef, has created a _____ dining experience that is both delicious and memorable. The restaurant offers a wide variety of dishes, ranging from classic comfort food to exotic _____ from around the world. Customers can choose to dine in the main dining room or in a more intimate private _____ for special occasions. The restaurant also offers catering services for corporate events and private parties.",
            reals: "The new restaurant in town is already causing quite a stir with its unique menu and elegant atmosphere. The restaurant's owner, a well-known chef, has created a refined dining experience that is both delicious and memorable. The restaurant offers a wide variety of dishes, ranging from classic comfort food to exotic delicacies from around the world. Customers can choose to dine in the main dining room or in a more intimate private booth for special occasions. The restaurant also offers catering services for corporate events and private parties.",
            sels: ["stir","steer","stare","store","refined","delightful","extravagant","delicate","delicacies","spices","beverages","desserts","booth","chamber","lounge","terrace",],
            exps: "Ceci est un article sur un nouveau restaurant, mentionnant le menu et l'ambiance du restaurant. D'après le contexte : la première phrase mentionne le menu unique et l'ambiance élégante du restaurant, la réponse devrait donc être remuer. La phrase 2 mentionne que les plats du restaurant sont délicieux et mémorables, donc la réponse doit être raffinée. La phrase 3 mentionne que le restaurant sert une grande variété de plats, y compris des plats réconfortants classiques et des cuisines exotiques du monde entier, donc la réponse devrait être « délices ». La phrase quatre fait référence à la salle à manger privée offerte par le restaurant, la réponse devrait donc être stand. Par conséquent, les réponses sont (A) remuer, (E) raffiné, (I) délices et (M) stand.",
            ans: ["(A)","(E)","(I)","(M)",],
            cns: "Le nouveau restaurant de la ville fait déjà sensation avec son menu unique et son ambiance élégante. Le propriétaire du restaurant est un chef renommé qui a créé une expérience culinaire raffinée à la fois délicieuse et mémorable. Le restaurant propose une grande variété de plats, de la cuisine réconfortante classique à la cuisine exotique du monde entier. Les clients peuvent choisir de dîner dans la salle à manger principale ou dans des loges plus intimes pour les occasions spéciales. Le restaurant accueille également des événements d'entreprise et des fêtes privées."
        },{
            ars: "The new marketing campaign has been _____ successful, with sales increasing by 20% since its launch. The campaign's focus on social media has helped the company reach a wider _____, particularly among younger consumers who spend a lot of time on their phones. The company's _____ strategy, which includes targeted ads and influencer partnerships, has also contributed to its success. However, the company's _____ has also played a role in the campaign's success, as its reputation for high-quality products has helped build trust with customers.",
            reals: "The new marketing campaign has been tremendously successful, with sales increasing by 20% since its launch. The campaign's focus on social media has helped the company reach a wider audience, particularly among younger consumers who spend a lot of time on their phones. The company's promotion strategy, which includes targeted ads and influencer partnerships, has also contributed to its success. However, the company's reputation has also played a role in the campaign's success, as its reputation for high-quality products has helped build trust with customers.",
            sels: ["moderately","tremendously","barely","slightly","audience","market","sector","niche","pricing","promotion","distribution","packaging","innovation","reputation","location","convenience",],
            exps: "Il s'agit d'un article sur une campagne de marketing qui mentionne pourquoi la campagne a réussi. Du contexte, il s'ensuit que le succès de la campagne est mentionné dans la première phrase, donc la réponse devrait être « énormément ». La phrase 2 mentionne que l'événement est particulièrement populaire auprès des jeunes consommateurs, donc la réponse devrait être audience. La stratégie de la campagne est mentionnée dans la troisième phrase, y compris la publicité ciblée et la coopération des influenceurs, la réponse devrait donc être promotion. La réputation de l'entreprise est mentionnée dans la phrase quatre, ce qui aide à établir la confiance avec les clients, donc la réponse devrait être réputation. Ainsi, les réponses sont (B) énormément, (E) audience, (J) promotion et (N) réputation.",
            ans: ["(B)","(E)","(J)","(N)",],
            cns: "La nouvelle campagne de marketing a été un énorme succès, avec des ventes en hausse de 20 % depuis son lancement. L'accent mis par la campagne sur les médias sociaux a aidé l'entreprise à toucher un public plus large, en particulier parmi les jeunes consommateurs qui passent beaucoup de temps sur leur téléphone. Les stratégies publicitaires des entreprises, notamment la publicité ciblée et les partenariats avec des influenceurs, ont également contribué à son succès. Cependant, la réputation d'une entreprise joue également un rôle dans le succès de l'événement, car sa réputation de produits de haute qualité contribue à renforcer la confiance des clients."
        },{
            ars: "The company has announced plans to _____ its workforce by 10% in an effort to reduce costs. The layoffs will primarily affect _____ in the company's administrative and support departments, although some managers and executives will also be let go. The company's CEO has stated that these changes are necessary to ensure the long-term _____ of the company and maintain its competitiveness in the marketplace. The company will provide severance packages and _____ services to affected employees to help them transition to new employment.",
            reals: "The company has announced plans to downsize its workforce by 10% in an effort to reduce costs. The layoffs will primarily affect employees in the company's administrative and support departments, although some managers and executives will also be let go. The company's CEO has stated that these changes are necessary to ensure the long-term sustainability of the company and maintain its competitiveness in the marketplace. The company will provide severance packages and counseling services to affected employees to help them transition to new employment.",
            sels: ["expand","downsize","diversify","centralize","employees","shareholders","customers","suppliers","profitability","stability","flexibility","sustainability","relocation","retraining","counseling","mentoring",],
            exps: "Il s'agit d'un article sur le plan de licenciement d'une entreprise, et l'article mentionne les causes et les effets du plan. Il peut être conclu à partir du contexte : la phrase 1 mentionne le plan de licenciement de l'entreprise, la réponse devrait donc être réduire les effectifs. La phrase 2 mentionne qu'un service spécifique d'employés est concerné, la réponse devrait donc être employés. La phrase 3 mentionne que le PDG de l'entreprise estime que ces changements sont nécessaires pour assurer la stabilité et la compétitivité à long terme de l'entreprise, la réponse devrait donc être durabilité. La phrase 4 mentionne que l'entreprise fournit des indemnités de départ et des services de conseil pour aider les employés concernés à faire la transition vers un nouvel emploi, la réponse devrait donc être conseil. Les réponses sont donc (B) réduction des effectifs, (E) employés, (L) durabilité et (O) conseil.",
            ans: ["(B)","(E)","(L)","(O)",],
            cns: "L'entreprise a annoncé son intention de réduire ses effectifs de 10 % afin de réduire ses coûts. Les licenciements concernent principalement les salariés des fonctions administratives et de support de l'entreprise, même si certains managers et cadres seront également licenciés. Le PDG de l'entreprise a déclaré que les changements étaient nécessaires pour assurer la durabilité à long terme et maintenir la compétitivité de l'entreprise sur le marché. L'entreprise fournira des indemnités de départ et des services de mentorat aux employés concernés pour les aider à faire la transition vers de nouveaux emplois."
        },{
            ars: "The _____ of the company's new product has been delayed due to manufacturing issues. The company had originally planned to launch the product in Q2, but now expects to release it in Q4. The delay has been _____ disappointing for the company, which had invested heavily in research and development and marketing efforts to support the launch. The company's management has reassured shareholders that the delay is temporary and that the product will be worth the wait, with features that are _____ superior to those of its competitors.",
            reals: "The launch of the company's new product has been delayed due to manufacturing issues. The company had originally planned to launch the product in Q2, but now expects to release it in Q4. The delay has been extremely disappointing for the company, which had invested heavily in research and development and marketing efforts to support the launch. The company's management has reassured shareholders that the delay is temporary and that the product will be worth the wait, with features that are significantly superior to those of its competitors.",
            sels: ["launch","design","development","testing","highly","somewhat","extremely","moderately","significantly","marginally","slightly","barely",],
            exps: "Il s'agit d'un article sur les retards dans les nouveaux produits, les raisons des retards et la réponse de l'entreprise. Cela découle du contexte : la phrase 1 mentionne que la sortie du produit est retardée, la réponse devrait donc être lancer. La deuxième phrase mentionnait que l'entreprise était très déçue de ce retard, la réponse devrait donc être extrêmement. La phrase 3 mentionne que le produit aura des fonctions supérieures, donc la réponse devrait être de manière significative. Les réponses sont donc (A) lancer, (G) extrêmement et (I) de manière significative.",
            ans: ["(A)","(G)","(I)",],
            cns: "Lancement, mise sur le marché Le nouveau produit de la société a été retardé en raison de problèmes de fabrication. La société avait initialement prévu de lancer le produit au deuxième trimestre, mais s'attend maintenant à une sortie au quatrième trimestre. Le retard a été important, ce qui est décevant pour l'entreprise, qui a beaucoup investi en R&D et en marketing pour accompagner le lancement. La direction de l'entreprise a assuré aux actionnaires que le retard était temporaire et que le produit valait la peine d'attendre, avec des caractéristiques notables par rapport à ses concurrents."
        },{
            ars: "The hotel industry in the city has been experiencing a boom in recent years due to increased tourism. Many new hotels have _____ up in the city center, offering tourists a range of options at different price points. However, this growth has also led to increased _____ and competition among hotels, with some struggling to fill their rooms during off-peak seasons. To address this, many hotels have been _____ their services to appeal to a wider range of customers, such as offering discounted rates to business travelers and families.",
            reals: "The hotel industry in the city has been experiencing a boom in recent years due to increased tourism. Many new hotels have opened up in the city center, offering tourists a range of options at different price points. However, this growth has also led to increased supply and competition among hotels, with some struggling to fill their rooms during off-peak seasons. To address this, many hotels have been diversifying their services to appeal to a wider range of customers, such as offering discounted rates to business travelers and families.",
            sels: ["closed","opened","expanded","renovated","demand","supply","marketing","innovation","diversifying","outsourcing","downsizing","streamlining",],
            exps: "Ceci est un article sur le développement de l'industrie hôtelière dans la ville, l'article mentionne la croissance de l'industrie hôtelière et les problèmes connexes. On peut conclure du contexte : la phrase 1 mentionne que l'industrie hôtelière urbaine a prospéré ces dernières années, donc la réponse devrait être ouverte. La phrase 2 mentionne que la croissance apporte également de la concurrence et une offre excédentaire, donc la réponse devrait être l'offre. La phrase 3 mentionne que de nombreux hôtels adaptent leurs services en réponse aux changements du marché, la réponse devrait donc être diversifier. Par conséquent, les réponses sont (B) ouvert, (F) offre et (I) diversification.",
            ans: ["(B)","(F)","(I)",],
            cns: "Ces dernières années, l'industrie hôtelière de la ville est en plein essor grâce à la croissance du tourisme. De nombreux nouveaux hôtels ont ouvert dans le centre-ville, offrant aux touristes une variété d'options à différents prix. Cependant, cette croissance a également entraîné une augmentation de l'offre et de la concurrence entre les hôtels, certains hôtels ayant du mal à remplir des chambres pendant la morte-saison. Pour lutter contre cela, de nombreux hôtels ont diversifié leurs offres pour attirer une clientèle plus large, en proposant par exemple des tarifs réduits pour les voyageurs d'affaires et les familles."
        },{
            ars: "The pharmaceutical industry has come under increased scrutiny in recent years due to concerns about rising drug prices and the role of pharmaceutical companies in the opioid crisis. Many consumers are _____ to pay for medications that they need to maintain their health, leading to calls for greater government regulation of drug prices. Meanwhile, several pharmaceutical companies have faced lawsuits for their role in the opioid epidemic, with some accused of _____ their products and contributing to addiction and overdose deaths. In response, the industry has pledged to improve transparency and _____ in drug pricing and marketing practices.",
            reals: "The pharmaceutical industry has come under increased scrutiny in recent years due to concerns about rising drug prices and the role of pharmaceutical companies in the opioid crisis. Many consumers are reluctant to pay for medications that they need to maintain their health, leading to calls for greater government regulation of drug prices. Meanwhile, several pharmaceutical companies have faced lawsuits for their role in the opioid epidemic, with some accused of overpromoting their products and contributing to addiction and overdose deaths. In response, the industry has pledged to improve transparency and accountability in drug pricing and marketing practices.",
            sels: ["reluctant","eager","unwilling","hesitant","overpromoting","underpromoting","misrepresenting","falsifying","accountability","efficiency","innovation","profitability",],
            exps: "Il s'agit d'un article sur les problèmes de l'industrie pharmaceutique, avec des références à des problèmes tels que la hausse des prix des médicaments et le rôle des sociétés pharmaceutiques dans la crise des opioïdes. Cela peut être tiré du contexte : la phrase 1 mentionne que de nombreux consommateurs ne sont pas disposés à payer des prix élevés pour les médicaments, la réponse devrait donc être « réticent ». La phrase 2 mentionne que certaines sociétés pharmaceutiques ont été accusées de surpromotion de leurs produits, contribuant à des problèmes tels que la dépendance et les décès par surdose, la réponse devrait donc être surpromotion. La troisième phrase fait référence à l'engagement de l'industrie pharmaceutique à améliorer la transparence et les pratiques responsables en matière de tarification et de commercialisation des médicaments. La réponse devrait donc être responsabilité. Les réponses sont donc (A) réticentes, (E) promotion excessive et (I) responsabilité.",
            ans: ["(A)","(E)","(I)",],
            cns: "L'industrie pharmaceutique a fait l'objet d'une surveillance accrue ces dernières années en raison des inquiétudes suscitées par la hausse des prix des médicaments et le rôle des sociétés pharmaceutiques dans la crise des opioïdes. De nombreux consommateurs ne sont pas disposés à payer pour les médicaments dont ils ont besoin pour maintenir leur santé, ce qui conduit les gouvernements à demander une plus grande réglementation des prix des médicaments. Pendant ce temps, plusieurs sociétés pharmaceutiques font face à des poursuites judiciaires pour leur rôle dans l'épidémie d'opioïdes, certaines étant accusées d'avoir fait une promotion excessive de leurs produits et d'avoir causé des décès par dépendance et par surdose. En réponse, l'industrie s'est engagée à accroître la transparence et la responsabilité dans les pratiques de tarification et de commercialisation des médicaments."
        },{
            ars: "In recent years, the global energy sector has undergone significant changes, driven by concerns about _____ and the need to reduce carbon emissions. As a result, many countries have implemented policies aimed at increasing the use of renewable energy sources, such as wind and solar power. This has led to a _____ in the renewable energy industry, with companies investing heavily in research and development to improve the efficiency and cost-effectiveness of their products. However, the shift towards renewable energy has not been without its _____, as some traditional energy companies have struggled to adapt to the changing market conditions.",
            reals: "In recent years, the global energy sector has undergone significant changes, driven by concerns about sustainability and the need to reduce carbon emissions. As a result, many countries have implemented policies aimed at increasing the use of renewable energy sources, such as wind and solar power. This has led to a surge in the renewable energy industry, with companies investing heavily in research and development to improve the efficiency and cost-effectiveness of their products. However, the shift towards renewable energy has not been without its challenges, as some traditional energy companies have struggled to adapt to the changing market conditions.",
            sels: ["sustainability","diversity","innovation","competition","surge","decline","stagnation","consolidation","challenges","opportunities","benefits","rewards",],
            exps: "Il s'agit d'un article sur l'industrie mondiale de l'énergie, qui mentionne les changements dans l'industrie et les défis correspondants. Elle peut être tirée du contexte : la phrase 1 mentionne le souci de durabilité et la nécessité de réduire les émissions de carbone, la réponse devrait donc être « durabilité ». La deuxième phrase mentionne la montée en flèche de l'industrie des énergies renouvelables, la réponse devrait donc être montée en flèche. La phrase 3 mentionnait la difficulté pour les entreprises énergétiques traditionnelles de s'adapter aux évolutions du marché, la réponse devrait donc être défis. Les réponses sont donc (A) la durabilité, (E) la montée en puissance et (I) les défis.",
            ans: ["(A)","(E)","(I)",],
            cns: "Ces dernières années, l'industrie mondiale de l'énergie a subi des changements majeurs, motivés par des préoccupations concernant la durabilité et la nécessité de réduire les émissions de carbone. En conséquence, de nombreux pays ont mis en œuvre des politiques visant à accroître l'utilisation des sources d'énergie renouvelables telles que l'éolien et le solaire. Cela a conduit à une montée en puissance de l'industrie des énergies renouvelables, les entreprises investissant massivement dans la recherche et le développement pour améliorer l'efficacité et la rentabilité de leurs produits. Cependant, la transition vers les énergies renouvelables n'a pas été sans défis, car certaines entreprises énergétiques traditionnelles ont eu du mal à s'adapter aux conditions changeantes du marché."
        },{
            ars: "Over the past decade, advances in technology have transformed the way we live and work. One of the most significant changes has been the widespread adoption of _____ devices, such as smartphones and tablets. These devices have revolutionized the way we _____ information, allowing us to access a wealth of knowledge at our fingertips. However, they have also had a number of _____ effects, such as the erosion of face-to-face communication skills and the development of addiction to social media.",
            reals: "Over the past decade, advances in technology have transformed the way we live and work. One of the most significant changes has been the widespread adoption of mobile devices, such as smartphones and tablets. These devices have revolutionized the way we retrieve information, allowing us to access a wealth of knowledge at our fingertips. However, they have also had a number of detrimental effects, such as the erosion of face-to-face communication skills and the development of addiction to social media.",
            sels: ["mobile","wireless","digital","handheld","process","retrieve","disseminate","interpret","beneficial","detrimental","positive","negative",],
            exps: "Il s'agit d'un article sur le changement technologique, et l'article mentionne l'impact du changement technologique sur la vie et le travail. D'après le contexte : la phrase 1 mentionne l'utilisation généralisée d'appareils mobiles tels que les smartphones et les tablettes, la réponse devrait donc être mobile. La deuxième phrase mentionne le changement révolutionnaire dans l'acquisition de connaissances à l'aide de ces appareils, la réponse devrait donc être récupérer. L'effet négatif de l'utilisation de ces appareils est mentionné dans la troisième phrase, la réponse devrait donc être préjudiciable. Les réponses sont donc (A) mobile, (F) récupérer et (J) préjudiciable.",
            ans: ["(A)","(F)","(J)",],
            cns: "Au cours de la dernière décennie, les avancées technologiques ont transformé notre façon de vivre et de travailler. L'un des changements les plus importants est l'adoption généralisée des appareils Internet mobiles, tels que les smartphones et les tablettes. Ces appareils ont révolutionné la façon dont nous récupérons l'information, mettant une richesse de connaissances à portée de main. Cependant, ils ont également des effets délétères, tels que l'érosion des compétences de communication en face à face et le développement de la dépendance aux médias sociaux."
        },{
            ars: "In recent years, businesses have increasingly turned to social media to _____ with their customers. Platforms like Facebook and Twitter offer companies a way to _____ with their audience in real-time, and can help to create a sense of community around a brand. However, social media also presents a number of _____, including the potential for negative feedback to spread quickly and damage a company's reputation.",
            reals: "In recent years, businesses have increasingly turned to social media to engage with their customers. Platforms like Facebook and Twitter offer companies a way to interact with their audience in real-time, and can help to create a sense of community around a brand. However, social media also presents a number of drawbacks, including the potential for negative feedback to spread quickly and damage a company's reputation.",
            sels: ["collaborate","engage","compete","negotiate","interact","market","advertise","promote","opportunities","challenges","benefits","drawbacks",],
            exps: "Ceci est un article sur les entreprises utilisant les médias sociaux pour interagir avec les clients, l'article mentionne l'impact des médias sociaux sur les entreprises. D'après le contexte : la phrase 1 mentionne que les entreprises utilisent de plus en plus les médias sociaux pour interagir avec les clients, la réponse devrait donc être engager. La phrase 2 mentionnait que les médias sociaux peuvent aider les entreprises à créer des communautés de marque, la réponse devrait donc être interagir. La phrase 3 mentionne les risques liés à l'utilisation des médias sociaux, la réponse devrait donc être inconvénients. La réponse est donc (B) s'engager, (E) interagir et (L) inconvénients.",
            ans: ["(B)","(E)","(L)",],
            cns: "Ces dernières années, les entreprises se sont de plus en plus tournées vers les médias sociaux pour interagir avec leurs clients. Des plateformes telles que Facebook et Twitter offrent aux entreprises un moyen interactif de communiquer avec leur public en temps réel et contribuent à créer un sentiment de communauté autour d'une marque. Cependant, les médias sociaux présentent également certains inconvénients, notamment la possibilité que des commentaires négatifs se propagent rapidement et nuisent à la réputation d'une entreprise."
        },{
            ars: "The hotel industry is experiencing a _____ in business due to the recent economic boom. With more people _____ disposable income, more and more individuals are choosing to travel and stay in hotels. In order to meet the demand, hotels are expanding their facilities and _____ their services to attract customers.",
            reals: "The hotel industry is experiencing a surge in business due to the recent economic boom. With more people spending disposable income, more and more individuals are choosing to travel and stay in hotels. In order to meet the demand, hotels are expanding their facilities and improving their services to attract customers.",
            sels: ["decline","stagnation","surge","fluctuation","having","earning","spending","saving","improving","reducing","limiting","discontinuing",],
            exps: "Il s'agit d'un article sur la croissance de l'hôtellerie. L'article mentionnait qu'à mesure que l'économie explose et que de plus en plus de personnes choisissent de voyager et de séjourner dans des hôtels, il y a une poussée dans l'hôtellerie. D'après le contexte, il s'ensuit que surge est mentionné dans la première phrase, donc la réponse devrait être (C) surge. La phrase 2 mentionne qu'au fur et à mesure que les gens « dépensent » plus de revenu disponible, ils choisissent de plus en plus de voyager et de séjourner dans des hôtels, la réponse devrait donc être (G) dépenses. La phrase 3 mentionne que pour répondre à la demande, l'hôtel agrandit ses installations et améliore ses services pour attirer les clients, la réponse devrait donc être (I) s'améliorer. Les réponses sont donc (C) augmentation, (G) dépenses et (I) amélioration.",
            ans: ["(C)","(G)","(I)",],
            cns: "L'industrie hôtelière connaît une forte augmentation de l'activité commerciale en raison du récent boom économique. De plus en plus de personnes consomment Avec l'augmentation du revenu disponible, de plus en plus de personnes choisissent de voyager et de séjourner dans des hôtels. Pour répondre à la demande, les hôtels agrandissent leurs installations et améliorent leurs services pour attirer les clients."
        },{
            ars: "In recent years, online shopping has become increasingly popular among consumers. One of the biggest advantages of online shopping is that it allows customers to _____ items from the comfort of their own homes. This means that people can avoid the hassle of traffic and crowded stores. Additionally, online shopping often offers a wider variety of products than traditional retail stores, as well as _____ prices. Many retailers also offer free shipping or other _____ to encourage customers to shop online.",
            reals: "In recent years, online shopping has become increasingly popular among consumers. One of the biggest advantages of online shopping is that it allows customers to purchase items from the comfort of their own homes. This means that people can avoid the hassle of traffic and crowded stores. Additionally, online shopping often offers a wider variety of products than traditional retail stores, as well as lower prices. Many retailers also offer free shipping or other promotions to encourage customers to shop online.",
            sels: ["purchase","return","exchange","rent","lower","higher","fixed","fluctuating","promotions","warranties","discounts","contracts",],
            exps: "Ceci est un article sur les achats en ligne. L'article mentionne les avantages des achats en ligne, notamment la commodité, l'évitement du trafic et des foules, une grande variété de produits, des prix plus bas, des promotions offertes par les magasins, la livraison gratuite, etc. Cela peut être tiré du contexte : la phrase 1 mentionne que les achats en ligne permettent aux gens d'acheter des biens à domicile, donc la réponse devrait être (A) achat. La phrase 2 mentionne que l'un des avantages des achats en ligne est des prix plus bas, donc la réponse devrait être (E) plus bas. La phrase 3 mentionne les promotions et la livraison gratuite offertes par le magasin, etc., donc la réponse devrait être (I) les promotions. Donc la réponse est (A) achat, (E) baisse et (I) promotions.",
            ans: ["(A)","(E)","(I)",],
            cns: "Ces dernières années, les achats en ligne sont devenus de plus en plus populaires auprès des consommateurs. L'un des plus grands avantages des achats en ligne est qu'ils permettent aux clients d'acheter des articles dans le confort de leur foyer. Cela signifie que les gens peuvent éviter les tracas de la circulation et des magasins bondés. De plus, les achats en ligne offrent souvent une plus grande variété de produits que les magasins de détail traditionnels, et à des prix inférieurs. De nombreux détaillants offrent également la livraison gratuite ou d'autres promotions pour encourager les clients à magasiner en ligne."
        },{
            ars: "The hospitality industry, which includes hotels, restaurants, and catering services, plays a crucial role in the global economy. As international travel continues to _____, the demand for hotels and restaurants has increased. In addition, many people today prefer to _____ out or order in rather than cook at home. This has led to a growth in the number of restaurants and catering services, both small and large.When it comes to hotels, there are a wide variety of options available to travelers. From luxury hotels to budget accommodations, there is something for every _____ of traveler. Many hotels now offer additional amenities such as fitness centers, swimming pools, and complimentary breakfast. In order to stay competitive, hotels must also keep up with the latest technologies, such as online reservation systems and mobile check-in options.",
            reals: "The hospitality industry, which includes hotels, restaurants, and catering services, plays a crucial role in the global economy. As international travel continues to increase, the demand for hotels and restaurants has increased. In addition, many people today prefer to dine out or order in rather than cook at home. This has led to a growth in the number of restaurants and catering services, both small and large.When it comes to hotels, there are a wide variety of options available to travelers. From luxury hotels to budget accommodations, there is something for every category of traveler. Many hotels now offer additional amenities such as fitness centers, swimming pools, and complimentary breakfast. In order to stay competitive, hotels must also keep up with the latest technologies, such as online reservation systems and mobile check-in options.",
            sels: ["decrease","stagnate","increase","fluctuate","eat","dine","take","make","kind","level","group","category",],
            exps: "Ceci est un article sur la restauration et l'hôtellerie. L'article mentionne qu'à mesure que le tourisme international augmente, la demande d'hôtels et de restaurants augmente également. Dans le même temps, de plus en plus de personnes choisissent de manger à l'extérieur ou de se faire livrer de la nourriture, de sorte que le nombre de restaurants et de services de restauration augmente également. De plus, les hôtels offrent également une variété d'options, y compris des hôtels de luxe et des hébergements économiques, etc., et pour rester compétitifs, les hôtels doivent également se tenir au courant des dernières technologies. La phrase 1 mentionne qu'à mesure que le tourisme international augmente, la demande d'hôtels et de restaurants augmente également, la réponse devrait donc être (C) augmenter. La phrase 2 mentionne que de plus en plus de personnes choisissent de manger au restaurant ou de se faire livrer de la nourriture, la réponse devrait donc être (F) dîner. La phrase 3 mentionne que l'hôtel propose diverses options, y compris des hôtels de luxe et des hébergements économiques, etc., donc la réponse devrait être la catégorie (L). Par conséquent, les réponses sont (C) augmentation, (F) dîner et (L) catégorie.",
            ans: ["(C)","(F)","(L)",],
            cns: "L'industrie hôtelière, y compris les hôtels, les restaurants et les services alimentaires, joue un rôle vital dans l'économie mondiale. Alors que les voyages internationaux continuent d'augmenter, la demande d'hôtels et de restaurants a augmenté. De plus, de nombreuses personnes préfèrent aujourd'hui dîner au restaurant ou commander plutôt que de cuisiner à la maison. Cela a entraîné une augmentation du nombre de petits et grands restaurants et de services alimentaires. En ce qui concerne les hôtels, les voyageurs ont une variété d'options. Des hôtels de luxe aux hébergements économiques, il y en a pour toutes les catégories de voyageurs. De nombreux hôtels proposent désormais des équipements supplémentaires tels que des centres de fitness, des piscines et un petit-déjeuner gratuit. Pour rester compétitifs, les hôtels doivent également suivre les dernières technologies, telles que les systèmes de réservation en ligne et les options d'enregistrement mobile."
        },]