const q = [{
            ars: "The new restaurant in town is already causing quite a _____ with its unique menu and elegant atmosphere. The restaurant's owner, a well-known chef, has created a _____ dining experience that is both delicious and memorable. The restaurant offers a wide variety of dishes, ranging from classic comfort food to exotic _____ from around the world. Customers can choose to dine in the main dining room or in a more intimate private _____ for special occasions. The restaurant also offers catering services for corporate events and private parties.",
            reals: "The new restaurant in town is already causing quite a stir with its unique menu and elegant atmosphere. The restaurant's owner, a well-known chef, has created a refined dining experience that is both delicious and memorable. The restaurant offers a wide variety of dishes, ranging from classic comfort food to exotic delicacies from around the world. Customers can choose to dine in the main dining room or in a more intimate private booth for special occasions. The restaurant also offers catering services for corporate events and private parties.",
            sels: ["stir","steer","stare","store","refined","delightful","extravagant","delicate","delicacies","spices","beverages","desserts","booth","chamber","lounge","terrace",],
            exps: "레스토랑의 메뉴와 분위기를 언급하는 새로운 레스토랑에 대한 기사입니다. 맥락에서: 문장 1은 레스토랑의 독특한 메뉴와 우아한 분위기를 언급하므로 대답은 저어여야 합니다. 문장 2는 레스토랑의 요리가 맛있고 기억에 남는다고 언급하므로 대답은 세련된이어야 합니다. 문장 3은 레스토랑이 고전적인 안락한 음식과 전 세계의 이국적인 요리를 포함하여 다양한 요리를 제공한다고 언급하므로 대답은 진미여야 합니다. 네 번째 문장은 레스토랑이 제공하는 프라이빗 다이닝 공간을 의미하므로 대답은 부스여야 합니다. 따라서 대답은 (A) 저어, (E) 정제, (I) 진미, (M) 부스입니다.",
            ans: ["(A)","(E)","(I)","(M)",],
            cns: "마을에 새로 생긴 레스토랑은 독특한 메뉴와 우아한 분위기로 이미 큰 화제를 불러일으키고 있습니다. 레스토랑의 주인은 맛있고 기억에 남을 세련된 식사 경험을 만든 유명한 요리사입니다. 레스토랑은 고전적인 편안한 음식부터 전 세계의 이국적인 요리에 이르기까지 다양한 요리를 제공합니다. 손님은 메인 다이닝 룸에서 식사를 하거나 특별한 경우를 위해 더 친밀한 상자에서 식사를 할 수 있습니다. 레스토랑은 또한 기업 행사 및 개인 파티를 위한 음식을 제공합니다."
        },{
            ars: "The new marketing campaign has been _____ successful, with sales increasing by 20% since its launch. The campaign's focus on social media has helped the company reach a wider _____, particularly among younger consumers who spend a lot of time on their phones. The company's _____ strategy, which includes targeted ads and influencer partnerships, has also contributed to its success. However, the company's _____ has also played a role in the campaign's success, as its reputation for high-quality products has helped build trust with customers.",
            reals: "The new marketing campaign has been tremendously successful, with sales increasing by 20% since its launch. The campaign's focus on social media has helped the company reach a wider audience, particularly among younger consumers who spend a lot of time on their phones. The company's promotion strategy, which includes targeted ads and influencer partnerships, has also contributed to its success. However, the company's reputation has also played a role in the campaign's success, as its reputation for high-quality products has helped build trust with customers.",
            sels: ["moderately","tremendously","barely","slightly","audience","market","sector","niche","pricing","promotion","distribution","packaging","innovation","reputation","location","convenience",],
            exps: "캠페인이 성공한 이유를 언급하는 마케팅 캠페인에 대한 기사입니다. 맥락에서 캠페인의 성공은 첫 번째 문장에서 언급되므로 대답은 엄청나게여야 합니다. 문장 2는 이벤트가 특히 젊은 소비자들에게 인기가 있다고 언급하므로 대답은 관객이어야 합니다. 타겟 광고, 인플루언서 협력 등 캠페인의 전략은 세 번째 문장에 언급되어 있으므로 답은 프로모션이어야 합니다. 회사의 평판은 고객과의 신뢰 구축에 도움이 되는 4문장에 언급되어 있으므로 대답은 평판이어야 합니다. 따라서 대답은 (B) 엄청나게, (E) 청중, (J) 홍보 및 (N) 명성입니다.",
            ans: ["(B)","(E)","(J)","(N)",],
            cns: "새로운 마케팅 캠페인은 출시 이후 매출이 20% 증가하는 등 큰 성공을 거두었습니다. 소셜 미디어에 대한 캠페인의 초점은 회사가 특히 휴대폰에서 많은 시간을 보내는 젊은 소비자들 사이에서 더 많은 청중에게 다가가는 데 도움이 되었습니다. 대상 광고 및 인플루언서 파트너십을 포함한 기업 홍보 전략도 성공에 기여했습니다. 그러나 고품질 제품에 대한 명성이 고객의 신뢰를 구축하는 데 도움이 되므로 회사의 평판도 행사의 성공에 중요한 역할을 합니다."
        },{
            ars: "The company has announced plans to _____ its workforce by 10% in an effort to reduce costs. The layoffs will primarily affect _____ in the company's administrative and support departments, although some managers and executives will also be let go. The company's CEO has stated that these changes are necessary to ensure the long-term _____ of the company and maintain its competitiveness in the marketplace. The company will provide severance packages and _____ services to affected employees to help them transition to new employment.",
            reals: "The company has announced plans to downsize its workforce by 10% in an effort to reduce costs. The layoffs will primarily affect employees in the company's administrative and support departments, although some managers and executives will also be let go. The company's CEO has stated that these changes are necessary to ensure the long-term sustainability of the company and maintain its competitiveness in the marketplace. The company will provide severance packages and counseling services to affected employees to help them transition to new employment.",
            sels: ["expand","downsize","diversify","centralize","employees","shareholders","customers","suppliers","profitability","stability","flexibility","sustainability","relocation","retraining","counseling","mentoring",],
            exps: "이것은 회사의 정리 해고 계획에 관한 기사이며 기사는 계획의 원인과 결과를 언급합니다. 문맥에서 결론을 내릴 수 있습니다. 문장 1은 회사의 정리 해고 계획을 언급하므로 대답은 축소여야 합니다. 문장 2는 직원의 특정 부서가 영향을 받았다고 언급하므로 대답은 직원이어야 합니다. 문장 3은 회사의 CEO가 회사의 장기적인 안정성과 경쟁력을 보장하기 위해 이러한 변화가 필요하다고 생각하므로 대답은 지속 가능성이어야 한다고 언급합니다. 4문장에 회사가 퇴직금과 상담을 통해 피해 직원의 이직을 돕는다고 언급되어 있으므로 답은 상담이어야 합니다. 따라서 대답은 (B) 축소, (E) 직원, (L) 지속 가능성 및 (O) 상담입니다.",
            ans: ["(B)","(E)","(L)","(O)",],
            cns: "회사는 비용 절감을 위해 인력을 10% 감축할 계획을 발표했습니다. 정리 해고는 주로 회사의 관리 및 지원 기능에 종사하는 직원에게 영향을 미치지만 일부 관리자와 임원도 해고될 것입니다. 회사의 CEO는 장기적인 지속 가능성을 보장하고 시장에서 회사의 경쟁력을 유지하기 위해 변화가 필요하다고 말했습니다. 회사는 피해를 입은 직원들에게 퇴직금과 멘토링 서비스를 제공하여 새로운 직장으로의 전환을 도울 것입니다."
        },{
            ars: "The _____ of the company's new product has been delayed due to manufacturing issues. The company had originally planned to launch the product in Q2, but now expects to release it in Q4. The delay has been _____ disappointing for the company, which had invested heavily in research and development and marketing efforts to support the launch. The company's management has reassured shareholders that the delay is temporary and that the product will be worth the wait, with features that are _____ superior to those of its competitors.",
            reals: "The launch of the company's new product has been delayed due to manufacturing issues. The company had originally planned to launch the product in Q2, but now expects to release it in Q4. The delay has been extremely disappointing for the company, which had invested heavily in research and development and marketing efforts to support the launch. The company's management has reassured shareholders that the delay is temporary and that the product will be worth the wait, with features that are significantly superior to those of its competitors.",
            sels: ["launch","design","development","testing","highly","somewhat","extremely","moderately","significantly","marginally","slightly","barely",],
            exps: "신제품 지연, 지연 사유 및 회사의 대응에 대한 기사입니다. 문장 1에서 제품 출시가 지연된다고 언급했으므로 대답은 출시여야 합니다. 두 번째 문장은 회사가 이러한 지연에 대해 매우 실망했다고 언급했으므로 답변은 매우여야 합니다. 문장 3은 제품이 우수한 기능을 가질 것이라고 언급하므로 대답은 중요하게여야 합니다. 따라서 답변은 (A) 출시, (G) 극도로, (I) 크게입니다.",
            ans: ["(A)","(G)","(I)",],
            cns: "출시, 시장 출시 회사의 신제품이 제조 문제로 인해 지연되었습니다. 이 회사는 당초 2분기에 제품을 출시할 계획이었지만 현재는 4분기에 출시될 것으로 예상하고 있습니다. 출시를 지원하기 위해 R&D 및 마케팅에 막대한 투자를 한 회사에 실망스러운 지연이 심했습니다. 회사 경영진은 지연이 일시적이며 제품이 경쟁사에 비해 주목할만한 기능을 갖추고 있어 기다릴만한 가치가 있다고 주주들에게 확신시켰습니다."
        },{
            ars: "The hotel industry in the city has been experiencing a boom in recent years due to increased tourism. Many new hotels have _____ up in the city center, offering tourists a range of options at different price points. However, this growth has also led to increased _____ and competition among hotels, with some struggling to fill their rooms during off-peak seasons. To address this, many hotels have been _____ their services to appeal to a wider range of customers, such as offering discounted rates to business travelers and families.",
            reals: "The hotel industry in the city has been experiencing a boom in recent years due to increased tourism. Many new hotels have opened up in the city center, offering tourists a range of options at different price points. However, this growth has also led to increased supply and competition among hotels, with some struggling to fill their rooms during off-peak seasons. To address this, many hotels have been diversifying their services to appeal to a wider range of customers, such as offering discounted rates to business travelers and families.",
            sels: ["closed","opened","expanded","renovated","demand","supply","marketing","innovation","diversifying","outsourcing","downsizing","streamlining",],
            exps: "이것은 도시의 호텔 산업 발전에 관한 기사이며 기사는 호텔 산업의 성장 및 관련 문제를 언급합니다. 문맥에서 결론을 내릴 수 있습니다. 문장 1은 최근 몇 년 동안 도시 호텔 산업이 번성했다고 언급하므로 대답은 개방되어야 합니다. 문장 2는 성장이 경쟁과 공급 과잉을 가져오기도 한다고 언급하므로 대답은 공급이어야 합니다. 문장 3은 많은 호텔이 시장 변화에 대응하여 서비스를 조정하고 있다고 언급하므로 대답은 다양화여야 합니다. 따라서 답은 (B) 개방, (F) 공급, (I) 다양화이다.",
            ans: ["(B)","(F)","(I)",],
            cns: "최근 몇 년 동안 도시의 호텔 산업은 관광 산업의 성장 덕분에 호황을 누리고 있습니다. 많은 새로운 호텔이 도심에 문을 열었으며 관광객들에게 다양한 가격대에서 다양한 옵션을 제공합니다. 그러나 이러한 성장으로 인해 일부 호텔은 비수기 동안 객실을 채우기 위해 고군분투하는 등 호텔 간의 공급 및 경쟁이 증가했습니다. 이에 대처하기 위해 많은 호텔은 비즈니스 여행객과 가족을 위한 할인 요금을 제공하는 등 더 많은 고객에게 어필하기 위해 서비스를 다양화하고 있습니다."
        },{
            ars: "The pharmaceutical industry has come under increased scrutiny in recent years due to concerns about rising drug prices and the role of pharmaceutical companies in the opioid crisis. Many consumers are _____ to pay for medications that they need to maintain their health, leading to calls for greater government regulation of drug prices. Meanwhile, several pharmaceutical companies have faced lawsuits for their role in the opioid epidemic, with some accused of _____ their products and contributing to addiction and overdose deaths. In response, the industry has pledged to improve transparency and _____ in drug pricing and marketing practices.",
            reals: "The pharmaceutical industry has come under increased scrutiny in recent years due to concerns about rising drug prices and the role of pharmaceutical companies in the opioid crisis. Many consumers are reluctant to pay for medications that they need to maintain their health, leading to calls for greater government regulation of drug prices. Meanwhile, several pharmaceutical companies have faced lawsuits for their role in the opioid epidemic, with some accused of overpromoting their products and contributing to addiction and overdose deaths. In response, the industry has pledged to improve transparency and accountability in drug pricing and marketing practices.",
            sels: ["reluctant","eager","unwilling","hesitant","overpromoting","underpromoting","misrepresenting","falsifying","accountability","efficiency","innovation","profitability",],
            exps: "이것은 의약품 가격 상승 및 오피오이드 위기에서 제약 회사의 역할과 같은 문제를 참조하여 제약 산업의 문제에 대한 기사입니다. 문장 1은 많은 소비자가 높은 약값을 지불하기를 꺼린다고 언급하므로 대답은 마지못해여야 합니다. 문장 2는 일부 제약 회사가 제품을 과도하게 홍보하여 ​​중독 및 과다복용 사망과 같은 문제에 기여한 혐의를 받고 있다고 언급하므로 대답은 과도하게 홍보해야 합니다. 세 번째 문장은 투명성과 책임 있는 약 가격 책정 및 마케팅 관행을 개선하려는 제약 업계의 약속을 언급하므로 대답은 책임이어야 합니다. 따라서 답은 (A) 마지못해, (E) 지나친 홍보, (I) 책임감입니다.",
            ans: ["(A)","(E)","(I)",],
            cns: "제약 산업은 마약 가격 상승과 오피오이드 위기에서 제약 회사의 역할에 대한 우려로 인해 최근 몇 년 동안 더 많은 조사를 받았습니다. 많은 소비자들이 자신의 건강을 유지하는 데 필요한 약값을 기꺼이 지불하지 않기 때문에 정부는 약가에 대한 더 큰 규제를 요구하고 있습니다. 한편, 여러 제약 회사는 오피오이드 전염병에 대한 역할에 대한 소송에 직면해 있으며 일부는 자사 제품을 과도하게 홍보하고 중독 및 과다 복용 사망을 초래한 혐의를 받고 있습니다. 이에 대해 업계는 의약품 가격 책정 및 마케팅 관행의 투명성과 책임성을 높이겠다고 약속했습니다."
        },{
            ars: "In recent years, the global energy sector has undergone significant changes, driven by concerns about _____ and the need to reduce carbon emissions. As a result, many countries have implemented policies aimed at increasing the use of renewable energy sources, such as wind and solar power. This has led to a _____ in the renewable energy industry, with companies investing heavily in research and development to improve the efficiency and cost-effectiveness of their products. However, the shift towards renewable energy has not been without its _____, as some traditional energy companies have struggled to adapt to the changing market conditions.",
            reals: "In recent years, the global energy sector has undergone significant changes, driven by concerns about sustainability and the need to reduce carbon emissions. As a result, many countries have implemented policies aimed at increasing the use of renewable energy sources, such as wind and solar power. This has led to a surge in the renewable energy industry, with companies investing heavily in research and development to improve the efficiency and cost-effectiveness of their products. However, the shift towards renewable energy has not been without its challenges, as some traditional energy companies have struggled to adapt to the changing market conditions.",
            sels: ["sustainability","diversity","innovation","competition","surge","decline","stagnation","consolidation","challenges","opportunities","benefits","rewards",],
            exps: "산업의 변화와 그에 따른 과제를 언급하는 글로벌 에너지 산업에 대한 기사입니다. 문맥에서 도출할 수 있습니다. 문장 1은 지속 가능성에 대한 우려와 탄소 배출 감소의 필요성을 언급하므로 대답은 지속 가능성이어야 합니다. 두 번째 문장은 재생 에너지 산업의 급증을 언급하므로 답은 급증이어야 합니다. 문장 3은 전통적인 에너지 회사가 시장 변화에 적응하는 데 어려움이 있다고 언급했기 때문에 대답은 도전이어야 합니다. 따라서 대답은 (A) 지속 가능성, (E) 급증 및 (I) 도전입니다.",
            ans: ["(A)","(E)","(I)",],
            cns: "최근 몇 년 동안 전 세계 에너지 산업은 지속 가능성에 대한 우려와 탄소 배출 감소의 필요성으로 인해 큰 변화를 겪었습니다. 그 결과 많은 국가에서 풍력 및 태양열과 같은 재생 가능 에너지원의 사용을 늘리는 것을 목표로 하는 정책을 시행했습니다. 이로 인해 회사는 제품의 효율성과 비용 효율성을 개선하기 위해 연구 개발에 막대한 투자를 하면서 재생 에너지 산업이 급증했습니다. 그러나 일부 전통적인 에너지 회사가 변화하는 시장 상황에 적응하기 위해 고군분투했기 때문에 재생 가능 에너지로의 전환에 문제가 없는 것은 아닙니다."
        },{
            ars: "Over the past decade, advances in technology have transformed the way we live and work. One of the most significant changes has been the widespread adoption of _____ devices, such as smartphones and tablets. These devices have revolutionized the way we _____ information, allowing us to access a wealth of knowledge at our fingertips. However, they have also had a number of _____ effects, such as the erosion of face-to-face communication skills and the development of addiction to social media.",
            reals: "Over the past decade, advances in technology have transformed the way we live and work. One of the most significant changes has been the widespread adoption of mobile devices, such as smartphones and tablets. These devices have revolutionized the way we retrieve information, allowing us to access a wealth of knowledge at our fingertips. However, they have also had a number of detrimental effects, such as the erosion of face-to-face communication skills and the development of addiction to social media.",
            sels: ["mobile","wireless","digital","handheld","process","retrieve","disseminate","interpret","beneficial","detrimental","positive","negative",],
            exps: "이것은 기술 변화에 관한 기사이며 기술 변화가 삶과 일에 미치는 영향에 대해 언급합니다. 문맥에서: 문장 1은 스마트폰 및 태블릿과 같은 모바일 장치의 광범위한 사용을 언급하므로 대답은 모바일이어야 합니다. 두 번째 문장은 이러한 장치를 사용하여 지식 습득의 혁명적인 변화를 언급하므로 대답은 검색이어야 합니다. 이러한 장치 사용의 부정적인 영향은 세 번째 문장에 언급되어 있으므로 대답은 해롭다 여야 합니다. 따라서 답변은 (A) 모바일, (F) 검색 및 (J) 유해합니다.",
            ans: ["(A)","(F)","(J)",],
            cns: "지난 10년 동안 기술의 발전은 우리가 생활하고 일하는 방식을 변화시켰습니다. 가장 중요한 변화 중 하나는 스마트폰 및 태블릿과 같은 모바일 인터넷 장치의 광범위한 채택입니다. 이러한 장치는 우리가 정보를 검색하는 방식을 혁신하여 풍부한 지식을 손끝에 제공합니다. 그러나 대면 커뮤니케이션 기술의 침식 및 소셜 미디어 중독의 발달과 같은 해로운 영향도 있습니다."
        },{
            ars: "In recent years, businesses have increasingly turned to social media to _____ with their customers. Platforms like Facebook and Twitter offer companies a way to _____ with their audience in real-time, and can help to create a sense of community around a brand. However, social media also presents a number of _____, including the potential for negative feedback to spread quickly and damage a company's reputation.",
            reals: "In recent years, businesses have increasingly turned to social media to engage with their customers. Platforms like Facebook and Twitter offer companies a way to interact with their audience in real-time, and can help to create a sense of community around a brand. However, social media also presents a number of drawbacks, including the potential for negative feedback to spread quickly and damage a company's reputation.",
            sels: ["collaborate","engage","compete","negotiate","interact","market","advertise","promote","opportunities","challenges","benefits","drawbacks",],
            exps: "이 기사는 소셜 미디어를 사용하여 고객과 상호 작용하는 비즈니스에 대한 기사이며 소셜 미디어가 비즈니스에 미치는 영향을 언급합니다. 맥락에서: 문장 1은 비즈니스가 점점 더 소셜 미디어를 사용하여 고객과 상호작용하고 있다고 언급하므로 대답은 참여해야 합니다. 문장 2는 소셜 미디어가 기업이 브랜드 커뮤니티를 구축하는 데 도움이 될 수 있다고 언급했기 때문에 답은 상호작용이어야 합니다. 문장 3은 소셜 미디어 사용의 위험을 언급하므로 대답은 단점이어야 합니다. 따라서 대답은 (B) 참여, (E) 상호 작용 및 (L) 단점입니다.",
            ans: ["(B)","(E)","(L)",],
            cns: "최근 몇 년 동안 기업은 고객과 소통하기 위해 점점 더 소셜 미디어로 눈을 돌리고 있습니다. Facebook 및 Twitter와 같은 플랫폼은 기업에 청중과 실시간으로 소통할 수 있는 대화형 방법을 제공하고 브랜드에 대한 공동체 의식을 형성하는 데 도움이 됩니다. 그러나 소셜 미디어에는 부정적인 피드백이 빠르게 확산되어 회사의 명성을 손상시킬 가능성을 포함하여 몇 가지 단점도 있습니다."
        },{
            ars: "The hotel industry is experiencing a _____ in business due to the recent economic boom. With more people _____ disposable income, more and more individuals are choosing to travel and stay in hotels. In order to meet the demand, hotels are expanding their facilities and _____ their services to attract customers.",
            reals: "The hotel industry is experiencing a surge in business due to the recent economic boom. With more people spending disposable income, more and more individuals are choosing to travel and stay in hotels. In order to meet the demand, hotels are expanding their facilities and improving their services to attract customers.",
            sels: ["decline","stagnation","surge","fluctuation","having","earning","spending","saving","improving","reducing","limiting","discontinuing",],
            exps: "호텔 사업의 성장에 관한 기사입니다.경제가 호황을 누리고 호텔에 숙박하는 여행을 선택하는 사람들이 많아지면서 호텔 사업에 급상승이 일어나고 있다고 기사에서 언급했습니다. 문맥상 surge가 문장 1에서 언급되었으므로 답은 (C) 급증이어야 합니다. 문장 2는 사람들이 더 많은 가처분 소득을 지출함에 따라 점점 더 여행하고 호텔에 머무르는 것을 선택하므로 답은 (G) 지출이어야 한다고 언급합니다. 문장 3은 수요를 충족시키기 위해 호텔이 고객을 유치하기 위해 시설을 확장하고 서비스를 개선하고 있으므로 대답은 (I) 개선되어야 한다고 언급했습니다. 따라서 답변은 (C) 급증, (G) 지출 및 (I) 개선입니다.",
            ans: ["(C)","(G)","(I)",],
            cns: "호스피탈리티 산업은 최근 경제 호황으로 인해 비즈니스 활동이 급증하고 있습니다. 점점 더 많은 사람들이 소비함에 따라 가처분 소득이 증가함에 따라 점점 더 많은 사람들이 여행과 호텔 숙박을 선택합니다. 수요를 충족시키기 위해 호텔은 고객을 유치하기 위해 시설을 확장하고 서비스를 개선하고 있습니다."
        },{
            ars: "In recent years, online shopping has become increasingly popular among consumers. One of the biggest advantages of online shopping is that it allows customers to _____ items from the comfort of their own homes. This means that people can avoid the hassle of traffic and crowded stores. Additionally, online shopping often offers a wider variety of products than traditional retail stores, as well as _____ prices. Many retailers also offer free shipping or other _____ to encourage customers to shop online.",
            reals: "In recent years, online shopping has become increasingly popular among consumers. One of the biggest advantages of online shopping is that it allows customers to purchase items from the comfort of their own homes. This means that people can avoid the hassle of traffic and crowded stores. Additionally, online shopping often offers a wider variety of products than traditional retail stores, as well as lower prices. Many retailers also offer free shipping or other promotions to encourage customers to shop online.",
            sels: ["purchase","return","exchange","rent","lower","higher","fixed","fluctuating","promotions","warranties","discounts","contracts",],
            exps: "이 기사는 온라인 쇼핑에 관한 기사입니다.이 기사는 편의성, 교통 체증 및 혼잡 방지, 다양한 제품, 저렴한 가격, 상점에서 제공하는 프로모션, 무료 배송 등 온라인 쇼핑의 장점을 언급합니다. 문맥에서 도출할 수 있습니다. 문장 1은 온라인 쇼핑을 통해 사람들이 집에서 물건을 살 수 있다고 언급하므로 대답은 (A) 구매여야 합니다. 문장 2는 온라인 쇼핑의 장점 중 하나가 저렴한 가격이라고 언급하므로 답은 (E) 더 낮아야 합니다. 문장 3은 상점 등에서 제공하는 판촉 및 무료 배송을 언급하므로 답은 (I) 판촉이어야 합니다. 따라서 답은 (A) 구매, (E) 할인 및 (I) 프로모션입니다.",
            ans: ["(A)","(E)","(I)",],
            cns: "최근 몇 년 동안 온라인 쇼핑은 소비자들 사이에서 점점 더 인기를 얻고 있습니다. 온라인 쇼핑의 가장 큰 장점 중 하나는 고객이 집에서 편안하게 물건을 구매할 수 있다는 점입니다. 이는 사람들이 번거로운 교통 체증과 혼잡한 상점을 피할 수 있음을 의미합니다. 또한 온라인 쇼핑은 종종 전통적인 소매점보다 더 다양한 제품을 저렴한 가격에 제공합니다. 또한 많은 소매업체에서 고객의 온라인 쇼핑을 장려하기 위해 무료 배송 또는 기타 프로모션을 제공합니다."
        },{
            ars: "The hospitality industry, which includes hotels, restaurants, and catering services, plays a crucial role in the global economy. As international travel continues to _____, the demand for hotels and restaurants has increased. In addition, many people today prefer to _____ out or order in rather than cook at home. This has led to a growth in the number of restaurants and catering services, both small and large.When it comes to hotels, there are a wide variety of options available to travelers. From luxury hotels to budget accommodations, there is something for every _____ of traveler. Many hotels now offer additional amenities such as fitness centers, swimming pools, and complimentary breakfast. In order to stay competitive, hotels must also keep up with the latest technologies, such as online reservation systems and mobile check-in options.",
            reals: "The hospitality industry, which includes hotels, restaurants, and catering services, plays a crucial role in the global economy. As international travel continues to increase, the demand for hotels and restaurants has increased. In addition, many people today prefer to dine out or order in rather than cook at home. This has led to a growth in the number of restaurants and catering services, both small and large.When it comes to hotels, there are a wide variety of options available to travelers. From luxury hotels to budget accommodations, there is something for every category of traveler. Many hotels now offer additional amenities such as fitness centers, swimming pools, and complimentary breakfast. In order to stay competitive, hotels must also keep up with the latest technologies, such as online reservation systems and mobile check-in options.",
            sels: ["decrease","stagnate","increase","fluctuate","eat","dine","take","make","kind","level","group","category",],
            exps: "이것은 레스토랑 및 호텔 산업에 관한 기사입니다. 이 기사는 국제 관광이 증가함에 따라 호텔과 레스토랑에 대한 수요도 증가한다고 언급합니다. 동시에 점점 더 많은 사람들이 외식을 선택하거나 음식 배달을 주문하여 레스토랑과 케이터링 서비스의 수도 증가하고 있습니다. 또한 호텔은 고급 호텔과 저렴한 숙박 시설 등 다양한 옵션을 제공하며 경쟁력을 유지하기 위해 호텔도 최신 기술을 따라잡아야 합니다. 문장 1은 국제 관광이 증가함에 따라 호텔과 레스토랑에 대한 수요도 증가하므로 대답은 (C) 증가해야 한다고 언급합니다. 문장 2는 점점 더 많은 사람들이 외식을 선택하거나 음식 배달을 선택한다고 언급하므로 대답은 (F) 식사해야 합니다. 문장 3은 호텔이 고급 호텔 및 저예산 숙박 시설 등 다양한 옵션을 제공한다고 언급하므로 답은 (L) 범주여야 합니다. 따라서 답은 (C) 증가, (F) 식사, (L) 범주입니다.",
            ans: ["(C)","(F)","(L)",],
            cns: "호텔, 레스토랑, 식품 서비스를 포함한 환대 산업은 세계 경제에서 중요한 역할을 합니다. 해외 여행이 계속 증가함에 따라 호텔과 레스토랑에 대한 수요가 증가했습니다. 또한 오늘날 많은 사람들은 집에서 요리하는 것보다 외식을 하거나 주문하는 것을 선호합니다. 이로 인해 크고 작은 식당과 급식 서비스가 증가했습니다. 호텔과 관련하여 여행자에게는 다양한 옵션이 있습니다. 고급 호텔에서 저예산 숙박 시설에 이르기까지 모든 범주의 여행자를 위한 무언가가 있습니다. 현재 많은 호텔에서 피트니스 센터, 수영장, 무료 아침 식사와 같은 추가 편의 시설을 제공합니다. 경쟁력을 유지하기 위해 호텔은 온라인 예약 시스템 및 모바일 체크인 옵션과 같은 최신 기술을 따라잡아야 합니다."
        },]