const q = [{
            ars: "The new restaurant in town is already causing quite a _____ with its unique menu and elegant atmosphere. The restaurant's owner, a well-known chef, has created a _____ dining experience that is both delicious and memorable. The restaurant offers a wide variety of dishes, ranging from classic comfort food to exotic _____ from around the world. Customers can choose to dine in the main dining room or in a more intimate private _____ for special occasions. The restaurant also offers catering services for corporate events and private parties.",
            reals: "The new restaurant in town is already causing quite a stir with its unique menu and elegant atmosphere. The restaurant's owner, a well-known chef, has created a refined dining experience that is both delicious and memorable. The restaurant offers a wide variety of dishes, ranging from classic comfort food to exotic delicacies from around the world. Customers can choose to dine in the main dining room or in a more intimate private booth for special occasions. The restaurant also offers catering services for corporate events and private parties.",
            sels: ["stir","steer","stare","store","refined","delightful","extravagant","delicate","delicacies","spices","beverages","desserts","booth","chamber","lounge","terrace",],
            exps: "Đây là bài viết về một nhà hàng mới, đề cập đến thực đơn và không khí của nhà hàng. Từ ngữ cảnh: Câu một đề cập đến thực đơn độc đáo và không gian trang nhã của nhà hàng, vì vậy câu trả lời phải là khuấy động. Câu 2 đề cập đến các món ăn của nhà hàng rất ngon và đáng nhớ, vì vậy câu trả lời nên là tinh tế. Câu 3 đề cập rằng nhà hàng phục vụ nhiều món ăn khác nhau, bao gồm các món ăn cổ điển và các món ăn lạ từ khắp nơi trên thế giới, vì vậy câu trả lời phải là món ngon. Câu bốn đề cập đến khu vực ăn uống riêng mà nhà hàng cung cấp, vì vậy câu trả lời phải là gian hàng. Do đó, các câu trả lời là (A) khuấy, (E) tinh chế, (I) món ngon và (M) gian hàng.",
            ans: ["(A)","(E)","(I)","(M)",],
            cns: "Nhà hàng mới trong thị trấn đã gây xôn xao dư luận với thực đơn độc đáo và không gian trang nhã. Chủ sở hữu của nhà hàng là một đầu bếp nổi tiếng, người đã tạo ra một trải nghiệm ẩm thực tinh tế vừa ngon miệng vừa đáng nhớ. Nhà hàng cung cấp nhiều món ăn khác nhau, từ những món ăn thoải mái cổ điển đến những món ăn lạ miệng từ khắp nơi trên thế giới. Khách hàng quen có thể chọn dùng bữa trong phòng ăn chính hoặc trong những hộp thân mật hơn cho những dịp đặc biệt. Nhà hàng cũng phục vụ cho các sự kiện của công ty và các bữa tiệc riêng tư."
        },{
            ars: "The new marketing campaign has been _____ successful, with sales increasing by 20% since its launch. The campaign's focus on social media has helped the company reach a wider _____, particularly among younger consumers who spend a lot of time on their phones. The company's _____ strategy, which includes targeted ads and influencer partnerships, has also contributed to its success. However, the company's _____ has also played a role in the campaign's success, as its reputation for high-quality products has helped build trust with customers.",
            reals: "The new marketing campaign has been tremendously successful, with sales increasing by 20% since its launch. The campaign's focus on social media has helped the company reach a wider audience, particularly among younger consumers who spend a lot of time on their phones. The company's promotion strategy, which includes targeted ads and influencer partnerships, has also contributed to its success. However, the company's reputation has also played a role in the campaign's success, as its reputation for high-quality products has helped build trust with customers.",
            sels: ["moderately","tremendously","barely","slightly","audience","market","sector","niche","pricing","promotion","distribution","packaging","innovation","reputation","location","convenience",],
            exps: "Đây là một bài viết về một chiến dịch tiếp thị đề cập đến lý do tại sao chiến dịch thành công. Từ ngữ cảnh, có thể thấy rằng thành công của chiến dịch đã được đề cập trong câu một, vì vậy câu trả lời phải là cực kỳ. Câu 2 đề cập rằng sự kiện này đặc biệt phổ biến với người tiêu dùng trẻ tuổi, vì vậy câu trả lời phải là khán giả. Chiến lược của chiến dịch được đề cập trong câu thứ ba, bao gồm quảng cáo được nhắm mục tiêu và hợp tác với người có ảnh hưởng, vì vậy câu trả lời phải là quảng cáo. Danh tiếng của công ty được đề cập ở câu 4, giúp tạo niềm tin với khách hàng, vì vậy đáp án nên là “danh tiếng”. Vì vậy, các câu trả lời là (B) rất nhiều, (E) khán giả, (J) quảng cáo và (N) danh tiếng.",
            ans: ["(B)","(E)","(J)","(N)",],
            cns: "Chiến dịch tiếp thị mới đã thành công rực rỡ, với doanh số bán hàng tăng 20% ​​kể từ khi ra mắt. Chiến dịch tập trung vào phương tiện truyền thông xã hội đã giúp công ty tiếp cận được nhiều đối tượng hơn, đặc biệt là những người tiêu dùng trẻ tuổi dành nhiều thời gian cho điện thoại của họ. Các chiến lược công khai của công ty bao gồm quảng cáo được nhắm mục tiêu và quan hệ đối tác với người có ảnh hưởng cũng đã góp phần vào thành công của nó. Tuy nhiên, danh tiếng của công ty cũng đóng một vai trò quan trọng trong sự thành công của sự kiện, vì danh tiếng về các sản phẩm chất lượng cao giúp xây dựng lòng tin của khách hàng."
        },{
            ars: "The company has announced plans to _____ its workforce by 10% in an effort to reduce costs. The layoffs will primarily affect _____ in the company's administrative and support departments, although some managers and executives will also be let go. The company's CEO has stated that these changes are necessary to ensure the long-term _____ of the company and maintain its competitiveness in the marketplace. The company will provide severance packages and _____ services to affected employees to help them transition to new employment.",
            reals: "The company has announced plans to downsize its workforce by 10% in an effort to reduce costs. The layoffs will primarily affect employees in the company's administrative and support departments, although some managers and executives will also be let go. The company's CEO has stated that these changes are necessary to ensure the long-term sustainability of the company and maintain its competitiveness in the marketplace. The company will provide severance packages and counseling services to affected employees to help them transition to new employment.",
            sels: ["expand","downsize","diversify","centralize","employees","shareholders","customers","suppliers","profitability","stability","flexibility","sustainability","relocation","retraining","counseling","mentoring",],
            exps: "Đây là một bài viết về kế hoạch sa thải nhân viên của một công ty, và bài viết đề cập đến nguyên nhân và ảnh hưởng của kế hoạch. Có thể kết luận từ ngữ cảnh: Câu 1 đề cập đến kế hoạch sa thải nhân viên của công ty, vì vậy câu trả lời phải là thu hẹp quy mô. Câu 2 đề cập rằng một bộ phận nhân viên cụ thể bị ảnh hưởng, vì vậy câu trả lời phải là nhân viên. Câu 3 đề cập rằng Giám đốc điều hành của công ty tin rằng những thay đổi này là cần thiết để đảm bảo sự ổn định lâu dài và khả năng cạnh tranh của công ty, vì vậy câu trả lời phải là sự bền vững. Câu 4 đề cập rằng công ty cung cấp dịch vụ trợ cấp thôi việc và tư vấn để giúp nhân viên bị ảnh hưởng chuyển sang công việc mới, vì vậy câu trả lời phải là tư vấn. Vì vậy, các câu trả lời là (B) thu hẹp quy mô, (E) nhân viên, (L) tính bền vững và (O) tư vấn.",
            ans: ["(B)","(E)","(L)","(O)",],
            cns: "Công ty đã công bố kế hoạch cắt giảm 10% lực lượng lao động trong nỗ lực giảm chi phí. Việc sa thải chủ yếu ảnh hưởng đến nhân viên trong các chức năng hành chính và hỗ trợ của công ty, mặc dù một số nhà quản lý và giám đốc điều hành cũng sẽ bị sa thải. Giám đốc điều hành của công ty cho biết những thay đổi là cần thiết để đảm bảo tính bền vững lâu dài và duy trì khả năng cạnh tranh của công ty trên thị trường. Công ty sẽ cung cấp trợ cấp thôi việc và dịch vụ tư vấn cho những nhân viên bị ảnh hưởng để giúp họ chuyển sang công việc mới."
        },{
            ars: "The _____ of the company's new product has been delayed due to manufacturing issues. The company had originally planned to launch the product in Q2, but now expects to release it in Q4. The delay has been _____ disappointing for the company, which had invested heavily in research and development and marketing efforts to support the launch. The company's management has reassured shareholders that the delay is temporary and that the product will be worth the wait, with features that are _____ superior to those of its competitors.",
            reals: "The launch of the company's new product has been delayed due to manufacturing issues. The company had originally planned to launch the product in Q2, but now expects to release it in Q4. The delay has been extremely disappointing for the company, which had invested heavily in research and development and marketing efforts to support the launch. The company's management has reassured shareholders that the delay is temporary and that the product will be worth the wait, with features that are significantly superior to those of its competitors.",
            sels: ["launch","design","development","testing","highly","somewhat","extremely","moderately","significantly","marginally","slightly","barely",],
            exps: "Đây là một bài viết về sự chậm trễ trong các sản phẩm mới, lý do cho sự chậm trễ và phản ứng của công ty. Nó xuất phát từ ngữ cảnh: Câu 1 đề cập rằng việc phát hành sản phẩm bị trì hoãn, vì vậy câu trả lời phải là ra mắt. Câu thứ hai đề cập rằng công ty đã rất thất vọng với sự chậm trễ này, vì vậy câu trả lời nên là cực kỳ. Câu 3 đề cập đến sản phẩm sẽ có những chức năng vượt trội nên đáp án phải là đáng kể. Vì vậy, các câu trả lời là (A) khởi động, (G) cực kỳ, và (I) đáng kể.",
            ans: ["(A)","(G)","(I)",],
            cns: "Ra mắt, tung ra thị trường Sản phẩm mới của công ty đã bị trì hoãn do vấn đề sản xuất. Công ty ban đầu đã lên kế hoạch ra mắt sản phẩm vào quý hai, nhưng hiện tại dự kiến ​​​​sẽ phát hành vào quý bốn. Sự chậm trễ là nghiêm trọng, điều này gây thất vọng cho công ty, công ty đã đầu tư rất nhiều vào R&D và tiếp thị để hỗ trợ việc ra mắt. Ban lãnh đạo công ty đã đảm bảo với các cổ đông rằng sự chậm trễ chỉ là tạm thời và sản phẩm đáng để chờ đợi, với các tính năng vượt trội so với các đối thủ cạnh tranh."
        },{
            ars: "The hotel industry in the city has been experiencing a boom in recent years due to increased tourism. Many new hotels have _____ up in the city center, offering tourists a range of options at different price points. However, this growth has also led to increased _____ and competition among hotels, with some struggling to fill their rooms during off-peak seasons. To address this, many hotels have been _____ their services to appeal to a wider range of customers, such as offering discounted rates to business travelers and families.",
            reals: "The hotel industry in the city has been experiencing a boom in recent years due to increased tourism. Many new hotels have opened up in the city center, offering tourists a range of options at different price points. However, this growth has also led to increased supply and competition among hotels, with some struggling to fill their rooms during off-peak seasons. To address this, many hotels have been diversifying their services to appeal to a wider range of customers, such as offering discounted rates to business travelers and families.",
            sels: ["closed","opened","expanded","renovated","demand","supply","marketing","innovation","diversifying","outsourcing","downsizing","streamlining",],
            exps: "Đây là bài viết về sự phát triển của ngành khách sạn tại TP.HCM, bài viết đề cập đến sự tăng trưởng của ngành khách sạn và các vấn đề liên quan. Có thể kết luận từ ngữ cảnh: Câu 1 đề cập rằng ngành công nghiệp khách sạn đô thị đã phát triển mạnh trong những năm gần đây, vì vậy câu trả lời nên là mở. Câu 2 đề cập đến việc tăng trưởng cũng kéo theo sự cạnh tranh và cung vượt cầu, vì vậy đáp án phải là cung. Câu 3 đề cập rằng nhiều khách sạn đang điều chỉnh dịch vụ của họ để đáp ứng với những thay đổi của thị trường, vì vậy câu trả lời nên là đa dạng hóa. Do đó, các câu trả lời là (B) mở ra, (F) cung cấp và (I) đa dạng hóa.",
            ans: ["(B)","(F)","(I)",],
            cns: "Trong những năm gần đây, ngành khách sạn của thành phố phát triển vượt bậc nhờ sự tăng trưởng của ngành du lịch. Nhiều khách sạn mới đã mở ở trung tâm thành phố, cung cấp cho khách du lịch nhiều lựa chọn với các mức giá khác nhau. Tuy nhiên, sự tăng trưởng này cũng dẫn đến tăng nguồn cung và cạnh tranh giữa các khách sạn, với một số khách sạn chật vật lấp đầy phòng trong mùa thấp điểm. Để chống lại điều này, nhiều khách sạn đã đa dạng hóa các dịch vụ của họ để thu hút nhiều khách hàng hơn, chẳng hạn như đưa ra mức giá chiết khấu cho khách doanh nhân và gia đình."
        },{
            ars: "The pharmaceutical industry has come under increased scrutiny in recent years due to concerns about rising drug prices and the role of pharmaceutical companies in the opioid crisis. Many consumers are _____ to pay for medications that they need to maintain their health, leading to calls for greater government regulation of drug prices. Meanwhile, several pharmaceutical companies have faced lawsuits for their role in the opioid epidemic, with some accused of _____ their products and contributing to addiction and overdose deaths. In response, the industry has pledged to improve transparency and _____ in drug pricing and marketing practices.",
            reals: "The pharmaceutical industry has come under increased scrutiny in recent years due to concerns about rising drug prices and the role of pharmaceutical companies in the opioid crisis. Many consumers are reluctant to pay for medications that they need to maintain their health, leading to calls for greater government regulation of drug prices. Meanwhile, several pharmaceutical companies have faced lawsuits for their role in the opioid epidemic, with some accused of overpromoting their products and contributing to addiction and overdose deaths. In response, the industry has pledged to improve transparency and accountability in drug pricing and marketing practices.",
            sels: ["reluctant","eager","unwilling","hesitant","overpromoting","underpromoting","misrepresenting","falsifying","accountability","efficiency","innovation","profitability",],
            exps: "Đây là một bài viết về các vấn đề trong ngành dược phẩm, có đề cập đến các vấn đề như giá thuốc tăng cao và vai trò của các công ty dược phẩm trong cuộc khủng hoảng opioid. Có thể rút ra từ ngữ cảnh: Câu 1 đề cập đến việc nhiều người tiêu dùng không sẵn sàng trả giá thuốc cao nên đáp án nên là “miễn cưỡng”. Câu 2 đề cập đến việc một số công ty dược phẩm bị cáo buộc quảng cáo quá mức sản phẩm của họ, góp phần gây ra các vấn đề như nghiện và tử vong do dùng thuốc quá liều, vì vậy câu trả lời nên là quảng cáo quá mức. Câu ba đề cập đến cam kết của ngành dược phẩm trong việc cải thiện tính minh bạch và các hoạt động tiếp thị và định giá thuốc có trách nhiệm, vì vậy câu trả lời phải là trách nhiệm giải trình. Vì vậy, các câu trả lời là (A) miễn cưỡng, (E) thúc đẩy quá mức và (I) trách nhiệm giải trình.",
            ans: ["(A)","(E)","(I)",],
            cns: "Ngành công nghiệp dược phẩm đã bị giám sát chặt chẽ hơn trong những năm gần đây trong bối cảnh lo ngại về giá thuốc tăng cao và vai trò của các công ty dược phẩm trong cuộc khủng hoảng opioid. Nhiều người tiêu dùng không sẵn sàng trả tiền cho các loại thuốc họ cần để duy trì sức khỏe, khiến các chính phủ kêu gọi quy định chặt chẽ hơn về giá thuốc. Trong khi đó, một số công ty dược phẩm đang phải đối mặt với các vụ kiện về vai trò của họ trong đại dịch opioid, với một số bị cáo buộc quảng cáo quá mức sản phẩm của họ và gây nghiện và tử vong do quá liều. Đáp lại, ngành công nghiệp đã cam kết tăng cường tính minh bạch và trách nhiệm giải trình trong việc định giá thuốc và thực hành tiếp thị."
        },{
            ars: "In recent years, the global energy sector has undergone significant changes, driven by concerns about _____ and the need to reduce carbon emissions. As a result, many countries have implemented policies aimed at increasing the use of renewable energy sources, such as wind and solar power. This has led to a _____ in the renewable energy industry, with companies investing heavily in research and development to improve the efficiency and cost-effectiveness of their products. However, the shift towards renewable energy has not been without its _____, as some traditional energy companies have struggled to adapt to the changing market conditions.",
            reals: "In recent years, the global energy sector has undergone significant changes, driven by concerns about sustainability and the need to reduce carbon emissions. As a result, many countries have implemented policies aimed at increasing the use of renewable energy sources, such as wind and solar power. This has led to a surge in the renewable energy industry, with companies investing heavily in research and development to improve the efficiency and cost-effectiveness of their products. However, the shift towards renewable energy has not been without its challenges, as some traditional energy companies have struggled to adapt to the changing market conditions.",
            sels: ["sustainability","diversity","innovation","competition","surge","decline","stagnation","consolidation","challenges","opportunities","benefits","rewards",],
            exps: "Đây là một bài viết về ngành năng lượng toàn cầu, trong đó đề cập đến những thay đổi trong ngành và những thách thức tương ứng. Có thể rút ra từ ngữ cảnh: Câu 1 đề cập đến mối quan tâm đến tính bền vững và sự cần thiết phải giảm lượng khí thải carbon, vì vậy câu trả lời phải là sự bền vững. Câu hai đề cập đến sự đột biến trong ngành năng lượng tái tạo nên đáp án phải là surge. Câu 3 đề cập đến việc các công ty năng lượng truyền thống gặp khó khăn trong việc thích ứng với những thay đổi của thị trường nên đáp án nên là “thách thức”. Vì vậy, các câu trả lời là (A) tính bền vững, (E) đột biến và (I) thách thức.",
            ans: ["(A)","(E)","(I)",],
            cns: "Trong những năm gần đây, ngành năng lượng toàn cầu đã trải qua những thay đổi lớn do những lo ngại về tính bền vững và nhu cầu giảm lượng khí thải carbon. Do đó, nhiều quốc gia đã thực hiện các chính sách nhằm tăng cường sử dụng các nguồn năng lượng tái tạo như gió và mặt trời. Điều này đã dẫn đến sự bùng nổ trong ngành năng lượng tái tạo, với các công ty đầu tư mạnh vào nghiên cứu và phát triển để nâng cao hiệu quả và tiết kiệm chi phí cho các sản phẩm của họ. Tuy nhiên, quá trình chuyển đổi sang năng lượng tái tạo không phải là không có thách thức, vì một số công ty năng lượng truyền thống đã phải vật lộn để thích nghi với các điều kiện thị trường đang thay đổi."
        },{
            ars: "Over the past decade, advances in technology have transformed the way we live and work. One of the most significant changes has been the widespread adoption of _____ devices, such as smartphones and tablets. These devices have revolutionized the way we _____ information, allowing us to access a wealth of knowledge at our fingertips. However, they have also had a number of _____ effects, such as the erosion of face-to-face communication skills and the development of addiction to social media.",
            reals: "Over the past decade, advances in technology have transformed the way we live and work. One of the most significant changes has been the widespread adoption of mobile devices, such as smartphones and tablets. These devices have revolutionized the way we retrieve information, allowing us to access a wealth of knowledge at our fingertips. However, they have also had a number of detrimental effects, such as the erosion of face-to-face communication skills and the development of addiction to social media.",
            sels: ["mobile","wireless","digital","handheld","process","retrieve","disseminate","interpret","beneficial","detrimental","positive","negative",],
            exps: "Đây là một bài viết về sự thay đổi công nghệ, và bài viết đề cập đến tác động của sự thay đổi công nghệ đối với cuộc sống và công việc. Từ ngữ cảnh: Câu 1 đề cập đến việc sử dụng rộng rãi các thiết bị di động như điện thoại thông minh và máy tính bảng, vì vậy câu trả lời phải là di động. Câu hai đề cập đến sự thay đổi mang tính cách mạng trong việc tiếp thu kiến ​​thức bằng các thiết bị này, vì vậy câu trả lời phải là lấy. Tác động tiêu cực của việc sử dụng các thiết bị này được đề cập trong câu thứ ba, vì vậy câu trả lời phải là bất lợi. Vì vậy, các câu trả lời là (A) di động, (F) truy xuất và (J) bất lợi.",
            ans: ["(A)","(F)","(J)",],
            cns: "Trong thập kỷ qua, những tiến bộ trong công nghệ đã thay đổi cách chúng ta sống và làm việc. Một trong những thay đổi quan trọng nhất là việc áp dụng rộng rãi các thiết bị Internet di động, chẳng hạn như điện thoại thông minh và máy tính bảng. Những thiết bị này đã cách mạng hóa cách chúng ta truy xuất thông tin, đưa vô số kiến ​​thức vào tầm tay của chúng ta. Tuy nhiên, chúng cũng có những tác động có hại, chẳng hạn như làm xói mòn các kỹ năng giao tiếp mặt đối mặt và phát triển chứng nghiện mạng xã hội."
        },{
            ars: "In recent years, businesses have increasingly turned to social media to _____ with their customers. Platforms like Facebook and Twitter offer companies a way to _____ with their audience in real-time, and can help to create a sense of community around a brand. However, social media also presents a number of _____, including the potential for negative feedback to spread quickly and damage a company's reputation.",
            reals: "In recent years, businesses have increasingly turned to social media to engage with their customers. Platforms like Facebook and Twitter offer companies a way to interact with their audience in real-time, and can help to create a sense of community around a brand. However, social media also presents a number of drawbacks, including the potential for negative feedback to spread quickly and damage a company's reputation.",
            sels: ["collaborate","engage","compete","negotiate","interact","market","advertise","promote","opportunities","challenges","benefits","drawbacks",],
            exps: "Đây là bài viết nói về việc doanh nghiệp sử dụng mạng xã hội để tương tác với khách hàng, bài viết đề cập đến tác động của mạng xã hội đối với doanh nghiệp. Từ bối cảnh: Câu 1 đề cập rằng các doanh nghiệp đang ngày càng sử dụng phương tiện truyền thông xã hội để tương tác với khách hàng, vì vậy câu trả lời phải là tương tác. Câu 2 đề cập rằng phương tiện truyền thông xã hội có thể giúp các công ty xây dựng cộng đồng thương hiệu, vì vậy câu trả lời phải là tương tác. Câu 3 đề cập đến rủi ro khi sử dụng mạng xã hội nên đáp án phải là hạn chế. Vì vậy, câu trả lời là (B) tham gia, (E) tương tác và (L) hạn chế.",
            ans: ["(B)","(E)","(L)",],
            cns: "Trong những năm gần đây, các doanh nghiệp ngày càng chuyển sang sử dụng phương tiện truyền thông xã hội để tương tác với khách hàng của họ. Các nền tảng như Facebook và Twitter cung cấp cho các công ty một cách tương tác để giao tiếp với khán giả của họ trong thời gian thực và giúp tạo cảm giác cộng đồng xung quanh một thương hiệu. Tuy nhiên, phương tiện truyền thông xã hội cũng có một số nhược điểm, bao gồm khả năng phản hồi tiêu cực lan truyền nhanh chóng và gây tổn hại đến danh tiếng của công ty."
        },{
            ars: "The hotel industry is experiencing a _____ in business due to the recent economic boom. With more people _____ disposable income, more and more individuals are choosing to travel and stay in hotels. In order to meet the demand, hotels are expanding their facilities and _____ their services to attract customers.",
            reals: "The hotel industry is experiencing a surge in business due to the recent economic boom. With more people spending disposable income, more and more individuals are choosing to travel and stay in hotels. In order to meet the demand, hotels are expanding their facilities and improving their services to attract customers.",
            sels: ["decline","stagnation","surge","fluctuation","having","earning","spending","saving","improving","reducing","limiting","discontinuing",],
            exps: "Đây là một bài viết về sự phát triển của ngành kinh doanh khách sạn. Bài báo đề cập rằng khi nền kinh tế bùng nổ và ngày càng có nhiều người chọn đi du lịch và ở trong khách sạn, thì ngành kinh doanh khách sạn có sự tăng đột biến. Từ ngữ cảnh, theo đó surge được đề cập trong câu một, vì vậy câu trả lời phải là (C) Surge. Câu 2 đề cập rằng khi mọi người chi tiêu nhiều hơn thu nhập khả dụng, họ ngày càng chọn đi du lịch và ở trong khách sạn, vì vậy câu trả lời phải là (G) chi tiêu. Câu 3 đề cập rằng để đáp ứng nhu cầu, khách sạn đang mở rộng cơ sở vật chất và “cải thiện” dịch vụ để thu hút khách hàng, vì vậy đáp án phải là (I) cải thiện. Vì vậy, các câu trả lời là (C) tăng, (G) chi tiêu và (I) cải thiện.",
            ans: ["(C)","(G)","(I)",],
            cns: "Ngành khách sạn đang trải qua một sự đột biến trong hoạt động kinh doanh do sự bùng nổ kinh tế gần đây. Khi ngày càng có nhiều người tiêu dùng Với thu nhập khả dụng tăng lên, ngày càng có nhiều người chọn đi du lịch và ở trong khách sạn. Để đáp ứng nhu cầu, các khách sạn đang mở rộng cơ sở vật chất và cải thiện dịch vụ của họ để thu hút khách hàng."
        },{
            ars: "In recent years, online shopping has become increasingly popular among consumers. One of the biggest advantages of online shopping is that it allows customers to _____ items from the comfort of their own homes. This means that people can avoid the hassle of traffic and crowded stores. Additionally, online shopping often offers a wider variety of products than traditional retail stores, as well as _____ prices. Many retailers also offer free shipping or other _____ to encourage customers to shop online.",
            reals: "In recent years, online shopping has become increasingly popular among consumers. One of the biggest advantages of online shopping is that it allows customers to purchase items from the comfort of their own homes. This means that people can avoid the hassle of traffic and crowded stores. Additionally, online shopping often offers a wider variety of products than traditional retail stores, as well as lower prices. Many retailers also offer free shipping or other promotions to encourage customers to shop online.",
            sels: ["purchase","return","exchange","rent","lower","higher","fixed","fluctuating","promotions","warranties","discounts","contracts",],
            exps: "Đây là một bài viết về mua sắm trực tuyến. Bài viết đề cập đến những lợi ích của mua sắm trực tuyến, bao gồm sự thuận tiện, tránh giao thông và đám đông, nhiều loại sản phẩm, giá thấp hơn, các chương trình khuyến mãi được cung cấp bởi các cửa hàng, miễn phí vận chuyển, v.v. Nó có thể được rút ra từ ngữ cảnh: Câu 1 đề cập rằng mua sắm trực tuyến cho phép mọi người mua hàng từ nhà, vì vậy câu trả lời nên là (A) mua hàng. Câu 2 đề cập rằng một trong những lợi thế của mua sắm trực tuyến là giá thấp hơn, vì vậy câu trả lời phải là (E) thấp hơn. Câu 3 đề cập đến các chương trình khuyến mãi và miễn phí vận chuyển được cung cấp bởi cửa hàng, v.v., vì vậy câu trả lời phải là (I) khuyến mãi. Vì vậy, câu trả lời là (A) mua hàng, (E) giảm giá và (I) khuyến mãi.",
            ans: ["(A)","(E)","(I)",],
            cns: "Trong những năm gần đây, mua sắm trực tuyến ngày càng trở nên phổ biến đối với người tiêu dùng. Một trong những lợi thế lớn nhất của mua sắm trực tuyến là nó cho phép khách hàng mua các mặt hàng một cách thoải mái tại nhà riêng của họ. Điều này có nghĩa là mọi người có thể tránh được những rắc rối về giao thông và các cửa hàng đông đúc. Ngoài ra, mua sắm trực tuyến thường cung cấp nhiều loại sản phẩm hơn so với các cửa hàng bán lẻ truyền thống và với giá thấp hơn. Nhiều nhà bán lẻ cũng cung cấp giao hàng miễn phí hoặc các chương trình khuyến mãi khác để khuyến khích khách hàng mua sắm trực tuyến."
        },{
            ars: "The hospitality industry, which includes hotels, restaurants, and catering services, plays a crucial role in the global economy. As international travel continues to _____, the demand for hotels and restaurants has increased. In addition, many people today prefer to _____ out or order in rather than cook at home. This has led to a growth in the number of restaurants and catering services, both small and large.When it comes to hotels, there are a wide variety of options available to travelers. From luxury hotels to budget accommodations, there is something for every _____ of traveler. Many hotels now offer additional amenities such as fitness centers, swimming pools, and complimentary breakfast. In order to stay competitive, hotels must also keep up with the latest technologies, such as online reservation systems and mobile check-in options.",
            reals: "The hospitality industry, which includes hotels, restaurants, and catering services, plays a crucial role in the global economy. As international travel continues to increase, the demand for hotels and restaurants has increased. In addition, many people today prefer to dine out or order in rather than cook at home. This has led to a growth in the number of restaurants and catering services, both small and large.When it comes to hotels, there are a wide variety of options available to travelers. From luxury hotels to budget accommodations, there is something for every category of traveler. Many hotels now offer additional amenities such as fitness centers, swimming pools, and complimentary breakfast. In order to stay competitive, hotels must also keep up with the latest technologies, such as online reservation systems and mobile check-in options.",
            sels: ["decrease","stagnate","increase","fluctuate","eat","dine","take","make","kind","level","group","category",],
            exps: "Đây là bài viết về ngành nhà hàng, khách sạn. Bài báo đề cập rằng khi du lịch quốc tế tăng lên, thì nhu cầu về khách sạn và nhà hàng cũng tăng theo. Đồng thời, ngày càng có nhiều người lựa chọn đi ăn ngoài hoặc đặt giao đồ ăn, do đó số lượng nhà hàng và dịch vụ ăn uống cũng ngày càng nhiều. Ngoài ra, các khách sạn cũng cung cấp nhiều lựa chọn khác nhau, bao gồm khách sạn hạng sang và phòng nghỉ bình dân, v.v. và để duy trì tính cạnh tranh, các khách sạn cũng phải bắt kịp công nghệ mới nhất. Câu 1 đề cập rằng khi du lịch quốc tế tăng lên, nhu cầu về khách sạn và nhà hàng cũng tăng theo, vì vậy đáp án phải là (C) tăng. Câu 2 đề cập rằng ngày càng có nhiều người chọn đi ăn ngoài hoặc gọi giao đồ ăn, vì vậy đáp án phải là (F) dine. Câu 3 đề cập rằng khách sạn cung cấp nhiều lựa chọn khác nhau, bao gồm khách sạn sang trọng và chỗ ở bình dân, v.v., vì vậy câu trả lời phải là (L) loại. Do đó, các câu trả lời là (C) tăng, (F) ăn tối, và (L) loại.",
            ans: ["(C)","(F)","(L)",],
            cns: "Ngành khách sạn, bao gồm khách sạn, nhà hàng và dịch vụ ăn uống, đóng một vai trò quan trọng trong nền kinh tế toàn cầu. Khi du lịch quốc tế tiếp tục tăng, nhu cầu về khách sạn và nhà hàng đã tăng lên. Ngoài ra, nhiều người ngày nay thích ăn tối hoặc gọi món hơn là nấu ăn ở nhà. Điều này đã dẫn đến sự gia tăng số lượng các nhà hàng lớn nhỏ và các dịch vụ ăn uống. Khi nói đến khách sạn, du khách có nhiều lựa chọn. Từ khách sạn sang trọng đến nhà nghỉ bình dân, luôn có thứ gì đó cho mọi đối tượng khách du lịch. Nhiều khách sạn hiện cung cấp các tiện nghi bổ sung như trung tâm thể dục, hồ bơi và bữa sáng miễn phí. Để duy trì tính cạnh tranh, các khách sạn cũng phải theo kịp các công nghệ mới nhất, chẳng hạn như hệ thống đặt phòng trực tuyến và các tùy chọn nhận phòng di động."
        },]