export const ja = [{
            ar: "For years, scientists have been working to find a cure for Alzheimer's disease, a progressive brain disorder that affects millions of people worldwide. The disease is caused by the buildup of abnormal proteins in the brain that damage and kill brain cells, leading to memory loss and other cognitive problems. Although there is currently no cure for Alzheimer's disease, there are medications that can help manage symptoms and improve quality of life for patients.Recently, researchers at the University of Texas at Dallas may have made a breakthrough in the search for a cure. In a study published in the journal Science Advances, the team showed that they were able to clear out the abnormal proteins that cause Alzheimer's disease from the brains of mice. They did this by using ultrasound waves to stimulate microglial cells in the brain, which are responsible for removing waste and other harmful substances. The researchers found that the ultrasound waves caused the microglial cells to consume the abnormal proteins, reducing their buildup in the brain.The study is still in its early stages, and more research is needed to determine whether the same approach could be effective in humans. However, the results are promising, and could pave the way for a future cure for Alzheimer's disease.",
            q: ["What is Alzheimer's disease?","What causes Alzheimer's disease?","Is there currently a cure for Alzheimer's disease?","What did researchers at the University of Texas at Dallas do to clear out the abnormal proteins that cause Alzheimer's disease from the brains of mice?","Is the study mentioned in the passage likely to lead to a cure for Alzheimer's disease in humans?",],
            q_sel:[[" A type of cancer"," A progressive brain disorder"," A genetic disorder"," A disorder caused by a virus",],[" The buildup of abnormal proteins in the brain"," A virus"," Genetics"," Smoking",],[" Yes, there is a cure."," No, there is no cure."," There is a cure, but it is not effective."," There used to be a cure, but it is no longer available.",],[" They used chemotherapy."," They used ultrasound waves to stimulate microglial cells."," They removed the affected parts of the brain."," They gave the mice a new medication.",],[" Yes, a cure is now available for humans."," No, the study is unlikely to lead to a cure for humans."," It is too early to tell."," The study has already led to a cure for humans.",],],
            q_ex: ["記事の最初の文で、アルツハイマー病は「進行性の脳障害」であると述べているため、答えは B です。","アルツハイマー病は「脳内に異常なタンパク質が蓄積すること」が原因と記事で言及されているので、答えはAです。","この記事では、現在アルツハイマー病の治療法はなく、症状を緩和するのに役立ついくつかの薬しかないため、答えは B.","この記事では、研究者が「超音波を使用して脳内のミクログリア細胞を刺激する」ことで、アルツハイマー病の原因となる異常なタンパク質を除去すると述べているため、答えは B です。","この記事では、この研究はまだ初期段階にあり、同じアプローチが人間で機能するかどうかを判断するにはさらに研究が必要であると述べているため、答えは C.この論文はまた、調査結果は有望であると述べていますが、さらなる研究が必要です.",],
            q_a: [" B"," A"," B"," B"," C",],
            zh: "何年もの間、科学者たちは、世界中の何百万もの人々に影響を与える進行性の脳疾患であるアルツハイマー病の治療法を見つけるために取り組んできました.この疾患は、脳細胞に損傷を与えて殺す異常なタンパク質が脳内に蓄積することによって引き起こされ、記憶喪失やその他の認知障害を引き起こします。現在、アルツハイマー病の治療法はありませんが、症状を管理し、患者の生活の質を改善するのに役立つ薬があります.最近、テキサス大学ダラス校の研究者が、治療法の探索において突破口を開いた可能性があります。 Science Advances 誌に掲載された研究で、研究チームはマウスの脳からアルツハイマー病の原因となる異常なタンパク質を取り除くことができたことを示しました。彼らは、老廃物やその他の有害物質の除去を担う脳内のミクログリア細胞を刺激するために超音波を使用することによってこれを行いました.研究者らは、超音波がミクログリアに異常なタンパク質を消費させ、脳内の蓄積を減少させることを発見しました。研究はまだ初期段階にあり、同じアプローチが人間で機能するかどうかを判断するには、さらに研究が必要です.しかし、結果は有望であり、アルツハイマー病の将来の治療法への道を開く可能性があります."
        },{
            ar: "In recent years, climate change has become an increasingly urgent issue. As global temperatures rise and extreme weather events become more frequent, it is clear that we need to take action to reduce our carbon footprint and prevent further damage to the planet. One solution that has gained popularity in recent years is renewable energy, which comes from sources that are naturally replenished and can be used without depleting finite resources.Renewable energy sources include solar, wind, and hydro power, as well as geothermal and biomass energy. These sources have many advantages over traditional fossil fuels, such as coal and oil. For example, they produce little to no emissions and are much less harmful to the environment. They also provide a sustainable and reliable source of energy, as they are not subject to the same price fluctuations and supply constraints as fossil fuels.Despite these advantages, renewable energy sources still face many challenges. For one, they are often more expensive to develop and implement than traditional energy sources. In addition, their effectiveness can be limited by factors such as weather patterns and geographic location. As a result, governments and private companies alike must invest in research and development to make renewable energy more efficient and cost-effective.",
            q: ["What is one reason why climate change has become an increasingly urgent issue in recent years?","What is renewable energy?","What are some examples of renewable energy sources?","What is one advantage of renewable energy sources over traditional fossil fuels?","What is one challenge that renewable energy sources face?",],
            q_sel:[[" Global temperatures are decreasing."," Extreme weather events are becoming less frequent."," The use of fossil fuels is declining."," Global temperatures are rising.",],[" Energy that is produced from fossil fuels."," Energy that is not subject to price fluctuations."," Energy that is naturally replenished and does not deplete finite resources."," Energy that produces large amounts of emissions.",],[" Coal and oil."," Natural gas and petroleum."," Solar, wind, and hydro power."," Nuclear and geothermal energy.",],[" Renewable energy sources are subject to price fluctuations."," Renewable energy sources are harmful to the environment."," Renewable energy sources are less expensive to develop and implement."," Renewable energy sources produce little to no emissions.",],[" They are often more expensive to develop and implement than traditional energy sources."," They produce large amounts of emissions."," They are subject to the same price fluctuations and supply constraints as fossil fuels."," They are not effective sources of energy.",],],
            q_ex: ["記事の冒頭で地球温暖化に言及しており、気候変動がますます深刻な問題になっていることを明確に指摘しているため、答えは D です。","この記事で言及されている再生可能エネルギーとは、自然に再生可能であり、限られた資源を枯渇させることなく使用できるエネルギー源を指すため、答えは C.","太陽光エネルギー、風力エネルギー、水力エネルギーなどのエネルギー源は、再生可能エネルギー源の例として記事に挙げられているので、答えは C.","この記事では、再生可能エネルギー源は石炭や石油などの従来の化石燃料よりも排出量が少ないと述べているため、答えは D.","この記事では、再生可能エネルギー源は一般に従来のエネルギー源よりも高価であるため、より効率的で費用対効果の高いものにするためには、より多くの研究開発が必要であると述べているため、答えは A.",],
            q_a: [" D"," C"," C"," D"," A",],
            zh: "近年、気候変動はますます差し迫った問題になっています。地球の気温が上昇し、極端な気象現象がより頻繁になるにつれて、二酸化炭素排出量を削減し、地球へのさらなる被害を防ぐために行動する必要があることは明らかです.近年普及しているソリューションの 1 つは再生可能エネルギーです。再生可能エネルギーは、自然に補充され、限りある資源を枯渇させることなく使用できます。再生可能エネルギーには、太陽光、風力、水力、地熱、バイオマスが含まれます。これらの資源には、石炭や石油などの従来の化石燃料よりも多くの利点があります。たとえば、排出物をほとんど排出せず、環境への害もはるかに少なくなります。また、化石燃料のように価格変動や供給制約を受けないため、持続可能で信頼できるエネルギー源を提供します。これらの利点にもかかわらず、再生可能エネルギーは依然として多くの課題に直面しています。一方では、従来のエネルギー源よりも開発と実装に費用がかかる傾向があります。さらに、その有効性は、天候パターンや地理的位置などの要因によって制限される場合があります。したがって、政府と民間企業の両方が、再生可能エネルギーの効率と費用対効果を改善するための研究開発に投資する必要があります。"
        },{
            ar: "In recent years, there has been growing concern about the impact of social media on mental health. While social media platforms have the potential to connect people from all over the world, they also have some negative effects. One study found that people who spend more than two hours a day on social media are more likely to experience feelings of social isolation and depression.One way that social media can contribute to mental health problems is through the comparison of oneself to others. Social media platforms often present idealized versions of people's lives, and users may feel pressure to conform to these unrealistic standards. This can lead to feelings of inadequacy and low self-esteem.Another way that social media can affect mental health is through the spread of misinformation. False information and rumors can spread rapidly on social media, leading to anxiety and confusion. In some cases, this can even lead to dangerous behavior or beliefs.Despite these negative effects, social media can also be a source of support and community for some people. It is important to use social media in a balanced and responsible way, and to be aware of the potential risks.",
            q: ["What is one concern about the impact of social media on mental health?","How can social media contribute to mental health problems?","What is one way that social media can lead to feelings of inadequacy and low self-esteem?",],
            q_sel:[[" Social media platforms can only connect people from certain parts of the world."," Social media platforms have no negative effects on mental health."," People who use social media are less likely to experience feelings of social isolation and depression."," People who spend more than two hours a day on social media are more likely to experience feelings of social isolation and depression.",],[" By presenting realistic versions of people's lives."," By providing users with accurate information."," By spreading rumors and misinformation."," By connecting people from all over the world.",],[" By providing users with support and community."," By presenting idealized versions of people's lives."," By spreading accurate information."," By connecting people from all over the world.",],],
            q_ex: ["この記事では、ソーシャル メディアに 1 日 2 時間以上費やす人は、社会的孤立感や抑うつ感を感じる可能性が高いと述べているため、答えは D です。","記事では、ソーシャル メディアが誤った情報や噂を広めることでメンタルヘルスに影響を与える可能性があると述べていたため、答えは C です。","この記事では、ソーシャル メディア プラットフォームは人々の生活の理想化されたバージョンを提供することが多く、ユーザーはこれらの非現実的な基準に準拠する必要があると感じる可能性があり、それが自尊心の低下や自尊心の低下につながる可能性があると述べています。したがって、答えは B です。",],
            q_a: [" D"," C"," B",],
            zh: "近年、ソーシャルメディアがメンタルヘルスに与える影響が懸念されています。ソーシャル メディア プラットフォームは、世界中の人々をつなぐ可能性を秘めていますが、いくつかの欠点もあります。ソーシャル メディアに 1 日 2 時間以上費やす人は、社会的孤立感や抑うつ感を経験する可能性が高いことが研究で明らかになりました。ソーシャル メディアがメンタルヘルスの問題に寄与する 1 つの方法は、他者との自己比較です。ソーシャル メディア プラットフォームは、多くの場合、人々の生活の理想化されたバージョンを提示し、ユーザーはこれらの非現実的な基準に従うようプレッシャーを感じる場合があります。これは、劣等感や劣等感につながる可能性があります。ソーシャル メディアがメンタルヘルスに影響を与えるもう 1 つの方法は、誤った情報を広めることです。ソーシャル メディアでは、誤った情報や噂が急速に広まり、不安や混乱を引き起こす可能性があります。場合によっては、これが危険な行動や信念につながることさえあります。これらの悪影響にもかかわらず、ソーシャル メディアはサポートやコミュニティの源にもなり得ます。バランスの取れた責任ある方法でソーシャル メディアを使用し、潜在的なリスクを認識しておくことが重要です。"
        },{
            ar: "As the world becomes more technologically advanced, people are becoming more and more reliant on electronic devices. While these devices can make life easier and more convenient in many ways, there are also downsides to this dependence.One issue is the effect of electronic devices on sleep. Studies have shown that the blue light emitted by screens can interfere with the production of melatonin, a hormone that helps regulate sleep. This can lead to difficulty falling asleep, as well as poor-quality sleep.Another issue is the impact of electronic devices on social interaction. Many people now spend a significant amount of time interacting with others through social media and messaging apps, rather than in-person communication. This can lead to feelings of loneliness and isolation, as well as a lack of important social skills.Despite these downsides, electronic devices are not going anywhere. It is important for individuals to recognize the potential negative effects of these devices and take steps to mitigate them, such as limiting screen time before bed and making an effort to engage in face-to-face communication with others.",
            q: ["What is the main topic of the passage?","What is one negative impact of electronic devices on sleep?","How can overuse of electronic devices affect social skills?","What is the author's main message?","What is one step individuals can take to mitigate the negative effects of electronic devices?",],
            q_sel:[[" The benefits of electronic devices"," The downsides of electronic devices"," The future of electronic devices"," The evolution of electronic devices",],[" Increased production of melatonin"," Improved sleep quality"," Interference with melatonin production"," Increased likelihood of dreaming",],[" It can improve social interaction"," It can lead to feelings of loneliness and isolation"," It can increase face-to-face communication"," It can enhance the ability to read social cues",],[" Electronic devices are all bad"," Electronic devices are all good"," Electronic devices have both benefits and downsides"," Electronic devices will eventually disappear",],[" Increase screen time before bed"," Avoid face-to-face communication"," Use electronic devices more frequently"," Limit screen time before bed",],],
            q_ex: ["記事の最初の段落では電子製品の利点について述べていますが、記事全体で電子製品の欠点について説明しているため、答えは B です。","記事の第 2 段落の説明によると、電化製品が放出する青色光はメラトニンの生成を妨げ、それによって睡眠に影響を与える可能性があるため、答えは C です。","記事の 3 番目のパラグラフでは、人々は現在、顔を合わせてコミュニケーションする代わりに、ソーシャル メディアやメッセージング アプリケーションを介して他者とやり取りすることに多くの時間を費やしており、これが孤独と孤立、そして重要なソーシャル スキルの欠如につながっていると述べています。答えは B です。","この記事では、電子製品の欠点に言及しましたが、電子製品の利点も指摘し、個人がこれらのデバイスの潜在的な悪影響を認識し、それらを軽減するための措置を講じる必要があることを強調したため、答えは C.","記事の最後の段落では、個人が電子製品の潜在的な悪影響を認識し、それらを軽減するための措置を講じることを推奨しています. 提案の1つは、就寝前に電子製品を使用する時間を制限することです, したがって、答えはDです. .",],
            q_a: [" B"," C"," B"," C"," D",],
            zh: "世界がますます技術的に進歩するにつれて、人々はますます電子機器に依存するようになっています。これらのデバイスは、多くの点で生活をより簡単かつ便利にすることができますが、この依存にはマイナス面もあります。懸念の 1 つは、電子機器が睡眠に及ぼす影響です。画面から発せられるブルーライトが、睡眠の調節を助けるホルモンであるメラトニンの生成を妨げる可能性があることが研究で示されています。これにより、入眠が困難になり、睡眠の質が低下する可能性があります。もう 1 つの問題は、電子機器が社会的相互作用に与える影響です。現在、多くの人が対面ではなく、ソーシャル メディアやメッセージ アプリを介して他者とやり取りすることに多くの時間を費やしています。これは、孤独感や孤立感につながるだけでなく、重要な社会的スキルの欠如につながる可能性があります.これらの欠点にもかかわらず、エレクトロニクスはどこにも行きません。個人は、これらのデバイスの潜在的な悪影響を認識し、就寝前のスクリーン時間を制限したり、他の人と顔を合わせてやり取りするように努めたりするなど、それらを軽減するための措置を講じる必要があります。"
        },{
            ar: "The human brain is incredibly complex, and there is still much that researchers do not understand about how it works. However, one thing that is clear is that the brain is highly adaptable and capable of change.Neuroplasticity is the term used to describe the brain's ability to reorganize itself in response to new experiences. This can involve creating new neural connections or strengthening existing ones. Neuroplasticity is thought to be a key factor in learning and memory, as well as in recovery from brain injuries.While the brain is capable of neuroplasticity throughout life, the extent to which it can change decreases with age. This means that young children are particularly adept at learning and adapting, while older adults may have more difficulty in these areas.However, there are things that individuals can do to promote neuroplasticity and enhance their brain's ability to adapt. Engaging in activities that are mentally stimulating, such as reading or solving puzzles, is one way to promote neuroplasticity. Physical exercise has also been shown to have a positive impact on brain function and neuroplasticity.",
            q: ["What is the main topic of the passage?","What is neuroplasticity?","How does neuroplasticity impact learning and memory?","What is one way to promote neuroplasticity?",],
            q_sel:[[" The complexity of the human brain"," The role of neuroplasticity in brain function"," The effects of aging on the brain"," The benefits of mental stimulation",],[" The brain's ability to change in response to new experiences"," The brain's ability to maintain the status quo"," The brain's inability to change with age"," The brain's resistance to new experiences",],[" It has no effect on learning and memory"," It makes learning and memory more difficult"," It is a key factor in learning and memory"," It only impacts memory, not learning",],[" Avoid mental stimulation"," Limit physical exercise"," Engage in mentally stimulating activities"," Only engage in physical exercise",],],
            q_ex: ["この記事は主に脳機能に対する神経可塑性の影響について話しているので、答えは B.","この記事の 2 番目の段落で述べたように、神経可塑性とは、新しい神経接続の構築や既存の神経接続の強化など、新しい経験に応じて脳が自らを再編成する能力であるため、答えは A です。","この記事では、神経可塑性が学習と記憶の重要な要素の 1 つだと述べているため、答えは C です。","この記事では、読書や問題解決などの精神を刺激する活動に従事することが、神経可塑性を促進する 1 つの方法であると述べているため、答えは C です。",],
            q_a: [" B"," A"," C"," C",],
            zh: "人間の脳は信じられないほど複雑で、研究者はその仕組みについてまだ多くを理解していません。しかし、1 つはっきりしていることは、脳は非常に適応性が高く、変化する能力があるということです。神経可塑性とは、新しい経験に反応して自分自身を再編成する脳の能力を説明するために使用される用語です。これには、新しい神経接続の作成または既存の神経接続の強化が含まれる場合があります。神経可塑性は、学習と記憶、および脳損傷からの回復における重要な要素と考えられています。脳は生涯を通じて神経可塑性ですが、年齢とともにその変化の程度は減少します。これは、年少の子供は学習と適応が特に得意であるのに対し、年長の大人はこれらの分野でより困難になる可能性があることを意味します.しかし、神経可塑性を促進し、脳の回復力を高めるために個人ができることがあります。読書やパズルを解くなど、精神を刺激する活動に従事することは、神経可塑性を促進する 1 つの方法です。身体活動は、脳機能と神経可塑性にプラスの影響を与えることも示されています。"
        },{
            ar: "Climate change is a pressing issue that has garnered significant attention in recent years. While there is still debate about the causes and extent of climate change, most scientists agree that it is largely driven by human activities, such as the burning of fossil fuels and deforestation.One of the consequences of climate change is rising sea levels. As temperatures continue to rise, glaciers and ice sheets are melting, causing water to flow into the oceans and contributing to sea level rise. This can have a devastating impact on coastal cities and communities, as well as on wildlife and ecosystems.Another consequence of climate change is extreme weather events, such as heat waves, droughts, and hurricanes. These events can lead to crop failures, water shortages, and infrastructure damage, among other things. They also pose a significant threat to human health and well-being.Addressing climate change requires a coordinated effort from individuals, governments, and businesses around the world. This may involve reducing greenhouse gas emissions, transitioning to renewable energy sources, and investing in technologies that can help mitigate the impacts of climate change.",
            q: ["What is the main topic of the passage?","What are some human activities that are contributing to climate change?","What is one consequence of rising temperatures?","What is one way to address climate change?","What is the author's opinion on climate change?",],
            q_sel:[[" The causes of climate change"," The impacts of climate change"," The debate about climate change"," The role of individuals in addressing climate change",],[" Eating meat and dairy products"," Planting trees and other vegetation"," Burning fossil fuels and deforestation"," Recycling and composting",],[" Decreasing sea levels"," Reduced crop yields"," Increased forest cover"," Improved wildlife habitats",],[" Increase greenhouse gas emissions"," Continue to rely on fossil fuels"," Transition to renewable energy sources"," Build more infrastructure in coastal areas",],[" It is not a significant issue"," It is entirely caused by human activities"," It is a topic of debate among scientists"," It requires a coordinated effort to address",],],
            q_ex: ["この記事は主に気候変動が環境、野生生物、人間社会に与える影響について話しているので、答えは B です。","記事では、気候変動は主に化石燃料の燃焼や森林伐採などの人間活動によって引き起こされていると述べているため、答えは C.","この記事は、気温が上昇し続けると、氷河と氷床が溶けて海に水が流れ込み、海面上昇に寄与し、沿岸の都市やコミュニティ、野生生物や生態系に壊滅的な影響を与える可能性があると述べています.なので答えはBです。","この記事では、気候変動に取り組むには、世界中の個人、政府、および企業の間で協調的な取り組みが必要であると述べています。これには、温室効果ガスの排出量の削減、再生可能エネルギー源への切り替え、気候変動の影響を緩和できる技術への投資が含まれる可能性があります。というわけで、答えはCです。","この記事の著者は、気候変動自体についての見解を表明するものではありませんが、気候変動と闘うには、世界中の個人、政府、および企業の間で協調的な取り組みが必要であることを強調しています。というわけで、答えはDです。",],
            q_a: [" B"," C"," B"," C"," D",],
            zh: "気候変動は、近年広く注目されている喫緊の課題です。気候変動の原因と範囲はまだ議論されていますが、ほとんどの科学者は、気候変動は主に化石燃料の燃焼や森林伐採などの人間の活動によって引き起こされていることに同意しています.気候変動の結果の 1 つは海面上昇です。気温が上昇し続けると、氷河と氷床が溶け、水が海に流れ込み、海面上昇の一因となります。これは、沿岸の都市やコミュニティ、野生生物や生態系に壊滅的な影響を与える可能性があります。気候変動のもう 1 つの影響は、熱波、干ばつ、ハリケーンなどの異常気象です。これらの出来事は、とりわけ、作物の不作、水不足、インフラストラクチャの損傷につながる可能性があります。それらはまた、人間の健康と幸福に大きな脅威をもたらします。気候変動に取り組むには、世界中の個人、政府、企業による協調的な取り組みが必要です。これには、温室効果ガス排出量の削減、再生可能エネルギー源への切り替え、気候変動の影響を緩和するのに役立つ技術への投資が含まれる可能性があります。"
        },{
            ar: "The concept of climate change has become an increasingly pressing issue in recent years. Climate change refers to the long-term changes in Earth's climate, including changes in temperature, precipitation, and wind patterns, among others. While natural factors such as volcanic activity and solar radiation can contribute to climate change, the overwhelming scientific consensus is that human activities, particularly the burning of fossil fuels, are the primary cause of the current trend.The consequences of climate change are vast and far-reaching. Rising temperatures can lead to extreme weather events such as hurricanes, floods, and droughts, which in turn can cause significant damage to infrastructure, property, and crops. Melting ice caps and rising sea levels can lead to the displacement of communities living in low-lying coastal areas. Climate change can also have negative impacts on public health, such as the spread of diseases and the exacerbation of existing health conditions.In response to the threat of climate change, many countries have taken action to reduce their greenhouse gas emissions and transition to more sustainable forms of energy. These efforts include investing in renewable energy sources such as wind and solar power, improving energy efficiency, and promoting public transportation and electric vehicles. While much remains to be done to address the challenges of climate change, there is reason for hope as countries and individuals work towards a more sustainable future.",
            q: ["What is climate change?","What is the primary cause of climate change, according to the scientific consensus?","What are some consequences of climate change?","What are some ways countries have responded to the threat of climate change?","What is the author's attitude towards the future of addressing climate change?",],
            q_sel:[[" Changes in temperature only"," Changes in temperature and precipitation only"," Changes in temperature, precipitation, and wind patterns, among others"," Changes in wind patterns only",],[" Volcanic activity"," Solar radiation"," Human activities, particularly the burning of fossil fuels"," A combination of natural and human factors",],[" Improved public health"," Decreased frequency of extreme weather events"," Damage to infrastructure, property, and crops due to extreme weather events"," Increased availability of natural resources",],[" Increasing the burning of fossil fuels"," Investingin renewable energy sources"," Encouraging the use of single-use plastics"," Decreasing public transportation options",],[" Pessimistic"," Optimistic"," Ambivalent"," Uncertain",],],
            q_ex: ["この記事は、気候変動には、気温、降水量、風の変化など、多くの側面で長期的な変化が含まれていることを示しています。したがって、答えはCです。","この記事は、火山活動や太陽放射などの自然要因も気候変動に寄与しているが、圧倒的な科学的コンセンサスは、人間の活動、特に化石燃料の燃焼が現在の気候変動の主な原因であることを指摘しています.したがって、答えはCです。","この記事は、ハリケーン、洪水、干ばつなどの極端な気象現象を含め、気候変動の影響が広範かつ広範囲に及んでおり、インフラストラクチャ、財産、作物に大きな損害を与える可能性があると述べています。したがって、答えはCです。","この記事では、多くの国が気候変動の脅威に対応して、再生可能エネルギーへの投資、エネルギー効率の改善、公共交通機関や電気自動車の利用促進などの行動を起こしていると述べています。したがって、答えはBです。","この記事は、気候変動に対処するという課題が残っているものの、国や個人がより持続可能な未来に向けて取り組むことには希望があると述べています。これは、著者が気候変動との戦いの将来について楽観的であることを示唆しています。したがって、答えはBです。",],
            q_a: [" C"," C"," C"," B"," B",],
            zh: "近年、気候変動の概念はますます差し迫った問題になっています。気候変動とは、気温、降水量、風のパターンの変化など、地球の気候の長期的な変化を指します。火山活動や太陽放射などの自然要因が気候変動の一因となっている一方で、圧倒的な科学的コンセンサスは、人間の活動、特に化石燃料の燃焼が現在の傾向の主な原因であるということです。気候変動の影響は広大で広範囲に及びます。気温の上昇は、ハリケーン、洪水、干ばつなどの異常気象につながる可能性があり、インフラストラクチャ、財産、作物に重大な損害を与える可能性があります。氷床が溶けて海面が上昇すると、低地の沿岸地域に住むコミュニティが移動する可能性があります。気候変動はまた、病気の蔓延や既存の健康状態の悪化など、公衆衛生に悪影響を及ぼす可能性があります。気候変動の脅威に対応して、多くの国が温室効果ガスの排出を削減し、より持続可能な形のエネルギーに移行するための行動を起こしています。これらの取り組みには、風力や太陽光などの再生可能エネルギー源への投資、エネルギー効率の改善、公共交通機関や電気自動車の促進が含まれます。気候変動の課題に対処するためにやるべきことはまだたくさんありますが、国や個人がより持続可能な未来に向けて取り組む中で、希望を持てる理由があります。"
        },{
            ar: "The Importance of SleepWe all know that getting a good night's sleep is important, but many of us still don't get enough sleep on a regular basis. In fact, studies have shown that more than one-third of American adults do not get the recommended seven hours of sleep each night.Lack of sleep can have a variety of negative effects on both our physical and mental health. For example, it can increase the risk of developing chronic health conditions such as obesity, diabetes, and cardiovascular disease. It can also impair our immune system, making us more susceptible to illnesses.In addition to these physical health effects, lack of sleep can also affect our mental health. It can lead to problems with mood regulation, making us more irritable, anxious, and depressed. It can also impair cognitive function, making it harder to concentrate, learn, and remember things.So how can we improve our sleep habits? Here are some tips:Stick to a regular sleep schedule. Go to bed and wake up at the same time every day, even on weekends.Create a relaxing sleep environment. Keep your bedroom dark, quiet, and cool, and avoid using electronic devices before bed.Avoid caffeine, nicotine, and alcohol before bedtime, as they can disrupt your sleep.Get regular exercise, but avoid exercising too close to bedtime.If you have trouble sleeping, try relaxation techniques such as deep breathing or meditation, or consider talking to a healthcare professional about sleep aids.",
            q: ["What is the main idea of the passage?","According to the passage, what are some physical health effects of lack of sleep?","What is the author's advice for creating a relaxing sleep environment?","According to the passage, what is one potential consequence of impaired cognitive function due to lack of sleep?","What is the author's advice for improving sleep habits?",],
            q_sel:[[" Lack of sleep can have negative effects on physical health."," Lack of sleep can have negative effects on mental health."," Lack of sleep is a problem for many Americans."," Getting a good night's sleep is important.",],[" Increased risk of developing depression."," Impaired cognitive function."," Increased risk of developing cardiovascular disease."," Difficulty concentrating.",],[" Use electronic devices before bed."," Keep the bedroom warm and bright."," Avoid noise in the bedroom."," Keep the bedroom cool and dark.",],[" Increased risk of developing obesity."," Difficulty concentrating and learning."," Higher susceptibility to illnesses."," Problems with mood regulation.",],[" Drink alcohol before bedtime."," Exercise right before going to bed."," Stick to a regular sleep schedule."," Use electronic devices in bed.",],],
            q_ex: ["記事の冒頭で睡眠の重要性について言及されており、以下のコンテンツでも睡眠の利点と睡眠習慣の改善方法が強調されています。したがって、答えはDです。","この記事では、睡眠不足は肥満、糖尿病、心血管疾患などの慢性疾患のリスクを高める可能性があると述べています.したがって、答えはCです。","この記事では、寝室を涼しく暗く保ち、就寝前に電子機器を避けるなど、リラックスできる睡眠環境を作るためのヒントに言及しています。したがって、答えはDです。","この記事では、睡眠不足が認知機能に与える影響について言及しており、集中、学習、記憶が困難になる可能性があります.したがって、答えはBです。","この記事では、定期的な睡眠スケジュールを維持すること、就寝前の夜のカフェイン、ニコチン、アルコールを避けること、就寝前の電子機器を避けることなど、睡眠習慣を改善するための提案に言及しています.したがって、答えはCです。",],
            q_a: [" D"," C"," D"," B"," C",],
            zh: "睡眠の重要性 夜ぐっすり眠ることが重要であることは誰もが知っていますが、それでも私たちの多くは定期的に十分な睡眠をとっていません。実際、調査によると、アメリカの成人の 3 分の 1 以上が毎晩推奨される 7 時間の睡眠をとっていません。睡眠不足は、私たちの身体的および精神的健康にさまざまな悪影響を及ぼす可能性があります。たとえば、肥満、糖尿病、心血管疾患などの慢性疾患のリスクを高めます。また、免疫システムに損傷を与える可能性があり、病気になりやすくなります.これらの身体的健康への影響に加えて、睡眠不足は私たちの精神的健康にも影響を与える可能性があります.感情の調節に問題が生じ、いらいらしたり、不安になったり、落ち込んだりします。また、認知機能を損なう可能性があり、集中、学習、記憶が困難になります。では、どうすれば睡眠習慣を改善できるのでしょうか。いくつかのヒントを次に示します。 規則正しい睡眠スケジュールを守りましょう。週末でも、毎日同じ時間に就寝し、同じ時間に起床してください。リラックスできる睡眠環境を作りましょう。寝室を暗く、静かで涼しく保ち、就寝前の電子機器の使用は避けてください。就寝前のカフェイン、ニコチン、アルコールは睡眠を妨げる可能性があるため避けてください。定期的に運動しますが、就寝直前の運動は避けてください。睡眠に問題がある場合は、深呼吸や瞑想などのリラクゼーション法を試すか、医療専門家と睡眠補助薬について話し合うことを検討してください."
        },{
            ar: "In recent years, there has been a growing interest in plant-based diets. Advocates of these diets argue that they are healthier for both people and the planet. But are plant-based diets really better? Let's take a closer look.One of the main benefits of plant-based diets is that they tend to be lower in saturated fats and higher in fiber, vitamins, and minerals. This can help reduce the risk of heart disease, stroke, and certain types of cancer. Plant-based diets have also been shown to be effective for weight loss and improving overall health.However, some people worry that plant-based diets might not provide all of the necessary nutrients, especially for people who are pregnant, breastfeeding, or have certain health conditions. For example, plant-based diets may not provide enough protein, calcium, or vitamin B12.Another concern is that some plant-based foods, such as soy and nuts, can be allergenic and cause reactions in some people. Additionally, some plant-based diets may not be sustainable in the long-term due to the large amounts of water and other resources needed to produce certain crops.Overall, plant-based diets can be a healthy and sustainable choice for many people. However, it's important to ensure that you are getting all of the necessary nutrients, and to speak with a healthcare professional before making any major dietary changes.",
            q: ["What is the main benefit of plant-based diets according to the passage?","According to the passage, what is a potential concern with plant-based diets?","What is the author's advice regarding plant-based diets?","According to the passage, why might some plant-based diets not be sustainable in the long-term?","What is the author's main purpose in writing this passage?",],
            q_sel:[[" They are lower in fiber and higher in saturated fats."," They can increase the risk of heart disease and stroke."," They can help reduce the risk of certain types of cancer."," They are less effective for weight loss than other diets.",],[" They may not provide enough protein, calcium, or vitamin B12."," They may cause allergic reactions in some people."," They may not be effective for weight loss."," They require more resources to produce than other diets.",],[" Everyone should switch to a plant-based diet immediately."," Plant-based diets are not sustainable in the long-term."," It is important to make sure you are getting all necessary nutrients."," Healthcare professionals do not need to be consulted before making dietary changes.",],[" They require too much time and effort to prepare."," They can cause allergic reactions in some people."," They are less effective for weight loss than other diets."," They require large amounts of water and resources to produce certain crops.",],[" To promote the benefits of a plant-based diet."," To provide a comprehensive guide to different types of diets."," To caution readers about the potential risks and drawbacks of plant-based diets."," To criticize the medical establishment for failing to promote plant-based diets.",],],
            q_ex: ["この記事では、プラントベースの食事は、一般的に飽和脂肪が少なく、繊維、ビタミン、ミネラルが多いため、心臓病、脳卒中、および特定の癌のリスクを軽減するという利点があると述べています.したがって、答えはCです。","この記事では、特に妊娠中、授乳中、または特定の健康状態に苦しんでいる場合、植物ベースの食事が必要な栄養素をすべて提供しない可能性があるという一部の人々の懸念に言及しています.たとえば、植物ベースの食事では、十分なタンパク質、カルシウム、またはビタミン B12 が提供されない場合があります。したがって、答えはAです。","この記事では、植物ベースの食事を選択する場合は、必要な栄養素をすべて摂取していることを確認する必要があり、大幅な食事の変更を行う前に医療専門家に相談する必要があると述べています.したがって、答えはCです。","この記事では、特定の作物を生産するために大量の水やその他の資源が必要なため、一部の植物ベースの食事は長期的に持続可能ではない可能性があると述べています.したがって、答えはDです。","この記事を通じて、著者の主な目的は、植物ベースの食事に潜在的なリスクとマイナス面があることを読者に警告し、バランスの取れた食事を維持し、医療専門家に相談することの重要性を強調することです.したがって、答えはCです。",],
            q_a: [" C"," A"," C"," D"," C",],
            zh: "近年、植物ベースの食事への関心が高まっています。これらの食事の支持者は、それらが人々と地球にとってより健康的であると主張しています.しかし、植物ベースの食事は本当に良いのでしょうか?詳しく見てみましょう。プラントベースの食事の主な利点の 1 つは、飽和脂肪が少なく、繊維、ビタミン、ミネラルが多い傾向があることです。これは、心臓病、脳卒中、および特定の種類の癌のリスクを軽減するのに役立ちます.プラントベースの食事は、体重を減らし、全体的な健康を改善するのにも効果的であることが示されています.しかし、一部の人々は、特に妊娠中、授乳中、または特定の病状を持っている人にとって、植物ベースの食事が必要な栄養素をすべて提供しない可能性があることを心配しています.たとえば、植物ベースの食事では、十分なタンパク質、カルシウム、またはビタミン B12 が提供されない場合があります。もう1つの懸念は、大豆やナッツなどの一部の植物性食品がアレルギーを引き起こし、一部の人に反応を引き起こす可能性があることです.さらに、一部の植物ベースの食事は、特定の作物を生産するために大量の水やその他の資源が必要なため、長期的に持続可能ではない場合があります.全体として、プラントベースの食事は、多くの人にとって健康的で持続可能な選択です。ただし、必要な栄養素をすべて摂取していることを確認し、大幅な食事の変更を行う前に医療専門家に相談することが重要です."
        },{
            ar: "It’s a common misconception that introverts are shy, antisocial individuals who don’t enjoy socializing. While introverts may not seek out constant social stimulation like their extroverted counterparts, they do enjoy social interaction, albeit in smaller doses.In fact, introverts can be just as social as extroverts, but they simply need more time to recharge after socializing. This is because introverts are more sensitive to external stimuli and tend to be more easily overwhelmed by excessive socializing or sensory input.Introverts also tend to be more reflective and introspective than extroverts, and may prefer to spend time alone with their thoughts rather than engaging in constant external stimulation. This can be mistaken for shyness or aloofness, but in reality, introverts are simply processing and reflecting on their experiences in a deeper way.Despite the common misconception that introverts are at a disadvantage in social situations, introverts can actually be very effective communicators. They tend to be more thoughtful and deliberate in their speech, taking the time to carefully choose their words and express their ideas in a clear and concise manner.Overall, introversion is simply a personality trait that reflects a preference for solitude and introspection, rather than a social deficit or inability to communicate effectively.",
            q: ["According to the passage, what is a common misconception about introverts?","What does the passage suggest about the difference between introverts and extroverts?","What is the main difference between introverts and extroverts in terms of socializing, according to the passage?",],
            q_sel:[[" They are more easily overwhelmed by external stimuli."," They do not enjoy socializing."," They are less effective communicators than extroverts."," They are more reflective and introspective than extroverts.",],[" Introverts need more time to recharge after socializing."," Extroverts are more easily overwhelmed by external stimuli."," Introverts are less thoughtful and deliberate in their speech."," Extroverts are more reflective and introspective than introverts.",],[" Introverts enjoy socializing more than extroverts."," Extroverts need more time to recharge after socializing."," Introverts are more easily overwhelmed by socializing."," There is no difference between introverts and extroverts in terms of socializing.",],],
            q_ex: ["この記事は、内向的な人が社交を好まないという一般的な誤解に言及することから始まりました。したがって、答えはBです。","この記事によると、外向的な人に比べて、内向的な人は充電して社会的相互作用の影響に対処するためにより多くの時間を必要とします。したがって、答えはAです。","この記事によると、内向的な人は外向的な人よりも過剰な社会的または感覚的刺激に圧倒される可能性が高いため、社会活動に従事するときに不快に感じる可能性が高くなります.したがって、答えはCです。",],
            q_a: [" B"," A"," C",],
            zh: "よくある誤解は、内向的な人は恥ずかしがり屋で反社会的で、社交を好まないというものです。内向的な人は、外向的な人のように一定の社会的刺激を求めないかもしれませんが、程度は低いものの、社会的相互作用を楽しんでいます。実際、内向的な人は外向的な人と同じように社交することができますが、社交の後に再充電する時間が必要です.これは、内向的な人は外部からの刺激に対してより敏感であり、過度の社会的または感覚的な入力に圧倒される可能性が高いためです.内向的な人はまた、外向的な人よりも内省的で内省的である傾向があり、絶え間ない外部刺激に参加するよりも、一人で考えることに時間を費やすことを好むかもしれません.これは恥ずかしがりやよそよそしさと誤解される可能性がありますが、実際には、内向的な人は自分の経験をより深いレベルで処理し、反映しているだけです。内向的な人は社会的状況において不利な立場にあるという一般的な誤解にもかかわらず、内向的な人は実際には非常に効果的なコミュニケーションをとることができます.慎重に話す傾向があり、時間をかけて慎重に言葉を選び、自分の考えを明確かつ簡潔に表現します。一般に、内向性は、社会的欠陥や効果的なコミュニケーションの欠如ではなく、孤独と内省の好みを反映する単なる性格特性です."
        },{
            ar: "As the world becomes more technologically advanced, people are becoming more and more reliant on electronic devices. While these devices can make life easier and more convenient in many ways, there are also downsides to this dependence.One issue is the effect of electronic devices on sleep. Studies have shown that the blue light emitted by screens can interfere with the production of melatonin, a hormone that helps regulate sleep. This can lead to difficulty falling asleep, as well as poor-quality sleep.Another issue is the impact of electronic devices on social interaction. Many people now spend a significant amount of time interacting with others through social media and messaging apps, rather than in-person communication. This can lead to feelings of loneliness and isolation, as well as a lack of important social skills.Despite these downsides, electronic devices are not going anywhere. It is important for individuals to recognize the potential negative effects of these devices and take steps to mitigate them, such as limiting screen time before bed and making an effort to engage in face-to-face communication with others.",
            q: ["What is the main topic of the passage?","What is one negative impact of electronic devices on sleep?","How can overuse of electronic devices affect social skills?","What is the author's main message?","What is one step individuals can take to mitigate the negative effects of electronic devices?",],
            q_sel:[[" The benefits of electronic devices"," The downsides of electronic devices"," The future of electronic devices"," The evolution of electronic devices",],[" Increased production of melatonin"," Improved sleep quality"," Interference with melatonin production"," Increased likelihood of dreaming",],[" It can improve social interaction"," It can lead to feelings of loneliness and isolation"," It can increase face-to-face communication"," It can enhance the ability to read social cues",],[" Electronic devices are all bad"," Electronic devices are all good"," Electronic devices have both benefits and downsides"," Electronic devices will eventually disappear",],[" Increase screen time before bed"," Avoid face-to-face communication"," Use electronic devices more frequently"," Limit screen time before bed",],],
            q_ex: ["記事の最初の段落では電子製品の利点について述べていますが、記事全体で電子製品の欠点について説明しているため、答えは B です。","記事の第 2 段落の説明によると、電化製品が放出する青色光はメラトニンの生成を妨げ、それによって睡眠に影響を与える可能性があるため、答えは C です。","記事の 3 番目のパラグラフでは、人々は現在、顔を合わせてコミュニケーションする代わりに、ソーシャル メディアやメッセージング アプリケーションを介して他者とやり取りすることに多くの時間を費やしており、これが孤独と孤立、そして重要なソーシャル スキルの欠如につながっていると述べています。答えは B です。","この記事では、電子製品の欠点に言及しましたが、電子製品の利点も指摘し、個人がこれらのデバイスの潜在的な悪影響を認識し、それらを軽減するための措置を講じる必要があることを強調したため、答えは C.","記事の最後の段落では、個人が電子製品の潜在的な悪影響を認識し、それらを軽減するための措置を講じることを推奨しています. 提案の1つは、就寝前に電子製品を使用する時間を制限することです, したがって、答えはDです. .",],
            q_a: [" B"," C"," B"," C"," D",],
            zh: "世界がますます技術的に進歩するにつれて、人々はますます電子機器に依存するようになっています。これらのデバイスは、多くの点で生活をより簡単かつ便利にすることができますが、この依存にはマイナス面もあります。懸念の 1 つは、電子機器が睡眠に及ぼす影響です。画面から発せられるブルーライトが、睡眠の調節を助けるホルモンであるメラトニンの生成を妨げる可能性があることが研究で示されています。これにより、入眠が困難になり、睡眠の質が低下する可能性があります。もう 1 つの問題は、電子機器が社会的相互作用に与える影響です。現在、多くの人が対面ではなく、ソーシャル メディアやメッセージ アプリを介して他者とやり取りすることに多くの時間を費やしています。これは、孤独感や孤立感につながるだけでなく、重要な社会的スキルの欠如につながる可能性があります.これらの欠点にもかかわらず、エレクトロニクスはどこにも行きません。個人は、これらのデバイスの潜在的な悪影響を認識し、就寝前のスクリーン時間を制限したり、他の人と顔を合わせてやり取りするように努めたりするなど、それらを軽減するための措置を講じる必要があります。"
        },{
            ar: "The human brain is incredibly complex, and there is still much that researchers do not understand about how it works. However, one thing that is clear is that the brain is highly adaptable and capable of change.Neuroplasticity is the term used to describe the brain's ability to reorganize itself in response to new experiences. This can involve creating new neural connections or strengthening existing ones. Neuroplasticity is thought to be a key factor in learning and memory, as well as in recovery from brain injuries.While the brain is capable of neuroplasticity throughout life, the extent to which it can change decreases with age. This means that young children are particularly adept at learning and adapting, while older adults may have more difficulty in these areas.However, there are things that individuals can do to promote neuroplasticity and enhance their brain's ability to adapt. Engaging in activities that are mentally stimulating, such as reading or solving puzzles, is one way to promote neuroplasticity. Physical exercise has also been shown to have a positive impact on brain function and neuroplasticity.",
            q: ["What is the main topic of the passage?","What is neuroplasticity?","How does neuroplasticity impact learning and memory?","What is one way to promote neuroplasticity?",],
            q_sel:[[" The complexity of the human brain"," The role of neuroplasticity in brain function"," The effects of aging on the brain"," The benefits of mental stimulation",],[" The brain's ability to change in response to new experiences"," The brain's ability to maintain the status quo"," The brain's inability to change with age"," The brain's resistance to new experiences",],[" It has no effect on learning and memory"," It makes learning and memory more difficult"," It is a key factor in learning and memory"," It only impacts memory, not learning",],[" Avoid mental stimulation"," Limit physical exercise"," Engage in mentally stimulating activities"," Only engage in physical exercise",],],
            q_ex: ["この記事は主に脳機能に対する神経可塑性の影響について話しているので、答えは B.","この記事の 2 番目の段落で述べたように、神経可塑性とは、新しい神経接続の構築や既存の神経接続の強化など、新しい経験に応じて脳が自らを再編成する能力であるため、答えは A です。","この記事では、神経可塑性が学習と記憶の重要な要素の 1 つだと述べているため、答えは C です。","この記事では、読書や問題解決などの精神を刺激する活動に従事することが、神経可塑性を促進する 1 つの方法であると述べているため、答えは C です。",],
            q_a: [" B"," A"," C"," C",],
            zh: "人間の脳は信じられないほど複雑で、研究者はその仕組みについてまだ多くを理解していません。しかし、1 つはっきりしていることは、脳は非常に適応性が高く、変化する能力があるということです。神経可塑性とは、新しい経験に反応して自分自身を再編成する脳の能力を説明するために使用される用語です。これには、新しい神経接続の作成または既存の神経接続の強化が含まれる場合があります。神経可塑性は、学習と記憶、および脳損傷からの回復における重要な要素と考えられています。脳は生涯を通じて神経可塑性ですが、年齢とともにその変化の程度は減少します。これは、年少の子供は学習と適応が特に得意であるのに対し、年長の大人はこれらの分野でより困難になる可能性があることを意味します.しかし、神経可塑性を促進し、脳の回復力を高めるために個人ができることがあります。読書やパズルを解くなど、精神を刺激する活動に従事することは、神経可塑性を促進する 1 つの方法です。身体活動は、脳機能と神経可塑性にプラスの影響を与えることも示されています。"
        },{
            ar: "Climate change is a pressing issue that has garnered significant attention in recent years. While there is still debate about the causes and extent of climate change, most scientists agree that it is largely driven by human activities, such as the burning of fossil fuels and deforestation.One of the consequences of climate change is rising sea levels. As temperatures continue to rise, glaciers and ice sheets are melting, causing water to flow into the oceans and contributing to sea level rise. This can have a devastating impact on coastal cities and communities, as well as on wildlife and ecosystems.Another consequence of climate change is extreme weather events, such as heat waves, droughts, and hurricanes. These events can lead to crop failures, water shortages, and infrastructure damage, among other things. They also pose a significant threat to human health and well-being.Addressing climate change requires a coordinated effort from individuals, governments, and businesses around the world. This may involve reducing greenhouse gas emissions, transitioning to renewable energy sources, and investing in technologies that can help mitigate the impacts of climate change.",
            q: ["What is the main topic of the passage?","What are some human activities that are contributing to climate change?","What is one consequence of rising temperatures?","What is one way to address climate change?","What is the author's opinion on climate change?",],
            q_sel:[[" The causes of climate change"," The impacts of climate change"," The debate about climate change"," The role of individuals in addressing climate change",],[" Eating meat and dairy products"," Planting trees and other vegetation"," Burning fossil fuels and deforestation"," Recycling and composting",],[" Decreasing sea levels"," Reduced crop yields"," Increased forest cover"," Improved wildlife habitats",],[" Increase greenhouse gas emissions"," Continue to rely on fossil fuels"," Transition to renewable energy sources"," Build more infrastructure in coastal areas",],[" It is not a significant issue"," It is entirely caused by human activities"," It is a topic of debate among scientists"," It requires a coordinated effort to address",],],
            q_ex: ["この記事は主に気候変動が環境、野生生物、人間社会に与える影響について話しているので、答えは B です。","記事では、気候変動は主に化石燃料の燃焼や森林伐採などの人間活動によって引き起こされていると述べているため、答えは C.","この記事は、気温が上昇し続けると、氷河と氷床が溶けて海に水が流れ込み、海面上昇に寄与し、沿岸の都市やコミュニティ、野生生物や生態系に壊滅的な影響を与える可能性があると述べています.なので答えはBです。","この記事では、気候変動に取り組むには、世界中の個人、政府、および企業の間で協調的な取り組みが必要であると述べています。これには、温室効果ガスの排出量の削減、再生可能エネルギー源への切り替え、気候変動の影響を緩和できる技術への投資が含まれる可能性があります。というわけで、答えはCです。","この記事の著者は、気候変動自体についての見解を表明するものではありませんが、気候変動と闘うには、世界中の個人、政府、および企業の間で協調的な取り組みが必要であることを強調しています。というわけで、答えはDです。",],
            q_a: [" B"," C"," B"," C"," D",],
            zh: "気候変動は、近年広く注目されている喫緊の課題です。気候変動の原因と範囲はまだ議論されていますが、ほとんどの科学者は、気候変動は主に化石燃料の燃焼や森林伐採などの人間の活動によって引き起こされていることに同意しています.気候変動の結果の 1 つは海面上昇です。気温が上昇し続けると、氷河と氷床が溶け、水が海に流れ込み、海面上昇の一因となります。これは、沿岸の都市やコミュニティ、野生生物や生態系に壊滅的な影響を与える可能性があります。気候変動のもう 1 つの影響は、熱波、干ばつ、ハリケーンなどの異常気象です。これらの出来事は、とりわけ、作物の不作、水不足、インフラストラクチャの損傷につながる可能性があります。それらはまた、人間の健康と幸福に大きな脅威をもたらします。気候変動に取り組むには、世界中の個人、政府、企業による協調的な取り組みが必要です。これには、温室効果ガス排出量の削減、再生可能エネルギー源への切り替え、気候変動の影響を緩和するのに役立つ技術への投資が含まれる可能性があります。"
        },{
            ar: "In recent years, social media has become an integral part of many people's lives. Social media platforms such as Facebook, Twitter, and Instagram allow individuals to connect with others, share information and opinions, and stay up-to-date with the latest news and trends.While social media has many benefits, there are also concerns about its impact on mental health. Studies have found that excessive social media use can lead to feelings of loneliness, anxiety, and depression. This is partly due to the fact that social media often presents an idealized version of reality, which can lead to feelings of inadequacy and low self-esteem.Another concern is the spread of misinformation and fake news on social media. With the ability for anyone to publish and share information, it can be difficult to distinguish between fact and fiction. This can lead to confusion, anxiety, and even harm if individuals make decisions based on false information.Despite these concerns, social media remains a popular and influential medium. As such, it is important for individuals to use social media responsibly and critically evaluate the information they encounter online.",
            q: ["What is the main topic of the passage?","What are some negative impacts of excessive social media use?","What is one concern about the spread of information on social media?","What is one way to use social media responsibly?","What is the author's overall attitude towards social media?",],
            q_sel:[[" The benefits of social media"," The impact of social media on mental health"," The spread of misinformation on social media"," The popularity of social media",],[" Improved self-esteem and mental well-being"," Increased feelings of connectedness and social support"," Feelings of loneliness, anxiety, and depression"," Improved ability to distinguish between fact and fiction",],[" The lack of access to information"," The inability to connect with others"," The spread of misinformation and fake news"," The cost of using social media",],[" Post without considering the impact on others"," Share all information encountered online"," Critically evaluate information encountered online"," Spend excessive amounts",],[" Positive"," Negative"," Neutral"," Ambivalent",],],
            q_ex: ["この記事では主に、ソーシャル メディアがメンタルヘルスに与える影響について述べ、ソーシャル メディアの利点と懸念事項に言及し、ソーシャル メディアの使用の責任を強調しています。なので答えはBです。","この記事では、ソーシャル メディアの過度の使用は、孤独、不安、抑うつなどの否定的な感情につながる可能性があると述べています。これは、ソーシャル メディアが現実の理想化されたバージョンを提示することが多く、自尊心や自尊心の欠如につながる可能性があるためです。 -価値。というわけで、答えはCです。","この記事は、個人が誤った情報に基づいて決定を下すと、ソーシャル メディア上の誤解やフェイク ニュースが混乱、不安、さらには害をもたらす可能性があると述べています。というわけで、答えはCです。","この記事では、ソーシャル メディアを使用する責任と、個人がオンラインで遭遇する情報を批判的に評価する必要があることを強調しています。したがって、答えはCです。","この記事では、著者はソーシャル メディアの利点と懸念事項に言及し、ソーシャル メディアの使用の責任を強調しています。したがって、著者の態度は、肯定的な見方と懸念の両方で、相反するものです。というわけで、答えはDです。",],
            q_a: [" B"," C"," C"," C"," D",],
            zh: "近年、ソーシャルメディアは多くの人々の生活に欠かせないものになっています。 Facebook、Twitter、Instagram などのソーシャル メディア プラットフォームを使用すると、個人が他のユーザーとつながり、情報や意見を共有し、最新のニュースやトレンドに遅れないようにすることができます。ソーシャル メディアには多くの利点がありますが、メンタルヘルスへの影響についても懸念があります。調査によると、ソーシャル メディアの過度の使用は、孤独感、不安感、抑うつ感につながる可能性があります。これは、ソーシャルメディアが現実の理想化されたバージョンを提示することが多く、劣等感や劣等感につながる可能性があるためです.もう1つの懸念は、ソーシャルメディアでの誤った情報やフェイクニュースの拡散です。誰でも情報を公開して共有できるため、事実とフィクションを区別するのは難しい場合があります。個人が誤った情報に基づいて決定を下すと、混乱、不安、さらには害につながる可能性があります。こうした懸念にもかかわらず、ソーシャル メディアは依然として人気があり、影響力のあるメディアです。したがって、個人が責任を持ってソーシャル メディアを使用し、オンラインで遭遇する情報を批判的に評価することが重要です。"
        },{
            ar: "The concept of climate change has become an increasingly pressing issue in recent years. Climate change refers to the long-term changes in Earth's climate, including changes in temperature, precipitation, and wind patterns, among others. While natural factors such as volcanic activity and solar radiation can contribute to climate change, the overwhelming scientific consensus is that human activities, particularly the burning of fossil fuels, are the primary cause of the current trend.The consequences of climate change are vast and far-reaching. Rising temperatures can lead to extreme weather events such as hurricanes, floods, and droughts, which in turn can cause significant damage to infrastructure, property, and crops. Melting ice caps and rising sea levels can lead to the displacement of communities living in low-lying coastal areas. Climate change can also have negative impacts on public health, such as the spread of diseases and the exacerbation of existing health conditions.In response to the threat of climate change, many countries have taken action to reduce their greenhouse gas emissions and transition to more sustainable forms of energy. These efforts include investing in renewable energy sources such as wind and solar power, improving energy efficiency, and promoting public transportation and electric vehicles. While much remains to be done to address the challenges of climate change, there is reason for hope as countries and individuals work towards a more sustainable future.",
            q: ["What is climate change?","What is the primary cause of climate change, according to the scientific consensus?","What are some consequences of climate change?","What are some ways countries have responded to the threat of climate change?","What is the author's attitude towards the future of addressing climate change?",],
            q_sel:[[" Changes in temperature only"," Changes in temperature and precipitation only"," Changes in temperature, precipitation, and wind patterns, among others"," Changes in wind patterns only",],[" Volcanic activity"," Solar radiation"," Human activities, particularly the burning of fossil fuels"," A combination of natural and human factors",],[" Improved public health"," Decreased frequency of extreme weather events"," Damage to infrastructure, property, and crops due to extreme weather events"," Increased availability of natural resources",],[" Increasing the burning of fossil fuels"," Investing in renewable energy sources"," Encouraging the use of single-use plastics"," Decreasing public transportation options",],[" Pessimistic"," Optimistic"," Ambivalent"," Uncertain",],],
            q_ex: ["この記事は、気候変動には、気温、降水量、風の変化など、多くの側面で長期的な変化が含まれていることを示しています。したがって、答えはCです。","この記事は、火山活動や太陽放射などの自然要因も気候変動に寄与しているが、圧倒的な科学的コンセンサスは、人間の活動、特に化石燃料の燃焼が現在の気候変動の主な原因であることを指摘しています.したがって、答えはCです。","この記事は、ハリケーン、洪水、干ばつなどの極端な気象現象を含め、気候変動の影響が広範かつ広範囲に及んでおり、インフラストラクチャ、財産、作物に大きな損害を与える可能性があると述べています。したがって、答えはCです。","この記事では、多くの国が気候変動の脅威に対応して、再生可能エネルギーへの投資、エネルギー効率の改善、公共交通機関や電気自動車の利用促進などの行動を起こしていると述べています。したがって、答えはBです。","この記事は、気候変動に対処するという課題が残っているものの、国や個人がより持続可能な未来に向けて取り組むことには希望があると述べています。これは、著者が気候変動との戦いの将来について楽観的であることを示唆しています。したがって、答えはBです。",],
            q_a: [" C"," C"," C"," B"," B",],
            zh: "近年、気候変動の概念はますます差し迫った問題になっています。気候変動とは、気温、降水量、風のパターンの変化など、地球の気候の長期的な変化を指します。火山活動や太陽放射などの自然要因が気候変動の一因となっている一方で、圧倒的な科学的コンセンサスは、人間の活動、特に化石燃料の燃焼が現在の傾向の主な原因であるということです。気候変動の影響は広大で広範囲に及びます。気温の上昇は、ハリケーン、洪水、干ばつなどの異常気象につながる可能性があり、インフラストラクチャ、財産、作物に重大な損害を与える可能性があります。氷床が溶けて海面が上昇すると、低地の沿岸地域に住むコミュニティが移動する可能性があります。気候変動はまた、病気の蔓延や既存の健康状態の悪化など、公衆衛生に悪影響を及ぼす可能性があります。気候変動の脅威に対応して、多くの国が温室効果ガスの排出を削減し、より持続可能な形のエネルギーに移行するための行動を起こしています。これらの取り組みには、風力や太陽光などの再生可能エネルギー源への投資、エネルギー効率の改善、公共交通機関や電気自動車の促進が含まれます。気候変動の課題に対処するためにやるべきことはまだたくさんありますが、国や個人がより持続可能な未来に向けて取り組む中で、希望を持てる理由があります。"
        },{
            ar: "The Importance of SleepWe all know that getting a good night's sleep is important, but many of us still don't get enough sleep on a regular basis. In fact, studies have shown that more than one-third of American adults do not get the recommended seven hours of sleep each night.Lack of sleep can have a variety of negative effects on both our physical and mental health. For example, it can increase the risk of developing chronic health conditions such as obesity, diabetes, and cardiovascular disease. It can also impair our immune system, making us more susceptible to illnesses.In addition to these physical health effects, lack of sleep can also affect our mental health. It can lead to problems with mood regulation, making us more irritable, anxious, and depressed. It can also impair cognitive function, making it harder to concentrate, learn, and remember things.So how can we improve our sleep habits? Here are some tips:Stick to a regular sleep schedule. Go to bed and wake up at the same time every day, even on weekends.Create a relaxing sleep environment. Keep your bedroom dark, quiet, and cool, and avoid using electronic devices before bed.Avoid caffeine, nicotine, and alcohol before bedtime, as they can disrupt your sleep.Get regular exercise, but avoid exercising too close to bedtime.If you have trouble sleeping, try relaxation techniques such as deep breathing or meditation, or consider talking to a healthcare professional about sleep aids.",
            q: ["What is the main idea of the passage?","According to the passage, what are some physical health effects of lack of sleep?","What is the author's advice for creating a relaxing sleep environment?","According to the passage, what is one potential consequence of impaired cognitive function due to lack of sleep?","What is the author's advice for improving sleep habits?",],
            q_sel:[[" Lack of sleep can have negative effects on physical health."," Lack of sleep can have negative effects on mental health."," Lack of sleep is a problem for many Americans."," Getting a good night's sleep is important.",],[" Increased risk of developing depression."," Impaired cognitive function."," Increased risk of developing cardiovascular disease."," Difficulty concentrating.",],[" Use electronic devices before bed."," Keep the bedroom warm and bright."," Avoid noise in the bedroom."," Keep the bedroom cool and dark.",],[" Increased risk of developing obesity."," Difficulty concentrating and learning."," Higher susceptibility to illnesses."," Problems with mood regulation.",],[" Drink alcohol before bedtime."," Exercise right before going to bed."," Stick to a regular sleep schedule."," Use electronic devices in bed.",],],
            q_ex: ["記事の冒頭で睡眠の重要性について言及されており、以下のコンテンツでも睡眠の利点と睡眠習慣の改善方法が強調されています。したがって、答えはDです。","この記事では、睡眠不足は肥満、糖尿病、心血管疾患などの慢性疾患のリスクを高める可能性があると述べています.したがって、答えはCです。","この記事では、寝室を涼しく暗く保ち、就寝前に電子機器を避けるなど、リラックスできる睡眠環境を作るためのヒントに言及しています。したがって、答えはDです。","この記事では、睡眠不足が認知機能に与える影響について言及しており、集中、学習、記憶が困難になる可能性があります.したがって、答えはBです。","この記事では、定期的な睡眠スケジュールを維持すること、就寝前の夜のカフェイン、ニコチン、アルコールを避けること、就寝前の電子機器を避けることなど、睡眠習慣を改善するための提案に言及しています.したがって、答えはCです。",],
            q_a: [" D"," C"," D"," B"," C",],
            zh: "睡眠の重要性 夜ぐっすり眠ることが重要であることは誰もが知っていますが、それでも私たちの多くは定期的に十分な睡眠をとっていません。実際、調査によると、アメリカの成人の 3 分の 1 以上が毎晩推奨される 7 時間の睡眠をとっていません。睡眠不足は、私たちの身体的および精神的健康にさまざまな悪影響を及ぼす可能性があります。たとえば、肥満、糖尿病、心血管疾患などの慢性疾患のリスクを高めます。また、免疫システムに損傷を与える可能性があり、病気になりやすくなります.これらの身体的健康への影響に加えて、睡眠不足は私たちの精神的健康にも影響を与える可能性があります.感情の調節に問題が生じ、いらいらしたり、不安になったり、落ち込んだりします。また、認知機能を損なう可能性があり、集中、学習、記憶が困難になります。では、どうすれば睡眠習慣を改善できるのでしょうか。いくつかのヒントを次に示します。 規則正しい睡眠スケジュールを守りましょう。週末でも、毎日同じ時間に就寝し、同じ時間に起床してください。リラックスできる睡眠環境を作りましょう。寝室を暗く、静かで涼しく保ち、就寝前の電子機器の使用は避けてください。就寝前のカフェイン、ニコチン、アルコールは睡眠を妨げる可能性があるため避けてください。定期的に運動しますが、就寝直前の運動は避けてください。睡眠に問題がある場合は、深呼吸や瞑想などのリラクゼーション法を試すか、医療専門家と睡眠補助薬について話し合うことを検討してください."
        },{
            ar: "It’s a common misconception that introverts are shy, antisocial individuals who don’t enjoy socializing. While introverts may not seek out constant social stimulation like their extroverted counterparts, they do enjoy social interaction, albeit in smaller doses.In fact, introverts can be just as social as extroverts, but they simply need more time to recharge after socializing. This is because introverts are more sensitive to external stimuli and tend to be more easily overwhelmed by excessive socializing or sensory input.Introverts also tend to be more reflective and introspective than extroverts, and may prefer to spend time alone with their thoughts rather than engaging in constant external stimulation. This can be mistaken for shyness or aloofness, but in reality, introverts are simply processing and reflecting on their experiences in a deeper way.Despite the common misconception that introverts are at a disadvantage in social situations, introverts can actually be very effective communicators. They tend to be more thoughtful and deliberate in their speech, taking the time to carefully choose their words and express their ideas in a clear and concise manner.Overall, introversion is simply a personality trait that reflects a preference for solitude and introspection, rather than a social deficit or inability to communicate effectively.",
            q: ["According to the passage, what is a common misconception about introverts?","What does the passage suggest about the difference between introverts and extroverts?","What is the main difference between introverts and extroverts in terms of socializing, according to the passage?",],
            q_sel:[[" They are more easily overwhelmed by external stimuli."," They do not enjoy socializing."," They are less effective communicators than extroverts."," They are more reflective and introspective than extroverts.",],[" Introverts need more time to recharge after socializing."," Extroverts are more easily overwhelmed by external stimuli."," Introverts are less thoughtful and deliberate in their speech."," Extroverts are more reflective and introspective than introverts.",],[" Introverts enjoy socializing more than extroverts."," Extroverts need more time to recharge after socializing."," Introverts are more easily overwhelmed by socializing."," There is no difference between introverts and extroverts in terms of socializing.",],],
            q_ex: ["この記事は、内向的な人が社交を好まないという一般的な誤解に言及することから始まりました。したがって、答えはBです。","この記事によると、外向的な人に比べて、内向的な人は充電して社会的相互作用の影響に対処するためにより多くの時間を必要とします。したがって、答えはAです。","この記事によると、内向的な人は外向的な人よりも過剰な社会的または感覚的刺激に圧倒される可能性が高いため、社会活動に従事するときに不快に感じる可能性が高くなります.したがって、答えはCです。",],
            q_a: [" B"," A"," C",],
            zh: "よくある誤解は、内向的な人は恥ずかしがり屋で反社会的で、社交を好まないというものです。内向的な人は、外向的な人のように、対面でのコミュニケーションではなく、ソーシャル メディアやメッセージ アプリを通じて絶え間ない社会的刺激を求めることはないかもしれません.これは、孤独感や孤立感、重要な社会的スキルの欠如につながる可能性があります.個人がこれらのデバイスの潜在的な悪影響を認識し、就寝前のスクリーン時間を制限して効果を上げるなど、それらを軽減するための措置を講じることが重要ですが、彼らは社会的相互作用を楽しんでいます。より少ない程度。実際、内向的な人は外向的な人と同じように社交することができますが、社交の後に再充電する時間が必要です.これは、内向的な人は外部からの刺激に対してより敏感であり、過度の社会的または感覚的な入力に圧倒される可能性が高いためです.内向的な人はまた、外向的な人よりも内省的で内省的である傾向があり、絶え間ない外部刺激に参加するよりも、一人で考えることに時間を費やすことを好むかもしれません.これは恥ずかしがりやよそよそしさと誤解される可能性がありますが、実際には、内向的な人は自分の経験をより深いレベルで処理し、反映しているだけです。内向的な人は社会的状況において不利な立場にあるという一般的な誤解にもかかわらず、内向的な人は実際には非常に効果的なコミュニケーションをとることができます.慎重に話す傾向があり、時間をかけて慎重に言葉を選び、自分の考えを明確かつ簡潔に表現します。一般に、内向性は、社会的欠陥や効果的なコミュニケーションの欠如ではなく、孤独と内省の好みを反映する単なる性格特性です."
        },{
            ar: "As the world becomes more technologically advanced, people are becoming more and more reliant on electronic devices. While these devices can make life easier and more convenient in many ways, there are also downsides to this dependence.One issue is the effect of electronic devices on sleep. Studies have shown that the blue light emitted by screens can interfere with the production of melatonin, a hormone that helps regulate sleep. This can lead to difficulty falling asleep, as well as poor-quality sleep.Another issue is the impact of electronic devices on social interaction. Many people now spend a significant amount of time interacting with others through ort to engage in face-to-face communication with others.",
            q: ["What is the main topic of the passage?","What is one negative impact of electronic devices on sleep?","How can overuse of electronic devices affect social skills?","What is the author's main message?","What is one step individuals can take to mitigate the negative effects of electronic devices?",],
            q_sel:[[" The benefits of electronic devices"," The downsides of electronic devices"," The future of electronic devices"," The evolution of electronic devices",],[" Increased production of melatonin"," Improved sleep quality"," Interference with melatonin production"," Increased likelihood of dreaming",],[" It can improve social interaction"," It can lead to feelings of loneliness and isolation"," It can increase face-to-face communication"," It can enhance the ability to read social cues",],[" Electronic devices are all bad"," Electronic devices are all good"," Electronic devices have both benefits and downsides"," Electronic devices will eventually disappear",],[" Increase screen time before bed"," Avoid face-to-face communication"," Use electronic devices more frequently"," Limit screen time before bed",],],
            q_ex: ["記事の最初の段落では電子製品の利点について述べていますが、記事全体で電子製品の欠点について説明しているため、答えは B です。","記事の第 2 段落の説明によると、電化製品が放出する青色光はメラトニンの生成を妨げ、それによって睡眠に影響を与える可能性があるため、答えは C です。","記事の 3 番目のパラグラフでは、人々は現在、顔を合わせてコミュニケーションする代わりに、ソーシャル メディアやメッセージング アプリケーションを介して他者とやり取りすることに多くの時間を費やしており、これが孤独と孤立、そして重要なソーシャル スキルの欠如につながっていると述べています。答えは B です。","この記事では、電子製品の欠点に言及しましたが、電子製品の利点も指摘し、個人がこれらのデバイスの潜在的な悪影響を認識し、それらを軽減するための措置を講じる必要があることを強調したため、答えは C.","記事の最後の段落では、個人が電子製品の潜在的な悪影響を認識し、それらを軽減するための措置を講じることを推奨しています. 提案の1つは、就寝前に電子製品を使用する時間を制限することです, したがって、答えはDです. .",],
            q_a: [" B"," C"," B"," C"," D",],
            zh: "世界がますます技術的に進歩するにつれて、人々はますます電子機器に依存するようになっています。これらのデバイスは、多くの点で生活をより簡単かつ便利にすることができますが、この依存にはマイナス面もあります。懸念の 1 つは、電子機器が睡眠に及ぼす影響です。画面から発せられるブルーライトが、睡眠の調節を助けるホルモンであるメラトニンの生成を妨げる可能性があることが研究で示されています。これにより、入眠が困難になり、睡眠の質が低下する可能性があります。もう 1 つの問題は、電子機器が社会的相互作用に与える影響です。現在、多くの人が対面ではなく、ソーシャル メディアやメッセージ アプリを介して他者とやり取りすることに多くの時間を費やしています。これは、孤独感や孤立感につながるだけでなく、重要な社会的スキルの欠如につながる可能性があります.これらの欠点にもかかわらず、エレクトロニクスはどこにも行きません。個人は、これらのデバイスの潜在的な悪影響を認識し、就寝前のスクリーン時間を制限したり、他の人と顔を合わせてやり取りするように努めたりするなど、それらを軽減するための措置を講じる必要があります。"
        },{
            ar: "The human brain is incredibly complex, and there is still much that researchers do not understand about how it works. However, one thing that is clear is that the brain is highly adaptable and capable of change.Neuroplasticity is the term used to describe the brain's ability to reorganize itself in response to new experiences. This can involve creating new neural connections or strengthening existing ones. Neuroplasticity is thought to be a key factor in learning and memory, as well as in recovery from brain injuries.While the brain is capable of neuroplasticity throughout life, the extent to which it can change decreases with age. This means that young children are particularly adept at learning and adapting, while older adults may have more difficulty in these areas.However, there are things that individuals can do to promote neuroplasticity and enhance their brain's ability to adapt. Engaging in activities that are mentally stimulating, such as reading or solving puzzles, is one way to promote neuroplasticity. Physical exercise has also been shown to have a positive impact on brain function and neuroplasticity.",
            q: ["What is the main topic of the passage?","What is neuroplasticity?","How does neuroplasticity impact learning and memory?","What is one way to promote neuroplasticity?",],
            q_sel:[[" The complexity of the human brain"," The role of neuroplasticity in brain function"," The effects of aging on the brain"," The benefits of mental stimulation",],[" The brain's ability to change in response to new experiences"," The brain's ability to maintain the status quo"," The brain's inability to change with age"," The brain's resistance to new experiences",],[" It has no effect on learning and memory"," It makes learning and memory more difficult"," It is a key factor in learning and memory"," It only impacts memory, not learning",],[" Avoid mental stimulation"," Limit physical exercise"," Engage in mentally stimulating activities"," Only engage in physical exercise",],],
            q_ex: ["この記事は主に脳機能に対する神経可塑性の影響について話しているので、答えは B.","この記事の 2 番目の段落で述べたように、神経可塑性とは、新しい神経接続の構築や既存の神経接続の強化など、新しい経験に応じて脳が自らを再編成する能力であるため、答えは A です。","この記事では、神経可塑性が学習と記憶の重要な要素の 1 つだと述べているため、答えは C です。","この記事では、読書や問題解決などの精神を刺激する活動に従事することが、神経可塑性を促進する 1 つの方法であると述べているため、答えは C です。",],
            q_a: [" B"," A"," C"," C",],
            zh: "人間の脳は信じられないほど複雑で、研究者はその仕組みについてまだ多くを理解していません。しかし、1 つはっきりしていることは、脳は非常に適応性が高く、変化する能力があるということです。神経可塑性とは、新しい経験に反応して自分自身を再編成する脳の能力を説明するために使用される用語です。これには、新しい神経接続の作成または既存の神経接続の強化が含まれる場合があります。神経可塑性は、学習と記憶、および脳損傷からの回復における重要な要素と考えられています。脳は生涯を通じて神経可塑性ですが、年齢とともにその変化の程度は減少します。これは、年少の子供は学習と適応が特に得意であるのに対し、年長の大人はこれらの分野でより困難になる可能性があることを意味します.しかし、神経可塑性を促進し、脳の回復力を高めるために個人ができることがあります。読書やパズルを解くなど、精神を刺激する活動に従事することは、神経可塑性を促進する 1 つの方法です。身体活動は、脳機能と神経可塑性にプラスの影響を与えることも示されています。"
        },{
            ar: "Climate change is a pressing issue that has garnered significant attention in recent years. While there is still debate about the causes and extent of climate change, most scientists agree that it is largely driven by human activities, such as the burning of fossil fuels and deforestation.One of the consequences of climate change is rising sea levels. As temperatures continue to rise, glaciers and ice sheets are melting, causing water to flow into the oceans and contributing to sea level rise. This can have a devastating impact on coastal cities and communities, as well as on wildlife and ecosystems.Another consequence of climate change is extreme weather events, such as heat waves, droughts, and hurricanes. These events can lead to crop failures, water shortages, and infrastructure damage, among other things. They also pose a significant threat to human health and well-being.Addressing climate change requires a coordinated effort from individuals, governments, and businesses around the world. This may involve reducing greenhouse gas emissions, transitioning to renewable energy sources, and investing in technologies that can help mitigate the impacts of climate change.",
            q: ["What is the main topic of the passage?","What are some human activities that are contributing to climate change?","What is one consequence of rising temperatures?","What is one way to address climate change?","What is the author's opinion on climate change?",],
            q_sel:[[" The causes of climate change"," The impacts of climate change"," The debate about climate change"," The role of individuals in addressing climate change",],[" Eating meat and dairy products"," Planting trees and other vegetation"," Burning fossil fuels and deforestation"," Recycling and composting",],[" Decreasing sea levels"," Reduced crop yields"," Increased forest cover"," Improved wildlife habitats",],[" Increase greenhouse gas emissions"," Continue to rely on fossil fuels"," Transition to renewable energy sources"," Build more infrastructure in coastal areas",],[" It is not a significant issue"," It is entirely caused by human activities"," It is a topic of debate among scientists"," It requires a coordinated effort to address",],],
            q_ex: ["この記事は主に気候変動が環境、野生生物、人間社会に与える影響について話しているので、答えは B です。","記事では、気候変動は主に化石燃料の燃焼や森林伐採などの人間活動によって引き起こされていると述べているため、答えは C.","この記事は、気温が上昇し続けると、氷河と氷床が溶けて海に水が流れ込み、海面上昇に寄与し、沿岸の都市やコミュニティ、野生生物や生態系に壊滅的な影響を与える可能性があると述べています.なので答えはBです。","この記事では、気候変動に取り組むには、世界中の個人、政府、および企業の間で協調的な取り組みが必要であると述べています。これには、温室効果ガスの排出量の削減、再生可能エネルギー源への切り替え、気候変動の影響を緩和できる技術への投資が含まれる可能性があります。というわけで、答えはCです。","この記事の著者は、気候変動自体についての見解を表明するものではありませんが、気候変動と闘うには、世界中の個人、政府、および企業の間で協調的な取り組みが必要であることを強調しています。というわけで、答えはDです。",],
            q_a: [" B"," C"," B"," C"," D",],
            zh: "気候変動は、近年広く注目されている喫緊の課題です。気候変動の原因と範囲はまだ議論されていますが、ほとんどの科学者は、気候変動は主に化石燃料の燃焼や森林伐採などの人間の活動によって引き起こされていることに同意しています.気候変動の結果の 1 つは海面上昇です。気温が上昇し続けると、氷河と氷床が溶け、水が海に流れ込み、海面上昇の一因となります。これは、沿岸の都市やコミュニティ、野生生物や生態系に壊滅的な影響を与える可能性があります。気候変動のもう 1 つの影響は、熱波、干ばつ、ハリケーンなどの異常気象です。これらの出来事は、とりわけ、作物の不作、水不足、インフラストラクチャの損傷につながる可能性があります。それらはまた、人間の健康と幸福に大きな脅威をもたらします。気候変動に取り組むには、世界中の個人、政府、企業による協調的な取り組みが必要です。これには、温室効果ガス排出量の削減、再生可能エネルギー源への切り替え、気候変動の影響を緩和するのに役立つ技術への投資が含まれる可能性があります。"
        },{
            ar: "For many years, scientists have been trying to find a cure for cancer. They have made some progress, but they still have not found a complete cure. However, there are ways to reduce the risk of getting cancer. One of these ways is to have a healthy diet.Eating a healthy diet is important for many reasons. A healthy diet can help you maintain a healthy weight, which is important because being overweight can increase your risk of cancer. A healthy diet can also provide your body with the nutrients it needs to fight off cancer.So what is a healthy diet? A healthy diet is one that is high in fruits, vegetables, whole grains, and lean protein. It is also low in saturated and trans fats, processed foods, and sugar. Eating a healthy diet can be challenging, but there are many resources available to help you make the right choices.In addition to eating a healthy diet, there are other things you can do to reduce your risk of cancer. These include exercising regularly, not smoking, and protecting your skin from the sun. By making these healthy choices, you can reduce your risk of cancer and improve your overall health.",
            q: ["What have scientists been trying to find for many years?","What are the benefits of eating a healthy diet?","What should a healthy diet be low in?","What are some other ways to reduce the risk of cancer?",],
            q_sel:[[" A complete cure for cancer."," A way to reduce the risk of cancer."," A healthy diet."," A bed diet.",],[" Maintaining a healthy weight and providing the body with the nutrients it needs."," Reducing the risk of smoking and protecting the skin from the sun."," Eating lean protein and avoiding processed foods."," Trying to find a cure for cancer.",],[" Fruits, vegetables, and whole grains."," Saturated and trans fats, processed foods, and sugar."," Lean protein."," A healthy diet can help you maintain a healthy weight.",],[" Eating a healthy diet and exercising regularly."," Smoking and protecting the skin from the sun."," Drinking alcohol and eating processed foods."," Reduce your risk of cancer.",],],
            q_ex: ["記事の最初の文によると、「For many years,cientscients has been trying to find a therapy for Cancer.」という記事は、科学者が長年にわたってがんの治療法を探し求めてきたことを示しており、この段落の主な内容は次のとおりです。は、健康的な食事をとることでがんのリスクを減らすことができるということなので、答えは A です。","記事の 2 番目の段落によると、健康的な食事は、人々が健康的な体重を維持するのに役立ち、同時に体が必要とする栄養素を提供できるため、答えは A です。","記事の 3 番目の段落によると、健康的な食事は飽和脂肪とトランス脂肪、加工食品、砂糖を少なくする必要があるため、答えは B です。","記事の第 4 段落によると、健康的な食事と定期的な運動はがんのリスクを低下させる可能性があるため、答えは A です。",],
            q_a: [" A"," A"," B"," A",],
            zh: "何年もの間、科学者たちはがんの治療法を見つけようとしてきました。彼らはある程度の進歩を遂げましたが、まだ決定的な治療法を見つけていません.しかし、がんのリスクを減らす方法はあります。その方法の1つは、健康的な食事をすることです。健康的な食事をとることは、多くの理由で重要です。健康的な食事をとることは、健康的な体重を維持するのに役立ちます。太りすぎはがんのリスクを高めるため、これは重要です。また、健康的な食事は、がんと闘うために必要な栄養素を体に与えます。では、健康的な食事とは？健康的な食事とは、果物、野菜、全粒穀物、赤身のタンパク質が豊富な食事です。また、飽和脂肪やトランス脂肪、加工食品、砂糖も少ない.健康的な食事をするのは難しいことですが、正しい選択をするのに役立つリソースはたくさんあります。健康的な食事をすることに加えて、がんのリスクを減らすためにできることは他にもあります。これらには、定期的に運動する、喫煙しない、太陽から肌を保護することが含まれます.これらの健康的な選択をすることで、がんのリスクを減らし、全体的な健康を改善することができます."
        },{
            ar: "The Great Barrier Reef is a natural wonder located off the coast of Australia. It is the largest coral reef system in the world, stretching over 2,300 kilometers. The Great Barrier Reef is home to thousands of species of marine life, including sea turtles, dolphins, and over 1,500 species of fish.Unfortunately, the Great Barrier Reef is facing many threats. Climate change is causing the water temperatures to rise, which is bleaching the coral and killing off many of the marine species that live there. Pollution from land-based activities is also damaging the reef. This includes pollution from agricultural runoff, sewage, and industrial waste.To help protect the Great Barrier Reef, the Australian government has implemented several initiatives. These include reducing carbon emissions, improving water quality, and reducing the amount of pollution that enters the reef. There are also many conservation organizations that are working to protect the reef, such as the Great Barrier Reef Foundation.It is important that we all do our part to protect the Great Barrier Reef. We can do this by reducing our carbon footprint, using environmentally-friendly products, and being mindful of our water usage. By working together, we can help ensure that the Great Barrier Reef remains a natural wonder for generations to come.",
            q: ["Where is the Great Barrier Reef located?","What is the Great Barrier Reef known for?","What are some threats to the Great Barrier Reef?","What initiatives has the Australian government implemented to protect the Great Barrier Reef?","How can we help protect the Great Barrier Reef?",],
            q_sel:[[" Off the coast of Africa."," Off the coast of Asia."," Off the coast of Australia."," Off the coast of Japen.",],[" Being the largest coral reef system in the world."," Being home to thousands of species of marine life."," Both A and B ."," To help protect the Great Barrier Reef.",],[" Rising water temperatures and pollution."," Overfishing and tourism."," Hurricanes and earthquakes."," The Australian government has implemented several initiatives.",],[" Reducing carbon emissions, improving water quality, and reducing pollution."," Increasing carbon emissions, improving tourism, and reducing fishing."," Both A and B ."," We can do this by reducing our carbon footprint.",],[" By using environmentally-friendly products."," By reducing our carbon footprint."," By being mindful of our water usage."," All of the above.",],],
            q_ex: ["「グレートバリアリーフはオーストラリア沖にある自然の驚異」という記事の最初の文によると、グレートバリアリーフはオーストラリア沖にあることがわかるので、答えはC.","記事の最初の段落によると、グレート バリア リーフは世界最大のサンゴ礁システムであり、数千種の海洋生物が生息しているため、答えは C です。","記事の第 2 段落によると、グレート バリア リーフは水温の上昇や陸上活動による汚染など、多くの脅威に直面しているため、答えは A.","記事の第 3 段落の内容によると、オーストラリア政府は炭素排出量の削減、水質の改善、サンゴ礁に入る汚染の削減など、多くの対策を実施しているため、答えは A.","記事の最後の段落によると、カーボン フットプリントを削減し、環境に優しい製品を使用し、水を節約することで、グレート バリア リーフを保護することができるので、答えは D です。",],
            q_a: [" C"," C"," A"," A"," D",],
            zh: "グレート バリア リーフは、オーストラリア沖に位置する自然の驚異です。全長 2,300 キロメートルを超える世界最大のサンゴ礁です。グレート バリア リーフには、カメ、イルカ、1,500 種以上の魚など、何千もの海洋生物が生息しています。残念ながら、グレートバリアリーフは多くの脅威に直面しています。気候変動は水温の上昇を引き起こし、サンゴの白化を引き起こし、そこに生息する多くの海洋生物を死に至らしめています。陸上活動による汚染もサンゴ礁にダメージを与えています。これには、農業排水、下水、産業廃棄物による汚染が含まれます。オーストラリア政府は、グレート バリア リーフを保護するためのさまざまな取り組みを実施しています。これらには、炭素排出量の削減、水質の改善、サンゴ礁に入る汚染の量の削減が含まれます。また、グレート バリア リーフ財団など、グレート バリア リーフの保護に専念している保護団体も数多くあります。グレート バリア リーフを保護するために、私たち全員が自分たちの役割を果たすことが重要です。これは、二酸化炭素排出量を削減し、環境に優しい製品を使用し、水の使用に注意することで実現できます。協力することで、グレート バリア リーフが今後何世代にもわたって自然の驚異であり続けるようにすることができます。"
        },{
            ar: "The Importance of SleepSleep is an essential part of a healthy lifestyle. It allows our bodies to rest and recharge, and it plays a vital role in our overall well-being. Unfortunately, many people do not get enough sleep, which can have serious consequences for their health and well-being.There are several reasons why people may not be getting enough sleep. Some people have busy schedules and find it difficult to make time for sleep. Others may have trouble falling asleep or staying asleep due to stress or anxiety. In addition, the use of electronic devices such as smartphones and computers before bedtime can interfere with sleep patterns.The consequences of not getting enough sleep can be severe. Lack of sleep can lead to a weakened immune system, increased risk of accidents, and decreased cognitive function. It can also contribute to mental health issues such as depression and anxiety.To ensure that you are getting enough sleep, it is important to establish a regular sleep schedule and stick to it. This means going to bed and waking up at the same time every day, even on weekends. Avoiding caffeine and alcohol before bedtime can also help improve sleep quality. Additionally, creating a relaxing sleep environment and limiting the use of electronic devices before bedtime can also improve sleep.In conclusion, sleep is a crucial part of a healthy lifestyle. By making sleep a priority and taking steps to improve sleep quality, we can improve our overall health and well-being.",
            q: ["What is the importance of sleep?","What are some reasons why people may not be getting enough sleep?","What are some consequences of not getting enough sleep?","What can we do to improve our sleep quality?",],
            q_sel:[[" It allows our bodies to rest and recharge."," It plays a vital role in our overall well-being."," Both A and B ."," It is important to establish a regular sleep schedule and stick to it.",],[" Busy schedules and stress."," Use of electronic devices before bedtime."," Both A and B ."," It allows our bodies to rest and recharge.",],[" Weakened immune system and increased risk of accidents."," Decreased cognitive function and mental health issues."," Both A and B ."," To ensure that you are getting enough sleep.",],[" Establish a regular sleep schedule and stick to it."," Avoid caffeine and alcohol before bedtime."," Create a relaxing sleep environment and limit the use of electronic devices before bedtime."," All of the above.",],],
            q_ex: ["記事の最初の文によると、睡眠は健康的なライフスタイルに不可欠な要素であり、体を休ませて充電し、健康全般に重要な役割を果たしているため、答えは C です。","記事の2段落目によると、忙しいスケジュールのために睡眠の時間を作るのが難しい人もいれば、ストレスや不安のために入眠や睡眠を維持するのが難しい人もいます. bedtime も睡眠モードに影響するため、答えは C です。","記事の 3 番目の段落によると、睡眠不足は免疫システムの弱体化につながり、事故のリスクを高め、認知機能を低下させます。また、うつ病や不安神経症などのメンタルヘルスの問題につながる可能性があるため、答えは C.","記事の最後の段落によると、十分な睡眠を確保するには、規則的な睡眠スケジュールを確立してそれを守り、就寝前にカフェインやアルコールを避け、リラックスできる睡眠環境を作り、就寝前の電子機器の使用を制限する必要があるため、答えは D.",],
            q_a: [" C"," C"," C"," D",],
            zh: "睡眠の重要性 睡眠は健康的なライフスタイルの重要な部分です。それは私たちの体の休息と再充電を可能にし、私たちの全体的な健康に重要な役割を果たします.残念なことに、多くの人が十分な睡眠をとっていないため、健康と幸福に深刻な影響を与える可能性があります.人が十分な睡眠をとれない理由はさまざまです。スケジュールが忙しく、眠る時間が取れない人もいます。ストレスや不安のために、入眠や睡眠維持が困難になる人もいます。さらに、就寝前にスマートフォンやコンピューターなどの電子機器を使用すると、睡眠パターンが妨げられる可能性があります。睡眠不足の結果は深刻な場合があります。睡眠不足は、免疫力の低下、事故のリスクの増加、認知機能の低下につながる可能性があります。また、うつ病や不安神経症などのメンタルヘルスの問題につながる可能性もあります。十分な睡眠を確保するには、規則的な睡眠スケジュールを作成し、それを守ることが重要です。これは、週末であっても、毎日同じ時間に就寝し、同時に起床することを意味します。就寝前にカフェインやアルコールを避けることも、睡眠の質を改善するのに役立ちます.さらに、リラックスできる睡眠環境を作り、就寝前の電子機器の使用を制限することも、睡眠を改善することができます.結論として、睡眠は健康的なライフスタイルの重要な部分です。睡眠を優先事項とし、睡眠の質を改善するための対策を講じることで、全体的な健康と幸福を改善できます。"
        },{
            ar: "In recent years, there has been a growing interest in sustainable fashion. Sustainable fashion aims to reduce the negative impact that the fashion industry has on the environment, while also promoting fair labor practices and ethical treatment of workers. This can include using eco-friendly materials, reducing waste through recycling and upcycling, and ensuring that workers are paid fair wages and have safe working conditions.",
            q: ["What is sustainable fashion?","What are some ways sustainable fashion can reduce negative impact on the environment?","What does sustainable fashion aim to promote?",],
            q_sel:[[" Fashion that is expensive."," Fashion that is trendy."," Fashion that aims to reduce negative impact on the environment and promote fair labor practices."," Fashion that is not made in developing countries.",],[" Using eco-friendly materials."," Promoting fair labor practices."," Recycling and upcycling."," Both A and C .",],[" Fair labor practices and ethical treatment of workers."," The use of expensive materials."," The production of trendy fashion."," The use of developing countries for manufacturing.",],],
            q_ex: ["記事の最初の文「近年、サステナブルファッションにますます注目が集まっています」によると、この記事は主にサステナブルファッションについて語っていることがわかります。持続可能なファッションの目標は、公正な労働慣行と労働者の倫理的扱いを促進しながら、ファッション業界の環境への悪影響を軽減することです。したがって、答えはCです。","記事の 2 番目の文によると、「持続可能なファッションは、環境に優しい素材を使用し、リサイクルと再利用によって廃棄物を削減し、労働者が公正な賃金と安全な労働条件を受けられるようにすることで、環境へのファッションの悪影響を軽減することを目的としています」、答えは次のとおりです。 D、つまり、環境に優しい素材を使用し、リサイクルと再利用によって廃棄物を削減します。","「持続可能なファッションは、公正な労働慣行と労働者の倫理的扱いを促進しながら、ファッション業界の環境への悪影響を軽減することを目的としています」という記事の最初の文によると、持続可能なファッションが公正な労働慣行と労働者の倫理的扱いを促進することを目的としていることがわかります。労働者の倫理的扱い。したがって、答えはAです。",],
            q_a: [" C"," D"," A",],
            zh: "近年、サステナブルファッションへの関心が高まっています。持続可能なファッションは、公正な労働慣行と労働者の倫理的扱いを促進しながら、ファッション業界の環境への悪影響を軽減することを目的としています。これには、環境に優しい材料の使用、リサイクルとアップサイクルによる廃棄物の削減、労働者が公正な賃金と安全な労働条件を確実に受けられるようにすることが含まれます。"
        },{
            ar: "Technology has transformed the way we live, work, and communicate. One area that has seen a significant impact is the job market. The rise of automation and artificial intelligence has led to the automation of many tasks that were previously performed by humans. This has resulted in a shift in the types of jobs available, with an increasing focus on jobs that require higher levels of skill, such as programming and data analysis.",
            q: ["What is the main idea of this passage?","What is one consequence of the rise of automation and artificial intelligence?","What types of jobs are becoming more important?",],
            q_sel:[[" Technology has had a significant impact on our lives."," The rise of automation and artificial intelligence has changed the job market."," Jobs that require higher levels of skill are becoming more important."," Both B and C .",],[" A decrease in the number of available jobs."," An increase in the types of jobs available."," A decrease in the need for workers with high levels of skill."," A decrease in the need for workers who can adapt to new technology.",],[" Jobs that require lower levels of skill."," Jobs that require higher levels of skill."," Jobs that can be automated."," Both A and C .",],],
            q_ex: ["記事は生活、仕事、コミュニケーションに対するテクノロジーの影響に関するものですが、テクノロジーが雇用市場に与える影響、特に自動化と人工知能の台頭に焦点を当てており、これまで人間が行っていた多くのタスクが自動化されています。これにより、利用できる仕事の種類が変化し、プログラミングやデータ分析など、より高度なスキルを必要とする仕事への注目が高まっています。したがって、答えはDです。","「自動化と人工知能の台頭により、以前は人間が行っていた多くのタスクが自動化されました」という記事の 2 番目の文によると、自動化と人工知能の台頭により、より多くの種類の作業が行われていることがわかります。なので答えはBです。","記事の最後の文「プログラミングやデータ分析など、より高度なスキルを必要とする仕事の重要性が増している」によると、より高度なスキルを必要とする仕事が重要になっていることがわかるので、答えはBです。 .",],
            q_a: [" D"," B"," B",],
            zh: "テクノロジーは、私たちの生活、仕事、コミュニケーションの方法を変えました。大きな影響を受けた分野の 1 つは、雇用市場です。自動化と人工知能の台頭により、以前は人間が行っていた多くのタスクが自動化されました。これにより、利用可能な仕事の種類が変化し、プログラミングやデータ分析など、より高いスキルレベルを必要とする仕事への注目が高まっています."
        },{
            ar: "In recent years, there has been a growing concern about the impact of plastic waste on the environment. It is estimated that over 8 million tons of plastic end up in the oceans every year, harming marine life and polluting our beaches. While recycling can help to reduce the amount of plastic waste, it is not a complete solution. To truly address the problem, we need to reduce our reliance on single-use plastics and find alternative materials that are more environmentally friendly.",
            q: ["What is the main idea of this passage?","What is the impact of plastic waste on the oceans?","What is the solution to the problem of plastic waste?",],
            q_sel:[[" Plastic waste is harming the environment."," Recycling is not a complete solution to the problem of plastic waste."," We need to reduce our reliance on single-use plastics and find alternative materials."," Both A and C .",],[" It harms marine life."," It increases the number of fish in the oceans."," It reduces pollution on the beaches."," Both B and C .",],[" Recycling."," Finding alternative materials."," Reducing our reliance on single-use plastics."," Both B and C .",],],
            q_ex: ["この記事では、プラスチック廃棄物が環境、特に海洋生態系に与える影響について説明しています。この記事は、リサイクルはプラスチック廃棄物の量を減らすのに役立ちますが、完全な解決策ではないと主張しています.この問題を本当に解決するには、使い捨てプラスチックへの依存を減らし、より環境に優しい代替品を見つける必要があります。したがって、答えはDです。","記事の最初の文によると、「近年、人々はプラスチック廃棄物が環境に与える影響にますます注意を払ってきました」、2番目の文によると、「800万トン以上のプラスチック廃棄物が世界に入り込んでいると推定されています。プラスチック廃棄物は海洋生態系に有害であることがわかります。","「使い捨てプラスチック製品への依存を減らし、より環境に優しい代替材料を見つける必要がある」という記事の最後の文によると、プラスチック廃棄物の問題の解決策は、より環境に優しい代替材料を見つけて、使い捨てプラスチック製品に依存しているので、答えはDです.",],
            q_a: [" D"," A"," D",],
            zh: "近年、プラスチックごみによる環境への影響が懸念されています。毎年 800 万トン以上のプラスチックが海に流出し、海洋生物に害を及ぼし、ビーチを汚染していると推定されています。リサイクルはプラスチック廃棄物の量を減らすのに役立ちますが、完全な解決策ではありません。この問題を本当に解決するには、使い捨てプラスチックへの依存を減らし、より環境に優しい代替品を見つける必要があります。"
        },{
            ar: "Climate change is one of the biggest challenges facing our planet today. The burning of fossil fuels, such as coal and oil, releases carbon dioxide and other greenhouse gases into the atmosphere, trapping heat and causing global temperatures to rise. The consequences of climate change include rising sea levels, more frequent and severe weather events, and the extinction of plant and animal species. To address this urgent issue, we must reduce our greenhouse gas emissions and transition to renewable energy sources such as wind, solar, and hydro power.",
            q: ["What is the main challenge facing our planet today?","What is the cause of global temperature rise?","What are the consequences of climate change?","What is the solution to address the issue of climate change?",],
            q_sel:[[" Rising sea levels."," Climate change."," The extinction of plant and animal species."," Burning fossil fuels.",],[" Rising sea levels."," Burning of fossil fuels."," Extinction of plant and animal species."," None of the above.",],[" Rising sea levels."," More frequent and severe weather events."," The extinction of plant and animal species."," All of the above.",],[" Reduce greenhouse gas emissions."," Transition to renewable energy sources."," Both A and B ."," None of the above.",],],
            q_ex: ["記事の冒頭で「気候変動」という言葉が出てきて、その原因と結果が説明されているので、主な課題は気候変動であり、答えはBと判断できます。","言及された記事によると、「石炭や石油などの化石燃料の燃焼は、二酸化炭素やその他の温室効果ガスを大気中に放出し、熱を閉じ込め、地球の気温上昇を引き起こします。」化石燃料の燃焼は地球規模の気温であり、答えは B です。","記事によると、「気候変動の影響には、海面上昇、より頻繁かつ深刻な気象現象、および動植物種の絶滅が含まれます。」気候変動の影響には、海面上昇、より頻繁かつ深刻な現象が含まれていることがわかります。気象現象、そして動物種の絶滅、答えはDです.","記事によると、「この差し迫った問題を解決するには、温室効果ガスの排出を削減し、風力、太陽光、水力などの再生可能エネルギー源に切り替える必要があります。気候変動の問題を解決する方法は、温室効果ガスの排出を削減し、再生可能エネルギー源に切り替える場合、答えは C です。",],
            q_a: [" B"," B"," D"," C",],
            zh: "気候変動は、今日の地球が直面している最大の課題の 1 つです。石炭や石油などの化石燃料を燃やすと、二酸化炭素やその他の温室効果ガスが大気中に放出され、熱が閉じ込められて地球の気温が上昇します。気候変動の影響には、海面上昇、より頻繁で深刻な気象現象、動植物種の絶滅などがあります。この差し迫った問題を解決するには、温室効果ガスの排出を削減し、風力、太陽光、水力発電などの再生可能エネルギー源に切り替える必要があります。"
        },]