export const id = [{
            ars: "The new restaurant in town is already causing quite a _____ with its unique menu and elegant atmosphere. The restaurant's owner, a well-known chef, has created a _____ dining experience that is both delicious and memorable. The restaurant offers a wide variety of dishes, ranging from classic comfort food to exotic _____ from around the world. Customers can choose to dine in the main dining room or in a more intimate private _____ for special occasions. The restaurant also offers catering services for corporate events and private parties.",
            reals: "The new restaurant in town is already causing quite a stir with its unique menu and elegant atmosphere. The restaurant's owner, a well-known chef, has created a refined dining experience that is both delicious and memorable. The restaurant offers a wide variety of dishes, ranging from classic comfort food to exotic delicacies from around the world. Customers can choose to dine in the main dining room or in a more intimate private booth for special occasions. The restaurant also offers catering services for corporate events and private parties.",
            sels: ["stir","steer","stare","store","refined","delightful","extravagant","delicate","delicacies","spices","beverages","desserts","booth","chamber","lounge","terrace",],
            exps: "Ini adalah artikel tentang restoran baru, menyebutkan menu dan suasana restoran. Dari konteks: Kalimat pertama menyebutkan menu restoran yang unik dan suasana yang elegan, jadi jawabannya harus aduk. Kalimat 2 menyebutkan bahwa masakan restoran tersebut enak dan berkesan, sehingga jawabannya harus “halus”. Kalimat 3 menyebutkan bahwa restoran menyajikan berbagai macam hidangan, termasuk makanan rumahan klasik dan masakan eksotis dari seluruh dunia, jadi jawabannya harus lezat. Kalimat empat mengacu pada ruang makan pribadi yang ditawarkan restoran, jadi jawabannya harus booth. Oleh karena itu, jawabannya adalah (A) aduk, (E) halus, (I) makanan lezat, dan (M) stan.",
            ans: ["(A)","(E)","(I)","(M)",],
            cns: "Restoran baru di kota ini sudah menimbulkan kehebohan dengan menunya yang unik dan suasana yang elegan. Pemilik restoran adalah koki terkenal yang telah menciptakan pengalaman bersantap mewah yang lezat dan berkesan. Restoran ini menawarkan berbagai macam hidangan, mulai dari makanan rumahan klasik hingga masakan eksotis dari seluruh dunia. Pelanggan dapat memilih untuk bersantap di ruang makan utama atau di kotak yang lebih intim untuk acara-acara khusus. Restoran ini juga melayani acara perusahaan dan pesta pribadi."
        },{
            ars: "The new marketing campaign has been _____ successful, with sales increasing by 20% since its launch. The campaign's focus on social media has helped the company reach a wider _____, particularly among younger consumers who spend a lot of time on their phones. The company's _____ strategy, which includes targeted ads and influencer partnerships, has also contributed to its success. However, the company's _____ has also played a role in the campaign's success, as its reputation for high-quality products has helped build trust with customers.",
            reals: "The new marketing campaign has been tremendously successful, with sales increasing by 20% since its launch. The campaign's focus on social media has helped the company reach a wider audience, particularly among younger consumers who spend a lot of time on their phones. The company's promotion strategy, which includes targeted ads and influencer partnerships, has also contributed to its success. However, the company's reputation has also played a role in the campaign's success, as its reputation for high-quality products has helped build trust with customers.",
            sels: ["moderately","tremendously","barely","slightly","audience","market","sector","niche","pricing","promotion","distribution","packaging","innovation","reputation","location","convenience",],
            exps: "Ini adalah artikel tentang kampanye pemasaran yang menyebutkan mengapa kampanye itu berhasil. Dari konteksnya, maka keberhasilan kampanye disebutkan dalam kalimat satu, jadi jawabannya harus luar biasa. Kalimat 2 menyebutkan bahwa acara tersebut sangat populer di kalangan konsumen muda, jadi jawabannya harus penonton. Strategi kampanye disebutkan di kalimat ketiga, termasuk iklan bertarget dan kerja sama influencer, jadi jawabannya harus promosi. Reputasi perusahaan disebutkan dalam kalimat empat, yang membantu membangun kepercayaan dengan pelanggan, jadi jawabannya harus reputasi. Jadi, jawabannya adalah (B) sangat besar, (E) audiens, (J) promosi, dan (N) reputasi.",
            ans: ["(B)","(E)","(J)","(N)",],
            cns: "Kampanye pemasaran baru telah sukses besar, dengan penjualan naik 20% sejak diluncurkan. Fokus kampanye di media sosial telah membantu perusahaan menjangkau audiens yang lebih luas, terutama di kalangan konsumen muda yang menghabiskan banyak waktu di ponsel mereka. Strategi publisitas korporat termasuk periklanan bertarget dan kemitraan influencer juga berkontribusi pada kesuksesannya. Namun, reputasi perusahaan juga berperan dalam kesuksesan acara tersebut, karena reputasinya atas produk berkualitas tinggi membantu membangun kepercayaan pelanggan."
        },{
            ars: "The company has announced plans to _____ its workforce by 10% in an effort to reduce costs. The layoffs will primarily affect _____ in the company's administrative and support departments, although some managers and executives will also be let go. The company's CEO has stated that these changes are necessary to ensure the long-term _____ of the company and maintain its competitiveness in the marketplace. The company will provide severance packages and _____ services to affected employees to help them transition to new employment.",
            reals: "The company has announced plans to downsize its workforce by 10% in an effort to reduce costs. The layoffs will primarily affect employees in the company's administrative and support departments, although some managers and executives will also be let go. The company's CEO has stated that these changes are necessary to ensure the long-term sustainability of the company and maintain its competitiveness in the marketplace. The company will provide severance packages and counseling services to affected employees to help them transition to new employment.",
            sels: ["expand","downsize","diversify","centralize","employees","shareholders","customers","suppliers","profitability","stability","flexibility","sustainability","relocation","retraining","counseling","mentoring",],
            exps: "Ini adalah artikel tentang rencana PHK perusahaan, dan artikel tersebut menyebutkan sebab dan akibat dari rencana tersebut. Dapat disimpulkan dari konteksnya: Kalimat 1 menyebutkan rencana PHK perusahaan, jadi jawabannya harus “berhemat”. Kalimat 2 menyebutkan bahwa departemen karyawan tertentu terpengaruh, jadi jawabannya harus karyawan. Kalimat 3 menyebutkan bahwa CEO perusahaan percaya bahwa perubahan ini diperlukan untuk memastikan stabilitas dan daya saing perusahaan dalam jangka panjang, sehingga jawabannya harus keberlanjutan. Kalimat 4 menyebutkan bahwa perusahaan memberikan pesangon dan layanan konseling untuk membantu transisi karyawan yang terkena dampak ke pekerjaan baru, jadi jawabannya harus konseling. Jadi jawabannya adalah (B) berhemat, (E) karyawan, (L) keberlanjutan dan (O) konseling.",
            ans: ["(B)","(E)","(L)","(O)",],
            cns: "Perusahaan telah mengumumkan rencana untuk mengurangi tenaga kerjanya sebesar 10% dalam upaya untuk mengurangi biaya. PHK terutama memengaruhi karyawan di fungsi administrasi dan pendukung perusahaan, meskipun beberapa manajer dan eksekutif juga akan diberhentikan. CEO perusahaan mengatakan perubahan itu diperlukan untuk memastikan keberlanjutan jangka panjang dan mempertahankan daya saing perusahaan di pasar. Perusahaan akan memberikan pesangon dan layanan pendampingan kepada karyawan yang terkena dampak untuk membantu mereka beralih ke pekerjaan baru."
        },{
            ars: "The _____ of the company's new product has been delayed due to manufacturing issues. The company had originally planned to launch the product in Q2, but now expects to release it in Q4. The delay has been _____ disappointing for the company, which had invested heavily in research and development and marketing efforts to support the launch. The company's management has reassured shareholders that the delay is temporary and that the product will be worth the wait, with features that are _____ superior to those of its competitors.",
            reals: "The launch of the company's new product has been delayed due to manufacturing issues. The company had originally planned to launch the product in Q2, but now expects to release it in Q4. The delay has been extremely disappointing for the company, which had invested heavily in research and development and marketing efforts to support the launch. The company's management has reassured shareholders that the delay is temporary and that the product will be worth the wait, with features that are significantly superior to those of its competitors.",
            sels: ["launch","design","development","testing","highly","somewhat","extremely","moderately","significantly","marginally","slightly","barely",],
            exps: "Ini adalah artikel tentang keterlambatan produk baru, alasan keterlambatan dan tanggapan perusahaan. Ini mengikuti dari konteksnya: Kalimat 1 menyebutkan bahwa peluncuran produk ditunda, jadi jawabannya harus peluncuran. Kalimat kedua menyebutkan bahwa perusahaan sangat kecewa dengan keterlambatan ini, sehingga jawabannya harus sangat. Kalimat 3 menyebutkan bahwa produk tersebut akan memiliki fungsi unggulan, sehingga jawabannya harus “signifikan”. Jadi jawabannya adalah (A) luncurkan, (G) sangat, dan (I) signifikan.",
            ans: ["(A)","(G)","(I)",],
            cns: "Peluncuran, peluncuran pasar Produk baru perusahaan telah tertunda karena masalah manufaktur. Perusahaan awalnya berencana meluncurkan produk pada kuartal kedua, tetapi sekarang mengharapkan rilis pada kuartal keempat. Penundaan itu parah, yang mengecewakan bagi perusahaan, yang telah banyak berinvestasi dalam R&D dan pemasaran untuk mendukung peluncuran tersebut. Manajemen perusahaan telah meyakinkan para pemegang saham bahwa penundaan itu bersifat sementara dan bahwa produk tersebut layak untuk ditunggu, dengan fitur-fitur penting dibandingkan para pesaingnya."
        },{
            ars: "The hotel industry in the city has been experiencing a boom in recent years due to increased tourism. Many new hotels have _____ up in the city center, offering tourists a range of options at different price points. However, this growth has also led to increased _____ and competition among hotels, with some struggling to fill their rooms during off-peak seasons. To address this, many hotels have been _____ their services to appeal to a wider range of customers, such as offering discounted rates to business travelers and families.",
            reals: "The hotel industry in the city has been experiencing a boom in recent years due to increased tourism. Many new hotels have opened up in the city center, offering tourists a range of options at different price points. However, this growth has also led to increased supply and competition among hotels, with some struggling to fill their rooms during off-peak seasons. To address this, many hotels have been diversifying their services to appeal to a wider range of customers, such as offering discounted rates to business travelers and families.",
            sels: ["closed","opened","expanded","renovated","demand","supply","marketing","innovation","diversifying","outsourcing","downsizing","streamlining",],
            exps: "Ini adalah artikel tentang perkembangan industri perhotelan di kota, artikel tersebut menyebutkan pertumbuhan industri perhotelan dan isu-isu terkait. Dapat disimpulkan dari konteksnya: Kalimat 1 menyebutkan bahwa industri perhotelan perkotaan berkembang pesat dalam beberapa tahun terakhir, jadi jawabannya harus dibuka. Kalimat 2 menyebutkan bahwa pertumbuhan juga membawa persaingan dan kelebihan pasokan, jadi jawabannya harus pasokan. Kalimat 3 menyebutkan bahwa banyak hotel yang menyesuaikan layanannya untuk menanggapi perubahan pasar, jadi jawabannya harus diversifikasi. Oleh karena itu, jawabannya adalah (B) terbuka, (F) penawaran, dan (I) diversifikasi.",
            ans: ["(B)","(F)","(I)",],
            cns: "Dalam beberapa tahun terakhir, industri perhotelan kota ini berkembang pesat berkat pertumbuhan pariwisata. Banyak hotel baru telah dibuka di pusat kota, menawarkan kepada wisatawan berbagai pilihan dengan harga berbeda. Namun, pertumbuhan ini juga menyebabkan peningkatan pasokan dan persaingan antar hotel, dengan beberapa hotel berjuang untuk mengisi kamar selama musim sepi. Untuk mengatasi hal ini, banyak hotel telah mendiversifikasi penawaran mereka untuk menarik pelanggan yang lebih luas, seperti menawarkan potongan harga untuk pelancong bisnis dan keluarga."
        },{
            ars: "The pharmaceutical industry has come under increased scrutiny in recent years due to concerns about rising drug prices and the role of pharmaceutical companies in the opioid crisis. Many consumers are _____ to pay for medications that they need to maintain their health, leading to calls for greater government regulation of drug prices. Meanwhile, several pharmaceutical companies have faced lawsuits for their role in the opioid epidemic, with some accused of _____ their products and contributing to addiction and overdose deaths. In response, the industry has pledged to improve transparency and _____ in drug pricing and marketing practices.",
            reals: "The pharmaceutical industry has come under increased scrutiny in recent years due to concerns about rising drug prices and the role of pharmaceutical companies in the opioid crisis. Many consumers are reluctant to pay for medications that they need to maintain their health, leading to calls for greater government regulation of drug prices. Meanwhile, several pharmaceutical companies have faced lawsuits for their role in the opioid epidemic, with some accused of overpromoting their products and contributing to addiction and overdose deaths. In response, the industry has pledged to improve transparency and accountability in drug pricing and marketing practices.",
            sels: ["reluctant","eager","unwilling","hesitant","overpromoting","underpromoting","misrepresenting","falsifying","accountability","efficiency","innovation","profitability",],
            exps: "Ini adalah artikel tentang isu-isu dalam industri farmasi, dengan referensi isu-isu seperti kenaikan harga obat dan peran perusahaan farmasi dalam krisis opioid. Dapat ditarik dari konteksnya: Kalimat 1 menyebutkan bahwa banyak konsumen yang tidak mau membayar biaya obat yang mahal, sehingga jawabannya harus enggan. Kalimat 2 menyebutkan bahwa beberapa perusahaan farmasi dituduh melakukan overpromoting produk mereka, berkontribusi terhadap masalah seperti kecanduan dan kematian akibat overdosis, jadi jawabannya harus overpromoting. Kalimat ketiga mengacu pada komitmen industri farmasi untuk meningkatkan transparansi dan praktik penetapan harga dan pemasaran obat yang bertanggung jawab, sehingga jawabannya harus “akuntabilitas”. Jadi jawabannya adalah (A) enggan, (E) promosi berlebihan, dan (I) akuntabilitas.",
            ans: ["(A)","(E)","(I)",],
            cns: "Industri farmasi semakin diawasi dalam beberapa tahun terakhir di tengah kekhawatiran tentang kenaikan harga obat dan peran perusahaan obat dalam krisis opioid. Banyak konsumen tidak mau membayar obat yang mereka butuhkan untuk menjaga kesehatan mereka, menyebabkan pemerintah menyerukan pengaturan harga obat yang lebih besar. Sementara itu, beberapa perusahaan farmasi menghadapi tuntutan hukum atas peran mereka dalam epidemi opioid, dengan beberapa dituduh mempromosikan produk mereka secara berlebihan dan menyebabkan kecanduan dan kematian akibat overdosis. Sebagai tanggapan, industri telah berjanji untuk meningkatkan transparansi dan akuntabilitas dalam praktik penetapan harga dan pemasaran obat."
        },{
            ars: "In recent years, the global energy sector has undergone significant changes, driven by concerns about _____ and the need to reduce carbon emissions. As a result, many countries have implemented policies aimed at increasing the use of renewable energy sources, such as wind and solar power. This has led to a _____ in the renewable energy industry, with companies investing heavily in research and development to improve the efficiency and cost-effectiveness of their products. However, the shift towards renewable energy has not been without its _____, as some traditional energy companies have struggled to adapt to the changing market conditions.",
            reals: "In recent years, the global energy sector has undergone significant changes, driven by concerns about sustainability and the need to reduce carbon emissions. As a result, many countries have implemented policies aimed at increasing the use of renewable energy sources, such as wind and solar power. This has led to a surge in the renewable energy industry, with companies investing heavily in research and development to improve the efficiency and cost-effectiveness of their products. However, the shift towards renewable energy has not been without its challenges, as some traditional energy companies have struggled to adapt to the changing market conditions.",
            sels: ["sustainability","diversity","innovation","competition","surge","decline","stagnation","consolidation","challenges","opportunities","benefits","rewards",],
            exps: "Ini adalah artikel tentang industri energi global, yang menyebutkan perubahan dalam industri dan tantangan terkait. Hal ini dapat ditarik dari konteksnya: Kalimat 1 menyebutkan kepedulian terhadap keberlanjutan dan kebutuhan untuk mengurangi emisi karbon, sehingga jawabannya harus “keberlanjutan”. Kalimat kedua menyebutkan lonjakan industri energi terbarukan, jadi jawabannya harus lonjakan. Kalimat 3 menyebutkan kesulitan bagi perusahaan energi tradisional untuk beradaptasi dengan perubahan pasar, sehingga jawabannya harus tantangan. Jadi jawabannya adalah (A) keberlanjutan, (E) lonjakan dan (I) tantangan.",
            ans: ["(A)","(E)","(I)",],
            cns: "Dalam beberapa tahun terakhir, industri energi global telah mengalami perubahan besar, didorong oleh kekhawatiran tentang keberlanjutan dan kebutuhan untuk mengurangi emisi karbon. Akibatnya, banyak negara telah menerapkan kebijakan yang ditujukan untuk meningkatkan penggunaan sumber energi terbarukan seperti angin dan matahari. Hal ini menyebabkan lonjakan industri energi terbarukan, dengan perusahaan berinvestasi besar-besaran dalam penelitian dan pengembangan untuk meningkatkan efisiensi dan efektivitas biaya produk mereka. Namun, transisi ke energi terbarukan bukannya tanpa tantangan, karena beberapa perusahaan energi tradisional kesulitan beradaptasi dengan perubahan kondisi pasar."
        },{
            ars: "Over the past decade, advances in technology have transformed the way we live and work. One of the most significant changes has been the widespread adoption of _____ devices, such as smartphones and tablets. These devices have revolutionized the way we _____ information, allowing us to access a wealth of knowledge at our fingertips. However, they have also had a number of _____ effects, such as the erosion of face-to-face communication skills and the development of addiction to social media.",
            reals: "Over the past decade, advances in technology have transformed the way we live and work. One of the most significant changes has been the widespread adoption of mobile devices, such as smartphones and tablets. These devices have revolutionized the way we retrieve information, allowing us to access a wealth of knowledge at our fingertips. However, they have also had a number of detrimental effects, such as the erosion of face-to-face communication skills and the development of addiction to social media.",
            sels: ["mobile","wireless","digital","handheld","process","retrieve","disseminate","interpret","beneficial","detrimental","positive","negative",],
            exps: "Ini adalah artikel tentang perubahan teknologi, dan artikel tersebut menyebutkan dampak perubahan teknologi terhadap kehidupan dan pekerjaan. Dari konteksnya: Kalimat 1 menyebutkan maraknya penggunaan perangkat mobile seperti smartphone dan tablet, sehingga jawabannya harus “mobile”. Kalimat kedua menyebutkan perubahan revolusioner dalam perolehan pengetahuan menggunakan perangkat ini, jadi jawabannya harus mengambil. Efek negatif dari penggunaan perangkat ini disebutkan di kalimat ketiga, jadi jawabannya harus merugikan. Jadi jawabannya adalah (A) bergerak, (F) mengambil, dan (J) merugikan.",
            ans: ["(A)","(F)","(J)",],
            cns: "Selama dekade terakhir, kemajuan teknologi telah mengubah cara kita hidup dan bekerja. Salah satu perubahan terpenting adalah adopsi perangkat Internet seluler secara luas, seperti smartphone dan tablet. Perangkat ini telah merevolusi cara kita mengambil informasi, memberikan banyak pengetahuan di ujung jari kita. Namun, mereka juga memiliki efek merusak, seperti erosi keterampilan komunikasi tatap muka dan berkembangnya kecanduan media sosial."
        },{
            ars: "In recent years, businesses have increasingly turned to social media to _____ with their customers. Platforms like Facebook and Twitter offer companies a way to _____ with their audience in real-time, and can help to create a sense of community around a brand. However, social media also presents a number of _____, including the potential for negative feedback to spread quickly and damage a company's reputation.",
            reals: "In recent years, businesses have increasingly turned to social media to engage with their customers. Platforms like Facebook and Twitter offer companies a way to interact with their audience in real-time, and can help to create a sense of community around a brand. However, social media also presents a number of drawbacks, including the potential for negative feedback to spread quickly and damage a company's reputation.",
            sels: ["collaborate","engage","compete","negotiate","interact","market","advertise","promote","opportunities","challenges","benefits","drawbacks",],
            exps: "Ini adalah artikel tentang bisnis yang menggunakan media sosial untuk berinteraksi dengan pelanggan, artikel tersebut menyebutkan dampak media sosial terhadap bisnis. Dari konteks: Kalimat 1 menyebutkan bahwa bisnis semakin banyak menggunakan media sosial untuk berinteraksi dengan pelanggan, sehingga jawabannya harus engage. Kalimat 2 menyebutkan bahwa media sosial dapat membantu perusahaan membangun komunitas merek, sehingga jawabannya harus “berinteraksi”. Kalimat 3 menyebutkan risiko menggunakan media sosial, jadi jawabannya harus kekurangan. Jadi jawabannya adalah (B) terlibat, (E) berinteraksi dan (L) kekurangan.",
            ans: ["(B)","(E)","(L)",],
            cns: "Dalam beberapa tahun terakhir, bisnis semakin beralih ke media sosial untuk terlibat dengan pelanggan mereka. Platform seperti Facebook dan Twitter menawarkan perusahaan cara interaktif untuk berkomunikasi dengan audiens mereka secara real time dan membantu menciptakan rasa komunitas di sekitar merek. Namun, media sosial juga memiliki beberapa kelemahan, antara lain potensi umpan balik negatif menyebar dengan cepat dan merusak reputasi perusahaan."
        },{
            ars: "The hotel industry is experiencing a _____ in business due to the recent economic boom. With more people _____ disposable income, more and more individuals are choosing to travel and stay in hotels. In order to meet the demand, hotels are expanding their facilities and _____ their services to attract customers.",
            reals: "The hotel industry is experiencing a surge in business due to the recent economic boom. With more people spending disposable income, more and more individuals are choosing to travel and stay in hotels. In order to meet the demand, hotels are expanding their facilities and improving their services to attract customers.",
            sels: ["decline","stagnation","surge","fluctuation","having","earning","spending","saving","improving","reducing","limiting","discontinuing",],
            exps: "Ini adalah artikel tentang pertumbuhan bisnis perhotelan.Artikel tersebut menyebutkan bahwa ketika ekonomi berkembang pesat dan semakin banyak orang memilih untuk bepergian dan menginap di hotel, terjadi lonjakan dalam bisnis perhotelan. Dari konteksnya, maka lonjakan disebutkan dalam kalimat pertama, jadi jawabannya harus (C) lonjakan. Kalimat 2 menyebutkan bahwa ketika orang menghabiskan lebih banyak pendapatan yang dapat dibelanjakan, mereka semakin memilih untuk bepergian dan tinggal di hotel, jadi jawabannya adalah (G) pengeluaran. Kalimat 3 menyebutkan bahwa untuk memenuhi permintaan, hotel memperluas fasilitasnya dan memperbaiki layanannya untuk menarik pelanggan, jadi jawabannya harus (I) meningkatkan. Jadi jawabannya adalah (C) lonjakan, (G) pembelanjaan, dan (I) peningkatan.",
            ans: ["(C)","(G)","(I)",],
            cns: "Industri perhotelan mengalami lonjakan aktivitas bisnis karena ledakan ekonomi baru-baru ini. Semakin banyak orang yang mengkonsumsi Dengan meningkatnya pendapatan yang dapat dibuang, semakin banyak orang memilih untuk bepergian dan tinggal di hotel. Untuk memenuhi permintaan, hotel memperluas fasilitas mereka dan meningkatkan layanan mereka untuk menarik pelanggan."
        },{
            ars: "In recent years, online shopping has become increasingly popular among consumers. One of the biggest advantages of online shopping is that it allows customers to _____ items from the comfort of their own homes. This means that people can avoid the hassle of traffic and crowded stores. Additionally, online shopping often offers a wider variety of products than traditional retail stores, as well as _____ prices. Many retailers also offer free shipping or other _____ to encourage customers to shop online.",
            reals: "In recent years, online shopping has become increasingly popular among consumers. One of the biggest advantages of online shopping is that it allows customers to purchase items from the comfort of their own homes. This means that people can avoid the hassle of traffic and crowded stores. Additionally, online shopping often offers a wider variety of products than traditional retail stores, as well as lower prices. Many retailers also offer free shipping or other promotions to encourage customers to shop online.",
            sels: ["purchase","return","exchange","rent","lower","higher","fixed","fluctuating","promotions","warranties","discounts","contracts",],
            exps: "Ini adalah artikel tentang belanja online. Artikel tersebut menyebutkan keuntungan belanja online, antara lain kemudahan, terhindar dari lalu lintas dan keramaian, variasi produk yang banyak, harga yang lebih murah, promosi yang ditawarkan oleh toko, pengiriman gratis, dll. Hal ini dapat ditarik dari konteksnya: Kalimat 1 menyebutkan bahwa belanja online memungkinkan orang membeli barang dari rumah, jadi jawabannya harus (A) pembelian. Kalimat 2 menyebutkan bahwa salah satu keuntungan belanja online adalah harga yang lebih murah, sehingga jawabannya harus (E) lebih rendah. Kalimat 3 menyebutkan promosi dan pengiriman gratis yang ditawarkan oleh toko, dll., jadi jawabannya harus (I) promosi. Jadi jawabannya adalah (A) beli, (E) turunkan dan (I) promosi.",
            ans: ["(A)","(E)","(I)",],
            cns: "Dalam beberapa tahun terakhir, belanja online menjadi semakin populer di kalangan konsumen. Salah satu keuntungan terbesar dari belanja online adalah memungkinkan pelanggan untuk membeli barang dari kenyamanan rumah mereka sendiri. Ini berarti orang dapat menghindari kerumitan lalu lintas dan toko-toko yang ramai. Selain itu, belanja online seringkali menawarkan variasi produk yang lebih luas daripada toko retail tradisional, dan dengan harga lebih murah. Banyak pengecer juga menawarkan pengiriman gratis atau promosi lainnya untuk mendorong pelanggan berbelanja online."
        },{
            ars: "The hospitality industry, which includes hotels, restaurants, and catering services, plays a crucial role in the global economy. As international travel continues to _____, the demand for hotels and restaurants has increased. In addition, many people today prefer to _____ out or order in rather than cook at home. This has led to a growth in the number of restaurants and catering services, both small and large.When it comes to hotels, there are a wide variety of options available to travelers. From luxury hotels to budget accommodations, there is something for every _____ of traveler. Many hotels now offer additional amenities such as fitness centers, swimming pools, and complimentary breakfast. In order to stay competitive, hotels must also keep up with the latest technologies, such as online reservation systems and mobile check-in options.",
            reals: "The hospitality industry, which includes hotels, restaurants, and catering services, plays a crucial role in the global economy. As international travel continues to increase, the demand for hotels and restaurants has increased. In addition, many people today prefer to dine out or order in rather than cook at home. This has led to a growth in the number of restaurants and catering services, both small and large.When it comes to hotels, there are a wide variety of options available to travelers. From luxury hotels to budget accommodations, there is something for every category of traveler. Many hotels now offer additional amenities such as fitness centers, swimming pools, and complimentary breakfast. In order to stay competitive, hotels must also keep up with the latest technologies, such as online reservation systems and mobile check-in options.",
            sels: ["decrease","stagnate","increase","fluctuate","eat","dine","take","make","kind","level","group","category",],
            exps: "Ini adalah artikel tentang industri restoran dan hotel. Artikel tersebut menyebutkan bahwa dengan meningkatnya pariwisata internasional, permintaan hotel dan restoran juga meningkat. Di saat yang sama, semakin banyak orang yang memilih untuk makan di luar atau memesan makanan pesan antar, sehingga jumlah restoran dan jasa catering juga terus bertambah. Selain itu, hotel juga menawarkan beragam pilihan, termasuk hotel mewah dan akomodasi hemat, dll., Dan agar tetap kompetitif, hotel juga harus mengikuti teknologi terkini. Kalimat 1 menyebutkan bahwa dengan meningkatnya pariwisata internasional, permintaan hotel dan restoran juga meningkat, sehingga jawabannya harus (C) meningkat. Kalimat 2 menyebutkan bahwa semakin banyak orang yang memilih untuk makan di luar atau memesan pesan antar makanan, maka jawabannya adalah (F) dine. Kalimat 3 menyebutkan bahwa hotel menawarkan berbagai pilihan, termasuk hotel mewah dan akomodasi murah, dll., jadi jawabannya harus kategori (L). Oleh karena itu, jawabannya adalah (C) meningkat, (F) makan, dan (L) kategori.",
            ans: ["(C)","(F)","(L)",],
            cns: "Industri perhotelan, termasuk hotel, restoran, dan layanan makanan, memainkan peran penting dalam ekonomi global. Karena perjalanan internasional terus meningkat, permintaan akan hotel dan restoran pun meningkat. Selain itu, banyak orang saat ini lebih suka makan di luar atau memesan daripada memasak di rumah. Hal ini menyebabkan peningkatan jumlah restoran besar dan kecil dan layanan makanan. Ketika datang ke hotel, wisatawan memiliki berbagai pilihan. Dari hotel mewah hingga penginapan hemat, selalu ada sesuatu untuk setiap kategori wisatawan. Banyak hotel sekarang menawarkan fasilitas tambahan seperti pusat kebugaran, kolam renang, dan sarapan gratis. Agar tetap kompetitif, hotel juga harus mengikuti teknologi terkini, seperti sistem reservasi online dan opsi mobile check-in."
        },]