export const ja = [{
            ars: "The new restaurant in town is already causing quite a _____ with its unique menu and elegant atmosphere. The restaurant's owner, a well-known chef, has created a _____ dining experience that is both delicious and memorable. The restaurant offers a wide variety of dishes, ranging from classic comfort food to exotic _____ from around the world. Customers can choose to dine in the main dining room or in a more intimate private _____ for special occasions. The restaurant also offers catering services for corporate events and private parties.",
            reals: "The new restaurant in town is already causing quite a stir with its unique menu and elegant atmosphere. The restaurant's owner, a well-known chef, has created a refined dining experience that is both delicious and memorable. The restaurant offers a wide variety of dishes, ranging from classic comfort food to exotic delicacies from around the world. Customers can choose to dine in the main dining room or in a more intimate private booth for special occasions. The restaurant also offers catering services for corporate events and private parties.",
            sels: ["stir","steer","stare","store","refined","delightful","extravagant","delicate","delicacies","spices","beverages","desserts","booth","chamber","lounge","terrace",],
            exps: "新しいお店のメニューや雰囲気などを紹介する記事です。文脈から: 文 1 は、レストランのユニークなメニューとエレガントな雰囲気について言及しているので、答えは「かき混ぜる」である必要があります。文 2 は、レストランの料理が美味しくて思い出に残るものであると述べているので、答えは「洗練された」にする必要があります。文 3 では、レストランでは伝統的なコンフォート フードから世界中のエキゾチックな料理まで、さまざまな料理を提供していると述べているため、答えは「珍味」にすべきです。文 4 は、レストランが提供するプライベート ダイニング エリアについて言及しているため、答えは「ブース」になります。したがって、答えは (A) 攪拌、(E) 洗練、(I) 珍味、(M) ブースです。",
            ans: ["(A)","(E)","(I)","(M)",],
            cns: "町の新しいレストランは、そのユニークなメニューとエレガントな雰囲気ですでにかなりの話題を呼んでいます.レストランのオーナーは、美味しく思い出に残る洗練されたダイニング体験を生み出した有名なシェフです。レストランでは、伝統的なコンフォート フードから世界中のエキゾチックな料理まで、さまざまな料理を提供しています。常連客は、メイン ダイニング ルームまたは特別な機会のためのより親密なボックスで食事をすることを選択できます。レストランでは、企業イベントやプライベート パーティーにも対応しています。"
        },{
            ars: "The new marketing campaign has been _____ successful, with sales increasing by 20% since its launch. The campaign's focus on social media has helped the company reach a wider _____, particularly among younger consumers who spend a lot of time on their phones. The company's _____ strategy, which includes targeted ads and influencer partnerships, has also contributed to its success. However, the company's _____ has also played a role in the campaign's success, as its reputation for high-quality products has helped build trust with customers.",
            reals: "The new marketing campaign has been tremendously successful, with sales increasing by 20% since its launch. The campaign's focus on social media has helped the company reach a wider audience, particularly among younger consumers who spend a lot of time on their phones. The company's promotion strategy, which includes targeted ads and influencer partnerships, has also contributed to its success. However, the company's reputation has also played a role in the campaign's success, as its reputation for high-quality products has helped build trust with customers.",
            sels: ["moderately","tremendously","barely","slightly","audience","market","sector","niche","pricing","promotion","distribution","packaging","innovation","reputation","location","convenience",],
            exps: "これは、キャンペーンが成功した理由に言及したマーケティング キャンペーンに関する記事です。文脈からすると、キャンペーンの成功は文 1 で言及されていることになるので、答えは「途方もなく」である必要があります。文 2 は、このイベントが特に若い消費者に人気があることを示しているため、答えは「聴衆」にする必要があります。ターゲティング広告やインフルエンサーの協力など、キャンペーンの戦略は3文目に挙げられているので、答えは「プロモーション」でしょう。会社の評判は、顧客との信頼関係を築くのに役立つ文 4 に記載されているため、答えは「評判」になります。したがって、答えは (B) 非常に、(E) 観客、(J) プロモーション、(N) 評判です。",
            ans: ["(B)","(E)","(J)","(N)",],
            cns: "新しいマーケティング キャンペーンは大成功を収め、発売以来、売り上げは 20% 増加しました。キャンペーンがソーシャル メディアに焦点を当てていることで、同社はより幅広いオーディエンス、特に携帯電話で多くの時間を過ごす若い消費者にリーチすることができました。ターゲットを絞った広告やインフルエンサーとのパートナーシップなど、企業の宣伝戦略も成功に貢献しています。ただし、高品質の製品に対する評判が顧客の信頼を築くのに役立つため、会社の評判もイベントの成功に影響を与えます。"
        },{
            ars: "The company has announced plans to _____ its workforce by 10% in an effort to reduce costs. The layoffs will primarily affect _____ in the company's administrative and support departments, although some managers and executives will also be let go. The company's CEO has stated that these changes are necessary to ensure the long-term _____ of the company and maintain its competitiveness in the marketplace. The company will provide severance packages and _____ services to affected employees to help them transition to new employment.",
            reals: "The company has announced plans to downsize its workforce by 10% in an effort to reduce costs. The layoffs will primarily affect employees in the company's administrative and support departments, although some managers and executives will also be let go. The company's CEO has stated that these changes are necessary to ensure the long-term sustainability of the company and maintain its competitiveness in the marketplace. The company will provide severance packages and counseling services to affected employees to help them transition to new employment.",
            sels: ["expand","downsize","diversify","centralize","employees","shareholders","customers","suppliers","profitability","stability","flexibility","sustainability","relocation","retraining","counseling","mentoring",],
            exps: "これは企業の一時解雇計画に関する記事で、この記事では計画の原因と結果について言及しています。文脈から結論づけることができます: 文 1 は会社のレイオフ計画に言及しているので、答えは「ダウンサイジング」でなければなりません。文 2 は、従業員の特定の部門が影響を受けると述べているため、回答は「従業員」にする必要があります。文 3 は、会社の CEO が、会社の長期的な安定性と競争力を確保するためにこれらの変更が必要であると考えていることを述べているため、答えは「持続可能性」である必要があります。文 4 は、影響を受けた従業員が新しい雇用に移行するのを支援するために会社が退職金とカウンセリング サービスを提供していると述べているため、答えは「カウンセリング」である必要があります。したがって、答えは (B) 縮小、(E) 従業員、(L) 持続可能性、(O) カウンセリングです。",
            ans: ["(B)","(E)","(L)","(O)",],
            cns: "同社は、コストを削減するために従業員を 10% 削減する計画を発表しました。レイオフは、主に会社の管理およびサポート機能の従業員に影響を与えますが、一部のマネージャーや幹部も解雇されます。同社のCEOは、長期的な持続可能性を確保し、市場での同社の競争力を維持するために変更が必要であると述べました.同社は、影響を受ける従業員に退職金と指導サービスを提供し、新しい仕事への移行を支援します。"
        },{
            ars: "The _____ of the company's new product has been delayed due to manufacturing issues. The company had originally planned to launch the product in Q2, but now expects to release it in Q4. The delay has been _____ disappointing for the company, which had invested heavily in research and development and marketing efforts to support the launch. The company's management has reassured shareholders that the delay is temporary and that the product will be worth the wait, with features that are _____ superior to those of its competitors.",
            reals: "The launch of the company's new product has been delayed due to manufacturing issues. The company had originally planned to launch the product in Q2, but now expects to release it in Q4. The delay has been extremely disappointing for the company, which had invested heavily in research and development and marketing efforts to support the launch. The company's management has reassured shareholders that the delay is temporary and that the product will be worth the wait, with features that are significantly superior to those of its competitors.",
            sels: ["launch","design","development","testing","highly","somewhat","extremely","moderately","significantly","marginally","slightly","barely",],
            exps: "新商品の入荷遅れとその理由と同社の対応についての記事です。文脈から次のようになります。文 1 は、製品のリリースが遅れていることを述べているため、答えは「発売」にする必要があります。 2 番目の文は、会社がこの遅延に非常に失望していることに言及しているので、答えは「非常に」であるべきです。文 3 は、その製品が優れた機能を備えていると述べているため、答えは「大幅に」となります。したがって、答えは (A) 打ち上げ、(G) 非常に、および (I) 非常に重要です。",
            ans: ["(A)","(G)","(I)",],
            cns: "発売、市場投入 同社の新製品は、製造上の問題により遅れています。同社は当初、第 2 四半期に製品を発売する予定でしたが、現在は第 4 四半期にリリースされる予定です。発売の遅れは深刻で、発売をサポートするために研究開発とマーケティングに多額の投資を行ってきた同社にとっては残念なことです。同社の経営陣は、遅延は一時的なものであり、競合他社よりも優れた機能を備えた製品は待つ価値があることを株主に保証しています。"
        },{
            ars: "The hotel industry in the city has been experiencing a boom in recent years due to increased tourism. Many new hotels have _____ up in the city center, offering tourists a range of options at different price points. However, this growth has also led to increased _____ and competition among hotels, with some struggling to fill their rooms during off-peak seasons. To address this, many hotels have been _____ their services to appeal to a wider range of customers, such as offering discounted rates to business travelers and families.",
            reals: "The hotel industry in the city has been experiencing a boom in recent years due to increased tourism. Many new hotels have opened up in the city center, offering tourists a range of options at different price points. However, this growth has also led to increased supply and competition among hotels, with some struggling to fill their rooms during off-peak seasons. To address this, many hotels have been diversifying their services to appeal to a wider range of customers, such as offering discounted rates to business travelers and families.",
            sels: ["closed","opened","expanded","renovated","demand","supply","marketing","innovation","diversifying","outsourcing","downsizing","streamlining",],
            exps: "これは、市内のホテル産業の発展に関する記事で、ホテル産業の成長と関連する問題について言及しています。文脈から結論づけることができます: 文 1 は、都市のホテル産業が近年繁栄していることに言及しているため、答えは「開かれている」必要があります。文 2 では、成長は競争と供給過剰ももたらすと述べているため、答えは「供給」にすべきです。文 3 は、多くのホテルが市場の変化に対応してサービスを調整していることに言及しているため、答えは「多様化」となるはずです。したがって、答えは（B）オープン、（F）供給、（I）多様化です。",
            ans: ["(B)","(F)","(I)",],
            cns: "近年、観光の成長により、市内のホテル産業は活況を呈しています。多くの新しいホテルが市内中心部にオープンし、観光客にさまざまな価格帯でさまざまなオプションを提供しています。ただし、この成長はホテル間の供給と競争の増加にもつながり、一部のホテルはオフシーズン中に部屋を埋めるのに苦労しています.これに対抗するために、多くのホテルは、ビジネス旅行者や家族向けの割引料金を提供するなど、より幅広い顧客にアピールするためにサービスを多様化しています."
        },{
            ars: "The pharmaceutical industry has come under increased scrutiny in recent years due to concerns about rising drug prices and the role of pharmaceutical companies in the opioid crisis. Many consumers are _____ to pay for medications that they need to maintain their health, leading to calls for greater government regulation of drug prices. Meanwhile, several pharmaceutical companies have faced lawsuits for their role in the opioid epidemic, with some accused of _____ their products and contributing to addiction and overdose deaths. In response, the industry has pledged to improve transparency and _____ in drug pricing and marketing practices.",
            reals: "The pharmaceutical industry has come under increased scrutiny in recent years due to concerns about rising drug prices and the role of pharmaceutical companies in the opioid crisis. Many consumers are reluctant to pay for medications that they need to maintain their health, leading to calls for greater government regulation of drug prices. Meanwhile, several pharmaceutical companies have faced lawsuits for their role in the opioid epidemic, with some accused of overpromoting their products and contributing to addiction and overdose deaths. In response, the industry has pledged to improve transparency and accountability in drug pricing and marketing practices.",
            sels: ["reluctant","eager","unwilling","hesitant","overpromoting","underpromoting","misrepresenting","falsifying","accountability","efficiency","innovation","profitability",],
            exps: "これは、薬価の上昇やオピオイド危機における製薬会社の役割などの問題に言及しながら、製薬業界の問題についての記事です。これは文脈から導き出すことができます: 文 1 は、多くの消費者が高額の薬代を払いたがらないと述べているため、答えは「気が進まない」である必要があります。センテンス 2 は、一部の製薬会社が自社製品を過度に宣伝し、依存症や過剰摂取による死亡などの問題を引き起こしていると非難されていることを述べているため、答えは「過剰宣伝」である必要があります。文 3 は、透明性と責任ある薬価設定およびマーケティング慣行を改善するための製薬業界のコミットメントに言及しているため、答えは「説明責任」である必要があります。したがって、答えは (A) 消極的、(E) 過剰な宣伝、および (I) 説明責任です。",
            ans: ["(A)","(E)","(I)",],
            cns: "製薬業界は、薬価の上昇とオピオイド危機における製薬会社の役割についての懸念の中で、近年ますます精査されています.多くの消費者は、健康を維持するために必要な薬にお金を払いたがらないため、政府は薬価の規制強化を求めています。一方、いくつかの製薬会社は、オピオイドの流行における役割をめぐって訴訟に直面しており、一部の製薬会社は自社製品を過度に宣伝し、中毒や過剰摂取による死亡を引き起こしていると非難されています.これに対応して、業界は医薬品の価格設定とマーケティング慣行の透明性と説明責任を高めることを約束しました。"
        },{
            ars: "In recent years, the global energy sector has undergone significant changes, driven by concerns about _____ and the need to reduce carbon emissions. As a result, many countries have implemented policies aimed at increasing the use of renewable energy sources, such as wind and solar power. This has led to a _____ in the renewable energy industry, with companies investing heavily in research and development to improve the efficiency and cost-effectiveness of their products. However, the shift towards renewable energy has not been without its _____, as some traditional energy companies have struggled to adapt to the changing market conditions.",
            reals: "In recent years, the global energy sector has undergone significant changes, driven by concerns about sustainability and the need to reduce carbon emissions. As a result, many countries have implemented policies aimed at increasing the use of renewable energy sources, such as wind and solar power. This has led to a surge in the renewable energy industry, with companies investing heavily in research and development to improve the efficiency and cost-effectiveness of their products. However, the shift towards renewable energy has not been without its challenges, as some traditional energy companies have struggled to adapt to the changing market conditions.",
            sels: ["sustainability","diversity","innovation","competition","surge","decline","stagnation","consolidation","challenges","opportunities","benefits","rewards",],
            exps: "これは世界のエネルギー産業に関する記事で、業界の変化とそれに対応する課題に言及しています。これは文脈から導き出すことができます。文 1 は、持続可能性への懸念と炭素排出量を削減する必要性について言及しているため、答えは「持続可能性」である必要があります。文 2 は、再生可能エネルギー産業の急増について言及しているため、答えは「急増」である必要があります。文 3 は、従来のエネルギー企業が市場の変化に適応することの難しさを述べているため、答えは「課題」である必要があります。つまり、答えは (A) 持続可能性、(E) 急増、(I) 課題です。",
            ans: ["(A)","(E)","(I)",],
            cns: "近年、世界のエネルギー産業は、持続可能性への懸念と二酸化炭素排出量削減の必要性に後押しされ、大きな変化を遂げています。その結果、多くの国が、風力や太陽光などの再生可能エネルギー源の使用を増やすことを目的とした政策を実施しています。これにより、再生可能エネルギー産業が急増し、企業は製品の効率と費用対効果を改善するために研究開発に多額の投資を行っています。しかし、再生可能エネルギーへの移行には課題がなかったわけではありません。従来のエネルギー企業の中には、変化する市場の状況に適応するのに苦労しているものもあります。"
        },{
            ars: "Over the past decade, advances in technology have transformed the way we live and work. One of the most significant changes has been the widespread adoption of _____ devices, such as smartphones and tablets. These devices have revolutionized the way we _____ information, allowing us to access a wealth of knowledge at our fingertips. However, they have also had a number of _____ effects, such as the erosion of face-to-face communication skills and the development of addiction to social media.",
            reals: "Over the past decade, advances in technology have transformed the way we live and work. One of the most significant changes has been the widespread adoption of mobile devices, such as smartphones and tablets. These devices have revolutionized the way we retrieve information, allowing us to access a wealth of knowledge at our fingertips. However, they have also had a number of detrimental effects, such as the erosion of face-to-face communication skills and the development of addiction to social media.",
            sels: ["mobile","wireless","digital","handheld","process","retrieve","disseminate","interpret","beneficial","detrimental","positive","negative",],
            exps: "これは技術の変化に関する記事で、技術の変化が生活や仕事に与える影響について言及しています。文脈から: 文 1 は、スマートフォンやタブレットなどのモバイル デバイスの普及について言及しているため、答えは「モバイル」である必要があります。センテンス 2 は、これらのデバイスを使用した知識獲得の革命的な変化について言及しているため、答えは「検索」である必要があります。これらのデバイスを使用することの悪影響は 3 番目の文で述べられているため、答えは「有害」である必要があります。したがって、答えは (A) モバイル、(F) 検索、および (J) 有害です。",
            ans: ["(A)","(F)","(J)",],
            cns: "過去 10 年間、テクノロジーの進歩は私たちの生活や仕事の仕方を変えてきました。最も重要な変化の 1 つは、スマートフォンやタブレットなどのモバイル インターネット デバイスの普及です。これらのデバイスは、情報を取得する方法に革命をもたらし、豊富な知識をすぐに利用できるようにしました。しかし、対面でのコミュニケーション スキルの低下やソーシャル メディア依存症の発症など、有害な影響もあります。"
        },{
            ars: "In recent years, businesses have increasingly turned to social media to _____ with their customers. Platforms like Facebook and Twitter offer companies a way to _____ with their audience in real-time, and can help to create a sense of community around a brand. However, social media also presents a number of _____, including the potential for negative feedback to spread quickly and damage a company's reputation.",
            reals: "In recent years, businesses have increasingly turned to social media to engage with their customers. Platforms like Facebook and Twitter offer companies a way to interact with their audience in real-time, and can help to create a sense of community around a brand. However, social media also presents a number of drawbacks, including the potential for negative feedback to spread quickly and damage a company's reputation.",
            sels: ["collaborate","engage","compete","negotiate","interact","market","advertise","promote","opportunities","challenges","benefits","drawbacks",],
            exps: "これは、ソーシャル メディアを使用して顧客と対話する企業に関する記事で、ソーシャル メディアが企業に与える影響について言及しています。文脈から: 文 1 は、企業がますますソーシャル メディアを使用して顧客と対話するようになっていることを示しているため、答えは「エンゲージメント」である必要があります。文 2 は、ソーシャル メディアは企業がブランド コミュニティを構築するのに役立つと述べているため、答えは「対話する」である必要があります。文 3 は、ソーシャル メディアを使用するリスクについて言及しているため、答えは「欠点」である必要があります。つまり、答えは (B) エンゲージ、(E) インタラクション、(L) 欠点です。",
            ans: ["(B)","(E)","(L)",],
            cns: "近年、企業はソーシャル メディアを利用して顧客との関係を強化する傾向にあります。 Facebook や Twitter などのプラットフォームは、企業が視聴者とリアルタイムで対話するインタラクティブな方法を提供し、ブランドの周りにコミュニティの感覚を生み出すのに役立ちます。ただし、ソーシャル メディアには、否定的なフィードバックが急速に広まり、企業の評判が損なわれる可能性など、いくつかの欠点もあります。"
        },{
            ars: "The hotel industry is experiencing a _____ in business due to the recent economic boom. With more people _____ disposable income, more and more individuals are choosing to travel and stay in hotels. In order to meet the demand, hotels are expanding their facilities and _____ their services to attract customers.",
            reals: "The hotel industry is experiencing a surge in business due to the recent economic boom. With more people spending disposable income, more and more individuals are choosing to travel and stay in hotels. In order to meet the demand, hotels are expanding their facilities and improving their services to attract customers.",
            sels: ["decline","stagnation","surge","fluctuation","having","earning","spending","saving","improving","reducing","limiting","discontinuing",],
            exps: "これは、ホテル ビジネスの成長に関する記事です。この記事では、経済が好況を呈し、旅行やホテルに滞在することを選択する人が増えるにつれて、ホテル ビジネスに「急増」があると述べています。文脈から、文 1 で「サージ」が言及されていることになるので、答えは (C) サージとなるはずです。文 2 は、人々がより多くの可処分所得を「消費」するにつれて、ますます旅行やホテル滞在を選択するようになると述べているため、答えは (G) 消費になります。文 3 は、需要を満たすために、ホテルが施設を拡張し、顧客を引き付けるためにサービスを 改善 していると述べているので、答えは (I) 改善する必要があります。したがって、答えは (C) 急増、(G) 支出、(I) 改善です。",
            ans: ["(C)","(G)","(I)",],
            cns: "ホスピタリティ業界は、最近の好景気によりビジネス活動が急増しています。より多くの人々が消費するにつれて、可処分所得の増加に伴い、ますます多くの人々が旅行やホテルに滞在することを選択します.その需要に応えるため、ホテルは施設の拡張やサービスの向上を図り、集客を図っています。"
        },{
            ars: "In recent years, online shopping has become increasingly popular among consumers. One of the biggest advantages of online shopping is that it allows customers to _____ items from the comfort of their own homes. This means that people can avoid the hassle of traffic and crowded stores. Additionally, online shopping often offers a wider variety of products than traditional retail stores, as well as _____ prices. Many retailers also offer free shipping or other _____ to encourage customers to shop online.",
            reals: "In recent years, online shopping has become increasingly popular among consumers. One of the biggest advantages of online shopping is that it allows customers to purchase items from the comfort of their own homes. This means that people can avoid the hassle of traffic and crowded stores. Additionally, online shopping often offers a wider variety of products than traditional retail stores, as well as lower prices. Many retailers also offer free shipping or other promotions to encourage customers to shop online.",
            sels: ["purchase","return","exchange","rent","lower","higher","fixed","fluctuating","promotions","warranties","discounts","contracts",],
            exps: "ネットショッピングに関する記事で、便利さ、渋滞回避、商品の豊富さ、低価格、店舗のキャンペーン、送料無料など、ネットショッピングのメリットを紹介しています。これは文脈から導き出すことができます: 文 1 では、オンライン ショッピングでは自宅から商品を購入できると述べているため、答えは (A) 購入になります。文 2 は、オンライン ショッピングの利点の 1 つは価格が安いことだと述べているので、答えは (E) 低いはずです。文 3 は、ストアが提供するプロモーションや送料無料などについて言及しているので、答えは (I) プロモーションとなります。したがって、答えは (A) 購入、(E) 値下げ、(I) プロモーションです。",
            ans: ["(A)","(E)","(I)",],
            cns: "近年、オンラインショッピングは消費者の間でますます人気が高まっています。オンライン ショッピングの最大の利点の 1 つは、顧客が自宅にいながら商品を購入できることです。これは、人々が渋滞や混雑した店の煩わしさを避けることができることを意味します。さらに、オンライン ショッピングは、多くの場合、従来の小売店よりも幅広い種類の製品を低価格で提供しています。多くの小売業者は、顧客にオンラインでの買い物を促すために、送料無料やその他のプロモーションも提供しています。"
        },{
            ars: "The hospitality industry, which includes hotels, restaurants, and catering services, plays a crucial role in the global economy. As international travel continues to _____, the demand for hotels and restaurants has increased. In addition, many people today prefer to _____ out or order in rather than cook at home. This has led to a growth in the number of restaurants and catering services, both small and large.When it comes to hotels, there are a wide variety of options available to travelers. From luxury hotels to budget accommodations, there is something for every _____ of traveler. Many hotels now offer additional amenities such as fitness centers, swimming pools, and complimentary breakfast. In order to stay competitive, hotels must also keep up with the latest technologies, such as online reservation systems and mobile check-in options.",
            reals: "The hospitality industry, which includes hotels, restaurants, and catering services, plays a crucial role in the global economy. As international travel continues to increase, the demand for hotels and restaurants has increased. In addition, many people today prefer to dine out or order in rather than cook at home. This has led to a growth in the number of restaurants and catering services, both small and large.When it comes to hotels, there are a wide variety of options available to travelers. From luxury hotels to budget accommodations, there is something for every category of traveler. Many hotels now offer additional amenities such as fitness centers, swimming pools, and complimentary breakfast. In order to stay competitive, hotels must also keep up with the latest technologies, such as online reservation systems and mobile check-in options.",
            sels: ["decrease","stagnate","increase","fluctuate","eat","dine","take","make","kind","level","group","category",],
            exps: "これは、レストランおよびホテル業界に関する記事です。この記事では、国際観光の増加に伴い、ホテルやレストランの需要も増加していると述べています。同時に、外食や出前を利用する人が増えているため、飲食店やケータリングサービスの数も増えています。また、ホテルも高級ホテルや格安宿泊施設など、さまざまなオプションを提供しており、競争力を維持するためにホテルも最新のテクノロジーに対応する必要があります。文 1 は、国際観光が増加すると、ホテルやレストランの需要も増加すると述べているので、答えは (C) 増加するはずです。文 2 は、ますます多くの人々が外食や食品の配達を選択することを示しているため、答えは (F) 食事となります。センテンス 3 は、ホテルが高級ホテルや低予算の宿泊施設など、さまざまなオプションを提供していることに言及しているため、答えは (L) カテゴリにする必要があります。したがって、答えは (C) 増加、(F) 食事、(L) カテゴリです。",
            ans: ["(C)","(F)","(L)",],
            cns: "ホテル、レストラン、フードサービスなどのホスピタリティ業界は、世界経済において重要な役割を果たしています。海外旅行の増加に伴い、ホテルやレストランの需要が高まっています。さらに、多くの人々は今日、家で料理をするよりも外食や注文を好む傾向にあります。これにより、大小さまざまなレストランやフード サービスの数が増加しました。ホテルに関して言えば、旅行者にはさまざまな選択肢があります。高級ホテルから手頃な宿泊施設まで、あらゆるカテゴリーの旅行者向けのホテルがあります。現在、多くのホテルでは、フィットネスセンター、スイミング プール、無料の朝食などの追加のアメニティを提供しています。競争力を維持するために、ホテルはオンライン予約システムやモバイル チェックイン オプションなどの最新テクノロジーにも対応する必要があります。"
        },]