export const pt = [{
            ars: "The new restaurant in town is already causing quite a _____ with its unique menu and elegant atmosphere. The restaurant's owner, a well-known chef, has created a _____ dining experience that is both delicious and memorable. The restaurant offers a wide variety of dishes, ranging from classic comfort food to exotic _____ from around the world. Customers can choose to dine in the main dining room or in a more intimate private _____ for special occasions. The restaurant also offers catering services for corporate events and private parties.",
            reals: "The new restaurant in town is already causing quite a stir with its unique menu and elegant atmosphere. The restaurant's owner, a well-known chef, has created a refined dining experience that is both delicious and memorable. The restaurant offers a wide variety of dishes, ranging from classic comfort food to exotic delicacies from around the world. Customers can choose to dine in the main dining room or in a more intimate private booth for special occasions. The restaurant also offers catering services for corporate events and private parties.",
            sels: ["stir","steer","stare","store","refined","delightful","extravagant","delicate","delicacies","spices","beverages","desserts","booth","chamber","lounge","terrace",],
            exps: "Este é um artigo sobre um novo restaurante, mencionando o menu e a atmosfera do restaurante. Do contexto: A primeira frase menciona o menu exclusivo e o ambiente elegante do restaurante, então a resposta deve ser agitar. A frase 2 menciona que os pratos do restaurante são deliciosos e memoráveis, então a resposta deve ser refinada. A frase 3 menciona que o restaurante serve uma grande variedade de pratos, incluindo comida caseira clássica e cozinhas exóticas de todo o mundo, pelo que a resposta deve ser iguarias. A frase quatro se refere à área de jantar privada que o restaurante oferece, então a resposta deve ser cabine. Portanto, as respostas são (A) mexer, (E) refinado, (I) iguarias e (M) estande.",
            ans: ["(A)","(E)","(I)","(M)",],
            cns: "O novo restaurante da cidade já está causando alvoroço com seu cardápio diferenciado e ambiente elegante. O proprietário do restaurante é um chef renomado que criou uma experiência gastronômica refinada, deliciosa e memorável. O restaurante oferece uma grande variedade de pratos, desde comida caseira clássica até cozinha exótica de todo o mundo. Os clientes podem optar por jantar na sala de jantar principal ou em camarotes mais íntimos para ocasiões especiais. O restaurante também atende eventos corporativos e festas particulares."
        },{
            ars: "The new marketing campaign has been _____ successful, with sales increasing by 20% since its launch. The campaign's focus on social media has helped the company reach a wider _____, particularly among younger consumers who spend a lot of time on their phones. The company's _____ strategy, which includes targeted ads and influencer partnerships, has also contributed to its success. However, the company's _____ has also played a role in the campaign's success, as its reputation for high-quality products has helped build trust with customers.",
            reals: "The new marketing campaign has been tremendously successful, with sales increasing by 20% since its launch. The campaign's focus on social media has helped the company reach a wider audience, particularly among younger consumers who spend a lot of time on their phones. The company's promotion strategy, which includes targeted ads and influencer partnerships, has also contributed to its success. However, the company's reputation has also played a role in the campaign's success, as its reputation for high-quality products has helped build trust with customers.",
            sels: ["moderately","tremendously","barely","slightly","audience","market","sector","niche","pricing","promotion","distribution","packaging","innovation","reputation","location","convenience",],
            exps: "Este é um artigo sobre uma campanha de marketing que menciona por que a campanha foi bem-sucedida. Do contexto, conclui-se que o sucesso da campanha é mencionado na frase um, então a resposta deve ser tremendamente. A frase 2 menciona que o evento é especialmente popular entre os consumidores jovens, então a resposta deve ser público. A estratégia da campanha é mencionada na terceira frase, incluindo publicidade direcionada e cooperação com influenciadores, então a resposta deve ser promoção. A reputação da empresa é mencionada na sentença quatro, o que ajuda a construir a confiança dos clientes, então a resposta deve ser reputação. Portanto, as respostas são (B) enormemente, (E) audiência, (J) promoção e (N) reputação.",
            ans: ["(B)","(E)","(J)","(N)",],
            cns: "A nova campanha de marketing foi um enorme sucesso, com vendas de 20% desde o lançamento. O foco da campanha nas mídias sociais ajudou a empresa a alcançar um público mais amplo, especialmente entre os consumidores mais jovens que passam muito tempo em seus telefones. Estratégias de publicidade corporativa, incluindo publicidade direcionada e parcerias com influenciadores, também contribuíram para seu sucesso. No entanto, a reputação de uma empresa também desempenha um papel no sucesso do evento, pois sua reputação de produtos de alta qualidade ajuda a construir a confiança do cliente."
        },{
            ars: "The company has announced plans to _____ its workforce by 10% in an effort to reduce costs. The layoffs will primarily affect _____ in the company's administrative and support departments, although some managers and executives will also be let go. The company's CEO has stated that these changes are necessary to ensure the long-term _____ of the company and maintain its competitiveness in the marketplace. The company will provide severance packages and _____ services to affected employees to help them transition to new employment.",
            reals: "The company has announced plans to downsize its workforce by 10% in an effort to reduce costs. The layoffs will primarily affect employees in the company's administrative and support departments, although some managers and executives will also be let go. The company's CEO has stated that these changes are necessary to ensure the long-term sustainability of the company and maintain its competitiveness in the marketplace. The company will provide severance packages and counseling services to affected employees to help them transition to new employment.",
            sels: ["expand","downsize","diversify","centralize","employees","shareholders","customers","suppliers","profitability","stability","flexibility","sustainability","relocation","retraining","counseling","mentoring",],
            exps: "Este é um artigo sobre o plano de dispensa de uma empresa, e o artigo menciona as causas e os efeitos do plano. Pode-se concluir do contexto: A frase 1 menciona o plano de demissões da empresa, então a resposta deve ser reduzir. A frase 2 menciona que um departamento específico de funcionários é afetado, portanto, a resposta deve ser funcionários. A frase 3 menciona que o CEO da empresa acredita que essas mudanças são necessárias para garantir a estabilidade e competitividade de longo prazo da empresa, então a resposta deve ser sustentabilidade. A frase 4 menciona que a empresa fornece indenizações e serviços de aconselhamento para ajudar os funcionários afetados na transição para um novo emprego, portanto, a resposta deve ser aconselhamento. Portanto, as respostas são (B) downsize, (E) funcionários, (L) sustentabilidade e (O) aconselhamento.",
            ans: ["(B)","(E)","(L)","(O)",],
            cns: "A empresa anunciou planos para reduzir sua força de trabalho em 10% em um esforço para reduzir custos. As demissões afetam principalmente os funcionários das funções administrativas e de suporte da empresa, embora alguns gerentes e executivos também sejam dispensados. O CEO da empresa disse que as mudanças são necessárias para garantir a sustentabilidade no longo prazo e manter a competitividade da empresa no mercado. A empresa fornecerá indenizações e serviços de orientação aos funcionários afetados para ajudá-los na transição para novos empregos."
        },{
            ars: "The _____ of the company's new product has been delayed due to manufacturing issues. The company had originally planned to launch the product in Q2, but now expects to release it in Q4. The delay has been _____ disappointing for the company, which had invested heavily in research and development and marketing efforts to support the launch. The company's management has reassured shareholders that the delay is temporary and that the product will be worth the wait, with features that are _____ superior to those of its competitors.",
            reals: "The launch of the company's new product has been delayed due to manufacturing issues. The company had originally planned to launch the product in Q2, but now expects to release it in Q4. The delay has been extremely disappointing for the company, which had invested heavily in research and development and marketing efforts to support the launch. The company's management has reassured shareholders that the delay is temporary and that the product will be worth the wait, with features that are significantly superior to those of its competitors.",
            sels: ["launch","design","development","testing","highly","somewhat","extremely","moderately","significantly","marginally","slightly","barely",],
            exps: "Este é um artigo sobre atrasos em novos produtos, os motivos dos atrasos e a resposta da empresa. Segue-se do contexto: A frase 1 menciona que o lançamento do produto está atrasado, então a resposta deve ser lançamento. A segunda frase mencionou que a empresa ficou muito decepcionada com esse atraso, então a resposta deveria ser extremamente. A frase 3 menciona que o produto terá funções superiores, então a resposta deve ser significativamente. Portanto, as respostas são (A) lançamento, (G) extremamente e (I) significativamente.",
            ans: ["(A)","(G)","(I)",],
            cns: "Lançamento, lançamento no mercado O novo produto da empresa foi adiado devido a problemas de fabricação. A empresa originalmente planejava lançar o produto no segundo trimestre, mas agora espera um lançamento no quarto trimestre. O atraso foi grande, o que é decepcionante para a empresa, que investiu pesadamente em P&D e marketing para dar suporte ao lançamento. A direção da empresa garantiu aos acionistas que o atraso é temporário e que o produto vale a pena esperar, com características diferenciadas em relação aos concorrentes."
        },{
            ars: "The hotel industry in the city has been experiencing a boom in recent years due to increased tourism. Many new hotels have _____ up in the city center, offering tourists a range of options at different price points. However, this growth has also led to increased _____ and competition among hotels, with some struggling to fill their rooms during off-peak seasons. To address this, many hotels have been _____ their services to appeal to a wider range of customers, such as offering discounted rates to business travelers and families.",
            reals: "The hotel industry in the city has been experiencing a boom in recent years due to increased tourism. Many new hotels have opened up in the city center, offering tourists a range of options at different price points. However, this growth has also led to increased supply and competition among hotels, with some struggling to fill their rooms during off-peak seasons. To address this, many hotels have been diversifying their services to appeal to a wider range of customers, such as offering discounted rates to business travelers and families.",
            sels: ["closed","opened","expanded","renovated","demand","supply","marketing","innovation","diversifying","outsourcing","downsizing","streamlining",],
            exps: "Este é um artigo sobre o desenvolvimento da indústria hoteleira na cidade, o artigo menciona o crescimento da indústria hoteleira e questões relacionadas. Pode-se concluir do contexto: A frase 1 menciona que a indústria hoteleira urbana floresceu nos últimos anos, então a resposta deve ser aberta. A frase 2 menciona que o crescimento também traz competição e excesso de oferta, então a resposta deve ser oferta. A frase 3 menciona que muitos hotéis estão ajustando seus serviços em resposta às mudanças do mercado, então a resposta deve ser diversificando. Portanto, as respostas são (B) aberta, (F) oferta e (I) diversificação.",
            ans: ["(B)","(F)","(I)",],
            cns: "Nos últimos anos, a hotelaria da cidade tem crescido graças ao crescimento do turismo. Muitos novos hotéis abriram no centro da cidade, oferecendo aos turistas uma variedade de opções em diferentes faixas de preço. No entanto, este crescimento também tem levado ao aumento da oferta e da concorrência entre os hotéis, com alguns hotéis a terem dificuldade em preencher os quartos durante a época baixa. Para combater isso, muitos hotéis diversificaram suas ofertas para atrair uma clientela mais ampla, oferecendo tarifas com desconto para viajantes a negócios e famílias."
        },{
            ars: "The pharmaceutical industry has come under increased scrutiny in recent years due to concerns about rising drug prices and the role of pharmaceutical companies in the opioid crisis. Many consumers are _____ to pay for medications that they need to maintain their health, leading to calls for greater government regulation of drug prices. Meanwhile, several pharmaceutical companies have faced lawsuits for their role in the opioid epidemic, with some accused of _____ their products and contributing to addiction and overdose deaths. In response, the industry has pledged to improve transparency and _____ in drug pricing and marketing practices.",
            reals: "The pharmaceutical industry has come under increased scrutiny in recent years due to concerns about rising drug prices and the role of pharmaceutical companies in the opioid crisis. Many consumers are reluctant to pay for medications that they need to maintain their health, leading to calls for greater government regulation of drug prices. Meanwhile, several pharmaceutical companies have faced lawsuits for their role in the opioid epidemic, with some accused of overpromoting their products and contributing to addiction and overdose deaths. In response, the industry has pledged to improve transparency and accountability in drug pricing and marketing practices.",
            sels: ["reluctant","eager","unwilling","hesitant","overpromoting","underpromoting","misrepresenting","falsifying","accountability","efficiency","innovation","profitability",],
            exps: "Este é um artigo sobre questões da indústria farmacêutica, com referências a questões como o aumento dos preços dos medicamentos e o papel das empresas farmacêuticas na crise dos opioides. Pode ser extraído do contexto: A frase 1 menciona que muitos consumidores não estão dispostos a pagar os altos preços dos medicamentos, portanto a resposta deve ser relutante. A frase 2 menciona que algumas empresas farmacêuticas foram acusadas de superpromover seus produtos, contribuindo para problemas como dependência e mortes por overdose, então a resposta deveria ser superpromoção. A frase três refere-se ao compromisso da indústria farmacêutica em melhorar a transparência e as práticas responsáveis ​​de preços e marketing de medicamentos, portanto, a resposta deve ser responsabilidade. Portanto, as respostas são (A) relutância, (E) superpromoção e (I) responsabilidade.",
            ans: ["(A)","(E)","(I)",],
            cns: "A indústria farmacêutica tem estado sob maior escrutínio nos últimos anos em meio a preocupações sobre o aumento dos preços dos medicamentos e o papel das empresas farmacêuticas na crise dos opioides. Muitos consumidores não estão dispostos a pagar pelos medicamentos de que precisam para manter a saúde, levando os governos a exigir maior regulamentação dos preços dos medicamentos. Enquanto isso, várias empresas farmacêuticas estão enfrentando processos judiciais por seu papel na epidemia de opioides, com algumas acusadas de promover demais seus produtos e causar dependência e mortes por overdose. Em resposta, a indústria se comprometeu a aumentar a transparência e a responsabilidade na precificação de medicamentos e nas práticas de marketing."
        },{
            ars: "In recent years, the global energy sector has undergone significant changes, driven by concerns about _____ and the need to reduce carbon emissions. As a result, many countries have implemented policies aimed at increasing the use of renewable energy sources, such as wind and solar power. This has led to a _____ in the renewable energy industry, with companies investing heavily in research and development to improve the efficiency and cost-effectiveness of their products. However, the shift towards renewable energy has not been without its _____, as some traditional energy companies have struggled to adapt to the changing market conditions.",
            reals: "In recent years, the global energy sector has undergone significant changes, driven by concerns about sustainability and the need to reduce carbon emissions. As a result, many countries have implemented policies aimed at increasing the use of renewable energy sources, such as wind and solar power. This has led to a surge in the renewable energy industry, with companies investing heavily in research and development to improve the efficiency and cost-effectiveness of their products. However, the shift towards renewable energy has not been without its challenges, as some traditional energy companies have struggled to adapt to the changing market conditions.",
            sels: ["sustainability","diversity","innovation","competition","surge","decline","stagnation","consolidation","challenges","opportunities","benefits","rewards",],
            exps: "Este é um artigo sobre a indústria global de energia, que menciona as mudanças na indústria e os desafios correspondentes. Pode ser extraído do contexto: A frase 1 menciona a preocupação com a sustentabilidade e a necessidade de reduzir as emissões de carbono, portanto a resposta deve ser sustentabilidade. A frase dois menciona o aumento na indústria de energia renovável, então a resposta deve ser aumento. A frase 3 mencionou a dificuldade das empresas tradicionais de energia se adaptarem às mudanças do mercado, então a resposta deveria ser “desafios”. Portanto, as respostas são (A) sustentabilidade, (E) aumento e (I) desafios.",
            ans: ["(A)","(E)","(I)",],
            cns: "Nos últimos anos, a indústria global de energia passou por grandes mudanças, impulsionadas por preocupações com a sustentabilidade e a necessidade de reduzir as emissões de carbono. Como resultado, muitos países implementaram políticas destinadas a aumentar o uso de fontes de energia renováveis, como eólica e solar. Isso levou a um aumento no setor de energia renovável, com empresas investindo pesadamente em pesquisa e desenvolvimento para melhorar a eficiência e o custo-benefício de seus produtos. No entanto, a transição para a energia renovável não foi isenta de desafios, pois algumas empresas tradicionais de energia têm lutado para se adaptar às mudanças nas condições do mercado."
        },{
            ars: "Over the past decade, advances in technology have transformed the way we live and work. One of the most significant changes has been the widespread adoption of _____ devices, such as smartphones and tablets. These devices have revolutionized the way we _____ information, allowing us to access a wealth of knowledge at our fingertips. However, they have also had a number of _____ effects, such as the erosion of face-to-face communication skills and the development of addiction to social media.",
            reals: "Over the past decade, advances in technology have transformed the way we live and work. One of the most significant changes has been the widespread adoption of mobile devices, such as smartphones and tablets. These devices have revolutionized the way we retrieve information, allowing us to access a wealth of knowledge at our fingertips. However, they have also had a number of detrimental effects, such as the erosion of face-to-face communication skills and the development of addiction to social media.",
            sels: ["mobile","wireless","digital","handheld","process","retrieve","disseminate","interpret","beneficial","detrimental","positive","negative",],
            exps: "Este é um artigo sobre mudança tecnológica, e o artigo menciona o impacto da mudança tecnológica na vida e no trabalho. Do contexto: A frase 1 menciona o uso generalizado de dispositivos móveis, como smartphones e tablets, portanto, a resposta deve ser mobile. A frase dois menciona a mudança revolucionária na aquisição de conhecimento usando esses dispositivos, então a resposta deve ser recuperar. O efeito negativo do uso desses dispositivos é mencionado na terceira frase, portanto a resposta deve ser prejudicial. Portanto, as respostas são (A) móvel, (F) recuperar e (J) prejudicial.",
            ans: ["(A)","(F)","(J)",],
            cns: "Na última década, os avanços tecnológicos transformaram a maneira como vivemos e trabalhamos. Uma das mudanças mais importantes é a adoção generalizada de dispositivos de Internet móvel, como smartphones e tablets. Esses dispositivos revolucionaram a maneira como recuperamos informações, colocando uma riqueza de conhecimento ao nosso alcance. No entanto, eles também têm efeitos deletérios, como a erosão das habilidades de comunicação face a face e o desenvolvimento do vício em mídias sociais."
        },{
            ars: "In recent years, businesses have increasingly turned to social media to _____ with their customers. Platforms like Facebook and Twitter offer companies a way to _____ with their audience in real-time, and can help to create a sense of community around a brand. However, social media also presents a number of _____, including the potential for negative feedback to spread quickly and damage a company's reputation.",
            reals: "In recent years, businesses have increasingly turned to social media to engage with their customers. Platforms like Facebook and Twitter offer companies a way to interact with their audience in real-time, and can help to create a sense of community around a brand. However, social media also presents a number of drawbacks, including the potential for negative feedback to spread quickly and damage a company's reputation.",
            sels: ["collaborate","engage","compete","negotiate","interact","market","advertise","promote","opportunities","challenges","benefits","drawbacks",],
            exps: "Este é um artigo sobre empresas que usam a mídia social para interagir com os clientes, o artigo menciona o impacto da mídia social nas empresas. Do contexto: A frase 1 menciona que as empresas estão usando cada vez mais as mídias sociais para interagir com os clientes, então a resposta deve ser engajar. A frase 2 mencionou que a mídia social pode ajudar as empresas a construir comunidades de marca, então a resposta deve ser interagir. A frase 3 menciona os riscos do uso de mídias sociais, então a resposta deve ser desvantagens. Portanto, a resposta é (B) envolver, (E) interagir e (L) desvantagens.",
            ans: ["(B)","(E)","(L)",],
            cns: "Nos últimos anos, as empresas têm se voltado cada vez mais para as mídias sociais para interagir com seus clientes. Plataformas como Facebook e Twitter oferecem às empresas uma forma interativa de se comunicar com seu público em tempo real e ajudam a criar um senso de comunidade em torno de uma marca. No entanto, a mídia social também tem algumas desvantagens, incluindo o potencial de feedback negativo se espalhar rapidamente e prejudicar a reputação de uma empresa."
        },{
            ars: "The hotel industry is experiencing a _____ in business due to the recent economic boom. With more people _____ disposable income, more and more individuals are choosing to travel and stay in hotels. In order to meet the demand, hotels are expanding their facilities and _____ their services to attract customers.",
            reals: "The hotel industry is experiencing a surge in business due to the recent economic boom. With more people spending disposable income, more and more individuals are choosing to travel and stay in hotels. In order to meet the demand, hotels are expanding their facilities and improving their services to attract customers.",
            sels: ["decline","stagnation","surge","fluctuation","having","earning","spending","saving","improving","reducing","limiting","discontinuing",],
            exps: "Este é um artigo sobre o crescimento do negócio hoteleiro.O artigo mencionou que à medida que a economia cresce e mais e mais pessoas optam por viajar e ficar em hotéis, há um aumento no negócio hoteleiro. A partir do contexto, segue-se que surge é mencionado na frase um, então a resposta deve ser (C) surge. A frase 2 menciona que, à medida que as pessoas gastam mais renda disponível, elas optam cada vez mais por viajar e ficar em hotéis, então a resposta deve ser (G) gastos. A frase 3 mencionou que para atender a demanda o hotel está ampliando suas instalações e “melhorando” seus serviços para atrair clientes, então a resposta deveria ser (I) melhorando. Portanto, as respostas são (C) aumento, (G) gastos e (I) melhoria.",
            ans: ["(C)","(G)","(I)",],
            cns: "A indústria da hospitalidade está experimentando um aumento na atividade comercial devido ao recente boom econômico. À medida que mais pessoas consomem Com o aumento da renda disponível, mais e mais pessoas optam por viajar e ficar em hotéis. Para atender a demanda, os hotéis estão ampliando suas instalações e melhorando seus serviços para atrair clientes."
        },{
            ars: "In recent years, online shopping has become increasingly popular among consumers. One of the biggest advantages of online shopping is that it allows customers to _____ items from the comfort of their own homes. This means that people can avoid the hassle of traffic and crowded stores. Additionally, online shopping often offers a wider variety of products than traditional retail stores, as well as _____ prices. Many retailers also offer free shipping or other _____ to encourage customers to shop online.",
            reals: "In recent years, online shopping has become increasingly popular among consumers. One of the biggest advantages of online shopping is that it allows customers to purchase items from the comfort of their own homes. This means that people can avoid the hassle of traffic and crowded stores. Additionally, online shopping often offers a wider variety of products than traditional retail stores, as well as lower prices. Many retailers also offer free shipping or other promotions to encourage customers to shop online.",
            sels: ["purchase","return","exchange","rent","lower","higher","fixed","fluctuating","promotions","warranties","discounts","contracts",],
            exps: "Este é um artigo sobre compras online. O artigo menciona as vantagens das compras online, incluindo conveniência, evitando trânsito e multidões, grande variedade de produtos, preços mais baixos, promoções oferecidas pelas lojas, frete grátis, etc. Pode ser extraído do contexto: A frase 1 menciona que as compras online permitem que as pessoas comprem mercadorias de casa, então a resposta deve ser (A) compra. A frase 2 menciona que uma das vantagens das compras online são os preços mais baixos, então a resposta deveria ser (E) mais baixo. A frase 3 menciona as promoções e frete grátis oferecidos pela loja, etc., então a resposta deve ser (I) promoções. Portanto, a resposta é (A) compra, (E) menor e (I) promoções.",
            ans: ["(A)","(E)","(I)",],
            cns: "Nos últimos anos, as compras online tornaram-se cada vez mais populares entre os consumidores. Uma das maiores vantagens das compras online é permitir que os clientes comprem itens no conforto de suas próprias casas. Isso significa que as pessoas podem evitar o incômodo do trânsito e das lojas lotadas. Além disso, as compras online geralmente oferecem uma variedade maior de produtos do que as lojas de varejo tradicionais e a preços mais baixos. Muitos varejistas também oferecem frete grátis ou outras promoções para incentivar os clientes a comprar online."
        },{
            ars: "The hospitality industry, which includes hotels, restaurants, and catering services, plays a crucial role in the global economy. As international travel continues to _____, the demand for hotels and restaurants has increased. In addition, many people today prefer to _____ out or order in rather than cook at home. This has led to a growth in the number of restaurants and catering services, both small and large.When it comes to hotels, there are a wide variety of options available to travelers. From luxury hotels to budget accommodations, there is something for every _____ of traveler. Many hotels now offer additional amenities such as fitness centers, swimming pools, and complimentary breakfast. In order to stay competitive, hotels must also keep up with the latest technologies, such as online reservation systems and mobile check-in options.",
            reals: "The hospitality industry, which includes hotels, restaurants, and catering services, plays a crucial role in the global economy. As international travel continues to increase, the demand for hotels and restaurants has increased. In addition, many people today prefer to dine out or order in rather than cook at home. This has led to a growth in the number of restaurants and catering services, both small and large.When it comes to hotels, there are a wide variety of options available to travelers. From luxury hotels to budget accommodations, there is something for every category of traveler. Many hotels now offer additional amenities such as fitness centers, swimming pools, and complimentary breakfast. In order to stay competitive, hotels must also keep up with the latest technologies, such as online reservation systems and mobile check-in options.",
            sels: ["decrease","stagnate","increase","fluctuate","eat","dine","take","make","kind","level","group","category",],
            exps: "Este é um artigo sobre a indústria de restaurantes e hotelaria. O artigo menciona que, à medida que o turismo internacional aumenta, também aumenta a demanda por hotéis e restaurantes. Ao mesmo tempo, mais e mais pessoas estão optando por comer fora ou pedir comida para entrega, então o número de restaurantes e serviços de catering também está crescendo. Além disso, os hotéis também oferecem uma variedade de opções, incluindo hotéis de luxo e acomodações econômicas, etc., e para se manterem competitivos, os hotéis também devem acompanhar a tecnologia mais recente. A frase 1 menciona que à medida que o turismo internacional aumenta, também aumenta a demanda por hotéis e restaurantes, então a resposta deve ser (C) aumentar. A frase 2 menciona que cada vez mais pessoas optam por comer fora ou pedir comida no delivery, então a resposta deve ser (F) jantar. A frase 3 menciona que o hotel oferece várias opções, incluindo hotéis de luxo e acomodações econômicas etc., portanto, a resposta deve ser a categoria (L). Portanto, as respostas são (C) aumentar, (F) jantar e (L) categoria.",
            ans: ["(C)","(F)","(L)",],
            cns: "A indústria hoteleira, incluindo hotéis, restaurantes e serviços de alimentação, desempenha um papel vital na economia global. Como as viagens internacionais continuam a aumentar, a demanda por hotéis e restaurantes também aumentou. Além disso, muitas pessoas hoje preferem jantar fora ou fazer pedidos em vez de cozinhar em casa. Isso levou a um aumento no número de grandes e pequenos restaurantes e serviços de alimentação. Quando se trata de hotéis, os viajantes têm uma variedade de opções. De hotéis de luxo a acomodações econômicas, há algo para cada categoria de viajante. Muitos hotéis agora oferecem comodidades extras, como academias de ginástica, piscinas e café da manhã gratuito. Para se manterem competitivos, os hotéis também devem acompanhar as tecnologias mais recentes, como sistemas de reserva online e opções de check-in móvel."
        },]