export const ru = [{
            ars: "The new restaurant in town is already causing quite a _____ with its unique menu and elegant atmosphere. The restaurant's owner, a well-known chef, has created a _____ dining experience that is both delicious and memorable. The restaurant offers a wide variety of dishes, ranging from classic comfort food to exotic _____ from around the world. Customers can choose to dine in the main dining room or in a more intimate private _____ for special occasions. The restaurant also offers catering services for corporate events and private parties.",
            reals: "The new restaurant in town is already causing quite a stir with its unique menu and elegant atmosphere. The restaurant's owner, a well-known chef, has created a refined dining experience that is both delicious and memorable. The restaurant offers a wide variety of dishes, ranging from classic comfort food to exotic delicacies from around the world. Customers can choose to dine in the main dining room or in a more intimate private booth for special occasions. The restaurant also offers catering services for corporate events and private parties.",
            sels: ["stir","steer","stare","store","refined","delightful","extravagant","delicate","delicacies","spices","beverages","desserts","booth","chamber","lounge","terrace",],
            exps: "Это статья о новом ресторане с упоминанием меню и атмосферы ресторана. Из контекста: в первом предложении упоминается уникальное меню ресторана и элегантная обстановка, поэтому ответ должен быть перемешивание. В предложении 2 упоминается, что блюда в ресторане вкусные и запоминающиеся, поэтому ответ следует уточнить. В предложении 3 упоминается, что в ресторане подают широкий выбор блюд, включая классическую домашнюю еду и экзотические кухни со всего мира, поэтому ответ должен быть «деликатесы». Четвертое предложение относится к приватной столовой, которую предлагает ресторан, поэтому ответ должен быть «кабинка». Следовательно, ответы: (А) размешать, (Д) изысканно, (I) деликатесы и (М) будка.",
            ans: ["(A)","(E)","(I)","(M)",],
            cns: "Новый ресторан в городе уже вызывает ажиотаж своим уникальным меню и элегантной обстановкой. Владелец ресторана — известный шеф-повар, создавший изысканную кухню, вкусную и запоминающуюся. Ресторан предлагает широкий выбор блюд, от классических комфортных блюд до экзотических блюд со всего мира. Посетители могут поужинать в главном обеденном зале или в более интимных ложах для особых случаев. Ресторан также обслуживает корпоративные мероприятия и частные вечеринки."
        },{
            ars: "The new marketing campaign has been _____ successful, with sales increasing by 20% since its launch. The campaign's focus on social media has helped the company reach a wider _____, particularly among younger consumers who spend a lot of time on their phones. The company's _____ strategy, which includes targeted ads and influencer partnerships, has also contributed to its success. However, the company's _____ has also played a role in the campaign's success, as its reputation for high-quality products has helped build trust with customers.",
            reals: "The new marketing campaign has been tremendously successful, with sales increasing by 20% since its launch. The campaign's focus on social media has helped the company reach a wider audience, particularly among younger consumers who spend a lot of time on their phones. The company's promotion strategy, which includes targeted ads and influencer partnerships, has also contributed to its success. However, the company's reputation has also played a role in the campaign's success, as its reputation for high-quality products has helped build trust with customers.",
            sels: ["moderately","tremendously","barely","slightly","audience","market","sector","niche","pricing","promotion","distribution","packaging","innovation","reputation","location","convenience",],
            exps: "Это статья о маркетинговой кампании, в которой упоминается, почему кампания была успешной. Из контекста следует, что успех кампании упоминается в первом предложении, поэтому ответ должен быть «чрезвычайно». В предложении 2 упоминается, что мероприятие особенно популярно среди молодых потребителей, поэтому ответ должен быть «аудитория». Стратегия кампании упоминается в третьем предложении, включая таргетированную рекламу и сотрудничество с влиятельными лицами, поэтому ответ должен быть «продвижение». Репутация компании упоминается в четвертом предложении, что помогает завоевать доверие клиентов, поэтому ответ должен быть «репутация». Итак, ответы: (B) чрезвычайно, (E) аудитория, (J) продвижение и (N) репутация.",
            ans: ["(B)","(E)","(J)","(N)",],
            cns: "Новая маркетинговая кампания имела огромный успех: с момента запуска продажи выросли на 20%. Ориентация кампании на социальные сети помогла компании охватить более широкую аудиторию, особенно среди молодых потребителей, которые проводят много времени со своими телефонами. Стратегии корпоративной рекламы, включая таргетированную рекламу и партнерские отношения с влиятельными лицами, также способствовали его успеху. Тем не менее, репутация компании также играет роль в успехе мероприятия, поскольку ее репутация в отношении высококачественных продуктов помогает завоевать доверие клиентов."
        },{
            ars: "The company has announced plans to _____ its workforce by 10% in an effort to reduce costs. The layoffs will primarily affect _____ in the company's administrative and support departments, although some managers and executives will also be let go. The company's CEO has stated that these changes are necessary to ensure the long-term _____ of the company and maintain its competitiveness in the marketplace. The company will provide severance packages and _____ services to affected employees to help them transition to new employment.",
            reals: "The company has announced plans to downsize its workforce by 10% in an effort to reduce costs. The layoffs will primarily affect employees in the company's administrative and support departments, although some managers and executives will also be let go. The company's CEO has stated that these changes are necessary to ensure the long-term sustainability of the company and maintain its competitiveness in the marketplace. The company will provide severance packages and counseling services to affected employees to help them transition to new employment.",
            sels: ["expand","downsize","diversify","centralize","employees","shareholders","customers","suppliers","profitability","stability","flexibility","sustainability","relocation","retraining","counseling","mentoring",],
            exps: "Это статья о плане увольнений компании, и в статье упоминаются причины и последствия этого плана. Из контекста можно сделать вывод: в предложении 1 упоминается план компании по сокращению штата, поэтому ответ должен быть «сокращение». В предложении 2 упоминается, что затрагивается конкретный отдел сотрудников, поэтому ответ должен быть «сотрудники». В предложении 3 упоминается, что генеральный директор компании считает, что эти изменения необходимы для обеспечения долгосрочной стабильности и конкурентоспособности компании, поэтому ответом должно быть «устойчивое развитие». В предложении 4 упоминается, что компания предоставляет выходное пособие и консультационные услуги, чтобы помочь пострадавшим сотрудникам перейти на новую работу, поэтому ответ должен быть «консультирование». Таким образом, ответы: (B) сокращение штата, (E) сотрудники, (L) устойчивость и (O) консультирование.",
            ans: ["(B)","(E)","(L)","(O)",],
            cns: "Компания объявила о планах сократить штат сотрудников на 10%, чтобы сократить расходы. Увольнения в первую очередь коснутся сотрудников, занимающих административные и вспомогательные функции компании, хотя некоторые менеджеры и руководители также будут уволены. Генеральный директор компании заявил, что изменения необходимы для обеспечения долгосрочной устойчивости и сохранения конкурентоспособности компании на рынке. Компания предоставит выходное пособие и услуги наставничества пострадавшим сотрудникам, чтобы помочь им перейти на новую работу."
        },{
            ars: "The _____ of the company's new product has been delayed due to manufacturing issues. The company had originally planned to launch the product in Q2, but now expects to release it in Q4. The delay has been _____ disappointing for the company, which had invested heavily in research and development and marketing efforts to support the launch. The company's management has reassured shareholders that the delay is temporary and that the product will be worth the wait, with features that are _____ superior to those of its competitors.",
            reals: "The launch of the company's new product has been delayed due to manufacturing issues. The company had originally planned to launch the product in Q2, but now expects to release it in Q4. The delay has been extremely disappointing for the company, which had invested heavily in research and development and marketing efforts to support the launch. The company's management has reassured shareholders that the delay is temporary and that the product will be worth the wait, with features that are significantly superior to those of its competitors.",
            sels: ["launch","design","development","testing","highly","somewhat","extremely","moderately","significantly","marginally","slightly","barely",],
            exps: "Это статья о задержках новых продуктов, причинах задержек и реакции компании. Из контекста следует: в предложении 1 упоминается, что выпуск продукта задерживается, поэтому ответ должен быть «запуск». Во втором предложении упоминается, что компания очень разочарована этой задержкой, поэтому ответ должен быть «крайне». В предложении 3 упоминается, что продукт будет иметь более высокие функции, поэтому ответ должен быть «значительно». Таким образом, ответы: (A) запустить, (G) чрезвычайно, и (I) значительно.",
            ans: ["(A)","(G)","(I)",],
            cns: "Запуск, выход на рынок Новый продукт компании задерживается из-за производственных проблем. Изначально компания планировала запустить продукт во втором квартале, но теперь ожидает релиза в четвертом квартале. Задержка была серьезной, что разочаровывает компанию, которая вложила значительные средства в исследования и разработки и маркетинг для поддержки запуска. Руководство компании заверило акционеров, что задержка носит временный характер и что продукт стоит того, чтобы подождать, поскольку он обладает заметными характеристиками по сравнению с конкурентами."
        },{
            ars: "The hotel industry in the city has been experiencing a boom in recent years due to increased tourism. Many new hotels have _____ up in the city center, offering tourists a range of options at different price points. However, this growth has also led to increased _____ and competition among hotels, with some struggling to fill their rooms during off-peak seasons. To address this, many hotels have been _____ their services to appeal to a wider range of customers, such as offering discounted rates to business travelers and families.",
            reals: "The hotel industry in the city has been experiencing a boom in recent years due to increased tourism. Many new hotels have opened up in the city center, offering tourists a range of options at different price points. However, this growth has also led to increased supply and competition among hotels, with some struggling to fill their rooms during off-peak seasons. To address this, many hotels have been diversifying their services to appeal to a wider range of customers, such as offering discounted rates to business travelers and families.",
            sels: ["closed","opened","expanded","renovated","demand","supply","marketing","innovation","diversifying","outsourcing","downsizing","streamlining",],
            exps: "Это статья о развитии гостиничного хозяйства в городе, в статье упоминается рост гостиничного хозяйства и сопутствующие вопросы. Из контекста можно сделать вывод: в предложении 1 упоминается, что городская гостиничная индустрия в последние годы процветала, поэтому ответ должен быть «открытым». В предложении 2 упоминается, что рост также приводит к конкуренции и избыточному предложению, поэтому ответ должен быть «предложение». В предложении 3 упоминается, что многие отели корректируют свои услуги в ответ на изменения рынка, поэтому ответ должен быть «диверсификация». Таким образом, ответы: (B) открытое, (F) предложение и (I) диверсифицирующее.",
            ans: ["(B)","(F)","(I)",],
            cns: "В последние годы гостиничная индустрия города переживает бум благодаря росту туризма. В центре города открылось много новых отелей, предлагающих туристам разнообразные варианты в разной ценовой категории. Однако этот рост также привел к увеличению предложения и конкуренции среди отелей, при этом некоторые отели изо всех сил пытаются заполнить номера в межсезонье. Чтобы бороться с этим, многие отели диверсифицировали свои предложения, чтобы привлечь внимание более широкой клиентуры, например, предлагая скидки для деловых путешественников и семей."
        },{
            ars: "The pharmaceutical industry has come under increased scrutiny in recent years due to concerns about rising drug prices and the role of pharmaceutical companies in the opioid crisis. Many consumers are _____ to pay for medications that they need to maintain their health, leading to calls for greater government regulation of drug prices. Meanwhile, several pharmaceutical companies have faced lawsuits for their role in the opioid epidemic, with some accused of _____ their products and contributing to addiction and overdose deaths. In response, the industry has pledged to improve transparency and _____ in drug pricing and marketing practices.",
            reals: "The pharmaceutical industry has come under increased scrutiny in recent years due to concerns about rising drug prices and the role of pharmaceutical companies in the opioid crisis. Many consumers are reluctant to pay for medications that they need to maintain their health, leading to calls for greater government regulation of drug prices. Meanwhile, several pharmaceutical companies have faced lawsuits for their role in the opioid epidemic, with some accused of overpromoting their products and contributing to addiction and overdose deaths. In response, the industry has pledged to improve transparency and accountability in drug pricing and marketing practices.",
            sels: ["reluctant","eager","unwilling","hesitant","overpromoting","underpromoting","misrepresenting","falsifying","accountability","efficiency","innovation","profitability",],
            exps: "Это статья о проблемах фармацевтической промышленности со ссылками на такие вопросы, как рост цен на лекарства и роль фармацевтических компаний в опиоидном кризисе. Это можно понять из контекста: в предложении 1 упоминается, что многие потребители не желают платить большие деньги за лекарства, поэтому ответ должен быть «неохотно». В предложении 2 упоминается, что некоторые фармацевтические компании обвиняются в чрезмерном продвижении своей продукции, способствуя таким проблемам, как зависимость и смерть от передозировки, поэтому ответ должен быть «чрезмерное продвижение». Третье предложение относится к стремлению фармацевтической промышленности к повышению прозрачности и ответственному ценообразованию и маркетингу лекарств, поэтому ответ должен быть «подотчетность». Таким образом, ответы: (А) неохота, (Д) чрезмерное продвижение и (I) ответственность.",
            ans: ["(A)","(E)","(I)",],
            cns: "Фармацевтическая промышленность в последние годы стала объектом повышенного внимания из-за опасений по поводу роста цен на лекарства и роли фармацевтических компаний в опиоидном кризисе. Многие потребители не желают платить за лекарства, необходимые им для поддержания здоровья, что заставляет правительства призывать к более строгому регулированию цен на лекарства. Между тем, несколько фармацевтических компаний столкнулись с судебными исками из-за своей роли в опиоидной эпидемии, причем некоторые из них обвиняются в чрезмерном продвижении своей продукции, вызывании зависимости и смерти от передозировки. В ответ отрасль обязалась повысить прозрачность и подотчетность ценообразования и маркетинга лекарственных средств."
        },{
            ars: "In recent years, the global energy sector has undergone significant changes, driven by concerns about _____ and the need to reduce carbon emissions. As a result, many countries have implemented policies aimed at increasing the use of renewable energy sources, such as wind and solar power. This has led to a _____ in the renewable energy industry, with companies investing heavily in research and development to improve the efficiency and cost-effectiveness of their products. However, the shift towards renewable energy has not been without its _____, as some traditional energy companies have struggled to adapt to the changing market conditions.",
            reals: "In recent years, the global energy sector has undergone significant changes, driven by concerns about sustainability and the need to reduce carbon emissions. As a result, many countries have implemented policies aimed at increasing the use of renewable energy sources, such as wind and solar power. This has led to a surge in the renewable energy industry, with companies investing heavily in research and development to improve the efficiency and cost-effectiveness of their products. However, the shift towards renewable energy has not been without its challenges, as some traditional energy companies have struggled to adapt to the changing market conditions.",
            sels: ["sustainability","diversity","innovation","competition","surge","decline","stagnation","consolidation","challenges","opportunities","benefits","rewards",],
            exps: "Это статья о мировой энергетике, в которой упоминаются изменения в отрасли и соответствующие вызовы. Это можно понять из контекста: в предложении 1 упоминается забота об устойчивости и необходимости сокращения выбросов углерода, поэтому ответ должен быть «устойчивость». Во втором предложении упоминается всплеск в отрасли возобновляемых источников энергии, поэтому ответ должен быть «всплеск». В предложении 3 упоминается, что традиционным энергетическим компаниям сложно адаптироваться к рыночным изменениям, поэтому ответ должен быть «вызовы». Таким образом, ответы таковы: (A) устойчивость, (E) всплеск и (I) проблемы.",
            ans: ["(A)","(E)","(I)",],
            cns: "В последние годы мировая энергетическая отрасль претерпела серьезные изменения, вызванные заботой об устойчивости и необходимостью сокращения выбросов углерода. В результате многие страны внедрили политику, направленную на увеличение использования возобновляемых источников энергии, таких как ветер и солнечная энергия. Это привело к резкому росту отрасли возобновляемых источников энергии, когда компании вкладывают значительные средства в исследования и разработки, чтобы повысить эффективность и рентабельность своей продукции. Однако переход на возобновляемые источники энергии не обошелся без проблем, поскольку некоторые традиционные энергетические компании с трудом адаптировались к изменяющимся рыночным условиям."
        },{
            ars: "Over the past decade, advances in technology have transformed the way we live and work. One of the most significant changes has been the widespread adoption of _____ devices, such as smartphones and tablets. These devices have revolutionized the way we _____ information, allowing us to access a wealth of knowledge at our fingertips. However, they have also had a number of _____ effects, such as the erosion of face-to-face communication skills and the development of addiction to social media.",
            reals: "Over the past decade, advances in technology have transformed the way we live and work. One of the most significant changes has been the widespread adoption of mobile devices, such as smartphones and tablets. These devices have revolutionized the way we retrieve information, allowing us to access a wealth of knowledge at our fingertips. However, they have also had a number of detrimental effects, such as the erosion of face-to-face communication skills and the development of addiction to social media.",
            sels: ["mobile","wireless","digital","handheld","process","retrieve","disseminate","interpret","beneficial","detrimental","positive","negative",],
            exps: "Это статья о технологических изменениях, и в статье упоминается влияние технологических изменений на жизнь и работу. Из контекста: в предложении 1 упоминается широкое использование мобильных устройств, таких как смартфоны и планшеты, поэтому ответ должен быть «мобильным». Во втором предложении упоминаются революционные изменения в получении знаний с помощью этих устройств, поэтому ответ должен быть «извлечение». Отрицательный эффект от использования этих устройств упоминается в третьем предложении, поэтому ответ должен быть «вредным». Таким образом, ответы: (A) мобильный, (F) извлекающий и (J) вредный.",
            ans: ["(A)","(F)","(J)",],
            cns: "За последнее десятилетие достижения в области технологий изменили то, как мы живем и работаем. Одним из наиболее важных изменений является широкое распространение мобильных интернет-устройств, таких как смартфоны и планшеты. Эти устройства произвели революцию в том, как мы извлекаем информацию, предоставив нам огромное количество знаний. Однако они также имеют пагубные последствия, такие как ухудшение навыков общения лицом к лицу и развитие зависимости от социальных сетей."
        },{
            ars: "In recent years, businesses have increasingly turned to social media to _____ with their customers. Platforms like Facebook and Twitter offer companies a way to _____ with their audience in real-time, and can help to create a sense of community around a brand. However, social media also presents a number of _____, including the potential for negative feedback to spread quickly and damage a company's reputation.",
            reals: "In recent years, businesses have increasingly turned to social media to engage with their customers. Platforms like Facebook and Twitter offer companies a way to interact with their audience in real-time, and can help to create a sense of community around a brand. However, social media also presents a number of drawbacks, including the potential for negative feedback to spread quickly and damage a company's reputation.",
            sels: ["collaborate","engage","compete","negotiate","interact","market","advertise","promote","opportunities","challenges","benefits","drawbacks",],
            exps: "Это статья о компаниях, использующих социальные сети для взаимодействия с клиентами, в статье упоминается влияние социальных сетей на бизнес. Из контекста: в предложении 1 упоминается, что компании все чаще используют социальные сети для взаимодействия с клиентами, поэтому ответ должен быть «вовлечение». В предложении 2 упоминается, что социальные сети могут помочь компаниям создавать сообщества брендов, поэтому ответ должен быть «взаимодействовать». В предложении 3 упоминаются риски использования социальных сетей, поэтому ответ должен быть «недостатки». Таким образом, ответ: (B) заниматься, (E) взаимодействовать и (L) недостатки.",
            ans: ["(B)","(E)","(L)",],
            cns: "В последние годы компании все чаще обращаются к социальным сетям для взаимодействия со своими клиентами. Такие платформы, как Facebook и Twitter, предлагают компаниям интерактивный способ общения со своей аудиторией в режиме реального времени и помогают создать ощущение общности вокруг бренда. Однако социальные сети также имеют некоторые недостатки, в том числе возможность быстрого распространения негативных отзывов и нанесения ущерба репутации компании."
        },{
            ars: "The hotel industry is experiencing a _____ in business due to the recent economic boom. With more people _____ disposable income, more and more individuals are choosing to travel and stay in hotels. In order to meet the demand, hotels are expanding their facilities and _____ their services to attract customers.",
            reals: "The hotel industry is experiencing a surge in business due to the recent economic boom. With more people spending disposable income, more and more individuals are choosing to travel and stay in hotels. In order to meet the demand, hotels are expanding their facilities and improving their services to attract customers.",
            sels: ["decline","stagnation","surge","fluctuation","having","earning","spending","saving","improving","reducing","limiting","discontinuing",],
            exps: "Это статья о росте гостиничного бизнеса. В статье упоминается, что по мере того, как экономика процветает и все больше и больше людей предпочитают путешествовать и останавливаться в отелях, в гостиничном бизнесе наблюдается «всплеск». Из контекста следует, что в первом предложении упоминается «всплеск», поэтому ответ должен быть (С) всплеск. В предложении 2 упоминается, что по мере того, как люди «тратят» больше располагаемого дохода, они все чаще предпочитают путешествовать и останавливаться в отелях, поэтому ответ должен быть (G) расходы. В предложении 3 упоминается, что для удовлетворения спроса отель расширяет свои возможности и «улучшает» свои услуги для привлечения клиентов, поэтому ответ должен быть (I) улучшением. Таким образом, ответы: (C) всплеск, (G) расходы и (I) улучшение.",
            ans: ["(C)","(G)","(I)",],
            cns: "Индустрия гостеприимства переживает всплеск деловой активности из-за недавнего экономического бума. По мере того, как все больше и больше людей потребляют С увеличением располагаемого дохода, все больше и больше людей предпочитают путешествовать и останавливаться в отелях. Чтобы удовлетворить спрос, отели расширяют свои возможности и улучшают свои услуги для привлечения клиентов."
        },{
            ars: "In recent years, online shopping has become increasingly popular among consumers. One of the biggest advantages of online shopping is that it allows customers to _____ items from the comfort of their own homes. This means that people can avoid the hassle of traffic and crowded stores. Additionally, online shopping often offers a wider variety of products than traditional retail stores, as well as _____ prices. Many retailers also offer free shipping or other _____ to encourage customers to shop online.",
            reals: "In recent years, online shopping has become increasingly popular among consumers. One of the biggest advantages of online shopping is that it allows customers to purchase items from the comfort of their own homes. This means that people can avoid the hassle of traffic and crowded stores. Additionally, online shopping often offers a wider variety of products than traditional retail stores, as well as lower prices. Many retailers also offer free shipping or other promotions to encourage customers to shop online.",
            sels: ["purchase","return","exchange","rent","lower","higher","fixed","fluctuating","promotions","warranties","discounts","contracts",],
            exps: "Это статья о покупках в Интернете, в которой упоминаются преимущества покупок в Интернете, в том числе удобство, отсутствие трафика и толпы, широкий ассортимент товаров, более низкие цены, акции, предлагаемые магазинами, бесплатная доставка и т. д. Это можно понять из контекста: в предложении 1 упоминается, что интернет-магазины позволяют людям покупать товары из дома, поэтому ответ должен быть (А) покупка. В предложении 2 упоминается, что одним из преимуществ онлайн-покупок являются более низкие цены, поэтому ответ должен быть (Е) ниже. В предложении 3 упоминаются рекламные акции и бесплатная доставка, предлагаемые магазином и т. д., поэтому ответ должен быть (I) рекламные акции. Таким образом, ответ: (A) покупка, (E) снижение и (I) продвижение по службе.",
            ans: ["(A)","(E)","(I)",],
            cns: "В последние годы онлайн-покупки становятся все более популярными среди потребителей. Одним из самых больших преимуществ онлайн-покупок является то, что они позволяют покупателям покупать товары, не выходя из собственного дома. Это означает, что люди могут избежать пробок и переполненных магазинов. Кроме того, интернет-магазины часто предлагают более широкий ассортимент товаров, чем традиционные розничные магазины, и по более низким ценам. Многие розничные продавцы также предлагают бесплатную доставку или другие акции, чтобы побудить клиентов делать покупки в Интернете."
        },{
            ars: "The hospitality industry, which includes hotels, restaurants, and catering services, plays a crucial role in the global economy. As international travel continues to _____, the demand for hotels and restaurants has increased. In addition, many people today prefer to _____ out or order in rather than cook at home. This has led to a growth in the number of restaurants and catering services, both small and large.When it comes to hotels, there are a wide variety of options available to travelers. From luxury hotels to budget accommodations, there is something for every _____ of traveler. Many hotels now offer additional amenities such as fitness centers, swimming pools, and complimentary breakfast. In order to stay competitive, hotels must also keep up with the latest technologies, such as online reservation systems and mobile check-in options.",
            reals: "The hospitality industry, which includes hotels, restaurants, and catering services, plays a crucial role in the global economy. As international travel continues to increase, the demand for hotels and restaurants has increased. In addition, many people today prefer to dine out or order in rather than cook at home. This has led to a growth in the number of restaurants and catering services, both small and large.When it comes to hotels, there are a wide variety of options available to travelers. From luxury hotels to budget accommodations, there is something for every category of traveler. Many hotels now offer additional amenities such as fitness centers, swimming pools, and complimentary breakfast. In order to stay competitive, hotels must also keep up with the latest technologies, such as online reservation systems and mobile check-in options.",
            sels: ["decrease","stagnate","increase","fluctuate","eat","dine","take","make","kind","level","group","category",],
            exps: "Это статья о ресторанном и гостиничном бизнесе. В статье отмечается, что по мере роста международного туризма растет и спрос на гостиницы и рестораны. В то же время все больше людей предпочитают питаться вне дома или заказывать доставку еды, поэтому количество ресторанов и служб общественного питания также растет. Кроме того, отели также предлагают множество вариантов, включая роскошные отели и бюджетное размещение и т. д., и, чтобы оставаться конкурентоспособными, отели также должны идти в ногу с новейшими технологиями. В предложении 1 упоминается, что по мере роста международного туризма растет и спрос на отели и рестораны, поэтому ответ должен быть (С) увеличивается. В предложении 2 упоминается, что все больше и больше людей предпочитают питаться вне дома или заказывать еду с доставкой, поэтому ответ должен быть (F) пообедать. В предложении 3 упоминается, что отель предлагает различные варианты, включая роскошные отели и бюджетное размещение и т. д., поэтому ответ должен быть категории (L). Следовательно, ответы: (C) увеличение, (F) обед и (L) категория.",
            ans: ["(C)","(F)","(L)",],
            cns: "Индустрия гостеприимства, включая гостиницы, рестораны и предприятия общественного питания, играет жизненно важную роль в мировой экономике. Поскольку количество международных поездок продолжает расти, спрос на отели и рестораны увеличился. Кроме того, многие люди сегодня предпочитают обедать вне дома или заказывать еду, а не готовить дома. Это привело к увеличению количества больших и малых ресторанов и предприятий общественного питания. Когда дело доходит до отелей, у путешественников есть множество вариантов. От роскошных отелей до бюджетного жилья — здесь найдется что-то для каждой категории путешественников. Многие отели теперь предлагают дополнительные удобства, такие как фитнес-центры, бассейны и бесплатный завтрак. Чтобы оставаться конкурентоспособными, отели также должны идти в ногу с новейшими технологиями, такими как системы онлайн-бронирования и возможности мобильной регистрации."
        },]