export const q = [{
    ars: "The new restaurant in town is already causing quite a _____ with its unique menu and elegant atmosphere. The restaurant's owner, a well-known chef, has created a _____ dining experience that is both delicious and memorable. The restaurant offers a wide variety of dishes, ranging from classic comfort food to exotic _____ from around the world. Customers can choose to dine in the main dining room or in a more intimate private _____ for special occasions. The restaurant also offers catering services for corporate events and private parties.",
    reals: "The new restaurant in town is already causing quite a stir with its unique menu and elegant atmosphere. The restaurant's owner, a well-known chef, has created a refined dining experience that is both delicious and memorable. The restaurant offers a wide variety of dishes, ranging from classic comfort food to exotic delicacies from around the world. Customers can choose to dine in the main dining room or in a more intimate private booth for special occasions. The restaurant also offers catering services for corporate events and private parties.",
    sels: [" stir", " steer", " stare", " store", " refined", " delightful", " extravagant", " delicate", " delicacies", " spices", " beverages", " desserts", " booth", " chamber", " lounge", " terrace",],
    exps: "這是一篇關於一家新餐廳的文章，文章提到了該餐廳的菜單和氛圍。從上下文中可以得出：句子一中提到了餐廳的獨特菜單和優雅的氛圍，因此答案應該是「stir」。句子二中提到了該餐廳的菜品美味而且難忘，因此答案應該是「refined」。句子三中提到了該餐廳提供的菜品種類很多，包括經典舒適食物和世界各地的異國美食，因此答案應該是「delicacies」。句子四中提到了該餐廳提供的私人用餐區，因此答案應該是「booth」。因此，答案為 (A) stir、(E) refined、(I) delicacies 和 (M) booth。",
    ans: ["(A)", "(E)", "(I)", "(M)",],
    cns: "鎮上的新餐廳已經引起了不小的轟動 以其獨特的菜單和優雅的氛圍。餐廳的老闆是一位知名廚師，他創造了一個精緻的 既美味又難忘的用餐體驗。餐廳提供種類繁多的菜餚，從經典的舒適食品到異國風味的美食 來自世界各地的。顧客可以選擇在主餐廳或更私密的包廂用餐 特殊場合。餐廳還為企業活動和私人聚會提供餐飲服務。"
}, {
    ars: "The new marketing campaign has been _____ successful, with sales increasing by 20% since its launch. The campaign's focus on social media has helped the company reach a wider _____, particularly among younger consumers who spend a lot of time on their phones. The company's _____ strategy, which includes targeted ads and influencer partnerships, has also contributed to its success. However, the company's _____ has also played a role in the campaign's success, as its reputation for high-quality products has helped build trust with customers.",
    reals: "The new marketing campaign has been tremendously successful, with sales increasing by 20% since its launch. The campaign's focus on social media has helped the company reach a wider audience, particularly among younger consumers who spend a lot of time on their phones. The company's promotion strategy, which includes targeted ads and influencer partnerships, has also contributed to its success. However, the company's reputation has also played a role in the campaign's success, as its reputation for high-quality products has helped build trust with customers.",
    sels: [" moderately", " tremendously", " barely", " slightly", " audience", " market", " sector", " niche", " pricing", " promotion", " distribution", " packaging", " innovation", " reputation", " location", " convenience",],
    exps: "這是一篇關於市場營銷活動的文章，文章提到了這個活動的成功原因。從上下文中可以得出：句子一中提到了該活動的成功，因此答案應該是「tremendously」。句子二中提到了該活動尤其受到了年輕消費者的歡迎，因此答案應該是「audience」。句子三中提到了該活動的策略，包括有針對性的廣告和影響者合作，因此答案應該是「promotion」。句子四中提到了公司的聲譽，這有助於建立客戶的信任，因此答案應該是「reputation」。因此，答案為 (B) tremendously、(E) audience、(J) promotion 和 (N) reputation。",
    ans: ["(B)", "(E)", "(J)", "(N)",],
    cns: "新的營銷活動取得了巨大的成功 成功，自推出以來銷售額增長了 20%。該活動對社交媒體的關注幫助該公司覆蓋了更廣泛的受眾，尤其是在手機上花費大量時間的年輕消費者中。公司宣傳 包括有針對性的廣告和有影響力的合作夥伴關係在內的戰略也為其成功做出了貢獻。但是，公司的聲譽 也為活動的成功發揮了作用，因為其高質量產品的聲譽有助於建立客戶的信任。"
}, {
    ars: "The company has announced plans to _____ its workforce by 10% in an effort to reduce costs. The layoffs will primarily affect _____ in the company's administrative and support departments, although some managers and executives will also be let go. The company's CEO has stated that these changes are necessary to ensure the long-term _____ of the company and maintain its competitiveness in the marketplace. The company will provide severance packages and _____ services to affected employees to help them transition to new employment.",
    reals: "The company has announced plans to downsize its workforce by 10% in an effort to reduce costs. The layoffs will primarily affect employees in the company's administrative and support departments, although some managers and executives will also be let go. The company's CEO has stated that these changes are necessary to ensure the long-term sustainability of the company and maintain its competitiveness in the marketplace. The company will provide severance packages and counseling services to affected employees to help them transition to new employment.",
    sels: [" expand", " downsize", " diversify", " centralize", " employees", " shareholders", " customers", " suppliers", " profitability", " stability", " flexibility", " sustainability", " relocation", " retraining", " counseling", " mentoring",],
    exps: "這是一篇關於公司裁員計劃的文章，文章提到了計劃的原因和影響。從上下文中可以得出：句子一中提到了公司的裁員計劃，因此答案應該是「downsize」。句子二中提到了員工中的特定部門受到影響，因此答案應該是「employees」。句子三中提到了公司的CEO認為這些變化是必要的，以確保公司的長期穩定性和競爭力，因此答案應該是「sustainability」。句子四中提到了公司提供撤職費和輔導服務，以幫助受影響的員工過渡到新的就業，因此答案應該是「counseling」。因此，答案為 (B) downsize、(E) employees、(L) sustainability 和 (O) counseling。",
    ans: ["(B)", "(E)", "(L)", "(O)",],
    cns: "公司已宣布裁員計劃 其勞動力減少了 10%，以努力降低成本。裁員主要影響員工 在公司的行政和支持部門，雖然一些經理和高管也會被裁掉。公司首席執行官表示，這些變化對於確保長期可持續性是必要的 並保持公司在市場上的競爭力。公司將提供遣散費和輔導 為受影響的員工提供服務，幫助他們過渡到新的工作崗位。"
}, {
    ars: "The _____ of the company's new product has been delayed due to manufacturing issues. The company had originally planned to launch the product in Q2, but now expects to release it in Q4. The delay has been _____ disappointing for the company, which had invested heavily in research and development and marketing efforts to support the launch. The company's management has reassured shareholders that the delay is temporary and that the product will be worth the wait, with features that are _____ superior to those of its competitors.",
    reals: "The launch of the company's new product has been delayed due to manufacturing issues. The company had originally planned to launch the product in Q2, but now expects to release it in Q4. The delay has been extremely disappointing for the company, which had invested heavily in research and development and marketing efforts to support the launch. The company's management has reassured shareholders that the delay is temporary and that the product will be worth the wait, with features that are significantly superior to those of its competitors.",
    sels: [" launch", " design", " development", " testing", " highly", " somewhat", " extremely", " moderately", " significantly", " marginally", " slightly", " barely",],
    exps: "這是一篇關於新產品延遲問題的文章，文章提到了延遲的原因和公司的反應。從上下文中可以得出：句子一中提到了產品的發布被延遲，因此答案應該是「launch」。句子二中提到了公司對這個延遲非常失望，因此答案應該是「extremely」。句子三中提到了產品將擁有優越的功能，因此答案應該是「significantly」。因此，答案為 (A) launch、(G) extremely 和 (I) significantly。",
    ans: ["(A)", "(G)", "(I)",],
    cns: "發射，市場投入 由於製造問題，該公司的新產品已被推遲。該公司原計劃在第二季度推出該產品，但現在預計將在第四季度發布。延遲非常嚴重 這對公司來說是令人失望的，該公司在研發和營銷方面投入了大量資金來支持發布。公司管理層已向股東保證，延遲是暫時的，該產品值得等待，具有顯著的功能 優於其競爭對手。"
}, {
    ars: "The hotel industry in the city has been experiencing a boom in recent years due to increased tourism. Many new hotels have _____ up in the city center, offering tourists a range of options at different price points. However, this growth has also led to increased _____ and competition among hotels, with some struggling to fill their rooms during off-peak seasons. To address this, many hotels have been _____ their services to appeal to a wider range of customers, such as offering discounted rates to business travelers and families.",
    reals: "The hotel industry in the city has been experiencing a boom in recent years due to increased tourism. Many new hotels have opened up in the city center, offering tourists a range of options at different price points. However, this growth has also led to increased supply and competition among hotels, with some struggling to fill their rooms during off-peak seasons. To address this, many hotels have been diversifying their services to appeal to a wider range of customers, such as offering discounted rates to business travelers and families.",
    sels: [" closed", " opened", " expanded", " renovated", " demand", " supply", " marketing", " innovation", " diversifying", " outsourcing", " downsizing", " streamlining",],
    exps: "這是一篇關於城市酒店行業發展的文章，文章提到了酒店行業的增長和相關問題。從上下文中可以得出：句子一中提到了城市酒店行業近年來繁榮發展，因此答案應該是「opened」。句子二中提到了增長也帶來了競爭和供過於求的問題，因此答案應該是「supply」。句子三中提到了許多酒店正在調整其服務，以應對市場變化，因此答案應該是「diversifying」。因此，答案為 (B) opened、(F) supply 和 (I) diversifying。",
    ans: ["(B)", "(F)", "(I)",],
    cns: "近年來，由於旅遊業的發展，該市的酒店業一直在蓬勃發展。許多新酒店已經開業 位於市中心，以不同的價位為遊客提供多種選擇。然而，這種增長也導致供應增加 以及酒店之間的競爭，一些酒店在淡季期間難以填補房間。為了解決這個問題，許多酒店一直在多元化 他們的服務以吸引更廣泛的客戶，例如為商務旅客和家庭提供折扣價。"
}, {
    ars: "The pharmaceutical industry has come under increased scrutiny in recent years due to concerns about rising drug prices and the role of pharmaceutical companies in the opioid crisis. Many consumers are _____ to pay for medications that they need to maintain their health, leading to calls for greater government regulation of drug prices. Meanwhile, several pharmaceutical companies have faced lawsuits for their role in the opioid epidemic, with some accused of _____ their products and contributing to addiction and overdose deaths. In response, the industry has pledged to improve transparency and _____ in drug pricing and marketing practices.",
    reals: "The pharmaceutical industry has come under increased scrutiny in recent years due to concerns about rising drug prices and the role of pharmaceutical companies in the opioid crisis. Many consumers are reluctant to pay for medications that they need to maintain their health, leading to calls for greater government regulation of drug prices. Meanwhile, several pharmaceutical companies have faced lawsuits for their role in the opioid epidemic, with some accused of overpromoting their products and contributing to addiction and overdose deaths. In response, the industry has pledged to improve transparency and accountability in drug pricing and marketing practices.",
    sels: [" reluctant", " eager", " unwilling", " hesitant", " overpromoting", " underpromoting", " misrepresenting", " falsifying", " accountability", " efficiency", " innovation", " profitability",],
    exps: "這是一篇關於製藥行業問題的文章，文章提到了藥價上漲和製藥公司在阿片類藥物危機中的角色等問題。從上下文中可以得出：句子一中提到了許多消費者不願意支付高昂的藥費，因此答案應該是「reluctant」。句子二中提到了一些製藥公司被指控過度宣傳其產品，貢獻了成癮和過量死亡等問題，因此答案應該是「overpromoting」。句子三中提到了製藥行業承諾改善透明度和負責任的藥品定價和市場營銷實踐，因此答案應該是「accountability」。因此，答案為 (A) reluctant、(E) overpromoting 和 (I) accountability。",
    ans: ["(A)", "(E)", "(I)",],
    cns: "近年來，由於擔心藥品價格上漲以及製藥公司在阿片類藥物危機中的作用，製藥行業受到越來越多的審查。許多消費者不願意 支付他們維持健康所需的藥物費用，導致政府呼籲加強對藥品價格的監管。與此同時，幾家製藥公司因其在阿片類藥物流行中的作用而面臨訴訟，其中一些公司被指控過度宣傳 他們的產品並導致成癮和過量死亡。作為回應，該行業已承諾提高透明度和問責制 在藥品定價和營銷實踐中。"
}, {
    ars: "In recent years, the global energy sector has undergone significant changes, driven by concerns about _____ and the need to reduce carbon emissions. As a result, many countries have implemented policies aimed at increasing the use of renewable energy sources, such as wind and solar power. This has led to a _____ in the renewable energy industry, with companies investing heavily in research and development to improve the efficiency and cost-effectiveness of their products. However, the shift towards renewable energy has not been without its _____, as some traditional energy companies have struggled to adapt to the changing market conditions.",
    reals: "In recent years, the global energy sector has undergone significant changes, driven by concerns about sustainability and the need to reduce carbon emissions. As a result, many countries have implemented policies aimed at increasing the use of renewable energy sources, such as wind and solar power. This has led to a surge in the renewable energy industry, with companies investing heavily in research and development to improve the efficiency and cost-effectiveness of their products. However, the shift towards renewable energy has not been without its challenges, as some traditional energy companies have struggled to adapt to the changing market conditions.",
    sels: [" sustainability", " diversity", " innovation", " competition", " surge", " decline", " stagnation", " consolidation", " challenges", " opportunities", " benefits", " rewards",],
    exps: "這是一篇關於全球能源行業的文章，文章提到了該行業的變化和相應的挑戰。從上下文中可以得出：句子一中提到了對永續性的關注和減少碳排放的需求，因此答案應該是「sustainability」。句子二中提到了可再生能源行業的激增，因此答案應該是「surge」。句子三中提到了傳統能源公司適應市場變化的困難，因此答案應該是「challenges」。因此，答案為 (A) sustainability、(E) surge 和 (I) challenges。",
    ans: ["(A)", "(E)", "(I)",],
    cns: "近年來，在對可持續性的擔憂推動下，全球能源行業發生了重大變化 以及減少碳排放的必要性。因此，許多國家實施了旨在增加風能和太陽能等可再生能源使用的政策。這導致了激增 在可再生能源行業，公司在研發方面投入巨資，以提高其產品的效率和成本效益。然而，向可再生能源的轉變並非沒有挑戰，因為一些傳統能源公司一直在努力適應不斷變化的市場條件。"
}, {
    ars: "Over the past decade, advances in technology have transformed the way we live and work. One of the most significant changes has been the widespread adoption of _____ devices, such as smartphones and tablets. These devices have revolutionized the way we _____ information, allowing us to access a wealth of knowledge at our fingertips. However, they have also had a number of _____ effects, such as the erosion of face-to-face communication skills and the development of addiction to social media.",
    reals: "Over the past decade, advances in technology have transformed the way we live and work. One of the most significant changes has been the widespread adoption of mobile devices, such as smartphones and tablets. These devices have revolutionized the way we retrieve information, allowing us to access a wealth of knowledge at our fingertips. However, they have also had a number of detrimental effects, such as the erosion of face-to-face communication skills and the development of addiction to social media.",
    sels: [" mobile", " wireless", " digital", " handheld", " process", " retrieve", " disseminate", " interpret", " beneficial", " detrimental", " positive", " negative",],
    exps: "這是一篇關於技術變革的文章，文章提到了技術變革對生活和工作的影響。從上下文中可以得出：句子一中提到了智能手機和平板電腦等行動設備的廣泛使用，因此答案應該是「mobile」。句子二中提到了使用這些設備獲取知識的革命性變化，因此答案應該是「retrieve」。句子三中提到了使用這些設備的負面效應，因此答案應該是「detrimental」。因此，答案為 (A) mobile、(F) retrieve 和 (J) detrimental。",
    ans: ["(A)", "(F)", "(J)",],
    cns: "在過去十年中，技術的進步改變了我們的生活和工作方式。最重要的變化之一是移動互聯網的廣泛採用 設備，例如智能手機和平板電腦。這些設備徹底改變了我們檢索的方式 信息，使我們能夠觸手可及地獲取豐富的知識。然而，他們也有一些有害的 影響，例如面對面交流技巧的侵蝕和社交媒體成癮的發展。"
}, {
    ars: "In recent years, businesses have increasingly turned to social media to _____ with their customers. Platforms like Facebook and Twitter offer companies a way to _____ with their audience in real-time, and can help to create a sense of community around a brand. However, social media also presents a number of _____, including the potential for negative feedback to spread quickly and damage a company's reputation.",
    reals: "In recent years, businesses have increasingly turned to social media to engage with their customers. Platforms like Facebook and Twitter offer companies a way to interact with their audience in real-time, and can help to create a sense of community around a brand. However, social media also presents a number of drawbacks, including the potential for negative feedback to spread quickly and damage a company's reputation.",
    sels: [" collaborate", " engage", " compete", " negotiate", " interact", " market", " advertise", " promote", " opportunities", " challenges", " benefits", " drawbacks",],
    exps: "這是一篇關於企業使用社交媒體與客戶互動的文章，文章提到了社交媒體對企業的影響。從上下文中可以得出：句子一中提到了企業越來越多地使用社交媒體與客戶互動，因此答案應該是「engage」。句子二中提到了社交媒體可以幫助企業建立品牌社區，因此答案應該是「interact」。句子三中提到了使用社交媒體所面臨的風險，因此答案應該是「drawbacks」。因此，答案為 (B) engage、(E) interact 和 (L) drawbacks。",
    ans: ["(B)", "(E)", "(L)",],
    cns: "近年來，企業越來越多地轉向社交媒體參與 與他們的客戶。 Facebook 和 Twitter 等平台為公司提供了一種互動方式 與他們的觀眾實時交流，並有助於營造圍繞品牌的社區感。然而，社交媒體也存在一些缺點，包括負面反饋迅速傳播並損害公司聲譽的可能性。"
}, {
    ars: "The hotel industry is experiencing a _____ in business due to the recent economic boom. With more people _____ disposable income, more and more individuals are choosing to travel and stay in hotels. In order to meet the demand, hotels are expanding their facilities and _____ their services to attract customers.",
    reals: "The hotel industry is experiencing a surge in business due to the recent economic boom. With more people spending disposable income, more and more individuals are choosing to travel and stay in hotels. In order to meet the demand, hotels are expanding their facilities and improving their services to attract customers.",
    sels: [" decline", " stagnation", " surge", " fluctuation", " having", " earning", " spending", " saving", " improving", " reducing", " limiting", " discontinuing",],
    exps: "這是一篇關於酒店業務增長的文章，文章提到了隨著經濟的蓬勃發展，越來越多的人選擇旅行和住酒店，酒店業務出現了一個「surge」。從上下文中可以得出：句子一中提到了「surge」，因此答案應該是 (C) surge。句子二中提到了隨著人們「spending」更多的可支配收入，他們越來越多地選擇旅行和住酒店，因此答案應該是 (G) spending。句子三中提到了為了滿足需求，酒店正在擴大設施並「improving」其服務來吸引顧客，因此答案應該是 (I) improving。因此，答案為 (C) surge、(G) spending 和 (I) improving。",
    ans: ["(C)", "(G)", "(I)",],
    cns: "酒店業正在經歷一場激增 由於最近的經濟繁榮而從事商業活動。隨著越來越多的人消費 隨著可支配收入的增加，越來越多的人選擇旅遊和入住酒店。為了滿足需求，酒店正在擴建設施和改進 他們的服務來吸引顧客。"
}, {
    ars: "In recent years, online shopping has become increasingly popular among consumers. One of the biggest advantages of online shopping is that it allows customers to _____ items from the comfort of their own homes. This means that people can avoid the hassle of traffic and crowded stores. Additionally, online shopping often offers a wider variety of products than traditional retail stores, as well as _____ prices. Many retailers also offer free shipping or other _____ to encourage customers to shop online.",
    reals: "In recent years, online shopping has become increasingly popular among consumers. One of the biggest advantages of online shopping is that it allows customers to purchase items from the comfort of their own homes. This means that people can avoid the hassle of traffic and crowded stores. Additionally, online shopping often offers a wider variety of products than traditional retail stores, as well as lower prices. Many retailers also offer free shipping or other promotions to encourage customers to shop online.",
    sels: [" purchase", " return", " exchange", " rent", " lower", " higher", " fixed", " fluctuating", " promotions", " warranties", " discounts", " contracts",],
    exps: "這是一篇關於網路購物的文章，文章提到了網路購物的優點，包括方便、避免交通和人潮、商品種類豐富、價格更低、還有店家提供的促銷和免運費等等。從上下文中可以得出：句子一中提到了網路購物可以讓人們從家中購買商品，因此答案應該是 (A) purchase。句子二中提到了網路購物的優勢之一是價格更低，因此答案應該是 (E) lower。句子三中提到了店家提供的促銷和免運費等等，因此答案應該是 (I) promotions。因此，答案為 (A) purchase、(E) lower 和 (I) promotions。",
    ans: ["(A)", "(E)", "(I)",],
    cns: "近年來，網上購物越來越受到消費者的歡迎。網上購物的最大優勢之一是它允許客戶購買 從他們自己家中舒適的物品。這意味著人們可以避免交通和商店擁擠的麻煩。此外，網上購物通常比傳統零售店提供更多種類的產品，而且價格更低 價格。許多零售商還提供免費送貨或其他促銷活動 以鼓勵顧客在線購物。"
}, {
    ars: "The hospitality industry, which includes hotels, restaurants, and catering services, plays a crucial role in the global economy. As international travel continues to _____, the demand for hotels and restaurants has increased. In addition, many people today prefer to _____ out or order in rather than cook at home. This has led to a growth in the number of restaurants and catering services, both small and large.When it comes to hotels, there are a wide variety of options available to travelers. From luxury hotels to budget accommodations, there is something for every _____ of traveler. Many hotels now offer additional amenities such as fitness centers, swimming pools, and complimentary breakfast. In order to stay competitive, hotels must also keep up with the latest technologies, such as online reservation systems and mobile check-in options.",
    reals: "The hospitality industry, which includes hotels, restaurants, and catering services, plays a crucial role in the global economy. As international travel continues to increase, the demand for hotels and restaurants has increased. In addition, many people today prefer to dine out or order in rather than cook at home. This has led to a growth in the number of restaurants and catering services, both small and large.When it comes to hotels, there are a wide variety of options available to travelers. From luxury hotels to budget accommodations, there is something for every category of traveler. Many hotels now offer additional amenities such as fitness centers, swimming pools, and complimentary breakfast. In order to stay competitive, hotels must also keep up with the latest technologies, such as online reservation systems and mobile check-in options.",
    sels: [" decrease", " stagnate", " increase", " fluctuate", " eat", " dine", " take", " make", " kind", " level", " group", " category",],
    exps: "這是一篇關於餐飲和旅館產業的文章。文章提到了隨著國際旅遊的增加，對旅館和餐廳的需求也增加了。同時，越來越多的人選擇外出用餐或點外送食物，因此餐廳和餐飲服務的數量也在增長。另外，旅館也提供了各種各樣的選擇，包括豪華旅館和預算住宿等等，而且為了保持競爭力，旅館也必須跟上最新的技術。句子一中提到了隨著國際旅遊的增加，對旅館和餐廳的需求也增加了，因此答案應該是 (C) increase。句子二中提到了越來越多的人選擇外出用餐或點外送食物，因此答案應該是 (F) dine。句子三中提到了旅館提供各種選擇，包括豪華旅館和預算住宿等等，因此答案應該是 (L) category。因此，答案為 (C) increase、(F) dine 和 (L) category。",
    ans: ["(C)", "(F)", "(L)",],
    cns: "包括酒店、餐廳和餐飲服務在內的酒店業在全球經濟中發揮著至關重要的作用。隨著國際旅行的不斷增加，對旅館和餐館的需求增加了。此外，如今許多人更喜歡用餐 外出或訂購而不是在家做飯。這導致了大大小小的餐館和餐飲服務數量的增加。說到酒店，旅客可以有多種選擇。從豪華酒店到經濟型住宿，每個類別都有適合的東西 的旅行者。許多酒店現在提供額外的便利設施，例如健身中心、游泳池和免費早餐。為了保持競爭力，酒店還必須跟上最新技術，例如在線預訂系統和移動入住選項。"
},]