/*export const r = [{
    ar: "For years, scientists have been working to find a cure for Alzheimer's disease, a progressive brain disorder that affects millions of people worldwide. The disease is caused by the buildup of abnormal proteins in the brain that damage and kill brain cells, leading to memory loss and other cognitive problems. Although there is currently no cure for Alzheimer's disease, there are medications that can help manage symptoms and improve quality of life for patients.Recently, researchers at the University of Texas at Dallas may have made a breakthrough in the search for a cure. In a study published in the journal Science Advances, the team showed that they were able to clear out the abnormal proteins that cause Alzheimer's disease from the brains of mice. They did this by using ultrasound waves to stimulate microglial cells in the brain, which are responsible for removing waste and other harmful substances. The researchers found that the ultrasound waves caused the microglial cells to consume the abnormal proteins, reducing their buildup in the brain.The study is still in its early stages, and more research is needed to determine whether the same approach could be effective in humans. However, the results are promising, and could pave the way for a future cure for Alzheimer's disease.",
    q: ["What is Alzheimer's disease?", "What causes Alzheimer's disease?", "Is there currently a cure for Alzheimer's disease?", "What did researchers at the University of Texas at Dallas do to clear out the abnormal proteins that cause Alzheimer's disease from the brains of mice?", "Is the study mentioned in the passage likely to lead to a cure for Alzheimer's disease in humans?",],
    q_sel: [[" A type of cancer", " A progressive brain disorder", " A genetic disorder", " A disorder caused by a virus"], [" The buildup of abnormal proteins in the brain", " A virus", " Genetics", " Smoking"], [" Yes, there is a cure.", " No, there is no cure.", " There is a cure, but it is not effective.", " There used to be a cure, but it is no longer available."], [" They used chemotherapy.", " They used ultrasound waves to stimulate microglial cells.", " They removed the affected parts of the brain.", " They gave the mice a new medication."], [" Yes, a cure is now available for humans.", " No, the study is unlikely to lead to a cure for humans.", " It is too early to tell.", " The study has already led to a cure for humans."],],
    q_ex: ["文章第一句就提到 Alzheimer's disease 是一種「progressive brain disorder」，因此答案為 B。", "文章中提到 Alzheimer's disease 是由於「the buildup of abnormal proteins in the brain」所引起，因此答案為 A。", "文章中提到目前沒有針對 Alzheimer's disease 的治療方法，只有一些可以幫助緩解症狀的藥物，因此答案為 B。", "文章中提到研究人員使用「ultrasound waves to stimulate microglial cells in the brain」以清除掉引起 Alzheimer's disease 的異常蛋白質，因此答案為 B。", "文章中提到這項研究仍處於早期階段，需要更多的研究才能確定同樣的方法是否對人類有效，因此答案為 C。文中也提到研究結果具有前途，但仍需要進一步的研究。",],
    q_a: [" B", " A", " B", " B", " C",],
    zh: "多年來，科學家們一直致力於尋找治療阿爾茨海默病的方法，阿爾茨海默病是一種影響全球數百萬人的進行性腦部疾病。這種疾病是由大腦中異常蛋白質的積累引起的，這些蛋白質會損害和殺死腦細胞，從而導致記憶力減退和其他認知問題。雖然目前還沒有治愈阿爾茨海默病的方法，但有一些藥物可以幫助控制症狀並改善患者的生活質量。最近，德克薩斯大學達拉斯分校的研究人員可能在尋找治愈方法方面取得了突破。在《科學進展》雜誌上發表的一項研究中，該團隊表明他們能夠從小鼠大腦中清除導致阿爾茨海默病的異常蛋白質。他們通過使用超聲波刺激大腦中負責清除廢物和其他有害物質的小神經膠質細胞來做到這一點。研究人員發現，超聲波導緻小膠質細胞消耗異常蛋白質，減少了它們在大腦中的積聚。這項研究仍處於早期階段，需要更多的研究來確定同樣的方法是否對人類有效。然而，結果很有希望，並可能為未來治愈阿爾茨海默病鋪平道路。"
}, {
    ar: "In recent years, climate change has become an increasingly urgent issue. As global temperatures rise and extreme weather events become more frequent, it is clear that we need to take action to reduce our carbon footprint and prevent further damage to the planet. One solution that has gained popularity in recent years is renewable energy, which comes from sources that are naturally replenished and can be used without depleting finite resources.Renewable energy sources include solar, wind, and hydro power, as well as geothermal and biomass energy. These sources have many advantages over traditional fossil fuels, such as coal and oil. For example, they produce little to no emissions and are much less harmful to the environment. They also provide a sustainable and reliable source of energy, as they are not subject to the same price fluctuations and supply constraints as fossil fuels.Despite these advantages, renewable energy sources still face many challenges. For one, they are often more expensive to develop and implement than traditional energy sources. In addition, their effectiveness can be limited by factors such as weather patterns and geographic location. As a result, governments and private companies alike must invest in research and development to make renewable energy more efficient and cost-effective.",
    q: ["What is one reason why climate change has become an increasingly urgent issue in recent years?", "What is renewable energy?", "What are some examples of renewable energy sources?", "What is one advantage of renewable energy sources over traditional fossil fuels?", "What is one challenge that renewable energy sources face?",],
    q_sel: [[" Global temperatures are decreasing.", " Extreme weather events are becoming less frequent.", " The use of fossil fuels is declining.", " Global temperatures are rising."], [" Energy that is produced from fossil fuels.", " Energy that is not subject to price fluctuations.", " Energy that is naturally replenished and does not deplete finite resources.", " Energy that produces large amounts of emissions."], [" Coal and oil.", " Natural gas and petroleum.", " Solar, wind, and hydro power.", " Nuclear and geothermal energy."], [" Renewable energy sources are subject to price fluctuations.", " Renewable energy sources are harmful to the environment.", " Renewable energy sources are less expensive to develop and implement.", " Renewable energy sources produce little to no emissions."], [" They are often more expensive to develop and implement than traditional energy sources.", " They produce large amounts of emissions.", " They are subject to the same price fluctuations and supply constraints as fossil fuels.", " They are not effective sources of energy."],],
    q_ex: ["文章開頭就提到全球氣溫上升，顯然地指出了氣候變遷成為一個越來越迫切的問題，因此答案為 D。", "文章中提到 renewable energy 是指那些來源是自然再生的，可以使用而不會耗盡有限資源的能源，因此答案為 C。", "文章中列舉了太陽能、風能和水能等能源，這些都是 renewable energy sources 的例子，因此答案為 C。", "文章中提到 renewable energy sources 相較於傳統的化石燃料，例如煤炭和石油，會產生較少的排放物，因此答案為 D。", "文章中提到 renewable energy sources 通常比傳統能源更昂貴，因此需要更多的研究和發展來使其更有效率和具有成本效益，因此答案為 A。",],
    q_a: [" D", " C", " C", " D", " A",],
    zh: "近年來，氣候變化已成為一個日益緊迫的問題。隨著全球氣溫上升和極端天氣事件變得更加頻繁，顯然我們需要採取行動減少我們的碳足跡並防止對地球造成進一步破壞。近年來流行的一種解決方案是可再生能源，它來自自然補充的資源，可以在不耗盡有限資源的情況下使用。可再生能源包括太陽能、風能和水力發電，以及地熱和生物質能。與煤炭和石油等傳統化石燃料相比，這些資源具有許多優勢。例如，它們幾乎不產生排放物，對環境的危害也小得多。它們還提供可持續和可靠的能源來源，因為它們不像化石燃料那樣受到價格波動和供應限制的影響。儘管有這些優勢，可再生能源仍然面臨許多挑戰。一方面，與傳統能源相比，它們的開發和實施成本往往更高。此外，它們的有效性可能會受到天氣模式和地理位置等因素的限制。因此，政府和私營公司都必須投資於研發，以提高可再生能源的效率和成本效益。"
}, {
    ar: "In recent years, there has been growing concern about the impact of social media on mental health. While social media platforms have the potential to connect people from all over the world, they also have some negative effects. One study found that people who spend more than two hours a day on social media are more likely to experience feelings of social isolation and depression.One way that social media can contribute to mental health problems is through the comparison of oneself to others. Social media platforms often present idealized versions of people's lives, and users may feel pressure to conform to these unrealistic standards. This can lead to feelings of inadequacy and low self-esteem.Another way that social media can affect mental health is through the spread of misinformation. False information and rumors can spread rapidly on social media, leading to anxiety and confusion. In some cases, this can even lead to dangerous behavior or beliefs.Despite these negative effects, social media can also be a source of support and community for some people. It is important to use social media in a balanced and responsible way, and to be aware of the potential risks.",
    q: ["What is one concern about the impact of social media on mental health?", "How can social media contribute to mental health problems?", "What is one way that social media can lead to feelings of inadequacy and low self-esteem?",],
    q_sel: [[" Social media platforms can only connect people from certain parts of the world.", " Social media platforms have no negative effects on mental health.", " People who use social media are less likely to experience feelings of social isolation and depression.", " People who spend more than two hours a day on social media are more likely to experience feelings of social isolation and depression."], [" By presenting realistic versions of people's lives.", " By providing users with accurate information.", " By spreading rumors and misinformation.", " By connecting people from all over the world."], [" By providing users with support and community.", " By presenting idealized versions of people's lives.", " By spreading accurate information.", " By connecting people from all over the world."],],
    q_ex: ["文章中提到花費超過每天兩個小時在社交媒體上的人，更有可能出現社交孤立和抑鬱的感覺，因此答案為 D。", "文章中提到社交媒體可以通過傳播不實信息和謠言對心理健康造成影響，因此答案為 C。", "文章中提到社交媒體平台經常呈現人們生活的理想化版本，使用者可能感到需要符合這些不現實的標準，這可能導致自卑和低自尊心，因此答案為 B。",],
    q_a: [" D", " C", " B",],
    zh: "近年來，人們越來越關注社交媒體對心理健康的影響。雖然社交媒體平台有可能將來自世界各地的人們聯繫起來，但它們也有一些負面影響。一項研究發現，每天在社交媒體上花費超過兩個小時的人更有可能體驗到社交孤立和抑鬱的感覺。社交媒體導致心理健康問題的一種方式是通過自我與他人的比較。社交媒體平台經常呈現人們生活的理想化版本，用戶可能會感到有壓力要遵守這些不切實際的標準。這會導致自卑感和自卑感。社交媒體影響心理健康的另一種方式是傳播錯誤信息。虛假信息和謠言會在社交媒體上迅速傳播，導致焦慮和困惑。在某些情況下，這甚至會導致危險的行為或信念。儘管有這些負面影響，社交媒體也可以成為某些人的支持和社區來源。以平衡和負責任的方式使用社交媒體並了解潛在風險非常重要。"
}, {
    ar: "As the world becomes more technologically advanced, people are becoming more and more reliant on electronic devices. While these devices can make life easier and more convenient in many ways, there are also downsides to this dependence.One issue is the effect of electronic devices on sleep. Studies have shown that the blue light emitted by screens can interfere with the production of melatonin, a hormone that helps regulate sleep. This can lead to difficulty falling asleep, as well as poor-quality sleep.Another issue is the impact of electronic devices on social interaction. Many people now spend a significant amount of time interacting with others through social media and messaging apps, rather than in-person communication. This can lead to feelings of loneliness and isolation, as well as a lack of important social skills.Despite these downsides, electronic devices are not going anywhere. It is important for individuals to recognize the potential negative effects of these devices and take steps to mitigate them, such as limiting screen time before bed and making an effort to engage in face-to-face communication with others.",
    q: ["What is the main topic of the passage?", "What is one negative impact of electronic devices on sleep?", "How can overuse of electronic devices affect social skills?", "What is the author's main message?", "What is one step individuals can take to mitigate the negative effects of electronic devices?",],
    q_sel: [[" The benefits of electronic devices", " The downsides of electronic devices", " The future of electronic devices", " The evolution of electronic devices"], [" Increased production of melatonin", " Improved sleep quality", " Interference with melatonin production", " Increased likelihood of dreaming"], [" It can improve social interaction", " It can lead to feelings of loneliness and isolation", " It can increase face-to-face communication", " It can enhance the ability to read social cues"], [" Electronic devices are all bad", " Electronic devices are all good", " Electronic devices have both benefits and downsides", " Electronic devices will eventually disappear"], [" Increase screen time before bed", " Avoid face-to-face communication", " Use electronic devices more frequently", " Limit screen time before bed"],],
    q_ex: ["文章第一段提到了電子產品的優點，但是整篇文章都是在探討電子產品的缺點，因此答案為B。", "根據文章第二段的描述，電子產品發出的藍光會干擾褪黑激素的產生，進而影響睡眠，因此答案為C。", "文章第三段提到，人們現在花大量的時間透過社交媒體和消息應用程式與他人互動，而不是進行面對面的交流，這會導致孤獨感和孤立感，以及缺乏重要的社交技能，因此答案為B。", "文章提到了電子產品的缺點，但也指出了電子產品的優點，並強調了個人需要認識到這些設備的潛在負面影響，並採取措施來緩解它們帶來的影響，因此答案為C。", "文章最後一段建議個人應該認識到電子產品的潛在負面影響，並採取措施來緩解它們帶來的影響，其中一個建議就是在睡前限制使用電子產品的時間，因此答案為D。",],
    q_a: [" B", " C", " B", " C", " D",],
    zh: "隨著世界技術變得越來越先進，人們越來越依賴電子設備。雖然這些設備可以在許多方面讓生活更輕鬆、更方便，但這種依賴也有不利之處。一個問題是電子設備對睡眠的影響。研究表明，屏幕發出的藍光會干擾褪黑激素的產生，褪黑激素是一種有助於調節睡眠的激素。這會導致難以入睡，以及睡眠質量差。另一個問題是電子設備對社交互動的影響。許多人現在花費大量時間通過社交媒體和消息應用程序與他人互動，而不是面對面交流。這可能會導致孤獨感和孤立感，以及缺乏重要的社交技能。儘管有這些缺點，電子設備仍無處可去。個人必須認識到這些設備的潛在負面影響並採取措施減輕這些影響，例如限制睡前看屏幕的時間並努力與他人進行面對面的交流。"
}, {
    ar: "The human brain is incredibly complex, and there is still much that researchers do not understand about how it works. However, one thing that is clear is that the brain is highly adaptable and capable of change.Neuroplasticity is the term used to describe the brain's ability to reorganize itself in response to new experiences. This can involve creating new neural connections or strengthening existing ones. Neuroplasticity is thought to be a key factor in learning and memory, as well as in recovery from brain injuries.While the brain is capable of neuroplasticity throughout life, the extent to which it can change decreases with age. This means that young children are particularly adept at learning and adapting, while older adults may have more difficulty in these areas.However, there are things that individuals can do to promote neuroplasticity and enhance their brain's ability to adapt. Engaging in activities that are mentally stimulating, such as reading or solving puzzles, is one way to promote neuroplasticity. Physical exercise has also been shown to have a positive impact on brain function and neuroplasticity.",
    q: ["What is the main topic of the passage?", "What is neuroplasticity?", "How does neuroplasticity impact learning and memory?", "What is one way to promote neuroplasticity?",],
    q_sel: [[" The complexity of the human brain", " The role of neuroplasticity in brain function", " The effects of aging on the brain", " The benefits of mental stimulation"], [" The brain's ability to change in response to new experiences", " The brain's ability to maintain the status quo", " The brain's inability to change with age", " The brain's resistance to new experiences"], [" It has no effect on learning and memory", " It makes learning and memory more difficult", " It is a key factor in learning and memory", " It only impacts memory, not learning"], [" Avoid mental stimulation", " Limit physical exercise", " Engage in mentally stimulating activities", " Only engage in physical exercise"],],
    q_ex: ["文章主要在談論神經可塑性對於大腦功能的影響，因此答案為B。", "文章第二段中提到，神經可塑性是大腦對新體驗做出反應時重新組織自己的能力，包括建立新的神經連接或加強現有的連接，因此答案為A。", "文章中提到神經可塑性是學習和記憶的關鍵因素之一，因此答案為C。", "文章中提到，進行腦力刺激的活動（例如閱讀或解決問題）是促進神經可塑性的一種方式，因此答案為C。",],
    q_a: [" B", " A", " C", " C",],
    zh: "人腦極其複雜，研究人員對它的工作原理仍有很多不了解。然而，有一點是明確的，即大腦具有高度的適應性和變化能力。神經可塑性是用來描述大腦重組自身以響應新體驗的能力的術語。這可能涉及創建新的神經連接或加強現有的神經連接。神經可塑性被認為是學習和記憶以及腦損傷恢復的關鍵因素。雖然大腦在整個生命過程中都具有神經可塑性，但它可以改變的程度會隨著年齡的增長而降低。這意味著年幼的孩子特別善於學習和適應，而老年人在這些方面可能會遇到更多困難。但是，個人可以做一些事情來促進神經可塑性並增強大腦的適應能力。參與精神刺激的活動，例如閱讀或解決難題，是促進神經可塑性的一種方式。體育鍛煉也被證明對大腦功能和神經可塑性有積極影響。"
}, {
    ar: "Climate change is a pressing issue that has garnered significant attention in recent years. While there is still debate about the causes and extent of climate change, most scientists agree that it is largely driven by human activities, such as the burning of fossil fuels and deforestation.One of the consequences of climate change is rising sea levels. As temperatures continue to rise, glaciers and ice sheets are melting, causing water to flow into the oceans and contributing to sea level rise. This can have a devastating impact on coastal cities and communities, as well as on wildlife and ecosystems.Another consequence of climate change is extreme weather events, such as heat waves, droughts, and hurricanes. These events can lead to crop failures, water shortages, and infrastructure damage, among other things. They also pose a significant threat to human health and well-being.Addressing climate change requires a coordinated effort from individuals, governments, and businesses around the world. This may involve reducing greenhouse gas emissions, transitioning to renewable energy sources, and investing in technologies that can help mitigate the impacts of climate change.",
    q: ["What is the main topic of the passage?", "What are some human activities that are contributing to climate change?", "What is one consequence of rising temperatures?", "What is one way to address climate change?", "What is the author's opinion on climate change?",],
    q_sel: [[" The causes of climate change", " The impacts of climate change", " The debate about climate change", " The role of individuals in addressing climate change"], [" Eating meat and dairy products", " Planting trees and other vegetation", " Burning fossil fuels and deforestation", " Recycling and composting"], [" Decreasing sea levels", " Reduced crop yields", " Increased forest cover", " Improved wildlife habitats"], [" Increase greenhouse gas emissions", " Continue to rely on fossil fuels", " Transition to renewable energy sources", " Build more infrastructure in coastal areas"], [" It is not a significant issue", " It is entirely caused by human activities", " It is a topic of debate among scientists", " It requires a coordinated effort to address"],],
    q_ex: ["文章主要在談論氣候變化對於環境、野生動物和人類社區帶來的影響，因此答案為B。", "文章中提到，氣候變化很大程度上是由人類活動引起的，例如燃燒化石燃料和森林砍伐，因此答案為C。", "文章中提到，隨著溫度持續上升，冰川和冰原融化，導致水流入海洋並促成海平面上升，這對沿海城市和社區以及野生動物和生態系統都會產生毀滅性的影響。因此答案為B。", "文章中提到，應對氣候變化需要全球個人、政府和企業之間的協調努力，這可能包括減少溫室氣體排放，轉向可再生能源來源以及投資於能減緩氣候變化影響的技術等。因此答案為C。", "文章作者沒有表達對氣候變化本身的觀點，而是強調需要全球個人、政府和企業之間的協調努力才能應對氣候變化。因此答案為D。",],
    q_a: [" B", " C", " B", " C", " D",],
    zh: "氣候變化是一個緊迫的問題，近年來引起了廣泛關注。儘管對氣候變化的原因和程度仍有爭論，但大多數科學家都認為，氣候變化主要是由人類活動驅動的，例如燃燒化石燃料和砍伐森林。氣候變化的後果之一是海平面上升。隨著氣溫持續上升，冰川和冰原正在融化，導致水流入海洋並導致海平面上升。這會對沿海城市和社區以及野生動物和生態系統產生毀滅性影響。氣候變化的另一個後果是極端天氣事件，例如熱浪、乾旱和颶風。這些事件可能導致作物歉收、缺水和基礎設施損壞等。它們還對人類健康和福祉構成重大威脅。應對氣候變化需要全世界個人、政府和企業的協調努力。這可能涉及減少溫室氣體排放、轉向可再生能源以及投資有助於減輕氣候變化影響的技術。"
}, {
    ar: "The concept of climate change has become an increasingly pressing issue in recent years. Climate change refers to the long-term changes in Earth's climate, including changes in temperature, precipitation, and wind patterns, among others. While natural factors such as volcanic activity and solar radiation can contribute to climate change, the overwhelming scientific consensus is that human activities, particularly the burning of fossil fuels, are the primary cause of the current trend.The consequences of climate change are vast and far-reaching. Rising temperatures can lead to extreme weather events such as hurricanes, floods, and droughts, which in turn can cause significant damage to infrastructure, property, and crops. Melting ice caps and rising sea levels can lead to the displacement of communities living in low-lying coastal areas. Climate change can also have negative impacts on public health, such as the spread of diseases and the exacerbation of existing health conditions.In response to the threat of climate change, many countries have taken action to reduce their greenhouse gas emissions and transition to more sustainable forms of energy. These efforts include investing in renewable energy sources such as wind and solar power, improving energy efficiency, and promoting public transportation and electric vehicles. While much remains to be done to address the challenges of climate change, there is reason for hope as countries and individuals work towards a more sustainable future.",
    q: ["What is climate change?", "What is the primary cause of climate change, according to the scientific consensus?", "What are some consequences of climate change?", "What are some ways countries have responded to the threat of climate change?", "What is the author's attitude towards the future of addressing climate change?",],
    q_sel: [[" Changes in temperature only", " Changes in temperature and precipitation only", " Changes in temperature, precipitation, and wind patterns, among others", " Changes in wind patterns only"], [" Volcanic activity", " Solar radiation", " Human activities, particularly the burning of fossil fuels", " A combination of natural and human factors"], [" Improved public health", " Decreased frequency of extreme weather events", " Damage to infrastructure, property, and crops due to extreme weather events", " Increased availability of natural resources"], [" Increasing the burning of fossil fuels", " Investingin renewable energy sources", " Encouraging the use of single-use plastics", " Decreasing public transportation options"], [" Pessimistic", " Optimistic", " Ambivalent", " Uncertain"],],
    q_ex: ["文章中說明了氣候變化包括許多方面的長期變化，包括溫度、降水和風等方面的變化。因此，答案為C。", "文章指出，雖然自然因素如火山活動和太陽輻射也會對氣候變化作出貢獻，但壓倒性的科學共識是人類活動，尤其是化石燃料的燃燒是當前氣候變化的主要原因。因此，答案為C。", "文章中提到，氣候變化的後果是廣泛而深遠的，包括極端天氣事件，如颶風、洪水和干旱，進而可能對基礎設施、財產和作物造成重大破壞。因此，答案為C。", "文章提到，為了應對氣候變化的威脅，許多國家已經採取了行動，包括投資於可再生能源，提高能源效率，以及促進公共交通和電動汽車的使用。因此，答案為B。", "文章中提到，雖然應對氣候變化的挑戰仍然存在，但是由於各國和個人正致力於實現更可持續的未來，因此有希望。這表明作者對應對氣候變化的未來持樂觀態度。因此，答案為B。",],
    q_a: [" C", " C", " C", " B", " B",],
    zh: "近年來，氣候變化的概念已成為一個日益緊迫的問題。氣候變化是指地球氣候的長期變化，包括溫度、降水和風型等的變化。雖然火山活動和太陽輻射等自然因素會導致氣候變化，但壓倒性的科學共識是人類活動，特別是化石燃料的燃燒，是當前趨勢的主要原因。氣候變化的後果是巨大而深遠的-達到。氣溫上升會導致颶風、洪水和乾旱等極端天氣事件，進而對基礎設施、財產和農作物造成重大破壞。冰蓋融化和海平面上升可能導致生活在低窪沿海地區的社區流離失所。氣候變化還會對公共衛生產生負面影響，例如疾病的傳播和現有健康狀況的惡化。為應對氣候變化的威脅，許多國家已採取行動減少溫室氣體排放並向更可持續的轉型能量形式。這些努力包括投資風能和太陽能等可再生能源，提高能源效率，以及推廣公共交通和電動汽車。儘管要應對氣候變化的挑戰還有很多工作要做，但隨著各國和個人朝著更可持續的未來努力，我們有理由抱有希望。"
}, {
    ar: "The Importance of SleepWe all know that getting a good night's sleep is important, but many of us still don't get enough sleep on a regular basis. In fact, studies have shown that more than one-third of American adults do not get the recommended seven hours of sleep each night.Lack of sleep can have a variety of negative effects on both our physical and mental health. For example, it can increase the risk of developing chronic health conditions such as obesity, diabetes, and cardiovascular disease. It can also impair our immune system, making us more susceptible to illnesses.In addition to these physical health effects, lack of sleep can also affect our mental health. It can lead to problems with mood regulation, making us more irritable, anxious, and depressed. It can also impair cognitive function, making it harder to concentrate, learn, and remember things.So how can we improve our sleep habits? Here are some tips:Stick to a regular sleep schedule. Go to bed and wake up at the same time every day, even on weekends.Create a relaxing sleep environment. Keep your bedroom dark, quiet, and cool, and avoid using electronic devices before bed.Avoid caffeine, nicotine, and alcohol before bedtime, as they can disrupt your sleep.Get regular exercise, but avoid exercising too close to bedtime.If you have trouble sleeping, try relaxation techniques such as deep breathing or meditation, or consider talking to a healthcare professional about sleep aids.",
    q: ["What is the main idea of the passage?", "According to the passage, what are some physical health effects of lack of sleep?", "What is the author's advice for creating a relaxing sleep environment?", "According to the passage, what is one potential consequence of impaired cognitive function due to lack of sleep?", "What is the author's advice for improving sleep habits?",],
    q_sel: [[" Lack of sleep can have negative effects on physical health.", " Lack of sleep can have negative effects on mental health.", " Lack of sleep is a problem for many Americans.", " Getting a good night's sleep is important."], [" Increased risk of developing depression.", " Impaired cognitive function.", " Increased risk of developing cardiovascular disease.", " Difficulty concentrating."], [" Use electronic devices before bed.", " Keep the bedroom warm and bright.", " Avoid noise in the bedroom.", " Keep the bedroom cool and dark."], [" Increased risk of developing obesity.", " Difficulty concentrating and learning.", " Higher susceptibility to illnesses.", " Problems with mood regulation."], [" Drink alcohol before bedtime.", " Exercise right before going to bed.", " Stick to a regular sleep schedule.", " Use electronic devices in bed."],],
    q_ex: ["文章一開始就提到了睡眠的重要性，後面的內容也在強調睡眠的好處以及如何改善睡眠習慣。因此，答案為D。", "文章提到，缺乏睡眠可以增加患上慢性疾病（例如肥胖症、糖尿病和心血管疾病）的風險。因此，答案為C。", "文章提到了創建一個放鬆的睡眠環境的建議，其中包括保持臥室涼爽、黑暗以及避免在睡前使用電子設備。因此，答案為D。", "文章提到了缺乏睡眠對認知功能的影響，可能會讓人難以集中注意力、學習和記憶。因此，答案為B。", "文章提到了改善睡眠習慣的建議，其中包括保持規律的睡眠時間表，晚上睡前避免飲用咖啡因、尼古丁和酒精，以及避免在睡前使用電子設備。因此，答案為C。",],
    q_a: [" D", " C", " D", " B", " C",],
    zh: "睡眠的重要性我們都知道睡個好覺很重要，但我們中的許多人仍然沒有定期獲得足夠的睡眠。事實上，研究表明，超過三分之一的美國成年人每晚沒有達到建議的七小時睡眠時間。睡眠不足會對我們的身心健康產生各種負面影響。例如，它會增加患肥胖症、糖尿病和心血管疾病等慢性疾病的風險。它還會損害我們的免疫系統，使我們更容易生病。除了這些身體健康影響外，睡眠不足還會影響我們的心理健康。它會導致情緒調節問題，使我們更加易怒、焦慮和抑鬱。它還會損害認知功能，使注意力、學習和記憶變得更加困難。那麼我們如何改善睡眠習慣呢？這裡有一些提示： 堅持規律的睡眠時間表。每天在同一時間睡覺和起床，週末也不例外。營造輕鬆的睡眠環境。保持臥室黑暗、安靜和涼爽，睡前避免使用電子設備。睡前避免咖啡因、尼古丁和酒精，因為它們會擾亂您的睡眠。定期鍛煉，但避免在臨睡前鍛煉。如果您有睡眠困難，嘗試放鬆技巧，如深呼吸或冥想，或考慮與醫療保健專業人員討論助眠劑。"
}, {
    ar: "In recent years, there has been a growing interest in plant-based diets. Advocates of these diets argue that they are healthier for both people and the planet. But are plant-based diets really better? Let's take a closer look.One of the main benefits of plant-based diets is that they tend to be lower in saturated fats and higher in fiber, vitamins, and minerals. This can help reduce the risk of heart disease, stroke, and certain types of cancer. Plant-based diets have also been shown to be effective for weight loss and improving overall health.However, some people worry that plant-based diets might not provide all of the necessary nutrients, especially for people who are pregnant, breastfeeding, or have certain health conditions. For example, plant-based diets may not provide enough protein, calcium, or vitamin B12.Another concern is that some plant-based foods, such as soy and nuts, can be allergenic and cause reactions in some people. Additionally, some plant-based diets may not be sustainable in the long-term due to the large amounts of water and other resources needed to produce certain crops.Overall, plant-based diets can be a healthy and sustainable choice for many people. However, it's important to ensure that you are getting all of the necessary nutrients, and to speak with a healthcare professional before making any major dietary changes.",
    q: ["What is the main benefit of plant-based diets according to the passage?", "According to the passage, what is a potential concern with plant-based diets?", "What is the author's advice regarding plant-based diets?", "According to the passage, why might some plant-based diets not be sustainable in the long-term?", "What is the author's main purpose in writing this passage?",],
    q_sel: [[" They are lower in fiber and higher in saturated fats.", " They can increase the risk of heart disease and stroke.", " They can help reduce the risk of certain types of cancer.", " They are less effective for weight loss than other diets."], [" They may not provide enough protein, calcium, or vitamin B12.", " They may cause allergic reactions in some people.", " They may not be effective for weight loss.", " They require more resources to produce than other diets."], [" Everyone should switch to a plant-based diet immediately.", " Plant-based diets are not sustainable in the long-term.", " It is important to make sure you are getting all necessary nutrients.", " Healthcare professionals do not need to be consulted before making dietary changes."], [" They require too much time and effort to prepare.", " They can cause allergic reactions in some people.", " They are less effective for weight loss than other diets.", " They require large amounts of water and resources to produce certain crops."], [" To promote the benefits of a plant-based diet.", " To provide a comprehensive guide to different types of diets.", " To caution readers about the potential risks and drawbacks of plant-based diets.", " To criticize the medical establishment for failing to promote plant-based diets."],],
    q_ex: ["文章提到，植物性飲食具有降低心臟病、中風和某些癌症風險的益處，因為它們通常含有較少的飽和脂肪，較多的纖維素、維生素和礦物質。因此，答案為C。", "文章提到了有些人擔心植物性飲食可能無法提供所有必需的營養素，尤其是對於懷孕、哺乳或患有某些健康問題的人。例如，植物性飲食可能無法提供足夠的蛋白質、鈣或維生素B12。因此，答案為A。", "文章提到了如果想要選擇植物性飲食，就必須確保自己攝取所有必要的營養素，而且在進行任何重大飲食變化之前應該諮詢醫療保健專業人員。因此，答案為C。", "文章提到了一些植物性飲食可能在長期內不可持續，這是因為生產某些作物需要大量的水和其他資源。因此，答案為D。", "通過本文，作者的主要目的是提醒讀者植物性飲食可能存在潛在風險和缺點，並強調重要性以保持均衡的飲食並向醫療保健專業人員諮詢。因此，答案為C。",],
    q_a: [" C", " A", " C", " D", " C",],
    zh: "近年來，人們對植物性飲食越來越感興趣。這些飲食的倡導者認為，它們對人類和地球都更健康。但是植物性飲食真的更好嗎？讓我們仔細看看。植物性飲食的主要好處之一是它們的飽和脂肪含量往往較低，纖維、維生素和礦物質含量較高。這有助於降低患心髒病、中風和某些類型癌症的風險。植物性飲食也被證明可有效減輕體重和改善整體健康。然而，有些人擔心植物性飲食可能無法提供所有必需的營養，尤其是對於孕婦、哺乳期或患有某些疾病的人健康狀況。例如，植物性飲食可能無法提供足夠的蛋白質、鈣或維生素 B12。另一個問題是一些植物性食物，如大豆和堅果，可能會引起過敏並引起某些人的反應。此外，由於生產某些作物需要大量的水和其他資源，一些植物性飲食可能無法長期持續。總的來說，植物性飲食對許多人來說是一種健康和可持續的選擇。但是，重要的是要確保您獲得所有必需的營養，並在進行任何重大飲食改變之前諮詢醫療保健專業人員。"
}, {
    ar: "It’s a common misconception that introverts are shy, antisocial individuals who don’t enjoy socializing. While introverts may not seek out constant social stimulation like their extroverted counterparts, they do enjoy social interaction, albeit in smaller doses.In fact, introverts can be just as social as extroverts, but they simply need more time to recharge after socializing. This is because introverts are more sensitive to external stimuli and tend to be more easily overwhelmed by excessive socializing or sensory input.Introverts also tend to be more reflective and introspective than extroverts, and may prefer to spend time alone with their thoughts rather than engaging in constant external stimulation. This can be mistaken for shyness or aloofness, but in reality, introverts are simply processing and reflecting on their experiences in a deeper way.Despite the common misconception that introverts are at a disadvantage in social situations, introverts can actually be very effective communicators. They tend to be more thoughtful and deliberate in their speech, taking the time to carefully choose their words and express their ideas in a clear and concise manner.Overall, introversion is simply a personality trait that reflects a preference for solitude and introspection, rather than a social deficit or inability to communicate effectively.",
    q: ["According to the passage, what is a common misconception about introverts?", "What does the passage suggest about the difference between introverts and extroverts?", "What is the main difference between introverts and extroverts in terms of socializing, according to the passage?",],
    q_sel: [[" They are more easily overwhelmed by external stimuli.", " They do not enjoy socializing.", " They are less effective communicators than extroverts.", " They are more reflective and introspective than extroverts."], [" Introverts need more time to recharge after socializing.", " Extroverts are more easily overwhelmed by external stimuli.", " Introverts are less thoughtful and deliberate in their speech.", " Extroverts are more reflective and introspective than introverts."], [" Introverts enjoy socializing more than extroverts.", " Extroverts need more time to recharge after socializing.", " Introverts are more easily overwhelmed by socializing.", " There is no difference between introverts and extroverts in terms of socializing."],],
    q_ex: ["文章開始時提到了關於內向者的一個常見誤解，即他們不喜歡社交。因此，答案為B。", "根據文章所說，相較於外向者，內向者需要更多時間來重新充電，以應對社交造成的影響。因此，答案為A。", "根據文章，相較於外向者，內向者更容易被過度的社交或感官刺激所壓垮，因此在進行社交活動時更容易感到不適。因此，答案為C。",],
    q_a: [" B", " A", " C",],
    zh: "一個普遍的誤解是，內向的人是害羞的、反社會的，不喜歡社交。雖然內向的人可能不會像外向的人那樣尋求持續的社交刺激，但他們確實喜歡社交互動，儘管程度較低。事實上，內向的人可以和外向的人一樣社交，只是他們在社交後需要更多的時間來充電。這是因為內向的人對外部刺激更敏感，更容易被過度的社交或感官輸入所淹沒。內向的人也往往比外向的人更善於反思和內省，並且可能更喜歡花時間獨自思考而不是參與不斷的外部刺激。這可能會被誤認為害羞或冷漠，但實際上，內向的人只是在更深層次地處理和反思他們的經歷。儘管人們普遍誤解內向的人在社交場合處於劣勢，但內向的人實際上可以成為非常有效的溝通者。他們在說話時往往更深思熟慮，花時間仔細選擇自己的用詞，並以清晰簡潔的方式表達自己的想法。總的來說，內向只是一種性格特徵，反映了對孤獨和內省的偏好，而不是社交缺陷或無法有效溝通。"
}, {
    ar: "As the world becomes more technologically advanced, people are becoming more and more reliant on electronic devices. While these devices can make life easier and more convenient in many ways, there are also downsides to this dependence.One issue is the effect of electronic devices on sleep. Studies have shown that the blue light emitted by screens can interfere with the production of melatonin, a hormone that helps regulate sleep. This can lead to difficulty falling asleep, as well as poor-quality sleep.Another issue is the impact of electronic devices on social interaction. Many people now spend a significant amount of time interacting with others through social media and messaging apps, rather than in-person communication. This can lead to feelings of loneliness and isolation, as well as a lack of important social skills.Despite these downsides, electronic devices are not going anywhere. It is important for individuals to recognize the potential negative effects of these devices and take steps to mitigate them, such as limiting screen time before bed and making an effort to engage in face-to-face communication with others.",
    q: ["What is the main topic of the passage?", "What is one negative impact of electronic devices on sleep?", "How can overuse of electronic devices affect social skills?", "What is the author's main message?", "What is one step individuals can take to mitigate the negative effects of electronic devices?",],
    q_sel: [[" The benefits of electronic devices", " The downsides of electronic devices", " The future of electronic devices", " The evolution of electronic devices"], [" Increased production of melatonin", " Improved sleep quality", " Interference with melatonin production", " Increased likelihood of dreaming"], [" It can improve social interaction", " It can lead to feelings of loneliness and isolation", " It can increase face-to-face communication", " It can enhance the ability to read social cues"], [" Electronic devices are all bad", " Electronic devices are all good", " Electronic devices have both benefits and downsides", " Electronic devices will eventually disappear"], [" Increase screen time before bed", " Avoid face-to-face communication", " Use electronic devices more frequently", " Limit screen time before bed"],],
    q_ex: ["文章第一段提到了電子產品的優點，但是整篇文章都是在探討電子產品的缺點，因此答案為B。", "根據文章第二段的描述，電子產品發出的藍光會干擾褪黑激素的產生，進而影響睡眠，因此答案為C。", "文章第三段提到，人們現在花大量的時間透過社交媒體和消息應用程式與他人互動，而不是進行面對面的交流，這會導致孤獨感和孤立感，以及缺乏重要的社交技能，因此答案為B。", "文章提到了電子產品的缺點，但也指出了電子產品的優點，並強調了個人需要認識到這些設備的潛在負面影響，並採取措施來緩解它們帶來的影響，因此答案為C。", "文章最後一段建議個人應該認識到電子產品的潛在負面影響，並採取措施來緩解它們帶來的影響，其中一個建議就是在睡前限制使用電子產品的時間，因此答案為D。",],
    q_a: [" B", " C", " B", " C", " D",],
    zh: "隨著世界技術變得越來越先進，人們越來越依賴電子設備。雖然這些設備可以在許多方面讓生活更輕鬆、更方便，但這種依賴也有不利之處。一個問題是電子設備對睡眠的影響。研究表明，屏幕發出的藍光會干擾褪黑激素的產生，褪黑激素是一種有助於調節睡眠的激素。這會導致難以入睡，以及睡眠質量差。另一個問題是電子設備對社交互動的影響。許多人現在花費大量時間通過社交媒體和消息應用程序與他人互動，而不是面對面交流。這可能會導致孤獨感和孤立感，以及缺乏重要的社交技能。儘管有這些缺點，電子設備仍無處可去。個人必須認識到這些設備的潛在負面影響並採取措施減輕這些影響，例如限制睡前看屏幕的時間並努力與他人進行面對面的交流。"
}, {
    ar: "The human brain is incredibly complex, and there is still much that researchers do not understand about how it works. However, one thing that is clear is that the brain is highly adaptable and capable of change.Neuroplasticity is the term used to describe the brain's ability to reorganize itself in response to new experiences. This can involve creating new neural connections or strengthening existing ones. Neuroplasticity is thought to be a key factor in learning and memory, as well as in recovery from brain injuries.While the brain is capable of neuroplasticity throughout life, the extent to which it can change decreases with age. This means that young children are particularly adept at learning and adapting, while older adults may have more difficulty in these areas.However, there are things that individuals can do to promote neuroplasticity and enhance their brain's ability to adapt. Engaging in activities that are mentally stimulating, such as reading or solving puzzles, is one way to promote neuroplasticity. Physical exercise has also been shown to have a positive impact on brain function and neuroplasticity.",
    q: ["What is the main topic of the passage?", "What is neuroplasticity?", "How does neuroplasticity impact learning and memory?", "What is one way to promote neuroplasticity?",],
    q_sel: [[" The complexity of the human brain", " The role of neuroplasticity in brain function", " The effects of aging on the brain", " The benefits of mental stimulation"], [" The brain's ability to change in response to new experiences", " The brain's ability to maintain the status quo", " The brain's inability to change with age", " The brain's resistance to new experiences"], [" It has no effect on learning and memory", " It makes learning and memory more difficult", " It is a key factor in learning and memory", " It only impacts memory, not learning"], [" Avoid mental stimulation", " Limit physical exercise", " Engage in mentally stimulating activities", " Only engage in physical exercise"],],
    q_ex: ["文章主要在談論神經可塑性對於大腦功能的影響，因此答案為B。", "文章第二段中提到，神經可塑性是大腦對新體驗做出反應時重新組織自己的能力，包括建立新的神經連接或加強現有的連接，因此答案為A。", "文章中提到神經可塑性是學習和記憶的關鍵因素之一，因此答案為C。", "文章中提到，進行腦力刺激的活動（例如閱讀或解決問題）是促進神經可塑性的一種方式，因此答案為C。",],
    q_a: [" B", " A", " C", " C",],
    zh: "人腦極其複雜，研究人員對它的工作原理仍有很多不了解。然而，有一點是明確的，即大腦具有高度的適應性和變化能力。神經可塑性是用來描述大腦重組自身以響應新體驗的能力的術語。這可能涉及創建新的神經連接或加強現有的神經連接。神經可塑性被認為是學習和記憶以及腦損傷恢復的關鍵因素。雖然大腦在整個生命過程中都具有神經可塑性，但它可以改變的程度會隨著年齡的增長而降低。這意味著年幼的孩子特別善於學習和適應，而老年人在這些方面可能會遇到更多困難。但是，個人可以做一些事情來促進神經可塑性並增強大腦的適應能力。參與精神刺激的活動，例如閱讀或解決難題，是促進神經可塑性的一種方式。體育鍛煉也被證明對大腦功能和神經可塑性有積極影響。"
}, {
    ar: "Climate change is a pressing issue that has garnered significant attention in recent years. While there is still debate about the causes and extent of climate change, most scientists agree that it is largely driven by human activities, such as the burning of fossil fuels and deforestation.One of the consequences of climate change is rising sea levels. As temperatures continue to rise, glaciers and ice sheets are melting, causing water to flow into the oceans and contributing to sea level rise. This can have a devastating impact on coastal cities and communities, as well as on wildlife and ecosystems.Another consequence of climate change is extreme weather events, such as heat waves, droughts, and hurricanes. These events can lead to crop failures, water shortages, and infrastructure damage, among other things. They also pose a significant threat to human health and well-being.Addressing climate change requires a coordinated effort from individuals, governments, and businesses around the world. This may involve reducing greenhouse gas emissions, transitioning to renewable energy sources, and investing in technologies that can help mitigate the impacts of climate change.",
    q: ["What is the main topic of the passage?", "What are some human activities that are contributing to climate change?", "What is one consequence of rising temperatures?", "What is one way to address climate change?", "What is the author's opinion on climate change?",],
    q_sel: [[" The causes of climate change", " The impacts of climate change", " The debate about climate change", " The role of individuals in addressing climate change"], [" Eating meat and dairy products", " Planting trees and other vegetation", " Burning fossil fuels and deforestation", " Recycling and composting"], [" Decreasing sea levels", " Reduced crop yields", " Increased forest cover", " Improved wildlife habitats"], [" Increase greenhouse gas emissions", " Continue to rely on fossil fuels", " Transition to renewable energy sources", " Build more infrastructure in coastal areas"], [" It is not a significant issue", " It is entirely caused by human activities", " It is a topic of debate among scientists", " It requires a coordinated effort to address"],],
    q_ex: ["文章主要在談論氣候變化對於環境、野生動物和人類社區帶來的影響，因此答案為B。", "文章中提到，氣候變化很大程度上是由人類活動引起的，例如燃燒化石燃料和森林砍伐，因此答案為C。", "文章中提到，隨著溫度持續上升，冰川和冰原融化，導致水流入海洋並促成海平面上升，這對沿海城市和社區以及野生動物和生態系統都會產生毀滅性的影響。因此答案為B。", "文章中提到，應對氣候變化需要全球個人、政府和企業之間的協調努力，這可能包括減少溫室氣體排放，轉向可再生能源來源以及投資於能減緩氣候變化影響的技術等。因此答案為C。", "文章作者沒有表達對氣候變化本身的觀點，而是強調需要全球個人、政府和企業之間的協調努力才能應對氣候變化。因此答案為D。",],
    q_a: [" B", " C", " B", " C", " D",],
    zh: "氣候變化是一個緊迫的問題，近年來引起了廣泛關注。儘管對氣候變化的原因和程度仍有爭論，但大多數科學家都認為，氣候變化主要是由人類活動驅動的，例如燃燒化石燃料和砍伐森林。氣候變化的後果之一是海平面上升。隨著氣溫持續上升，冰川和冰原正在融化，導致水流入海洋並導致海平面上升。這會對沿海城市和社區以及野生動物和生態系統產生毀滅性影響。氣候變化的另一個後果是極端天氣事件，例如熱浪、乾旱和颶風。這些事件可能導致作物歉收、缺水和基礎設施損壞等。它們還對人類健康和福祉構成重大威脅。應對氣候變化需要全世界個人、政府和企業的協調努力。這可能涉及減少溫室氣體排放、轉向可再生能源以及投資有助於減輕氣候變化影響的技術。"
}, {
    ar: "In recent years, social media has become an integral part of many people's lives. Social media platforms such as Facebook, Twitter, and Instagram allow individuals to connect with others, share information and opinions, and stay up-to-date with the latest news and trends.While social media has many benefits, there are also concerns about its impact on mental health. Studies have found that excessive social media use can lead to feelings of loneliness, anxiety, and depression. This is partly due to the fact that social media often presents an idealized version of reality, which can lead to feelings of inadequacy and low self-esteem.Another concern is the spread of misinformation and fake news on social media. With the ability for anyone to publish and share information, it can be difficult to distinguish between fact and fiction. This can lead to confusion, anxiety, and even harm if individuals make decisions based on false information.Despite these concerns, social media remains a popular and influential medium. As such, it is important for individuals to use social media responsibly and critically evaluate the information they encounter online.",
    q: ["What is the main topic of the passage?", "What are some negative impacts of excessive social media use?", "What is one concern about the spread of information on social media?", "What is one way to use social media responsibly?", "What is the author's overall attitude towards social media?",],
    q_sel: [[" The benefits of social media", " The impact of social media on mental health", " The spread of misinformation on social media", " The popularity of social media"], [" Improved self-esteem and mental well-being", " Increased feelings of connectedness and social support", " Feelings of loneliness, anxiety, and depression", " Improved ability to distinguish between fact and fiction"], [" The lack of access to information", " The inability to connect with others", " The spread of misinformation and fake news", " The cost of using social media"], [" Post without considering the impact on others", " Share all information encountered online", " Critically evaluate information encountered online", " Spend excessive amounts"], [" Positive", " Negative", " Neutral", " Ambivalent"],],
    q_ex: ["文章主要在談論社交媒體對於精神健康的影響，提到社交媒體的好處和擔憂，並強調了社交媒體使用的責任。因此答案為B。", "文章中提到，過度使用社交媒體可能會導致孤獨、焦慮和抑鬱等負面情緒，部分原因是社交媒體經常呈現現實的理想化版本，這可能會導致自尊心和自我價值感的不足。因此答案為C。", "文章中提到，社交媒體上的誤解和虛假新聞可能會導致混淆、焦慮，甚至造成傷害，如果個人基於錯誤信息做出決定。因此答案為C。", "文章強調了使用社交媒體的責任，個人應該批判性地評估在線遇到的信息。因此，答案為C。", "作者在文章中提到社交媒體的好處和擔憂，並強調了社交媒體使用的責任。因此，作者的態度是矛盾的（ambivalent），既有正面的看法，也有擔憂。因此答案為D。",],
    q_a: [" B", " C", " C", " C", " D",],
    zh: "近年來，社交媒體已成為許多人生活中不可或缺的一部分。 Facebook、Twitter 和 Instagram 等社交媒體平台允許個人與他人聯繫、分享信息和觀點，並及時了解最新消息和趨勢。雖然社交媒體有很多好處，但也有人擔心它對心理健康的影響。研究發現，過度使用社交媒體會導致孤獨、焦慮和抑鬱的感覺。部分原因是社交媒體經常呈現理想化的現實版本，這會導致自卑感和自卑感。另一個擔憂是社交媒體上錯誤信息和假新聞的傳播。由於任何人都可以發布和共享信息，因此很難區分事實和虛構。如果個人根據虛假信息做出決定，這可能會導致混亂、焦慮甚至傷害。儘管存在這些擔憂，社交媒體仍然是一種流行且有影響力的媒體。因此，個人負責任地使用社交媒體並批判性地評估他們在網上遇到的信息非常重要。"
}, {
    ar: "The concept of climate change has become an increasingly pressing issue in recent years. Climate change refers to the long-term changes in Earth's climate, including changes in temperature, precipitation, and wind patterns, among others. While natural factors such as volcanic activity and solar radiation can contribute to climate change, the overwhelming scientific consensus is that human activities, particularly the burning of fossil fuels, are the primary cause of the current trend.The consequences of climate change are vast and far-reaching. Rising temperatures can lead to extreme weather events such as hurricanes, floods, and droughts, which in turn can cause significant damage to infrastructure, property, and crops. Melting ice caps and rising sea levels can lead to the displacement of communities living in low-lying coastal areas. Climate change can also have negative impacts on public health, such as the spread of diseases and the exacerbation of existing health conditions.In response to the threat of climate change, many countries have taken action to reduce their greenhouse gas emissions and transition to more sustainable forms of energy. These efforts include investing in renewable energy sources such as wind and solar power, improving energy efficiency, and promoting public transportation and electric vehicles. While much remains to be done to address the challenges of climate change, there is reason for hope as countries and individuals work towards a more sustainable future.",
    q: ["What is climate change?", "What is the primary cause of climate change, according to the scientific consensus?", "What are some consequences of climate change?", "What are some ways countries have responded to the threat of climate change?", "What is the author's attitude towards the future of addressing climate change?",],
    q_sel: [[" Changes in temperature only", " Changes in temperature and precipitation only", " Changes in temperature, precipitation, and wind patterns, among others", " Changes in wind patterns only"], [" Volcanic activity", " Solar radiation", " Human activities, particularly the burning of fossil fuels", " A combination of natural and human factors"], [" Improved public health", " Decreased frequency of extreme weather events", " Damage to infrastructure, property, and crops due to extreme weather events", " Increased availability of natural resources"], [" Increasing the burning of fossil fuels", " Investing in renewable energy sources", " Encouraging the use of single-use plastics", " Decreasing public transportation options"], [" Pessimistic", " Optimistic", " Ambivalent", " Uncertain"],],
    q_ex: ["文章中說明了氣候變化包括許多方面的長期變化，包括溫度、降水和風等方面的變化。因此，答案為C。", "文章指出，雖然自然因素如火山活動和太陽輻射也會對氣候變化作出貢獻，但壓倒性的科學共識是人類活動，尤其是化石燃料的燃燒是當前氣候變化的主要原因。因此，答案為C。", "文章中提到，氣候變化的後果是廣泛而深遠的，包括極端天氣事件，如颶風、洪水和干旱，進而可能對基礎設施、財產和作物造成重大破壞。因此，答案為C。", "文章提到，為了應對氣候變化的威脅，許多國家已經採取了行動，包括投資於可再生能源，提高能源效率，以及促進公共交通和電動汽車的使用。因此，答案為B。", "文章中提到，雖然應對氣候變化的挑戰仍然存在，但是由於各國和個人正致力於實現更可持續的未來，因此有希望。這表明作者對應對氣候變化的未來持樂觀態度。因此，答案為B。",],
    q_a: [" C", " C", " C", " B", " B",],
    zh: "近年來，氣候變化的概念已成為一個日益緊迫的問題。氣候變化是指地球氣候的長期變化，包括溫度、降水和風型等的變化。雖然火山活動和太陽輻射等自然因素會導致氣候變化，但壓倒性的科學共識是人類活動，特別是化石燃料的燃燒，是當前趨勢的主要原因。氣候變化的後果是巨大而深遠的-達到。氣溫上升會導致颶風、洪水和乾旱等極端天氣事件，進而對基礎設施、財產和農作物造成重大破壞。冰蓋融化和海平面上升可能導致生活在低窪沿海地區的社區流離失所。氣候變化還會對公共衛生產生負面影響，例如疾病的傳播和現有健康狀況的惡化。為應對氣候變化的威脅，許多國家已採取行動減少溫室氣體排放並向更可持續的轉型能量形式。這些努力包括投資風能和太陽能等可再生能源，提高能源效率，以及推廣公共交通和電動汽車。儘管要應對氣候變化的挑戰還有很多工作要做，但隨著各國和個人朝著更可持續的未來努力，我們有理由抱有希望。"
}, {
    ar: "The Importance of SleepWe all know that getting a good night's sleep is important, but many of us still don't get enough sleep on a regular basis. In fact, studies have shown that more than one-third of American adults do not get the recommended seven hours of sleep each night.Lack of sleep can have a variety of negative effects on both our physical and mental health. For example, it can increase the risk of developing chronic health conditions such as obesity, diabetes, and cardiovascular disease. It can also impair our immune system, making us more susceptible to illnesses.In addition to these physical health effects, lack of sleep can also affect our mental health. It can lead to problems with mood regulation, making us more irritable, anxious, and depressed. It can also impair cognitive function, making it harder to concentrate, learn, and remember things.So how can we improve our sleep habits? Here are some tips:Stick to a regular sleep schedule. Go to bed and wake up at the same time every day, even on weekends.Create a relaxing sleep environment. Keep your bedroom dark, quiet, and cool, and avoid using electronic devices before bed.Avoid caffeine, nicotine, and alcohol before bedtime, as they can disrupt your sleep.Get regular exercise, but avoid exercising too close to bedtime.If you have trouble sleeping, try relaxation techniques such as deep breathing or meditation, or consider talking to a healthcare professional about sleep aids.",
    q: ["What is the main idea of the passage?", "According to the passage, what are some physical health effects of lack of sleep?", "What is the author's advice for creating a relaxing sleep environment?", "According to the passage, what is one potential consequence of impaired cognitive function due to lack of sleep?", "What is the author's advice for improving sleep habits?",],
    q_sel: [[" Lack of sleep can have negative effects on physical health.", " Lack of sleep can have negative effects on mental health.", " Lack of sleep is a problem for many Americans.", " Getting a good night's sleep is important."], [" Increased risk of developing depression.", " Impaired cognitive function.", " Increased risk of developing cardiovascular disease.", " Difficulty concentrating."], [" Use electronic devices before bed.", " Keep the bedroom warm and bright.", " Avoid noise in the bedroom.", " Keep the bedroom cool and dark."], [" Increased risk of developing obesity.", " Difficulty concentrating and learning.", " Higher susceptibility to illnesses.", " Problems with mood regulation."], [" Drink alcohol before bedtime.", " Exercise right before going to bed.", " Stick to a regular sleep schedule.", " Use electronic devices in bed."],],
    q_ex: ["文章一開始就提到了睡眠的重要性，後面的內容也在強調睡眠的好處以及如何改善睡眠習慣。因此，答案為D。", "文章提到，缺乏睡眠可以增加患上慢性疾病（例如肥胖症、糖尿病和心血管疾病）的風險。因此，答案為C。", "文章提到了創建一個放鬆的睡眠環境的建議，其中包括保持臥室涼爽、黑暗以及避免在睡前使用電子設備。因此，答案為D。", "文章提到了缺乏睡眠對認知功能的影響，可能會讓人難以集中注意力、學習和記憶。因此，答案為B。", "文章提到了改善睡眠習慣的建議，其中包括保持規律的睡眠時間表，晚上睡前避免飲用咖啡因、尼古丁和酒精，以及避免在睡前使用電子設備。因此，答案為C。",],
    q_a: [" D", " C", " D", " B", " C",],
    zh: "睡眠的重要性我們都知道睡個好覺很重要，但我們中的許多人仍然沒有定期獲得足夠的睡眠。事實上，研究表明，超過三分之一的美國成年人每晚沒有達到建議的七小時睡眠時間。睡眠不足會對我們的身心健康產生各種負面影響。例如，它會增加患肥胖症、糖尿病和心血管疾病等慢性疾病的風險。它還會損害我們的免疫系統，使我們更容易生病。除了這些身體健康影響外，睡眠不足還會影響我們的心理健康。它會導致情緒調節問題，使我們更加易怒、焦慮和抑鬱。它還會損害認知功能，使注意力、學習和記憶變得更加困難。那麼我們如何改善睡眠習慣呢？這裡有一些提示： 堅持規律的睡眠時間表。每天在同一時間睡覺和起床，週末也不例外。營造輕鬆的睡眠環境。保持臥室黑暗、安靜和涼爽，睡前避免使用電子設備。睡前避免咖啡因、尼古丁和酒精，因為它們會擾亂您的睡眠。定期鍛煉，但避免在臨睡前鍛煉。如果您有睡眠困難，嘗試放鬆技巧，如深呼吸或冥想，或考慮與醫療保健專業人員討論助眠劑。"
}, {
    ar: "It’s a common misconception that introverts are shy, antisocial individuals who don’t enjoy socializing. While introverts may not seek out constant social stimulation like their extroverted counterparts, they do enjoy social interaction, albeit in smaller doses.In fact, introverts can be just as social as extroverts, but they simply need more time to recharge after socializing. This is because introverts are more sensitive to external stimuli and tend to be more easily overwhelmed by excessive socializing or sensory input.Introverts also tend to be more reflective and introspective than extroverts, and may prefer to spend time alone with their thoughts rather than engaging in constant external stimulation. This can be mistaken for shyness or aloofness, but in reality, introverts are simply processing and reflecting on their experiences in a deeper way.Despite the common misconception that introverts are at a disadvantage in social situations, introverts can actually be very effective communicators. They tend to be more thoughtful and deliberate in their speech, taking the time to carefully choose their words and express their ideas in a clear and concise manner.Overall, introversion is simply a personality trait that reflects a preference for solitude and introspection, rather than a social deficit or inability to communicate effectively.",
    q: ["According to the passage, what is a common misconception about introverts?", "What does the passage suggest about the difference between introverts and extroverts?", "What is the main difference between introverts and extroverts in terms of socializing, according to the passage?",],
    q_sel: [[" They are more easily overwhelmed by external stimuli.", " They do not enjoy socializing.", " They are less effective communicators than extroverts.", " They are more reflective and introspective than extroverts."], [" Introverts need more time to recharge after socializing.", " Extroverts are more easily overwhelmed by external stimuli.", " Introverts are less thoughtful and deliberate in their speech.", " Extroverts are more reflective and introspective than introverts."], [" Introverts enjoy socializing more than extroverts.", " Extroverts need more time to recharge after socializing.", " Introverts are more easily overwhelmed by socializing.", " There is no difference between introverts and extroverts in terms of socializing."],],
    q_ex: ["文章開始時提到了關於內向者的一個常見誤解，即他們不喜歡社交。因此，答案為B。", "根據文章所說，相較於外向者，內向者需要更多時間來重新充電，以應對社交造成的影響。因此，答案為A。", "根據文章，相較於外向者，內向者更容易被過度的社交或感官刺激所壓垮，因此在進行社交活動時更容易感到不適。因此，答案為C。",],
    q_a: [" B", " A", " C",],
    zh: "一個普遍的誤解是，內向的人是害羞的、反社會的，不喜歡社交。雖然內向的人可能不會像外向的人那樣尋求持續的社交刺激social media and messaging apps, rather than in-person communication. This can lead to feelings of loneliness and isolation, as well as a lack of important social skills.Despite these downsides, electronic devices are not going anywhere. It is important for individuals to recognize the potential negative effects of these devices and take steps to mitigate them, such as limiting screen time before bed and making an eff，但他們確實喜歡社交互動，儘管程度較低。事實上，內向的人可以和外向的人一樣社交，只是他們在社交後需要更多的時間來充電。這是因為內向的人對外部刺激更敏感，更容易被過度的社交或感官輸入所淹沒。內向的人也往往比外向的人更善於反思和內省，並且可能更喜歡花時間獨自思考而不是參與不斷的外部刺激。這可能會被誤認為害羞或冷漠，但實際上，內向的人只是在更深層次地處理和反思他們的經歷。儘管人們普遍誤解內向的人在社交場合處於劣勢，但內向的人實際上可以成為非常有效的溝通者。他們在說話時往往更深思熟慮，花時間仔細選擇自己的用詞，並以清晰簡潔的方式表達自己的想法。總的來說，內向只是一種性格特徵，反映了對孤獨和內省的偏好，而不是社交缺陷或無法有效溝通。"
}, {
    ar: "As the world becomes more technologically advanced, people are becoming more and more reliant on electronic devices. While these devices can make life easier and more convenient in many ways, there are also downsides to this dependence.One issue is the effect of electronic devices on sleep. Studies have shown that the blue light emitted by screens can interfere with the production of melatonin, a hormone that helps regulate sleep. This can lead to difficulty falling asleep, as well as poor-quality sleep.Another issue is the impact of electronic devices on social interaction. Many people now spend a significant amount of time interacting with others through ort to engage in face-to-face communication with others.",
    q: ["What is the main topic of the passage?", "What is one negative impact of electronic devices on sleep?", "How can overuse of electronic devices affect social skills?", "What is the author's main message?", "What is one step individuals can take to mitigate the negative effects of electronic devices?",],
    q_sel: [[" The benefits of electronic devices", " The downsides of electronic devices", " The future of electronic devices", " The evolution of electronic devices"], [" Increased production of melatonin", " Improved sleep quality", " Interference with melatonin production", " Increased likelihood of dreaming"], [" It can improve social interaction", " It can lead to feelings of loneliness and isolation", " It can increase face-to-face communication", " It can enhance the ability to read social cues"], [" Electronic devices are all bad", " Electronic devices are all good", " Electronic devices have both benefits and downsides", " Electronic devices will eventually disappear"], [" Increase screen time before bed", " Avoid face-to-face communication", " Use electronic devices more frequently", " Limit screen time before bed"],],
    q_ex: ["文章第一段提到了電子產品的優點，但是整篇文章都是在探討電子產品的缺點，因此答案為B。", "根據文章第二段的描述，電子產品發出的藍光會干擾褪黑激素的產生，進而影響睡眠，因此答案為C。", "文章第三段提到，人們現在花大量的時間透過社交媒體和消息應用程式與他人互動，而不是進行面對面的交流，這會導致孤獨感和孤立感，以及缺乏重要的社交技能，因此答案為B。", "文章提到了電子產品的缺點，但也指出了電子產品的優點，並強調了個人需要認識到這些設備的潛在負面影響，並採取措施來緩解它們帶來的影響，因此答案為C。", "文章最後一段建議個人應該認識到電子產品的潛在負面影響，並採取措施來緩解它們帶來的影響，其中一個建議就是在睡前限制使用電子產品的時間，因此答案為D。",],
    q_a: [" B", " C", " B", " C", " D",],
    zh: "隨著世界技術變得越來越先進，人們越來越依賴電子設備。雖然這些設備可以在許多方面讓生活更輕鬆、更方便，但這種依賴也有不利之處。一個問題是電子設備對睡眠的影響。研究表明，屏幕發出的藍光會干擾褪黑激素的產生，褪黑激素是一種有助於調節睡眠的激素。這會導致難以入睡，以及睡眠質量差。另一個問題是電子設備對社交互動的影響。許多人現在花費大量時間通過社交媒體和消息應用程序與他人互動，而不是面對面交流。這可能會導致孤獨感和孤立感，以及缺乏重要的社交技能。儘管有這些缺點，電子設備仍無處可去。個人必須認識到這些設備的潛在負面影響並採取措施減輕這些影響，例如限制睡前看屏幕的時間並努力與他人進行面對面的交流。"
}, {
    ar: "The human brain is incredibly complex, and there is still much that researchers do not understand about how it works. However, one thing that is clear is that the brain is highly adaptable and capable of change.Neuroplasticity is the term used to describe the brain's ability to reorganize itself in response to new experiences. This can involve creating new neural connections or strengthening existing ones. Neuroplasticity is thought to be a key factor in learning and memory, as well as in recovery from brain injuries.While the brain is capable of neuroplasticity throughout life, the extent to which it can change decreases with age. This means that young children are particularly adept at learning and adapting, while older adults may have more difficulty in these areas.However, there are things that individuals can do to promote neuroplasticity and enhance their brain's ability to adapt. Engaging in activities that are mentally stimulating, such as reading or solving puzzles, is one way to promote neuroplasticity. Physical exercise has also been shown to have a positive impact on brain function and neuroplasticity.",
    q: ["What is the main topic of the passage?", "What is neuroplasticity?", "How does neuroplasticity impact learning and memory?", "What is one way to promote neuroplasticity?",],
    q_sel: [[" The complexity of the human brain", " The role of neuroplasticity in brain function", " The effects of aging on the brain", " The benefits of mental stimulation"], [" The brain's ability to change in response to new experiences", " The brain's ability to maintain the status quo", " The brain's inability to change with age", " The brain's resistance to new experiences"], [" It has no effect on learning and memory", " It makes learning and memory more difficult", " It is a key factor in learning and memory", " It only impacts memory, not learning"], [" Avoid mental stimulation", " Limit physical exercise", " Engage in mentally stimulating activities", " Only engage in physical exercise"],],
    q_ex: ["文章主要在談論神經可塑性對於大腦功能的影響，因此答案為B。", "文章第二段中提到，神經可塑性是大腦對新體驗做出反應時重新組織自己的能力，包括建立新的神經連接或加強現有的連接，因此答案為A。", "文章中提到神經可塑性是學習和記憶的關鍵因素之一，因此答案為C。", "文章中提到，進行腦力刺激的活動（例如閱讀或解決問題）是促進神經可塑性的一種方式，因此答案為C。",],
    q_a: [" B", " A", " C", " C",],
    zh: "人腦極其複雜，研究人員對它的工作原理仍有很多不了解。然而，有一點是明確的，即大腦具有高度的適應性和變化能力。神經可塑性是用來描述大腦重組自身以響應新體驗的能力的術語。這可能涉及創建新的神經連接或加強現有的神經連接。神經可塑性被認為是學習和記憶以及腦損傷恢復的關鍵因素。雖然大腦在整個生命過程中都具有神經可塑性，但它可以改變的程度會隨著年齡的增長而降低。這意味著年幼的孩子特別善於學習和適應，而老年人在這些方面可能會遇到更多困難。但是，個人可以做一些事情來促進神經可塑性並增強大腦的適應能力。參與精神刺激的活動，例如閱讀或解決難題，是促進神經可塑性的一種方式。體育鍛煉也被證明對大腦功能和神經可塑性有積極影響。"
}, {
    ar: "Climate change is a pressing issue that has garnered significant attention in recent years. While there is still debate about the causes and extent of climate change, most scientists agree that it is largely driven by human activities, such as the burning of fossil fuels and deforestation.One of the consequences of climate change is rising sea levels. As temperatures continue to rise, glaciers and ice sheets are melting, causing water to flow into the oceans and contributing to sea level rise. This can have a devastating impact on coastal cities and communities, as well as on wildlife and ecosystems.Another consequence of climate change is extreme weather events, such as heat waves, droughts, and hurricanes. These events can lead to crop failures, water shortages, and infrastructure damage, among other things. They also pose a significant threat to human health and well-being.Addressing climate change requires a coordinated effort from individuals, governments, and businesses around the world. This may involve reducing greenhouse gas emissions, transitioning to renewable energy sources, and investing in technologies that can help mitigate the impacts of climate change.",
    q: ["What is the main topic of the passage?", "What are some human activities that are contributing to climate change?", "What is one consequence of rising temperatures?", "What is one way to address climate change?", "What is the author's opinion on climate change?",],
    q_sel: [[" The causes of climate change", " The impacts of climate change", " The debate about climate change", " The role of individuals in addressing climate change"], [" Eating meat and dairy products", " Planting trees and other vegetation", " Burning fossil fuels and deforestation", " Recycling and composting"], [" Decreasing sea levels", " Reduced crop yields", " Increased forest cover", " Improved wildlife habitats"], [" Increase greenhouse gas emissions", " Continue to rely on fossil fuels", " Transition to renewable energy sources", " Build more infrastructure in coastal areas"], [" It is not a significant issue", " It is entirely caused by human activities", " It is a topic of debate among scientists", " It requires a coordinated effort to address"],],
    q_ex: ["文章主要在談論氣候變化對於環境、野生動物和人類社區帶來的影響，因此答案為B。", "文章中提到，氣候變化很大程度上是由人類活動引起的，例如燃燒化石燃料和森林砍伐，因此答案為C。", "文章中提到，隨著溫度持續上升，冰川和冰原融化，導致水流入海洋並促成海平面上升，這對沿海城市和社區以及野生動物和生態系統都會產生毀滅性的影響。因此答案為B。", "文章中提到，應對氣候變化需要全球個人、政府和企業之間的協調努力，這可能包括減少溫室氣體排放，轉向可再生能源來源以及投資於能減緩氣候變化影響的技術等。因此答案為C。", "文章作者沒有表達對氣候變化本身的觀點，而是強調需要全球個人、政府和企業之間的協調努力才能應對氣候變化。因此答案為D。",],
    q_a: [" B", " C", " B", " C", " D",],
    zh: "氣候變化是一個緊迫的問題，近年來引起了廣泛關注。儘管對氣候變化的原因和程度仍有爭論，但大多數科學家都認為，氣候變化主要是由人類活動驅動的，例如燃燒化石燃料和砍伐森林。氣候變化的後果之一是海平面上升。隨著氣溫持續上升，冰川和冰原正在融化，導致水流入海洋並導致海平面上升。這會對沿海城市和社區以及野生動物和生態系統產生毀滅性影響。氣候變化的另一個後果是極端天氣事件，例如熱浪、乾旱和颶風。這些事件可能導致作物歉收、缺水和基礎設施損壞等。它們還對人類健康和福祉構成重大威脅。應對氣候變化需要全世界個人、政府和企業的協調努力。這可能涉及減少溫室氣體排放、轉向可再生能源以及投資有助於減輕氣候變化影響的技術。"
}, {
    ar: "For many years, scientists have been trying to find a cure for cancer. They have made some progress, but they still have not found a complete cure. However, there are ways to reduce the risk of getting cancer. One of these ways is to have a healthy diet.Eating a healthy diet is important for many reasons. A healthy diet can help you maintain a healthy weight, which is important because being overweight can increase your risk of cancer. A healthy diet can also provide your body with the nutrients it needs to fight off cancer.So what is a healthy diet? A healthy diet is one that is high in fruits, vegetables, whole grains, and lean protein. It is also low in saturated and trans fats, processed foods, and sugar. Eating a healthy diet can be challenging, but there are many resources available to help you make the right choices.In addition to eating a healthy diet, there are other things you can do to reduce your risk of cancer. These include exercising regularly, not smoking, and protecting your skin from the sun. By making these healthy choices, you can reduce your risk of cancer and improve your overall health.",
    q: ["What have scientists been trying to find for many years?", "What are the benefits of eating a healthy diet?", "What should a healthy diet be low in?", "What are some other ways to reduce the risk of cancer?",],
    q_sel: [[" A complete cure for cancer.", " A way to reduce the risk of cancer.", " A healthy diet.", " A bed diet."], [" Maintaining a healthy weight and providing the body with the nutrients it needs.", " Reducing the risk of smoking and protecting the skin from the sun.", " Eating lean protein and avoiding processed foods.", " Trying to find a cure for cancer."], [" Fruits, vegetables, and whole grains.", " Saturated and trans fats, processed foods, and sugar.", " Lean protein.", " A healthy diet can help you maintain a healthy weight."], [" Eating a healthy diet and exercising regularly.", " Smoking and protecting the skin from the sun.", " Drinking alcohol and eating processed foods.", " Reduce your risk of cancer."],],
    q_ex: ["根據文章第一句話'For many years, scientists have been trying to find a cure for cancer.'可知科學家多年來一直在尋找治癒癌症的方法，而本段的主要內容是講述吃健康飲食可以降低患癌症的風險，因此答案為A。", "根據文章第二段的內容，一個健康的飲食可以幫助人們保持健康的體重，同時也能提供身體所需的營養素，因此答案為A。", "根據文章第三段的內容，一個健康的飲食應該低於飽和和反式脂肪、加工食品和糖，因此答案為B。", "根據文章第四段的內容，健康飲食和定期鍛煉，可以降低患癌症的風險，因此答案為A。",],
    q_a: [" A", " A", " B", " A",],
    zh: "多年來，科學家們一直在努力尋找治療癌症的方法。他們取得了一些進展，但仍未找到徹底治癒的方法。但是，有一些方法可以降低患癌症的風險。其中一種方法是健康飲食。出於多種原因，健康飲食很重要。健康的飲食可以幫助您保持健康的體重，這很重要，因為超重會增加患癌症的風險。健康的飲食還可以為您的身體提供抗癌所需的營養。那麼什麼是健康的飲食呢？健康的飲食是富含水果、蔬菜、全穀物和瘦肉蛋白的飲食。它的飽和脂肪和反式脂肪、加工食品和糖含量也很低。健康飲食可能具有挑戰性，但有許多資源可以幫助您做出正確的選擇。除了健康飲食之外，您還可以採取其他措施來降低患癌症的風險。這些措施包括定期鍛煉、不吸煙和保護皮膚免受陽光照射。通過做出這些健康的選擇，您可以降低患癌症的風險並改善整體健康狀況。"
}, {
    ar: "The Great Barrier Reef is a natural wonder located off the coast of Australia. It is the largest coral reef system in the world, stretching over 2,300 kilometers. The Great Barrier Reef is home to thousands of species of marine life, including sea turtles, dolphins, and over 1,500 species of fish.Unfortunately, the Great Barrier Reef is facing many threats. Climate change is causing the water temperatures to rise, which is bleaching the coral and killing off many of the marine species that live there. Pollution from land-based activities is also damaging the reef. This includes pollution from agricultural runoff, sewage, and industrial waste.To help protect the Great Barrier Reef, the Australian government has implemented several initiatives. These include reducing carbon emissions, improving water quality, and reducing the amount of pollution that enters the reef. There are also many conservation organizations that are working to protect the reef, such as the Great Barrier Reef Foundation.It is important that we all do our part to protect the Great Barrier Reef. We can do this by reducing our carbon footprint, using environmentally-friendly products, and being mindful of our water usage. By working together, we can help ensure that the Great Barrier Reef remains a natural wonder for generations to come.",
    q: ["Where is the Great Barrier Reef located?", "What is the Great Barrier Reef known for?", "What are some threats to the Great Barrier Reef?", "What initiatives has the Australian government implemented to protect the Great Barrier Reef?", "How can we help protect the Great Barrier Reef?",],
    q_sel: [[" Off the coast of Africa.", " Off the coast of Asia.", " Off the coast of Australia.", " Off the coast of Japen."], [" Being the largest coral reef system in the world.", " Being home to thousands of species of marine life.", " Both A and B .", " To help protect the Great Barrier Reef."], [" Rising water temperatures and pollution.", " Overfishing and tourism.", " Hurricanes and earthquakes.", " The Australian government has implemented several initiatives."], [" Reducing carbon emissions, improving water quality, and reducing pollution.", " Increasing carbon emissions, improving tourism, and reducing fishing.", " Both A and B .", " We can do this by reducing our carbon footprint."], [" By using environmentally-friendly products.", " By reducing our carbon footprint.", " By being mindful of our water usage.", " All of the above."],],
    q_ex: ["根據文章第一句話'The Great Barrier Reef is a natural wonder located off the coast of Australia.'可知大堡礁位於澳洲海岸外，因此答案為C。", "根據文章第一段可知，大堡礁是世界上最大的珊瑚礁系統，同時也是數千種海洋生物的家園，因此答案為C。", "根據文章第二段的內容，大堡礁正面臨許多威脅，包括水溫上升和來自陸地活動的污染，因此答案為A。", "根據文章第三段的內容，澳洲政府實施了許多措施，包括減少碳排放、改善水質和減少進入珊瑚礁的污染，因此答案為A。", "根據文章最後一段的內容，我們可以透過減少碳足跡、使用環保產品和注意節約用水等方式來幫助保護大堡礁，因此答案為D。",],
    q_a: [" C", " C", " A", " A", " D",],
    zh: "大堡礁是位於澳大利亞海岸外的自然奇觀。它是世界上最大的珊瑚礁系統，綿延 2,300 多公里。大堡礁是數千種海洋生物的家園，包括海龜、海豚和 1,500 多種魚類。不幸的是，大堡礁正面臨著許多威脅。氣候變化導致水溫升高，導致珊瑚白化並殺死許多生活在那裡的海洋物種。陸上活動造成的污染也在破壞珊瑚礁。這包括農業徑流、污水和工業廢料造成的污染。為幫助保護大堡礁，澳大利亞政府實施了多項舉措。其中包括減少碳排放、改善水質以及減少進入珊瑚礁的污染量。也有許多保護組織致力於保護大堡礁，例如大堡礁基金會。重要的是我們都儘自己的一份力量來保護大堡礁。我們可以通過減少碳足跡、使用環保產品和注意用水來做到這一點。通過共同努力，我們可以幫助確保大堡礁為子孫後代留下一個自然奇觀。"
}, {
    ar: "The Importance of SleepSleep is an essential part of a healthy lifestyle. It allows our bodies to rest and recharge, and it plays a vital role in our overall well-being. Unfortunately, many people do not get enough sleep, which can have serious consequences for their health and well-being.There are several reasons why people may not be getting enough sleep. Some people have busy schedules and find it difficult to make time for sleep. Others may have trouble falling asleep or staying asleep due to stress or anxiety. In addition, the use of electronic devices such as smartphones and computers before bedtime can interfere with sleep patterns.The consequences of not getting enough sleep can be severe. Lack of sleep can lead to a weakened immune system, increased risk of accidents, and decreased cognitive function. It can also contribute to mental health issues such as depression and anxiety.To ensure that you are getting enough sleep, it is important to establish a regular sleep schedule and stick to it. This means going to bed and waking up at the same time every day, even on weekends. Avoiding caffeine and alcohol before bedtime can also help improve sleep quality. Additionally, creating a relaxing sleep environment and limiting the use of electronic devices before bedtime can also improve sleep.In conclusion, sleep is a crucial part of a healthy lifestyle. By making sleep a priority and taking steps to improve sleep quality, we can improve our overall health and well-being.",
    q: ["What is the importance of sleep?", "What are some reasons why people may not be getting enough sleep?", "What are some consequences of not getting enough sleep?", "What can we do to improve our sleep quality?",],
    q_sel: [[" It allows our bodies to rest and recharge.", " It plays a vital role in our overall well-being.", " Both A and B .", " It is important to establish a regular sleep schedule and stick to it."], [" Busy schedules and stress.", " Use of electronic devices before bedtime.", " Both A and B .", " It allows our bodies to rest and recharge."], [" Weakened immune system and increased risk of accidents.", " Decreased cognitive function and mental health issues.", " Both A and B .", " To ensure that you are getting enough sleep."], [" Establish a regular sleep schedule and stick to it.", " Avoid caffeine and alcohol before bedtime.", " Create a relaxing sleep environment and limit the use of electronic devices before bedtime.", " All of the above."],],
    q_ex: ["根據文章第一句話，睡眠是健康生活方式中必不可少的一部分，它讓我們的身體得到休息和充電，對我們的整體健康起著至關重要的作用，因此答案為C。", "根據文章第二段的內容，有些人因為繁忙的日程而很難為睡眠騰出時間，有些人可能因為壓力或焦慮而難以入睡或保持睡眠，此外，在睡前使用電子設備，如智能手機和電腦，也會影響睡眠模式，因此答案為C。", "根據文章第三段的內容，睡眠不足會導致免疫系統虛弱，增加意外事故風險，並減少認知功能。它還可能導致心理健康問題，如抑鬱和焦慮，因此答案為C。", "根據文章最後一段的內容，確保有足夠的睡眠，需要建立一個定期的睡眠計劃並堅持下去，避免在睡前使用咖啡因和酒精，同時創造一個放鬆的睡眠環境和限制睡前使用電子設備，因此答案為D。",],
    q_a: [" C", " C", " C", " D",],
    zh: "睡眠的重要性睡眠是健康生活方式的重要組成部分。它讓我們的身體得到休息和充電，對我們的整體健康起著至關重要的作用。不幸的是，許多人睡眠不足，這會對他們的健康和福祉造成嚴重後果。人們可能睡眠不足的原因有多種。有些人的日程安排很忙，很難抽出時間睡覺。其他人可能由於壓力或焦慮而難以入睡或難以入睡。此外，睡前使用智能手機和電腦等電子設備會干擾睡眠模式。睡眠不足的後果可能很嚴重。睡眠不足會導致免疫系統減弱、事故風險增加和認知功能下降。它還會導致心理健康問題，例如抑鬱和焦慮。為確保您獲得充足的睡眠，重要的是要製定規律的睡眠時間表並堅持下去。這意味著每天在同一時間睡覺和起床，即使在周末也不例外。睡前避免攝入咖啡因和酒精也有助於改善睡眠質量。此外，創造一個放鬆的睡眠環境和限制睡前使用電子設備也可以改善睡眠。總之，睡眠是健康生活方式的重要組成部分。通過將睡眠放在首位並採取措施改善睡眠質量，我們可以改善整體健康和福祉。"
}, {
    ar: "In recent years, there has been a growing interest in sustainable fashion. Sustainable fashion aims to reduce the negative impact that the fashion industry has on the environment, while also promoting fair labor practices and ethical treatment of workers. This can include using eco-friendly materials, reducing waste through recycling and upcycling, and ensuring that workers are paid fair wages and have safe working conditions.",
    q: ["What is sustainable fashion?", "What are some ways sustainable fashion can reduce negative impact on the environment?", "What does sustainable fashion aim to promote?",],
    q_sel: [[" Fashion that is expensive.", " Fashion that is trendy.", " Fashion that aims to reduce negative impact on the environment and promote fair labor practices.", " Fashion that is not made in developing countries."], [" Using eco-friendly materials.", " Promoting fair labor practices.", " Recycling and upcycling.", " Both A and C ."], [" Fair labor practices and ethical treatment of workers.", " The use of expensive materials.", " The production of trendy fashion.", " The use of developing countries for manufacturing."],],
    q_ex: ["根據文章第一句話“近年來，對可持續時尚的關注越來越高”，可知這段文章主要在談論可持續時尚。可持續時尚的目標是減少時尚產業對環境的負面影響，同時促進公平勞動慣例和對工人的道德對待。因此，答案為C。", "根據文章第二句話“可持續時尚旨在通過使用環保材料、通過回收和再利用減少浪費以及確保工人得到公平的工資和安全的工作條件等方式來減少時尚對環境的負面影響”，可知答案為D，即使用環保材料和通過回收和再利用減少浪費。", "根據文章第一句話“可持續時尚旨在減少時尚產業對環境的負面影響，同時促進公平勞動慣例和對工人的道德對待”，可知可持續時尚旨在促進公平勞動慣例和對工人的道德對待。因此，答案為A。",],
    q_a: [" C", " D", " A",],
    zh: "近年來，人們對可持續時尚的興趣與日俱增。可持續時尚旨在減少時尚業對環境的負面影響，同時促進公平的勞動實踐和對工人的道德對待。這可以包括使用環保材料，通過回收和升級回收減少浪費，並確保工人獲得公平的工資和安全的工作條件。"
}, {
    ar: "Technology has transformed the way we live, work, and communicate. One area that has seen a significant impact is the job market. The rise of automation and artificial intelligence has led to the automation of many tasks that were previously performed by humans. This has resulted in a shift in the types of jobs available, with an increasing focus on jobs that require higher levels of skill, such as programming and data analysis.",
    q: ["What is the main idea of this passage?", "What is one consequence of the rise of automation and artificial intelligence?", "What types of jobs are becoming more important?",],
    q_sel: [[" Technology has had a significant impact on our lives.", " The rise of automation and artificial intelligence has changed the job market.", " Jobs that require higher levels of skill are becoming more important.", " Both B and C ."], [" A decrease in the number of available jobs.", " An increase in the types of jobs available.", " A decrease in the need for workers with high levels of skill.", " A decrease in the need for workers who can adapt to new technology."], [" Jobs that require lower levels of skill.", " Jobs that require higher levels of skill.", " Jobs that can be automated.", " Both A and C ."],],
    q_ex: ["文章講述了科技對生活、工作和溝通的影響，但重點是科技對就業市場的影響，尤其是自動化和人工智慧的崛起導致了許多以前由人類執行的任務自動化。這導致了可用工作類型的轉變，越來越注重需要更高水平技能的工作，如編程和數據分析。因此，答案為D。", "根據文章第二句話“自動化和人工智慧的崛起導致了許多以前由人類執行的任務自動化”，可知自動化和人工智慧的崛起導致了更多類型的工作，因此答案為B。", "根據文章最後一句話“越來越注重需要更高水平技能的工作，如編程和數據分析”，可知需要更高水平技能的工作正在變得更加重要，因此答案為B。",],
    q_a: [" D", " B", " B",],
    zh: "技術改變了我們生活、工作和交流的方式。一個受到重大影響的領域是就業市場。自動化和人工智能的興起導致許多以前由人類執行的任務實現了自動化。這導致了可用工作類型的轉變，人們越來越關注需要更高技能水平的工作，例如編程和數據分析。"
}, {
    ar: "In recent years, there has been a growing concern about the impact of plastic waste on the environment. It is estimated that over 8 million tons of plastic end up in the oceans every year, harming marine life and polluting our beaches. While recycling can help to reduce the amount of plastic waste, it is not a complete solution. To truly address the problem, we need to reduce our reliance on single-use plastics and find alternative materials that are more environmentally friendly.",
    q: ["What is the main idea of this passage?", "What is the impact of plastic waste on the oceans?", "What is the solution to the problem of plastic waste?",],
    q_sel: [[" Plastic waste is harming the environment.", " Recycling is not a complete solution to the problem of plastic waste.", " We need to reduce our reliance on single-use plastics and find alternative materials.", " Both A and C ."], [" It harms marine life.", " It increases the number of fish in the oceans.", " It reduces pollution on the beaches.", " Both B and C ."], [" Recycling.", " Finding alternative materials.", " Reducing our reliance on single-use plastics.", " Both B and C ."],],
    q_ex: ["文章講述了塑料垃圾對環境的影響，尤其是對海洋生態系統的影響。文章認為，儘管回收可以幫助減少塑料垃圾的量，但這不是一個完整的解決方案。為了真正解決問題，我們需要減少對一次性塑料制品的依賴，找到更環保的替代材料。因此，答案為D。", "根據文章第一句話“近年來，人們越來越關注塑料垃圾對環境的影響”，和第二句話“據估計，每年有超過800萬噸的塑料垃圾進入海洋，損害海洋生物並污染我們的海灘”，可知塑料垃圾對海洋生態系統有害，因此答案為A。", "根據文章最後一句話“我們需要減少對一次性塑料制品的依賴，找到更環保的替代材料”，可知解決塑料垃圾問題的方案是找到更環保的替代材料和減少對一次性塑料制品的依賴，因此答案為D。",],
    q_a: [" D", " A", " D",],
    zh: "近年來，人們越來越關注塑料垃圾對環境的影響。據估計，每年有超過 800 萬噸塑料最終流入海洋，危害海洋生物並污染我們的海灘。雖然回收有助於減少塑料垃圾的數量，但這並不是一個完整的解決方案。要真正解決這個問題，我們需要減少對一次性塑料的依賴，並尋找更環保的替代材料。"
}, {
    ar: "Climate change is one of the biggest challenges facing our planet today. The burning of fossil fuels, such as coal and oil, releases carbon dioxide and other greenhouse gases into the atmosphere, trapping heat and causing global temperatures to rise. The consequences of climate change include rising sea levels, more frequent and severe weather events, and the extinction of plant and animal species. To address this urgent issue, we must reduce our greenhouse gas emissions and transition to renewable energy sources such as wind, solar, and hydro power.",
    q: ["What is the main challenge facing our planet today?", "What is the cause of global temperature rise?", "What are the consequences of climate change?", "What is the solution to address the issue of climate change?",],
    q_sel: [[" Rising sea levels.", " Climate change.", " The extinction of plant and animal species.", " Burning fossil fuels."], [" Rising sea levels.", " Burning of fossil fuels.", " Extinction of plant and animal species.", " None of the above."], [" Rising sea levels.", " More frequent and severe weather events.", " The extinction of plant and animal species.", " All of the above."], [" Reduce greenhouse gas emissions.", " Transition to renewable energy sources.", " Both A and B .", " None of the above."],],
    q_ex: ["文章開頭提到了「氣候變遷」這個詞，接著說明了其原因和後果，因此可以判斷出主要挑戰是氣候變遷，答案為B。", "根據文章提到的「化石燃料的燃燒，如煤和油，釋放出二氧化碳和其他溫室氣體到大氣中，將熱量困住，導致全球氣溫上升。」可知全球氣溫上升的原因是化石燃料的燃燒，答案為B。", "根據文章提到的「氣候變遷的後果包括海平面上升、更頻繁和嚴重的氣象事件以及植物和動物物種的滅絕。」可知氣候變遷的後果有海平面上升、更頻繁和嚴重的氣象事件以及植物和動物物種的滅絕，答案為D。", "根據文章提到的「要解決這個緊迫的問題，我們必須減少溫室氣體排放，轉向風、太陽和水力發電等可再生能源。」可知解決氣候變遷問題的方法是減少溫室氣體排放和轉向可再生能源，答案為C。",],
    q_a: [" B", " B", " D", " C",],
    zh: "氣候變化是當今地球面臨的最大挑戰之一。煤炭和石油等化石燃料的燃燒會向大氣中釋放二氧化碳和其他溫室氣體，吸收熱量並導致全球氣溫上升。氣候變化的後果包括海平面上升、更頻繁和更惡劣的天氣事件以及植物和動物物種的滅絕。為了解決這個緊迫的問題，我們必須減少溫室氣體排放，並轉向風能、太陽能和水力發電等可再生能源。"
},]*/


import { cn } from './ques7/cn.js'
import { de } from './ques7/de.js'
import { en } from './ques7/en.js'
import { es } from './ques7/es.js'
import { fr } from './ques7/fr.js'
import { id } from './ques7/id.js'
import { it } from './ques7/it.js'
import { ja } from './ques7/ja.js'
import { ko } from './ques7/ko.js'
import { pt } from './ques7/pt.js'
import { ru } from './ques7/ru.js'
import { th } from './ques7/th.js'
import { vi } from './ques7/vi.js'
import { zh } from './ques7/zh.js'

export function getQ(a) {
    if (a == 'cn') return cn
    else if (a == 'de') return de
    else if (a == 'en') return en
    else if (a == 'es') return es
    else if (a == 'fr') return fr
    else if (a == 'id') return id
    else if (a == 'it') return it
    else if (a == 'ja') return ja
    else if (a == 'ko') return ko
    else if (a == 'pt') return pt
    else if (a == 'ru') return ru
    else if (a == 'th') return th
    else if (a == 'vi') return vi
    else return zh
}