/* eslint-disable */
export const q = [{
  id: 0,
  q: 'The __________ of DNA molecules determines the genetic traits of an organism.',
  s: ['structure', 'function', 'color', 'temperature'],
  a: 'structure',
  e: '這個題目在描述 DNA 分子的性質，使用了名詞 "structure" 來指出它的結構特徵，以及片語 "genetic traits" 來指出它如何決定生物的遺傳特徵。而選項中只有 A. structure 符合語境和概念。B. function 可能是一個常見的選項，但它不足以完全解釋 DNA 分子的特性。C. color 和 D. temperature 則明顯不相關。',
}, {
  id: 1,
  q: "The human body has an internal __________ system that helps regulate and maintain the body's functions.",
  s: ['respiratory', 'digestive', 'circulatory', 'muscular'],
  a: 'circulatory',
  e: "這個題目在描述人體的生理系統，使用了名詞 system 來指出它是一個系統，並且片語 helps regulate and maintain the body's functions 進一步說明了它的作用。而選項中只有 C. circulatory 符合這個描述，因為循環系統是一個由心臟、血管和血液組成的系統，它負責將氧氣和營養物質運送到身體的各個部位，同時將二氧化碳和其他代謝廢物帶回肺和腎臟以進行排泄。A. respiratory 和 B. digestive 是其他兩個生理系統，而 D. muscular 則是描述人體的肌肉系統。",
}, {
  id: 2,
  q: 'The ___________ is the smallest unit of life and is capable of carrying out all the functions of life, including metabolism and reproduction.',
  s: ['cell', 'organ', 'tissue', 'organism'],
  a: 'cell',
  e: '這個題目在描述生命的最小單位，使用了 "smallest unit of life" 這個短語來提示。而選項中只有 A. cell 符合這個描述，因為細胞是生命的基本單位，能夠執行代謝、分裂、分化等生命活動，而器官 (organ)、組織 (tissue) 和有機體 (organism) 則都是由多個細胞組成的更大的單位。因此，答案為 A. cell。',
}, {
  id: 3,
  q: 'In the process of ___________, plants convert light energy into chemical energy in the form of glucose.',
  s: ['photosynthesis', 'respiration', 'digestion', 'circulation'],
  a: 'photosynthesis',
  e: '這個題目在描述植物如何利用光能進行能量轉換，使用了 "convert light energy into chemical energy" 這個短語來提示。而選項中只有 A. photosynthesis 符合這個描述，因為光合作用是指植物利用光合色素吸收陽光能量，將二氧化碳和水轉化為葡萄糖和氧氣的過程，這個過程就是將光能轉換為化學能的過程。而呼吸 (respiration)、消化 (digestion) 和循環 (circulation) 則與此不同，因此答案為 A. photosynthesis。',
}, {
  id: 4,
  q: 'The human __________ system is responsible for protecting the body from harmful substances and invading pathogens.',
  s: ['circulatory', 'respiratory', 'immune', 'nervous'],
  a: 'immune',
  e: '這個題目描述了一個保護身體免受有害物質和侵略性病原體侵害的系統。選項中只有 C. immune (免疫) 符合這個描述，因為免疫系統負責保護身體免受病毒、細菌、真菌等病原體的攻擊，以及防止異物進入體內，維持身體健康。而循環 (circulatory)、呼吸 (respiratory) 和神經 (nervous) 系統都不是負責這個功能的系統，因此答案為 C. immune。',
}, {
  id: 5,
  q: '______________ is the study of how living organisms interact with each other and with their environment.',
  s: ['Anatomy', 'Physiology', 'Ecology', 'Genetics'],
  a: 'Ecology',
  e: '這個題目描述了一個研究生物與其環境互動的領域。選項中只有 C. Ecology (生態學) 符合這個描述，因為生態學研究生物與環境之間的關係，包括生物之間的相互作用、物種與物種之間的關係、生物與非生物環境之間的關係等。而解剖學 (Anatomy)、生理學 (Physiology) 和遺傳學 (Genetics) 則分別研究生物體的結構、功能和遺傳機制，與生物與環境之間的關係不直接相關，因此答案為 C. Ecology。',
}, {
  id: 6,
  q: "The ___________ gland produces hormones that regulate the body's metabolism.",
  s: ['Thyroid', 'Pituitary', 'Adrenal', 'Pancreas'],
  a: 'Thyroid',
  e: '這個題目描述了一個腺體，該腺體產生調節人體代謝率的荷爾蒙。選項中只有甲狀腺 (Thyroid) 符合這個描述，因為甲狀腺荷爾蒙可以影響人體的新陳代謝率，從而影響身體的生理機能，例如心率、體溫和消化。垂體 (Pituitary)、腎上腺 (Adrenal) 和胰臟 (Pancreas) 分別分泌其他種類的荷爾蒙，與代謝率無關，因此答案為 A. Thyroid。',
}, {
  id: 7,
  q: 'The _________ War was a conflict that lasted from 1950 to 1953 between North Korea, which was supported by China and the Soviet Union, and South Korea, which was supported by the United States and other countries.',
  s: ['Vietnam', 'Gulf', 'Korean', 'Iraq'],
  a: 'Korean',
  e: '這個題目描述了一個戰爭，該戰爭持續了從1950年到1953年之間，參戰雙方分別為支持北韓的中國和蘇聯，以及支持南韓的美國和其他國家。只有選項 C. Korean 符合這個描述，因為其他選項分別代表不同的戰爭，如越南戰爭 (Vietnam War)、海灣戰爭 (Gulf War) 和伊拉克戰爭 (Iraq War)，與此題目所描述的戰爭無關。因此答案為 C. Korean。',
}, {
  id: 8,
  q: 'The ________ of the novel is full of twists and turns that keep readers on the edge of their seats.',
  s: ['plot', 'protagonist', 'theme', 'conflict'],
  a: 'plot',
  e: '這句話中的 "twists and turns" 暗示著這本小說的劇情複雜而曲折，因此空格處應填入描述小說劇情的詞彙。選項中只有 A. plot (劇情) 能夠恰當地填入空格，因此 A 為正確答案。B. protagonist (主角)、C. theme (主題) 和 D. conflict (衝突) 都不能夠恰當地填入空格。',
}, {
  id: 9,
  q: 'Despite having no prior acting experience, Emily managed to ________ the role of Juliet in the school play.',
  s: ['procure', 'exude', 'concede', 'secure'],
  a: 'secure',
  e: '在這個句子中，空格後面的“the role of Juliet in the school play”表示“Juliet這個角色在學校的話劇中”，所以我們需要找一個動詞，表示Emily“得到”了這個角色。A選項“procure”表示“取得”，也可以表示“購買”或“強迫”，但在這個句子中不合適。B選項“exude”表示“散發”，C選項“concede”表示“承認”，但它們都不符合句子的意思。因此，D選項“secure”表示“獲得”或“取得”，是正確的選項。',
}, {
  id: 10,
  q: 'The _______ is the central processing unit of a computer, which controls all other parts of the computer system.',
  s: ['monitor', 'keyboard', 'mouse', 'CPU'],
  a: 'CPU',
  e: '因為題目所描述的是電腦的中央處理器，而選項 A、B、C 則分別是顯示器、鍵盤和滑鼠。',
}, {
  id: 11,
  q: 'Despite the ___________ of the internet, some people still prefer reading books made from paper.',
  s: ['convenience', 'popularity', 'novelty', 'complexity'],
  a: 'convenience',
  e: '句子的意思是“儘管有互聯網，仍有些人喜歡閱讀用紙張印刷的書籍”。convenience是“方便”或“便利”的意思，符合句意。B. popularity表示“流行”，不符合句意；C. novelty表示“新奇”或“新穎”，也不符合句意；D. complexity表示“複雜”，同樣不符合句意。',
}, {
  id: 12,
  q: 'The teacher asked the students to submit a(n) _________ of their project before the deadline.',
  s: ['summary', 'analysis', 'evaluation', 'interpretation'],
  a: 'summary',
  e: '通常是簡潔而全面地概述整個文本或文章的主要內容，以便讓讀者可以快速了解它的核心思想和結論。B. analysis（分析）： 是一種細心研究文本或文章的方法，通常涉及特定主題、模式或細節，目的是理解和詮釋所分析的材料。C. evaluation（評價）： 是評估文本或文章質量的過程。 評估可以基於某種標準或範圍，可以是專業的或個人的。D. interpretation（解釋）： 是理解文本或文章的基本含義，通常基於個人或特定文化的背景和觀點。 解釋通常涉及詮釋文本或文章的意圖和目的，並可能導致對該材料的不同理解。解析：根據上下文，老師要求學生在最後期限之前提交一份「評價」，以便老師評估學生的項目。因此，答案是 C. evaluation（評價）。其他選項在上下文中不太適合，因為「摘要」不足以評估學生的項目，「分析」並不一定需要提交給老師，「解釋」與老師要求的不符。',
}, {
  id: 13,
  q: "The company's financial ____ showed that they had a net profit of $10 million last year.",
  s: ['statement', 'status', 'strategy', 'stimulation'],
  a: 'statement',
  e: '本題考查詞彙理解和應用能力。句子中說到“公司的財務____顯示他們去年有1000萬美元的淨利潤”，因此需要選出一個與“財務”相關、可以顯示公司利潤的單詞。根據常識可知，表示公司利潤的英文單詞為“statement”，因此選項 A 正確。選項 B 中的“status”表示“狀態”，選項 C 的“strategy”表示“策略”，選項 D 的“stimulation”表示“刺激”，均與句子意思不符，故為錯誤選項。因此，本題答案為 A。 ',
}, {
  id: 14,
  q: 'Despite being known as a shy person, John was surprisingly ___ at the party last night.',
  s: ['outgoing', 'reserved', 'introverted', 'timid'],
  a: 'outgoing',
  e: '本題考察形容詞在句子中的修飾作用，選擇正確的形容詞填入空格中。句子開頭已經明確表示約翰是一個較內向的人，因此需要在四個選項中選擇一個與此相反的形容詞。A選項的意思是外向的，B選項是內向的，C選項也是內向的，D選項的意思是膽小的。根據句子意思，John在昨晚的派對上表現出人意料之外的行為，因此應該選擇與內向相反的選項A，也就是outgoing，意思是外向的，與內向相反。正確答案：A. outgoing',
}, {
  id: 15,
  q: 'It is important to __________ a healthy and balanced diet to maintain good health.',
  s: ['eat', 'ate', 'eating', 'eats'],
  a: 'eat',
  e: '句子中缺少的是一個動詞，而主語是 “it” ，根據主語是單數，所以選項中只有 A 和 D 可能是正確答案。但是，因為是要講述維持健康，所以選項 A 用現在式的 “eat” 更合適。選項 B 的 “ate” 是過去式，不符合文意。選項 C 的 “eating” 是進行式，也不符合文意。選項 D 的 “eats” 是第三人稱單數現在式，文意對但主語不符。因此，正確答案是 A. eat。',
}, {
  id: 16,
  q: 'The Internet has ___ changed the way we communicate, ___ we do business, and even ___ we shop for groceries.',
  s: ['radially', 'what', 'how', 'radically'],
  a: 'changed',
  e: '這句話描述了互聯網對我們生活的幾個方面的影響，因此需要填入“changed”來表示過去的變化。由於“changed”是動詞過去分詞，因此需要一個助動詞，那麼應選擇“radically”，意為“根本地、徹底地”，與“changed”形成較好的搭配。接下來，需要填寫一個連詞來引導後面的兩個從句。因為第二個空格是“we do business”，而“how”是副詞，因此應選擇“what”，表示“我們做什麼樣的業務”。最後一個空格之前提到了購物，因此應填寫“how”來表示“我們如何購物”。綜上所述，正確的答案是C：radically, what, how。',
}, {
  id: 18,
  q: 'In order to _____ for the upcoming exam, he spent hours every day reviewing his notes and practicing problems.',
  s: ['revise', 'reject', 'release', 'regulate'],
  a: 'revise',
  e: '這句話的意思是為了準備即將到來的考試，他每天花了幾個小時複習筆記和練習問題。根據句意，應該用一個表示“修訂、修改”的詞來填空。A. revise 符合句意，表示“修訂、修改”，為正確答案。B. reject 表示“拒絕、排斥”，與句意不符。C. release 表示“釋放、發行”，與句意不符。D. regulate 表示“調節、管理”，與句意不符。因此，正確答案為 A. revise。',
}, {
  id: 19,
  q: 'The young athlete was _____ to give up his Olympic dreams after suffering a severe injury during training.',
  s: ['forced', 'refused', 'expected', 'encouraged'],
  a: 'forced',
  e: '根據題意，這位年輕的運動員因受傷而要放棄他的奧運夢想。從文意來看，他被迫要做出這個決定。因此，選項 A "forced"（被迫）是正確的答案。選項 B "refused"（拒絕）和選項 D "encouraged"（鼓勵）都與文意不符，因為這位運動員受傷後沒有選擇放棄是因為他被迫這樣做。選項 C "expected"（預期）也與文意不符。儘管教練和團隊可能意識到這位運動員的受傷可能會對他的夢想產生影響，但他們並沒有期望他放棄，而是被迫要做出這個決定。因此，答案是 A "forced"。',
}]